### ISSUE TITLE
Clicking outside of the etterna window causes files or packs to open

### ISSUE THREAD

**Issue by 11brendon** [etternagame/etterna#10]
when im in game, i'll click out of the window and it will open a pack or start a song. this happens in fullscreen as well. https://youtu.be/5BlX4edcvSc

**Comment by RGates94** [comment]
We (mina, xwidghet, and myself) cannot replicate this issue.  More detail about your exact setup is required to determine why an issue is occurring.  Please include as much information as you can think of, as in general more information is more useful.

Also as an aside when posting an issue it is good practice to always include all relevant information. If we cannot replicate your bug we can't fix it.

**Comment by 11brendon** [comment]
the only other relevant information that i can give is im using the 0,55 pre release of etterna https://drive.google.com/file/d/0B4kA0cSC7Jo1R1hpelU3S1lUR00/view (from this dl link), and im using 64 bit version of windows 10. sorry if this information would have been more useful in my original post. if theres anything more specific that you need, i can elaborate.

**Comment by Nickito12** [comment]
What resolution and aspect ratio is your Etterna using? What's your desktop resolution?

**Comment by 11brendon** [comment]
using 1920x1080 resolution and 16:9 ratio, as well that is my desktop resolution.

**Comment by Nickito12** [comment]
I finally managed to replicate this. The problem started happening when i resized my window.

This seems to fix the issue, at least in windows: https://github.com/Nickito12/etterna/tree/mousepos (Specifically https://github.com/Nickito12/etterna/commit/518880e52484ed47dcda113220336f4f823b4cd3)

**Comment by Nickito12** [comment]
Ok I think this can be closed (https://github.com/etternagame/etterna/pull/19)

**Comment by martensm** [comment]
Fix by #19.
