### ISSUE TITLE
Bare Frames doesn't work

### ISSUE THREAD

**Issue by TeamSoldierNub2** [etternagame/etterna#1002]
Bare frames is broken when trying to start the game

**To Reproduce**
1. Select Bare Frames as a theme
2. Go to Play
3. Select Single or Double

**Expected behavior**
It should go in the song list as normal.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10 Home
 - 20H2
 - 64-bit operating system, x64-based processor

**Additional context**
I was attempting to play on solo mode. this bug can be replicated with any mode, however.

Crash report: 
`
Crash reason: Unhandled Microsoft C++ Exception

Unknown thread
        NotesLoaderDWI.cpp:512 DWILoader::LoadFromDWITokens()
        NotesLoaderDWI.cpp:512 DWILoader::LoadFromDWITokens()
        NotesLoaderDWI.cpp:512 DWILoader::LoadFromDWITokens()
        NotesLoaderDWI.cpp:512 DWILoader::LoadFromDWITokens()
        NotesLoaderDWI.cpp:512 DWILoader::LoadFromDWITokens()
Thread: Main thread
        FontManager.cpp:70 FontManager::UnloadFont(/Themes/_fallback/Fonts/_open sans semibold 24px.ini).
        FontManager.cpp:70 FontManager::UnloadFont(/Themes/_fallback/Fonts/_open sans semibold 24px.ini).
        FontManager.cpp:70 FontManager::UnloadFont(/Themes/_fallback/Fonts/_open sans semibold 24px.ini).
        FontManager.cpp:70 FontManager::UnloadFont(/Themes/_fallback/Fonts/_open sans semibold 24px.ini).
        RageTextureManager.cpp:168 RageTextureManager::LoadTexture(__blank__).
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:237 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:237 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:237 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:237 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:237 Processing the sound while buffers are available.
Thread: Mixer thread
Thread: Music thread
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:893 
        InputHandler_DirectInput.cpp:868 
        InputHandler_DirectInput.cpp:887 
        InputHandler_DirectInput.cpp:893 
        InputHandler_DirectInput.cpp:868 
debug resource file 'E:\Etterna\Program\Etterna.vdi': CreateFile failed (The system cannot find the file specified.).

Static log:
Etterna0.70.3
(build )
Log starting 2021-06-29 13:32:36
	Verbosity: 1
Windows 6.2 (Win8) build 9200 []
WARNING: Detected steps with unknown style 'bm-single' in '/Songs/BCMP3/THE DETONATOR/THE DETONATOR.sm'
Not caching unrecognized stepstype in file /Songs/BCMP3/THE DETONATOR/
WARNING: Unmatched 3 in "3001"
WARNING: Unmatched 3 in "3001"
WARNING: Detected steps with unknown style 'pump-couple' in '/Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/tiw.sm'
WARNING: Detected steps with unknown style 'para-versus' in '/Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/tiw.sm'
WARNING: Detected steps with unknown style 'bm-single' in '/Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/tiw.sm'
WARNING: Detected steps with unknown style 'bm-double' in '/Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/tiw.sm'
WARNING: Detected steps with unknown style 'iidx-single7' in '/Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/tiw.sm'
WARNING: Detected steps with unknown style 'iidx-double7' in '/Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/tiw.sm'
WARNING: Detected steps with unknown style 'iidx-single5' in '/Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/tiw.sm'
WARNING: Detected steps with unknown style 'iidx-double5' in '/Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/tiw.sm'
WARNING: Detected steps with unknown style 'techno-single4' in '/Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/tiw.sm'
WARNING: Detected steps with unknown style 'techno-single5' in '/Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/tiw.sm'
WARNING: Detected steps with unknown style 'techno-single8' in '/Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/tiw.sm'
WARNING: Detected steps with unknown style 'techno-double4' in '/Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/tiw.sm'
WARNING: Detected steps with unknown style 'techno-double5' in '/Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/tiw.sm'
Not caching unrecognized stepstype in file /Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/
Not caching unrecognized stepstype in file /Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/
Not caching unrecognized stepstype in file /Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/
Not caching unrecognized stepstype in file /Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/
Not caching unrecognized stepstype in file /Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/
Not caching unrecognized stepstype in file /Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/
Not caching unrecognized stepstype in file /Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/
Not caching unrecognized stepstype in file /Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/
Not caching unrecognized stepstype in file /Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/
Not caching unrecognized stepstype in file /Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/
Not caching unrecognized stepstype in file /Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/
Not caching unrecognized stepstype in file /Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/
Not caching unrecognized stepstype in file /Songs/Solo Rulz Pack 4/Toaru Itsumo Wo (Hazelnut)/
WARNING: Detected steps with unknown style 'pump-couple' in '/Songs/Solo Rulz Pack 2/(lurker) Proper Mid-Fi/04 - Clark - Proper Mid-Fi.ssc'
WARNING: Detected steps with unknown style 'pump-routine' in '/Songs/Solo Rulz Pack 2/(lurker) Proper Mid-Fi/04 - Clark - Proper Mid-Fi.ssc'
WARNING: Detected steps with unknown style 'para-single' in '/Songs/Solo Rulz Pack 2/(lurker) Proper Mid-Fi/04 - Clark - Proper Mid-Fi.ssc'
WARNING: Detected steps with unknown style 'techno-single4' in '/Songs/Solo Rulz Pack 2/(lurker) Proper Mid-Fi/04 - Clark - Proper Mid-Fi.ssc'
WARNING: Detected steps with unknown style 'techno-single5' in '/Songs/Solo Rulz Pack 2/(lurker) Proper Mid-Fi/04 - Clark - Proper Mid-Fi.ssc'
WARNING: Detected steps with unknown style 'techno-single8' in '/Songs/Solo Rulz Pack 2/(lurker) Proper Mid-Fi/04 - Clark - Proper Mid-Fi.ssc'
WARNING: Detected steps with unknown style 'techno-double4' in '/Songs/Solo Rulz Pack 2/(lurker) Proper Mid-Fi/04 - Clark - Proper Mid-Fi.ssc'
WARNING: Detected steps with unknown style 'techno-double5' in '/Songs/Solo Rulz Pack 2/(lurker) Proper Mid-Fi/04 - Clark - Proper Mid-Fi.ssc'
WARNING: Detected steps with unknown style 'techno-double8' in '/Songs/Solo Rulz Pack 2/(lurker) Proper Mid-Fi/04 - Clark - Proper Mid-Fi.ssc'
Not caching unrecognized stepstype in file /Songs/Solo Rulz Pack 2/(lurker) Proper Mid-Fi/
Not caching unrecognized stepstype in file /Songs/Solo Rulz Pack 2/(lurker) Proper Mid-Fi/
Not caching unrecognized stepstype in file /Songs/Solo Rulz Pack 2/(lurker) Proper Mid-Fi/
Not caching unrecognized stepstype in file /Songs/Solo Rulz Pack 2/(lurker) Proper Mid-Fi/
Not caching unrecognized stepstype in file /Songs/Solo Rulz Pack 2/(lurker) Proper Mid-Fi/
Not caching unrecognized stepstype in file /Songs/Solo Rulz Pack 2/(lurker) Proper Mid-Fi/
Not caching unrecognized stepstype in file /Songs/Solo Rulz Pack 2/(lurker) Proper Mid-Fi/
Not caching unrecognized stepstype in file /Songs/Solo Rulz Pack 2/(lurker) Proper Mid-Fi/
Not caching unrecognized stepstype in file /Songs/Solo Rulz Pack 2/(lurker) Proper Mid-Fi/
Attempting to connect to: multi.etternaonline.com, Port: 8765
Server Version: 0 
Video renderers: 'd3d, opengl'
WARNING: RageDisplay_D3D::TryVideoMode( 0, 1920, 1080, 32, 0, 0 )
D3D Fullscreen 1920x1080 32 color 32 texture 144Hz NoVsync SmoothLines
WARNING: RageSoundDriver::GetHardwareFrame: too many tries
Players joined: P1
Top Screen: ScreenSelectMusic
Current renderer: Direct3D

Partial log:
00:24.847: This will work.
00:24.849: Present Parameters: 1920, 1080, 22, 1, 8, 1, 2950412, 0, 1, 80, 0, 0, -2147483648
00:24.989: D3D Fullscreen 1920x1080 32 color 32 texture 144Hz NoVsync SmoothLines
00:27.531: Ettp server identified: Etterna Online (Version: 1)
00:27.531: Connection to 'Etterna Online' successful.
00:27.589: App doesn't have focus
00:45.144: App has focus
00:53.895: WARNING: RageSoundDriver::GetHardwareFrame: too many tries
00:54.261: MusicWheel sorting took: 54.261002
00:54.269: MusicWheel sorting took: 54.269001

-- End of report`

**Comment by poco0317** [comment]
fixed in 0.71 release presumably
check again after release and reopen if needed
