### ISSUE TITLE
You can't do audio sync on Solo mode

### ISSUE THREAD

**Issue by TeamSoldierNub2** [etternagame/etterna#1003]
Audio Sync crashes on Solo

**To Reproduce**
1. Open Etterna
2. Go to Options -> Select Game
3. Go to solo
4. Go to Input Options
5. Go to Calibrate Audio Sync and hit it

**Expected behavior**
I expected it to load a chart for audio syncing (ideal sync ogg)

**Screenshots**
[unavailable]

**Desktop (please complete the following information):**
 - Windows 10 Home
 - 20H2
 - 64-bit operating system, x64-based processor

**Additional context**
I was on Solo mode (6k)

**Comment by poco0317** [comment]
duplicate #877
