### ISSUE TITLE
Etterna doesn't run at 144Hz when a 60Hz screen is connected

### ISSUE THREAD

**Issue by skydiver221** [etternagame/etterna#1005]
**Describe the bug**
The game will always run at 60Hz when a 60Hz monitor is connected, even though the game is played on the 144Hz screen and the refresh rate in the settings is set to 144Hz.

**To Reproduce**
1. Connect a 144Hz display
2. Connect a 60Hz display
3. Set refresh rate to 144Hz in the settings
4. The game still runs at 60Hz

**Expected behavior**
The game running at 144Hz.

**Desktop (please complete the following information):**
 - OS: Arch Linux 64-bit
 - Kernel version 5.11.13
 - Etterna v0.70.3

**Additional context**
If I disconnect the 60Hz monitor, the game will run at 144Hz as expected.
This issue never happened to me in Windows.

**Comment by Ulti-FD** [comment]
I assume this is a valid issue, but it can be mitigated by running the game in exclusive fullscreen with your specific monitor targeted. Depending on your window manager, this may or may not be a viable solution (in my case, it isnt).
![image](https://user-images.githubusercontent.com/24206396/124457632-007e3b80-dd5a-11eb-8aba-8655c7f9fb76.png)
At least for me, when using this I get the normal 1000fps cap and can run the game at 144Hz.

**Comment by skydiver221** [comment]
I run the game in exclusive fullscreen on the right monitor just like in your screenshot and it still doesn't work. 
Running the game with `env vblank_mode=0 ./Etterna` had no effect unfortunately.

**Comment by ajyri** [comment]
I had this issue too when using Arch Linux. The solution for me was to change the monitor sync option to my 144hz monitor in nvidia-settings.

**Comment by skydiver221** [comment]
The sync option of the monitor in nvidia-settings is set to 144Hz.

**Comment by skydiver221** [comment]
I have found out the cause of the problem.
Turns out the compositor of KDE Plasma was limiting the refresh rate of everything, so I disabled it in the system settings and now it runs perfectly fine at 144hz.
