### ISSUE TITLE
Playlists and favoriting cause issues when used simultaneously

### ISSUE THREAD

**Issue by foxfire667** [etternagame/etterna#1007]
**What happens**
When the user attempts to use the playlist feature in tandem with adding or removing an preexisting favorite (i.e. one which has been saved to the profile), it causes either the playlist to be inaccessible with 0 songs, or a game crash to occur. 

**To Reproduce**
1. Open the playlist tab and go to any song you have previously saved to favorites
2. Enter the list of favorite songs
3. Remove favorite, hit back on playlist menu
4. Favorite again, enter playlist menu
5. Repeat as necessary until the game throws one of the two errors

**Expected behavior**
Playlists to add or remove the file from favorites when ctrl+f is applied, without the playlist vanishing or the game crashing. 

**Demonstration of both events occurring:**
https://user-images.githubusercontent.com/7039995/125147499-b9959a80-e0f9-11eb-850c-2bbdcfd5f08c.mp4
https://user-images.githubusercontent.com/7039995/125147410-09c02d00-e0f9-11eb-8b8d-66a0fb9fd7d0.mp4

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version: 10
 - 64bit

**Additional context**
Tested in release 0.70.3 trying to reproduce an issue in the EO discord encountered by Faustas. It appears to be a consistent bug.

**Comment by poco0317** [comment]
resolved long ago for 0.71 e90d6164dfb533e08aea7fca53d88be7ba99e6be
