### ISSUE TITLE
What are the system requirements?

### ISSUE THREAD

**Issue by Crafterz125** [etternagame/etterna#1008]
I have this error: Unknown video renderer value:  opengl
What are the system requirements.

**Comment by poco0317** [comment]
technically any hardware that can run directx9 on windows or opengl glew 1.5.8 on any platform
and on windows you will need a system that is able to install vc++ 2013 and 2015

anyways the reason you get this error could be a really long list of things so try:
- rebooting
- having a better computer
- swapping the videorenderer values in /save/preferences.ini
- reinstalling windows
