### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by Duduarakaki** [etternagame/etterna#1014]
startup error, unplayable

crashinfo:
Etterna0.70.3 crash report (build )
--------------------------------------

Crash reason: Access Violation

Thread: Main thread
        IniFile.cpp:22 Reading 'Themes/_fallback/metrics.ini'
        IniFile.cpp:22 Reading 'Themes/_fallback/Languages/en.ini'
        IniFile.cpp:22 Reading 'Themes/_fallback/Languages/pt.ini'
        IniFile.cpp:22 Reading 'Themes/_fallback/ThemeInfo.ini'
        IniFile.cpp:22 Reading 'Themes/Til Death/ThemeInfo.ini'
debug resource file 'C:\Users\macei\OneDrive\Área de Trabalho\Etterna\Program\Etterna.vdi': CreateFile failed (O sistema não pode encontrar o arquivo especificado.).

Static log:
Etterna0.70.3
(build )
Log starting 2021-07-21 12:10:10
	Verbosity: 1
Windows 6.2 (Win8) build 9200 []
WARNING: Selected theme '_fallback' not found.  Trying Theme preference default value '_fallback'.
WARNING: Theme preference defaults to '_fallback', which cannot be used.  Trying DefaultTheme preference 'Til Death'.

Partial log:
00:00.584: Windows 6.2 (Win8) build 9200 []
00:00.819: Memory changed from 4010 to 2047; settings changed
00:00.824: Reading 'Data/Static.ini' failed: No such file or directory
00:00.825: WARNING: Selected theme '_fallback' not found.  Trying Theme preference default value '_fallback'.
00:00.825: WARNING: Theme preference defaults to '_fallback', which cannot be used.  Trying DefaultTheme preference 'Til Death'.
00:00.834: Reading 'Themes/Til Death/Languages/pt.ini' failed: No such file or directory
00:00.850: Reading 'Themes/_fallback/Languages/pt.ini' failed: No such file or directory
00:00.870: Reading 'Themes/_fallback/ThemeInfo.ini' failed: No such file or directory
00:00.879: Reading 'Themes/Til Death/ThemeInfo.ini' failed: No such file or directory
00:01.085: Error reading cache db: unable to open database file

-- End of report

viewlog:
00:00.052: Etterna0.70.3
00:00.052: (build )
00:00.052: Log starting 2021-07-21 12:10:10
00:00.052: 	Verbosity: 1
00:00.053:  
00:00.053: Reading 'Data/Defaults.ini' failed: No such file or directory
00:00.054: Reading 'Data/Static.ini' failed: No such file or directory
00:00.584: Windows 6.2 (Win8) build 9200 []
00:00.819: Memory changed from 4010 to 2047; settings changed
00:00.824: Reading 'Data/Static.ini' failed: No such file or directory
/////////////////////////////////////////
00:00.825: WARNING: Selected theme '_fallback' not found.  Trying Theme preference default value '_fallback'.
/////////////////////////////////////////
/////////////////////////////////////////
00:00.825: WARNING: Theme preference defaults to '_fallback', which cannot be used.  Trying DefaultTheme preference 'Til Death'.
/////////////////////////////////////////

 32bit

**Additional context**

**Comment by Duduarakaki** [comment]
help please

**Comment by poco0317** [comment]
for one, i would recommend not running this game within onedrive

and the issue the game is having is you appear to be missing the themes folder from the install directory. alternatively, you are running the program exe from outside the install folder (and not as a shortcut instead or something)

reinstall or something

**Comment by Duduarakaki** [comment]
il try that

**Comment by Duduarakaki** [comment]
![etterna](https://user-images.githubusercontent.com/87770923/126515933-a64cf46f-f2da-4f46-a070-5a9a283141b5.png)

**Comment by Duduarakaki** [comment]
does not work still

**Comment by Duduarakaki** [comment]
![etterna2](https://user-images.githubusercontent.com/87770923/126517034-0d02092a-df66-459e-b5a4-f921db0118e7.png)

**Comment by Duduarakaki** [comment]
i can see the themes there

**Comment by Duduarakaki** [comment]
also i tried reinstalling before so yea

**Comment by poco0317** [comment]
in the Program folder try opening that Etterna.exe

if not, try right clicking and open as Admin

**Comment by Duduarakaki** [comment]
still not working :p

**Comment by jameskr97** [comment]
Try showing us the programs folder.

**Comment by Duduarakaki** [comment]
okay

**Comment by Duduarakaki** [comment]
![image](https://user-images.githubusercontent.com/87770923/126563731-59835998-39f5-4e96-8898-0029ee20889d.png)

**Comment by poco0317** [comment]
Move the game out of your OneDrive. It looks like your entire Desktop is in OneDrive, which is where you have Etterna, too. Try putting it in C:/Games/Etterna (or anywhere else that is not managed by some cloud service)

**Comment by Duduarakaki** [comment]
okayyyy

**Comment by Duduarakaki** [comment]
It worked tysm everyone who participated and extra thanks to poco0317 :D
