### ISSUE TITLE
Errors Building on Arch

### ISSUE THREAD

**Issue by FyreWolf99** [etternagame/etterna#1017]
I've been trying to compile Etterna from source for 3 days now, and after getting all the openssl errors out of the way, I get this one:
```
CMake Error at /home/fyre/git/etterna/build/CMakeFiles/CMakeTmp/CMakeLists.txt:16 (add_executable):
  Target "cmTC_a9970" links to target "OpenSSL::SSL" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at /home/fyre/git/etterna/build/CMakeFiles/CMakeTmp/CMakeLists.txt:16 (add_executable):
  Target "cmTC_a9970" links to target "OpenSSL::Crypto" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at /usr/share/cmake-3.21/Modules/CheckLibraryExists.cmake:72 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  extern/curl/CMake/Macros.cmake:9 (check_library_exists)
  extern/curl/CMakeLists.txt:542 (check_library_exists_concat)
```
The output of Neofetch is the Following:
```
OS: Manjaro Linux x86_64
Host: MS-7C02 1.0
Kernel: 5.10.52-1-MANJARO
Uptime: 4 hours, 25 mins
Packages: 1065 (pacman)
Shell: bash 5.1.8
Resolution: 2560x1440
WM: dwm
Terminal: st
Terminal Font: Hack
CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz
GPU: NVIDIA GeForce GTX 1060 6GB
Memory: 3927MiB / 32118MiB
```
Is there anything I'm missing? I've tried compiling with ninja and unix makefiles, but I still get this exact error.

**Comment by bluebandit21** [comment]
There is an actively maintained AUR that works -- see https://aur.archlinux.org/packages/etterna/

If you want to do it yourself, I think `sed -i CMakeLists.txt -e 's/\(set(OPENSSL_USE_STATIC_LIBS\) ON/\1 OFF/'` (taken from that AUR) should fix that error.

**Comment by FyreWolf99** [comment]
> If you want to do it yourself, I think `sed -i CMakeLists.txt -e 's/\(set(OPENSSL_USE_STATIC_LIBS\) ON/\1 OFF/'` (taken from that AUR) should fix that error.

I tried to use that command, and i didn't reduce the number of errors at all, and for some reason that aur package doesn't have sound, but that might be an issue with JACK or pulseaudio

**Comment by FyreWolf99** [comment]
After installing the aur package and adding /usr/share/applications to PATH, and also setting execute perms on etterna.desktop for some reason, I realize that this issue was entirely user error
