### ISSUE TITLE
Chart preview and music breaks upon changing display name

### ISSUE THREAD

**Issue by yaatii** [etternagame/etterna#1027]
**Describe the bug**
If i have chart preview open and change my display name a variety of different bugs occur.
**To Reproduce**
1. Go to any song
2. Click on the display name
3. Change it or keep it how it is
4. Music breaks, if the song is up/downrated the scroll speed and physical chart difficulty goes weird, especially if its a major rate change, you cant pause the chart

**Expected behavior**
The chart preview resumes as normal.

**Screenshots**
I cant use screenshots because the problem isnt noticeable unless its as a video,

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10
 - 64bit or 32bit 64 bit

**Additional context**
I found it out originally on connect 1986 but it still applys for other charts

**Comment by poco0317** [comment]
duplicate #878
