### ISSUE TITLE
Missing pack in expanded core bundle

### ISSUE THREAD

**Issue by onebitboy** [etternagame/etterna#1030]
Pack ID 10259 is included in the "advanced" core bundle, but is missing from the "advanced-expanded" one. Since the expanded bundles usually include all of the packs from the non-expanded versions, 10259 should be added to advanced-expanded too.

**Comment by MinaciousGrace** [comment]
my hope was the community would keep the bundle sets updated over time but that never really happened

maybe a little push will get the ball rolling so if that happens it will be fixed in the process, otherwise we should just fix this oversight in 0.71 before release
