### ISSUE TITLE
Having a wallpaperengine screensaver on while Etterna boots makes it crash

### ISSUE THREAD

**Issue by TeamSoldierNub2** [etternagame/etterna#1031]
**Describe the bug**
Basically, if a wallpaperengine screensaver activates while you wait on etterna, it will crash as soon as its done loading.

**To Reproduce**
1. Boot etterna (Make sure you have a fuckton of songs, otherwise it will not take long at all)
2.) Have a WallpaperEngine screensaver... loaded I guess?
3.) Wait then come back after a few moments

**Expected behavior**
What I expected to happen was the game would boot up, and when I moved the mouse it would be normal.

**Screenshots**
https://pasteboard.co/Kf5P4Td.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 20H2
 - 64bit

**Additional context**
none

**Comment by jameskr97** [comment]
Maybe there are changes that fix this in latest develop, but when I run the game and activate a wallpaper engine screensaver while it's loading, the screensaver will deactivate when then window pops up.

Can you confirm you're still experiencing this?

**Comment by nico-abram** [comment]
Closing because of the lack of a response. @TeamSoldierNub2 feel free to leave a comment if this is still happening.
