### ISSUE TITLE
Change judge window view on results crashes game

### ISSUE THREAD

**Issue by Celytic** [etternagame/etterna#1035]
**Describe the bug**
Changing Judge windows down higher than J4 on results crashes the game
**To Reproduce**

**Expected behavior**
View the score downscaled to J4 from J7

**Screenshots**
My game crashed, no screenshots to be had.

**Desktop (please complete the following information):**
OS: Arch Linux x64 kernel 5.13.7

**Additional context**
I'm using the package for the game from the AUR that installs into /opt/. I did chmod /opt/etterna to 777

**Comment by poco0317** [comment]
Your score should have saved. We need to know what score it is. Does it still do this for every score or just that specific score?

**Comment by Celytic** [comment]
Reinstalling the client and deleting a config file resolved this, so I'm going to close this. Apologies for being a hassle.
