### ISSUE TITLE
Etterna on macOS is not responding to any keyboard inputs or mouse clicks

### ISSUE THREAD

**Issue by 4li77l3n00b** [etternagame/etterna#1047]
Etterna won't react to any operations after launching, while the program itself is not hanging.
I've allowed Etterna to receive inputs in Preferences as is requested at its first launch, and disabling it won't make any changes either.  Besides, Etterna requests to receive inputs on every start though I've allowed it to. I don't know if it is supposed to do so or there's something I haven't set up correctly.

**Desktop:**
 - OS: macOS Big Sur 11.4(mba 2013)
 - Version 0.70.3 and 0.70.4(it says 0.71.0 on the start screen idk how)
 - 64bit

**Additional context**
I previously have Etterna work on another Big Sur hackintosh machine(even without allowing input receiving), so I guess the preblem perhaps comes from my laptop. But since I've done all the steps to install Etterna on mac(including xattr, installing openssl and linking libc), I really have no idea how to fix it.

**Comment by bluebandit21** [comment]
Would you mind coming to our development Discord server for debugging?

https://discord.gg/ZqpUjsJ

**Comment by grhkm21** [comment]
You wanna try running `/Applications/Etterna/Etterna.app/Contents/MacOS/Etterna` from terminal?

**Comment by poco0317** [comment]
superceded by #1260
