### ISSUE TITLE
Duration doesn't update when filtering

### ISSUE THREAD

**Issue by grhkm21** [etternagame/etterna#1050]
Bug: The screenshots below should demonstrate the issue pretty well.
<img width="991" alt="Screenshot 2021-09-07 at 14 24 57" src="https://user-images.githubusercontent.com/83517584/132297123-5a66ec75-7488-4a1e-ac4d-dc5a1c9fe57f.png">
<img width="994" alt="Screenshot 2021-09-07 at 14 58 40" src="https://user-images.githubusercontent.com/83517584/132298771-7b123e80-2355-4bd6-a529-830e48866dd8.png">

As a note, the song above ("rain" from CCC2) has two steps, an "EZ 01:46" with "ED 04:05". The EZ difficulty is filtered correctly when the 0-120 length filter is applied. However, the group is not updated, it should be under 01:00-01:59.

If this doesn't introduce performance issue, it would be nice to fix.

**Comment by poco0317** [comment]
cannot reproduce on 0.71.2
