### ISSUE TITLE
[Snap colours] Wrong division on 1x9 skins when texture dimensions exceed texture resolution option in graphics

### ISSUE THREAD

**Issue by Jolomann** [etternagame/etterna#1062]
**Describe the bug**
Basically snaps get divided wrong in a skin with 9 snaps if dimensions of the note spritesheet exceed the "texture resolution" option under `Options->Graphics/Sound Options`

It's easily reproducible with `DivideByInf` while using texture resolution 256, since the note spritesheet is 576px height, exceeding the 256 option. Using 512 texture res would also work, but when using 256 you can confirm that the same conditions don't cause the issue on 8-snap skins (they usually have 512px textures, which don't exceed the 512 option). For example, the issue is *not* present in `DivideByZero` because it has 8 snaps

Presumably related to #935 but I can only guess

**To Reproduce**

The easy way
1. Set texture res to 256
2. Use `DivideByInf` noteskin
3. Observe wrong division
4. Set texture res to 512
5. Use `DivideByInf`
6. Observe correct division

The hard way
1. Use these under `[NoteDisplay]` in `metrics.ini`:
`TapNoteNoteColorCount=9`
`TapNoteNoteColorTextureCoordSpacingY=0.0625` (You need 0.0625 for 9 snaps, don't know don't ask. It should be 0.1111 but just stepmania things)
2. Pick a texture resolution in `Options->Graphics/Sound Options` that's lower than your note spritesheet's dimensions (If the sheet is 576, pick 256 or 512. If it's 1152, pick 1024, 512, or 256.
3. Use the skin
4. Snaps are now wrong
5. Pick a higher texture res than your notesheet's dimensions
6. Snaps are correct

**Expected behavior**
Divide the damn thing

**Screenshots**
1024 vs. 256 texture resolution option while using `DivideByInf`. both screenshots should have 4ths and 12ths but it's divided wrong with 256 texture res
![](https://cdn.discordapp.com/attachments/357630502296879104/894006769041424384/unknown.png)

**Version**
Etterna 0.70.3

**Comment by poco0317** [comment]
closely related #935

**Comment by poco0317** [comment]
Tested and verified issue exists on all versions of Etterna 0.50 - current
also exists on stepmania 5.0.9

**Comment by poco0317** [comment]
the 0.0625 is 1/16 which one way or another comes from a quirk of having a 9(?) framed texture with a height of a number not a power of 2, divided by its corresponding height adjusted upwards to be a power of 2. for example, 1 / 9 * 576 / 1024 is 0.0625. 1 / 9 * 1024 / 1024 is 0.1111.

i fixed this in a really really bad way by basically making the size of any noteskin element completely unlimited, and not bound by maxtexture size. the drawback of this is that you cant change the quality of your noteskins using the ingame settings (texture size...)
f768506a06c2a053e202ba76df476e7ec5bd926b

**Comment by Jolomann** [comment]
just wanna make sure i understand this correctly - following https://github.com/etternagame/etterna/commit/f768506a06c2a053e202ba76df476e7ec5bd926b, noteskin textures can exceed the normal 2048px limit without issues? if so, that'll be immensely useful for spritesheet animations

**Comment by poco0317** [comment]
all elements loaded as the result of noteskin loading (meaning all noteskin elements and anything you may add on to files via LoadActor at or before InitCommand) should have their texture size limits effectively removed by this. unless you have an image that is 1million x 1million
