### ISSUE TITLE
noteskins which utilize hold note heads(for example midi-note and its varients) either dont show the heads or show them on tail end of a hold note

### ISSUE THREAD

**Issue by bommy985** [etternagame/etterna#1077]
2 present issues, both involving hold notes
for reference, https://etternaonline.com/noteskins_repo/55dd5-midi-note.zip was used to diagnose the first issue, which is not present in stepmania 5,
while https://etternaonline.com/noteskins_repo/9e555-uswdefault9sm5.zip, and variants of such, was used to diagnose the second issue

issue one pertains to midi-note, hold note heads flat out do not show up at all in gameplay, when using the vivid variant included with the skin, it does show up, this issue does not occur on stepmania 5, on both versions, heads correlate to the scroll direction, even accounting for issues present,  heads do not show up at all with either scroll direction, vivid does show the heads, and is the only variant of the included noteskin to do so.

issue 2 is present on sm5, and I might possibly be an idiot who doesn't know how noteskin settings work, but regardless

heads  only show up as if up scrolling is used, regardless of weather upscroll or downscroll is used...that's really it for this issue.

**Comment by poco0317** [comment]
You need to explain your understanding as for what vivid is. I've used midi-note for 11 years and it's been like this the entire time. Hold heads do show up in gameplay, and there is no apparently explicit vivid version of the hold head given in the linked skin

**Comment by bommy985** [comment]
my understanding of what vivid is litterly "hehe color changing arrows"
I meant the vivid version of the skin included on midi-note, which does show hold heads, not in vivid format, but the green hold head alone, the rest do not appear for me at all, and seems broken to me in gameplay

1st problem, relating to midi note(the one where hold heads dont show up at all
![image](https://user-images.githubusercontent.com/61766076/140626598-c8ca6131-2bc7-4917-b929-ebf2df905b79.png)
2nd problem, relating to usdefault(where hold heads don't correlate to scroll direction
![image](https://user-images.githubusercontent.com/61766076/140626628-1bb7edf1-2655-4be1-ba7f-42e9d62bd47c.png)

**Comment by bommy985** [comment]
im stupid
