### ISSUE TITLE
Program Crash

### ISSUE THREAD

**Issue by Crab5316** [etternagame/etterna#1082]
Game always enter a Windows Boot Options like screen asking to start game, but after pressing start it always seems to go to the Error screen. Redownloading the game does not work nor does deleting it cache files.

I don't know how to recreate these steps for other to try it out but it says: Crash reason: Unhandled Microsoft C++ Exception
This is on Windows 64bit
![crashrpt](https://user-images.githubusercontent.com/51486384/142759106-6b073c14-57b8-4e0c-b80b-36e42fbf93d9.JPG)
![crashtxt](https://user-images.githubusercontent.com/51486384/142759109-aea00c37-5267-41fa-98e3-570964ba4619.JPG)

https://user-images.githubusercontent.com/51486384/142759113-e5efa4fe-f8a8-4ec1-bf8d-072471afbc87.mp4

**Comment by nico-abram** [comment]
It looks to me like you're missing some Theme files but I'm not sure. Is this a fresh install, or were you updating and overwriting a pre-existing installation?

**Comment by nico-abram** [comment]
Also, could you try editing C:\Games\Etterna\Save\Preferences.ini and changing `Verbosity=1` for `Verbosity=3` ?

Then run the game until it crashes again and share the crashinfo.txt and the log file (Should be in C:\Games\Etterna\Logs)

**Comment by Crab5316** [comment]
> 

00:00.009: Etterna0.70.3
00:00.010: (build )
00:00.010: Log starting 2021-11-21 20:55:59
00:00.010: 	Verbosity: 3
00:00.010:  
00:00.010: Failed to find Type commandline argument (Not required)
00:00.010: Reading 'Data/Defaults.ini' failed: No such file or directory
00:00.010: Failed to find Type commandline argument (Not required)
00:00.010: Reading 'Data/Static.ini' failed: No such file or directory
00:00.010: Failed to find Type commandline argument (Not required)
00:00.010: Reading 'Data/Static.ini' failed: No such file or directory
00:00.284: Loading window: win32
00:00.304: Windows 6.2 (Win8) build 9200 []
00:00.304: Memory: 16313mb total, 23481mb swap (6031mb swap avail)
00:00.304: Video driver: NVIDIA GeForce GTX 1650 SUPER [NVIDIA]
00:00.304:               30.0.14.9649, 10-20-2021 [pci\ven_10de&dev_2187]
00:00.304: Drive: "Samsung SSD 870 EVO 500GSVT0" Driver: storahci DMA: N/A
00:00.305: Drive: "NVMe    ADATA SX8200PNP SANA" Driver: stornvme DMA: N/A
00:00.329: Sound device 0: Speakers (High Definition Audio, 0.0, MID 1, PID 65535 
00:00.329: Sound device 1: 24G2W1G5 (NVIDIA High Definitio, 10.0, MID 1, PID 100 
00:00.330: Sound device 2: Speakers (Steam Streaming Micro, 10.0, MID 1, PID 100 
00:00.330: Sound device 3: Speakers (USB PnP Sound Device), 1.0, MID 65535, PID 65535 
00:00.331: Sound device 4: Speakers (Steam Streaming Speak, 10.0, MID 1, PID 100 
00:00.331: ThemeManager::SwitchThemeAndLanguage: "bare-frames", "en"
00:00.337: Loading "/Scripts/32log.lua" ...
00:00.337: Loading "/Scripts/extend_table.lua" ...
00:00.338: Loading "/Scripts/unavailable_functions.lua" ...
00:00.338: Loading "/Scripts/32log.lua" ...
00:00.338: Loading "/Scripts/extend_table.lua" ...
00:00.338: Loading "/Scripts/unavailable_functions.lua" ...
00:00.338: Loading "/Themes/_fallback/Scripts/00 init.lua" ...
00:00.338: Loading "/Themes/_fallback/Scripts/00 Utility.lua" ...
00:00.339: Loading "/Themes/_fallback/Scripts/01 alias.lua" ...
00:00.339: Loading "/Themes/_fallback/Scripts/01 base.lua" ...
00:00.339: Loading "/Themes/_fallback/Scripts/01 Functional.lua" ...
00:00.340: Loading "/Themes/_fallback/Scripts/01 IniFile.lua" ...
00:00.340: Loading "/Themes/_fallback/Scripts/02 Actor.lua" ...
00:00.340: Loading "/Themes/_fallback/Scripts/02 ActorDef.lua" ...
00:00.340: Loading "/Themes/_fallback/Scripts/02 Branches.lua" ...
00:00.340: Loading "/Themes/_fallback/Scripts/02 Colors.lua" ...
00:00.341: Loading "/Themes/_fallback/Scripts/02 Debug.lua" ...
00:00.341: Loading "/Themes/_fallback/Scripts/02 Enum.lua" ...
00:00.341: Loading "/Themes/_fallback/Scripts/02 OptionsMenu.lua" ...
00:00.341: Loading "/Themes/_fallback/Scripts/02 Other.lua" ...
00:00.341: Loading "/Themes/_fallback/Scripts/02 Serialize.lua" ...
00:00.342: Loading "/Themes/_fallback/Scripts/02 Sprite.lua" ...
00:00.342: Loading "/Themes/_fallback/Scripts/02 StageMods.lua" ...
00:00.342: Loading "/Themes/_fallback/Scripts/02 ThemePrefs.lua" ...
00:00.342: Loading "/Themes/_fallback/Scripts/02 ThemePrefsRows.lua" ...
00:00.342: Loading "/Themes/_fallback/Scripts/02 Utilities.lua" ...
00:00.343: Loading "/Themes/_fallback/Scripts/03 CustomSpeedMods.lua" ...
00:00.343: Loading "/Themes/_fallback/Scripts/03 DisplaySpecs.lua" ...
00:00.344: Loading "/Themes/_fallback/Scripts/03 Gameplay.lua" ...
00:00.344: Loading "/Themes/_fallback/Scripts/03 GamePreferences.lua" ...
00:00.344: Loading "/Themes/_fallback/Scripts/03 ThemeAndGamePrefs.lua" ...
00:00.344: Loading "/Themes/_fallback/Scripts/03 ThemeLibrary.lua" ...
00:00.344: Loading "/Themes/_fallback/Scripts/03 UserPreferences2.lua" ...
00:00.344: Reading 'Themes/_fallback/ThemeInfo.ini' failed: No such file or directory
00:00.345: Loading "/Themes/_fallback/Scripts/04 CreditsHelpers.lua" ...
00:00.346: Loading "/Themes/_fallback/Scripts/04 LogDisplay.lua" ...
00:00.346: Loading "/Themes/_fallback/Scripts/04 NumPadEntry.lua" ...
00:00.346: Loading "/Themes/_fallback/Scripts/04 pause_menu_helper.lua" ...
00:00.346: Loading "/Themes/_fallback/Scripts/04 SetBGFitHelpers.lua" ...
00:00.346: Loading "/Themes/_fallback/Scripts/09 PackList.lua" ...
00:00.347: Loading "/Themes/_fallback/Scripts/09 SimNSkinPreview.lua" ...
00:00.347: Loading "/Themes/_fallback/Scripts/10 AudioVisualizer.lua" ...
00:00.347: Loading "/Themes/_fallback/Scripts/10 FileUtils.lua" ...
00:00.347: Loading "/Themes/_fallback/Scripts/10 Scores.lua" ...
00:00.348: Loading "/Themes/_fallback/Scripts/10 settings_system.lua" ...
00:00.348: Reading 'Themes/bare-frames/ThemeInfo.ini' failed: No such file or directory
00:00.348: Loading "/Themes/_fallback/Scripts/10 Texts.lua" ...
00:00.348: Loading "/Themes/_fallback/Scripts/10 WifeSundries.lua" ...
00:00.348: Loading "/Themes/_fallback/Scripts/11 AssetsConfig.lua" ...
00:00.349: Loading "/Themes/_fallback/Scripts/12 AssetsUtils.lua" ...
00:00.349: Loading "/Themes/_fallback/Scripts/find_missing_lang_strings.lua" ...
00:00.349: Loading "/Themes/bare-frames/Scripts/Branches.lua" ...
00:00.567: WaveOut software mixing at 44100 hz
00:00.567: Starting thread: Decode thread
00:00.567: Starting thread: Mixer thread
00:00.567: Sound driver: WaveOut
00:00.567: Starting thread: Music thread
00:00.568: ThemeManager::SwitchThemeAndLanguage: "bare-frames", "en"
00:01.218: Loaded 2 songs from "Songs/Love Live! ITG Project Vol. 1"
00:01.445: Found 452 songs in 0.865000 seconds.
00:01.473: Profile::LoadAllFromDir( /Save/LocalProfiles/00000000/ )
00:01.473: Loading /Save/LocalProfiles/00000000/Etterna.xml
00:01.473: Done.
00:01.475: Calculating stats from scores
00:01.771: Attempting to connect to: multi.etternaonline.com, Port: 8765
00:01.771: Could not create ettp connection because: Connection creation attempt failed
00:02.239: Connected to ett server: multi.etternaonline.com
00:02.239: Server Version: 0 
00:02.249: Last seen video driver: NVIDIA GeForce GTX 1650 SUPER
00:02.249: Card matches '(unknown card)'.
00:02.249: Video renderers: 'd3d, opengl'
00:02.249: RageDisplay_D3D::RageDisplay_D3D()
00:02.276: Driver: nvldumdx.dll
00:02.276: Description: NVIDIA GeForce GTX 1650 SUPER
00:02.276: Max texture size: 16384
00:02.276: Alpha in palette: yes
00:02.276: 
00:02.276: This display adaptor supports the following modes:
00:02.279:   640x480 59Hz, format 22
00:02.279:   640x480 60Hz, format 22
00:02.279:   640x480 72Hz, format 22
00:02.279:   640x480 75Hz, format 22
00:02.279:   720x480 60Hz, format 22
00:02.279:   720x480 59Hz, format 22
00:02.279:   720x576 50Hz, format 22
00:02.279:   800x600 56Hz, format 22
00:02.279:   800x600 60Hz, format 22
00:02.279:   800x600 72Hz, format 22
00:02.279:   800x600 75Hz, format 22
00:02.279:   1024x768 60Hz, format 22
00:02.279:   1024x768 70Hz, format 22
00:02.279:   1024x768 75Hz, format 22
00:02.279:   1152x864 60Hz, format 22
00:02.279:   1176x664 50Hz, format 22
00:02.279:   1176x664 60Hz, format 22
00:02.279:   1176x664 59Hz, format 22
00:02.279:   1280x720 60Hz, format 22
00:02.279:   1280x720 59Hz, format 22
00:02.279:   1280x720 50Hz, format 22
00:02.279:   1280x768 60Hz, format 22
00:02.279:   1280x800 60Hz, format 22
00:02.279:   1280x960 60Hz, format 22
00:02.279:   1280x1024 60Hz, format 22
00:02.279:   1280x1024 75Hz, format 22
00:02.279:   1360x768 60Hz, format 22
00:02.279:   1366x768 60Hz, format 22
00:02.279:   1600x900 59Hz, format 22
00:02.279:   1600x900 60Hz, format 22
00:02.279:   1600x1024 59Hz, format 22
00:02.279:   1600x1024 60Hz, format 22
00:02.279:   1680x1050 59Hz, format 22
00:02.279:   1680x1050 60Hz, format 22
00:02.279:   1920x1080 60Hz, format 22
00:02.279:   1920x1080 59Hz, format 22
00:02.279:   1920x1080 75Hz, format 22
00:02.279:   1920x1080 50Hz, format 22
00:02.279:   1440x900 60Hz, format 22
/////////////////////////////////////////
00:02.279: WARNING: RageDisplay_D3D::TryVideoMode( 1, 1920, 1080, 32, 0, 0 )
/////////////////////////////////////////
00:02.280: Testing format: display 22, back buffer 20, windowed 1...
00:02.280: Testing format: display 22, back buffer 22, windowed 1...
00:02.280: This will work.
00:02.285: WM_ACTIVATE (0, 0): has focus
00:02.293: Testing format: display 22, back buffer 20, windowed 1...
00:02.293: Testing format: display 22, back buffer 22, windowed 1...
00:02.293: This will work.
00:02.293: Present Parameters: 1920, 1080, 22, 1, 0, 1, 6160816, 1, 1, 80, 0, 0, -2147483648
00:02.490: D3D Windowed 1920x1080 32 color 32 texture 75Hz NoVsync NoSmoothLines
00:02.490: RageInput::RageInput()
00:02.490: InputHandler_DInput::InputHandler_DInput()
00:02.503: InputHandler_DInput: IDirectInput::EnumDevices(DIDEVTYPE_KEYBOARD)
00:02.517: DInput: Enumerating device - Type: 0x00000413 Instance Name: "Keyboard" Product Name: "Keyboard"
00:02.634: InputHandler_DInput: IDirectInput::EnumDevices(DIDEVTYPE_JOYSTICK)
00:02.757: InputHandler_DInput: IDirectInput::EnumDevices(DIDEVTYPE_MOUSE)
00:02.766: DInput: Enumerating device - Type: 0x00000112 Instance Name: "Mouse" Product Name: "Mouse"
00:02.881: Opening device 'Keyboard'
00:02.882: Opening device 'Mouse'
00:02.882: Found 2 DirectInput devices:
00:02.882:    0: 'Keyboard' axes: 0, hats: 0, buttons: 256 (buffered)
00:02.882:    1: 'Mouse' axes: 3, hats: 0, buttons: 8 (buffered)

**Comment by Crab5316** [comment]
> It looks to me like you're missing some Theme files but I'm not sure. Is this a fresh install, or were you updating and overwriting a pre-existing installation?

It was a fresh install

**Comment by nico-abram** [comment]
oh, that's not a missing theme, it's bare-frames. Sorry, I got that wrong.

Thanks for the log, sadly I'm not seeing anything useful in it. Maybe someone else has an idea I don't.

After a new release happens this might be easier to debug if the crash server Hidden's been working on works.

What packs do you have installed? Maybe it's an issue with a specific simfile

**Comment by poco0317** [comment]
switch to til death from the options menu - display options - appearance

you are in bare-frames which does not work in 0.70.3
