### ISSUE TITLE
multiple instances detection is scuffed

### ISSUE THREAD

**Issue by poco0317** [etternagame/etterna#1087]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version Info

Latest available release

**Comment by nico-abram** [comment]
Hidden found out it's the window title matching. If the explorer title window is "Etterna" it will think the game is currently launched.

I will try to instead use a system wide winapi mutex as mentioned in https://stackoverflow.com/questions/18184019/use-win-api-to-determine-if-an-instance-of-an-executable-is-already-running to detect running instances. If I don't have this working by monday (13/11/2021) feel free to pick this up, that would mean I probably forgot about it

**Comment by nico-abram** [comment]
Ok, opened https://github.com/etternagame/etterna/pull/1093 which should fix this

**Comment by poco0317** [comment]
fixed 2f1d766dffdb99194433aa4e8cf29e59c0ca152f
