### ISSUE TITLE
[Bug]: ideal sync audio.ogg scales with current rate

### ISSUE THREAD

**Issue by OddBread** [etternagame/etterna#1091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

OddBread#3922

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Windows

### Bug Behavior

The ideal sync .ogg audio / offset calibration chart scales with the currently applied rate when opening the menu

### Expected Behavior

the file should always stay at 1.0x, and not scale with the currently applied rate

### Reproduction Steps

1. open game
2. go to 'game start' menu
3. choose a faster or slower rate (1.2x, for example)
4. open the settings menu via the gear icon
5. open the audio calibration tab
6. the file will now be sped up or slowed down based on what you chose 

### Anything else?

![image](https://user-images.githubusercontent.com/58830765/145662478-1f047aaf-91d3-43bf-9b2a-6bb8f9babafb.png)
the sync ogg audio on a rate higher than it is supposed to be (notice the bottom right)

**Comment by poco0317** [comment]
fixed ac855747c96814a4296aa463ea7c3110c10cd583
