### ISSUE TITLE
Scores that aren't for the current song/difficulty can show anyway

### ISSUE THREAD

**Issue by PCBoyGames** [etternagame/etterna#1103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Windows

### Bug Behavior

On songs with nine or fewer scores, it is possible to go through the Score tab and reset it only to find there are now either more scores than there were before (which are scores from different songs/difficulties), or there will be white spaces where scores would go. Switching the song, the difficulty, or scrolling on the board will temporarily fix this.

### Reproduction Steps

1. Look for any song that is either unranked, unscored, or that has nine or fewer scores (using Top Scores might help).
2. Switch to the Scores tab.
3. Switch to the Online section.
4. Right-click to open the Scores in the General tab.

### Anything else?

[This video](https://www.youtube.com/watch?v=t0Vvj6s0sgA) demonstrates the bug in action. Seems like whoever this "Lucky" is might be the one to get in touch with if you ever want to have four or more personalities.

**Comment by poco0317** [comment]
fixed 6a2a963470018741a21b12c2da8ac6cc5bb7586f
