### ISSUE TITLE
[Bug]: When entering a song, game loads the wrong difficulty

### ISSUE THREAD

**Issue by aoskarih** [etternagame/etterna#1104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

planckcons#0002

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Windows

### Bug Behavior

The selected difficulty shown while in the musicwheel is different than the one that is loaded when entering the song.

For example: In the musicwheel the selected difficulty is "IN" and the one that starts playing is "HD"
Attached is video showing:
1. Exiting the previous song
2. Selecting next song (the selected difficulty is shown as IN)
3. The loaded chart is the HD difficulty

https://user-images.githubusercontent.com/12530148/145721794-6f9a86b0-b97c-44da-bc2a-5f941341a6df.mp4

.

### Expected Behavior

If the musicwheel shows for example the IN difficulty it is expected that when entering the song, the loaded difficulty will be IN.

### Reproduction Steps

I could not find a way to consistently reproduce the bug. 
- It can happen when the song is the first in the session
- It can happen after playing song with multiple or single difficulty
- The difficulty (IN, HD, ...) of the previous song doesn't seem to affect the chance
- I couldn't reproduce it with every song I tried, but it can happen with at least "Happy H. Christmas" in stepping stones 4
- If the song has 3 difficulties both of the 2 non-selected difficulties can be the one that starts.

**Comment by Lucien0001** [comment]
Do you mash the keys that you have bound to MenuUp and MenuDown before starting the chart? If so, try not doing that, as that stopped this behavior for me when I was having this same issue.

**Comment by aoskarih** [comment]
Okay I tested it and that was the cause. After pressing enter when entering a song there is a small window where you can still change the difficulty.

**Comment by poco0317** [comment]
fixed 9877c2a2eb1a788809ec76438996f725a224dcf6
