### ISSUE TITLE
custom aspect ratios are reset when closing settings if you had opened the graphics tab

### ISSUE THREAD

**Issue by velaachlorine** [etternagame/etterna#1107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version Info

Latest available release

### Bug Behavior

in rebirth, with a custom aspect ratio and resolution set in preferences.ini (in my case 1366x715, 1.910490)
open the settings tab, go to the graphics tab and then try to close settings

**Comment by poco0317** [comment]
fixed 833c33c5168186c84a3d2dd58058180e58a47323
