### ISSUE TITLE
[Bug]: Game crashes randomly 

### ISSUE THREAD

**Issue by ghost** [etternagame/etterna#1110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version Info

Compiled from develop

### What operating system are you seeing the problem on?

Linux (any distro)

### Bug Behavior

I am launching a fresh build of the game and trying to well, play Etterna.

Game crashes with this error message in console:
```
[2021-12-18 09:43:21][FATAL]: to_move >= 0
[20637:20637:20211218,094321.267832:WARNING exception_snapshot_linux.cc:427] Unhandled signal -1
```

### Expected Behavior

The game doesn't crash

### Reproduction Steps

1. Build the game
2. run the game
3. wait

### Anything else?

I don't have any songs downloaded so this is from the screen you see when you start the game with no songs.

uname -a:
```
Linux celes 4.16.18-galliumos #1 SMP PREEMPT Sun Jun 23 04:14:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by poco0317** [comment]
the location of crash here is extremely vague, although it may appear to be specific. we need a particular condition to cause it

**Comment by wozniak** [comment]
It literally just happens randomly. When playing a song, when in the main menu, when downloading packs.

**Comment by nico-abram** [comment]
@wozniak Do you still get this crash? Were you able to figure out anything about it, ideally how to reproduce it?

If you're still experiencing it maybe compiling the game with debug info and get the game to generate a core dump on crash, which might give us more info like a backtrace/callstack. If needed, you could join the development discord and I might be able to help you with that

**Comment by poco0317** [comment]
this bug makes sense to happen if the system clock moves backwards

**Comment by poco0317** [comment]
no re-reports and OP account deleted
