### ISSUE TITLE
[Bug]: Case sensitivity for "artist=", "subtitle=", etc. when searching in Rebirth

### ISSUE THREAD

**Issue by quaristice** [etternagame/etterna#1113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Windoze#5122

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Windows

### Bug Behavior

When searching in Rebirth, you can do "artist=" to search for text in the artist field. However, this only works with "artist" being entirely lowercase. If anything is uppercase, it does not work, and instead interprets the "artist=" as part of a song title. The same happens for the other fields.

### Expected Behavior

Case sensitivity should not matter, so "ARTIST=" or "ArTiSt=" should both be interpreted the same way as "artist=".

### Reproduction Steps

1. Run the game
2. Select "Game Start"
3. Search for an artist, subtitle, or any non-title field through typing "[field]=", but with capitalization in the field.

**Comment by poco0317** [comment]
78fac4636abd4b9289d6b3c6a3cd63aed31dc15f
