### ISSUE TITLE
[Feature Request]: Rebirth local leaderboard

### ISSUE THREAD

**Issue by Bestfast** [etternagame/etterna#1115]
### Is there an existing issue for the feature?

- [X] I have searched the existing feature requests

### Describe the Feature

In rebirth you can enable the leaderboard overlay to show up while playing a song (pretty much like multiplayer)
In 0.71.1 it's only possible to have online leaderboard as an overlay, but I think it would be a nice addition to being able to switch between online and local leaderboard.

### How Does The Feature Add To The Game?

The overlay is already there. My idea was to change the scores in the leaderboard with local scores (including rate up/down scores).
It will first prioritize MSD over acc, and when there are 2 scores with the same MSD (for example in the case where you are going for acc scores and MSD is capped) prioritize acc. 
There are probably better way of implementing this though

**Comment by poco0317** [comment]
17d91f062f2bafb650c7d29d02bb1d4dd163b937
