### ISSUE TITLE
[Feature Request]: disable holding Start to give up as an options parameter (bHoldingGiveUp)

### ISSUE THREAD

**Issue by formi** [etternagame/etterna#1116]
### Is there an existing issue for the feature?

- [X] I have searched the existing feature requests

### Describe the Feature

I'd like to have an option to disable holding the Start-button giving up the current play of a chart after a few seconds while still being able using it. So Start will trigger playing a selected chart as well as opening the options menu while holding/tapping it when a chart starts but not being able to give up a current play.

### How Does The Feature Add To The Game?

This feature allows players using a 5-Panel input device to keep standing in center while playing charts and still being able to use the center-button as a Start-button.

### Additional Context

The "Hold to give up" seems to be hardcoded to the start key in the C++ code:

if (m_DancingState != STATE_OUTRO && GAMESTATE->IsHumanPlayer(input.pn) &&
        !m_Cancel.IsTransitioning()) {
        /* Allow bailing out by holding any START button. */
        auto bHoldingGiveUp = false;
        if (GAMESTATE->GetCurrentStyle(input.pn)->GameInputToColumn(
              input.GameI) == Column_Invalid) {
            bHoldingGiveUp |= (input.MenuI == GAME_BUTTON_START);

---

The current workaround is to:

add to [ScreenGameplay] in */Languages/en.ini of the used theme
GiveUpAbortedText=
GiveUpStartText=

add to [Common] in metrics.ini of the used theme
GiveUpSeconds=99999

**Comment by poco0317** [comment]
done 719651388ee54023224b32990946ef4c61b9b917
