### ISSUE TITLE
Change download folder for in-game downloads

### ISSUE THREAD

**Issue by Sklitterbeer** [etternagame/etterna#1121]
When using the in-game downloader to download packs, I noticed it downloads to the "primary" folder on my C drive as opposed to my HDD where I have a lot more space. Would it be possible to add the option of downloading to one of the AdditionalSongFolders? 
Thank you

**Comment by poco0317** [comment]
this has been an option since etterna 0.60

preferences.ini -> downloadPacksToAdditionalSongs
