### ISSUE TITLE
[Bug]: Double clicking on "Options" in menu too fast crashes game

### ISSUE THREAD

**Issue by TrentTheTrumpCard** [etternagame/etterna#1124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

TrentTheTrumpCard#3557

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Windows

### Bug Behavior

I can't double click fast enough with a single mouse button, but with left and right at the same time it crashes.

### Expected Behavior

It should just go to the options like normal

### Reproduction Steps

1. Run the game
2. Click "Options" with both left and right mouse buttons
3. Profit

### Anything else?

[b8f58004-aec5-4b0b-ac4f-cf53ad1aac68.zip](https://github.com/etternagame/etterna/files/7916203/b8f58004-aec5-4b0b-ac4f-cf53ad1aac68.zip)

**Comment by poco0317** [comment]
fixed 651b6cbe9f77bf4c6748e374904ec1c1b678703e
