### ISSUE TITLE
[Bug]: Pine Nut Hyeon replay finishing crashes game

### ISSUE THREAD

**Issue by g-robertson** [etternagame/etterna#1127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

NNNN#9545

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Linux (any distro)

### Bug Behavior

When finishing hyeon's pine nut replay the game immediately crashes

### Expected Behavior

The game should go to the results screen

### Reproduction Steps

1. Go to Pine Nut in Attang's Dumpmix
2. Open Hyeon's score replay
3. Let it play through (or fast forward through it, or just click the results button, all will result in a crash)

### Anything else?

I can't seem to get this to happen for any other replay, even on the same song and on similarly low accuracy scores.
It's the only online score I can find where it looks like the player fails out in the song replay.

The results screen button also causes a crash for this score.

**Comment by poco0317** [comment]
the systems involved in causing this crash no longer exist ea3e98f0b126bc5e63c190c8ef5206ad003169e3
