### ISSUE TITLE
[Feature Request]: Allow judge counter to be zoomed

### ISSUE THREAD

**Issue by g-robertson** [etternagame/etterna#1130]
### Is there an existing issue for the feature?

- [X] I have searched the existing feature requests

### Describe the Feature

A zoom thing for customize gameplay for judge counter

### How Does The Feature Add To The Game?

It would let people (bommy985) zoom the judge counter in game

**Comment by poco0317** [comment]
40896582bad30257ef20137853e9fd4eff6e6044

**Comment by poco0317** [comment]
needs to be done for til death but we also need more keys on the keyboard
