### ISSUE TITLE
[Feature Request]: Main Menu Music Player

### ISSUE THREAD

**Issue by Lucien0001** [etternagame/etterna#1134]
### Is there an existing issue for the feature?

- [X] I have searched the existing feature requests

### Describe the Feature

Currently, the main menu has no music. It would be nice if it could be used as a jukebox of sorts, kind of like how osu! does it. Could use packs as a playlist of sorts or have a shuffle function to shuffle music from every pack.

### How Does The Feature Add To The Game?

Since a lot of players have close to 100gb of music, it would be nice to be able to use the game as a music player of sorts. It would also allow players to potentially discover some songs they've never played before but enjoy and decide to play.

**Comment by MaliciousFace** [comment]
The Rebirth Theme has this and its awesome. If possible id like to see it in Til' Death aswell.

**Comment by poco0317** [comment]
3a85e9ff1bc33b162d6db6be0666e6889635457a
