### ISSUE TITLE
[Feature Request]: Better Personal Best Tracker and Better Tracking Display

### ISSUE THREAD

**Issue by Lucien0001** [etternagame/etterna#1137]
### Is there an existing issue for the feature?

- [X] I have searched the existing feature requests

### Describe the Feature

Currently, the game only uses a set percentage when using the personal best tracker. This should either be updated or include a separate mode that takes into account your score at given points throughout a map (for example, consistently missing on one section halfway through the map boosting your acc for the first half of the chart and then the second half is a considerably lower percentage.) A potential upgrade to this could also utilize the goal tracker as mentioned in [#646](https://github.com/etternagame/etterna/issues/646) to adapt the scaling of the goal percentage with potential problem areas in a chart (diffspikes that are normally cbrushed or good rushed within a given chart for lower acc or perfect rushed when setting acc scores.) Additionally, an optional better display for viewers could be accommodated through use of a display similar to that of the one found in [Staiain's ultralight edit](https://www.youtube.com/watch?v=MjCem4UgZyc)

### How Does The Feature Add To The Game?

For players, a better in-game tracker would mean players are better able to know when they're on a run that is on PB or goal pace. For viewers, a display similar to that of the ultralight theme mentioned above would make the viewing experience more exciting, as one would know when a player is close to a good score.

**Comment by poco0317** [comment]
i stopped reading at "given points throughout"
this does that thing in the next release 4e35669afc38177b8c6478bdd5324b331fe51285
