### ISSUE TITLE
[Bug]: Judgement Select Preview Images Look Very Blurry In Rebirth

### ISSUE THREAD

**Issue by bluebandit21** [etternagame/etterna#1141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version Info

Latest available release

### What operating system are you seeing the problem on?

macOS

### Bug Behavior

The preview images of judgements from the Rebirth asset selection screen look awful.
<img width="517" alt="Screen Shot 2022-03-02 at 7 37 30 PM" src="https://user-images.githubusercontent.com/32799046/156473921-907e3877-d3fb-4571-9c9f-e539ce2c4324.png">

As seen in the above screenshot (which is not compressed in any way!!), judgement preview images are a blurry mess in Rebirth.
The other assets (e.g. avatar as seen below) don't seem to suffer from the same problem.
<img width="410" alt="Screen Shot 2022-03-02 at 7 42 47 PM" src="https://user-images.githubusercontent.com/32799046/156474083-92106c56-773d-4f8b-a199-05530a870fa1.png">

### Expected Behavior

Judgement selection previews should be clear and crisp like in Til Death

<img width="701" alt="Screen Shot 2022-03-02 at 7 43 50 PM" src="https://user-images.githubusercontent.com/32799046/156474186-943d4a46-0acb-4041-81cd-7ea1e50ece70.png">

**Comment by poco0317** [comment]
73452e325f4dd0d7198c8b7d0c93f7da26f51491
