### ISSUE TITLE
[Bug]: Etterna Rebirth reliably crashes on "Game Start" on OSX Monterey (12.0.1)

### ISSUE THREAD

**Issue by rreed** [etternagame/etterna#1144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Reply to the issue, or meow@amdusi.as

### Version Info

Latest available release

### What operating system are you seeing the problem on?

macOS

### Bug Behavior

The game crashes 100% of the time on pressing `Game Start` on OSX 12.0.1.

### Expected Behavior

The song list should have loaded.

### Reproduction Steps

- open Etterna from the dock
- click "Accept" on the crash logs upload popup
- press Enter on "Game Start"
- the game crashes and writes a `.dmp` file to `/Applications/Etterna/CrashFiles/completed`

### Anything else?

Here's a zipfile of three recent crash dumps.

[EtternaCrashes.zip](https://github.com/etternagame/etterna/files/8238740/EtternaCrashes.zip)

The only thing in Songs is a years-old zenius-i-vanisher dump of In The Groove 1.

All other menus seem to work perfectly; I'm able to modify inputs, navigate the main menu, etc just fine.

A random person on Reddit seems to have had [my exact issue](https://www.reddit.com/r/Stepmania/comments/iboz2q/etterna_crashes_upon_entering_song_select_screen/) two years ago, but left no further context; they were also on a much older version of OSX than I am (unsurprisingly).

I do not know if this has worked before because I've been out of rhythm games for a while and, since leaving and returning, Stepmania stopped working on OSX. So I need new software. :)

**Comment by poco0317** [comment]
the crash reason given for one of these is interestingly related to the notefield preview
https://crash.etterna.dev/crash-reports/88fc97af-a43d-4390-a38b-c5a2a46472f7

do you have any songs installed?

**Comment by rreed** [comment]
> The only thing in Songs is a years-old zenius-i-vanisher dump of In The Groove 1.

I can try pulling new songs from somewhere else if we think it's just a very old format thing?

**Comment by poco0317** [comment]
you could try switching themes

main menu - options - display options - appearance options - theme -> Til Death or Rebirth

**Comment by rreed** [comment]
Ah, well! Rebirth was what was already selected (and what was crashing), but Til Death gets me to the song selection screen just fine. 

Computers! The worst!

**Comment by poco0317** [comment]
hmmmmm

**Comment by rreed** [comment]
I'm fine if you close this, because I do at least have a workaround now, but I also understand as a fellow software-screamer-atter if you want to keep it open to debug. :p

**Comment by poco0317** [comment]
there are known mac crashes on rebirth and notefieldpreview crashes which both need to be discovered and covered so i will leave this opened until i look at what may have precisely caused it and attempted to cover it up

**Comment by poco0317** [comment]
tried somethin maybe it will be fixed next release 911061a5b1f3f2851965290b9283233682429067
