### ISSUE TITLE
[Feature Request]: Associate a profile to a gamemode

### ISSUE THREAD

**Issue by g-robertson** [etternagame/etterna#1149]
### Is there an existing issue for the feature?

- [X] I have searched the existing feature requests

### Describe the Feature

Allow a player to have a default gamemode tied to a given profile

Example of what this might look like:
![image](https://user-images.githubusercontent.com/39735358/158274954-79952516-7bfd-4729-828b-1cee3a127ed3.png)

### How Does The Feature Add To The Game?

People who play on multiple different gamemodes usually do so with separate profiles for each gamemode, this would allow you to just select the profile that you want to play with, instead of swapping gamemodes and then selecting that profile.

**Comment by poco0317** [comment]
I would like to trash this issue in favor of eventually migrating the entire game to a scenario in which only "one" gamemode is present and easily sortable/filterable. This type of issue would be recreated at that point in time to request the ability to set profile specific filter defaults. Remake the issue at that time if the desire persists
