### ISSUE TITLE
[Bug]: all sound gone

### ISSUE THREAD

**Issue by taaigo** [etternagame/etterna#1151]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Contact Details

discord: taigo#8744

### Version Info

Compiled from develop

### What operating system are you seeing the problem on?

Linux (any distro)

### Bug Behavior

there's no sound anywhere in the game on a manual compile. However the sound seems to work on the linux pre-compiled release.

### Expected Behavior

When booting after compiling it should output sound of the game.

### Reproduction Steps

1. compile
2. run the game
3. play like normal and notice there's no map or menu sounds

**Comment by zoey-on-github** [comment]
Did you do the first troubleshooting steps like restarting your system, trying another compile, etc? 
If you have, you said "linux(any distro)", what distros have you tried compiling etterna on? 
Could you provide your log file(s), please?(IIRC, these are located in a folder called `logs`)

**Comment by taigochan** [comment]
I tried compiling and running on arch Linux. I have indeed tried restarting, I also tried compiling it on a different system that also runs the same distro but the issue was still there. I can't try anything else right now because I'm at school but when I get home I will try searching through the logs and upload them here as well.

**Comment by zoey-on-github** [comment]
i'll try compiling etterna from source on my arch machine to see if this also happens for me. 

also, what are you using for sound?

**Comment by taigochan** [comment]
I don't have the installation anymore (it got corrupted 💀) but I think I used alsa and pulseaudio, I'm not sure but that's what I would usually use.

**Comment by zoey-on-github** [comment]
out of curiosity, did you do another arch install and did this same issue occur for you?

**Comment by taigochan** [comment]
no, I used a different device that already had a different arch install.

**Comment by taigochan** [comment]
Yeah the issue was still there, i think i might try again because i now have an install with pipewire and alsa instead of alsa and pulseaudio and see if the issue is still there.

**Comment by taigochan** [comment]
Im done compiling and it seems the sound works when using pipewire
