### ISSUE TITLE
[Bug]: Exiting a replay while it's loading sometimes wipes your modifiers (noteskin, scroll speed, etc)

### ISSUE THREAD

**Issue by velaachlorine** [etternagame/etterna#1152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Windows

### Bug Behavior

this happens when entering a replay and mashing escape on the black transition screen and on a certain time window; playing a file in this state will load dbz and use xmod 1
![image](https://user-images.githubusercontent.com/53107421/159508444-188a8900-fab9-4e88-8e87-bbb992b88156.png)
A score set in this state shows as having no modifiers besides overhead
![image](https://user-images.githubusercontent.com/53107421/159508759-ed67b976-b0b7-431e-ae86-1cd2176b54ed.png)
this used to crash pre-0.71 but it doesn't anymore

**Comment by poco0317** [comment]
should be fixed by the latest replay changes
