### ISSUE TITLE
[Bug]: Scrolling certain packs causes "RageBitmapTexture: Couldn't load <File>: Too many open files"

### ISSUE THREAD

**Issue by zhulov3rz** [etternagame/etterna#1155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

You can reply here or get my attention faster on twitter @zhu346p

### Version Info

Latest available release

### What operating system are you seeing the problem on?

macOS

### Bug Behavior

Tested on MacOS both 11.6 and 12.3 (other OS versions untested) with Apple Silicon M1 translated with rosetta2

If a pack contains video assets, scrolling through of them will cause a "Too many open files" prompt to come up and keep recurring. On version 0.71.1 you may crash to the crash handler but I have not gotten this on 0.71.2 yet.

For some reason crashing to the crash handler on MacOS didn't give me a crashlog text file. Despite this happening numerous times in the past few months testing it out my crash folder is empty.

### Expected Behavior

You should be able to scroll normally without encountering error popups, regardless of whether the pack contains videos or not.

### Reproduction Steps

1. Run the game
2. Select a pack that contains songs that have video assets
3. Scroll through the list of songs for about a minute
4. The errors will start popping up

[Refer to this video for the reproduction steps. ](https://www.youtube.com/watch?v=1UcEvgdYMvI)

Both tests done with the same pack. 
Folder titled "Crash" has all the video assets like a normal download would.
Folder that is titled normally has all video assets (.mp4, .avi) removed and does not crash regardless of how long I scroll the list.

Here are the logs from the runs in the video:

[2022_04_08-10_44_36.log](https://github.com/etternagame/etterna/files/8448172/2022_04_08-10_44_36.log)
[2022_04_08-10_48_38.log](https://github.com/etternagame/etterna/files/8448174/2022_04_08-10_48_38.log)

### Anything else?

I have done a lot of testing over the last few months to determine what causes this. If you delete mp4 files but keep avi files, it still returns the issue. Same happens if you only delete avi files.

In general there seems to be something weird with the handling of video on macOS. Not sure if this is apple silicon specific but the reason this test is done with 'Til Death is because if you try this with Rebirth and the pack thumbnail is a .mp4, the folder icon containing a mp4 thumbnail causes a crash that bypasses the crash handler, and returns you an OS crash dump (segfault). (Obviously a separate issue but still both tests lead me to believe that video files are the issue here)

**Comment by nico-abram** [comment]
@zhulov3rz could you recommend a specific pack to reproduce this crash with?

**Comment by zhulov3rz** [comment]
> @zhulov3rz could you recommend a specific pack to reproduce this crash with?

In the video I used https://forums.etternaonline.com/t/6k-the-idolm-ster-cinderella-girls-solo-project-iii/3486 as it is a nice pack bundled with a lot of video resources.

**Comment by nico-abram** [comment]
Thanks @zhulov3rz !

I tested on windows, and while the crash itself does not happen, I can reproduce the problem. Here's a screenshot of the file handles open after scrolling through the pack a couple times:
![imagen](https://user-images.githubusercontent.com/24706838/170572340-d1e4eb59-48a5-4d76-b6c6-ebd5ef199426.png)

(Obtained using [Process Hacker](https://processhacker.sourceforge.io/) )

It's clear that the ".avi" files are open multiple times. The files were not closed even after reloading metrics, scripts, etc, or even when changing themes. I'll see if I can figure out a fix now that I can repro.

**Comment by nico-abram** [comment]
Sent https://github.com/etternagame/etterna/pull/1176 with a fix for the leak I saw on windows, which I'm assuming is the cause for the crash on macOS.

@zhulov3rz Could you test that patch to see if it fixes the crash on mac? In ~20 minutes the `.dmg` should be available for download at https://github.com/etternagame/etterna/actions/runs/2393397108 at the bottom under "Artifacts" with the name "Etterna - macOS x64 "

**Comment by zhulov3rz** [comment]
@nico-abram Thanks for the patch. I've tested it and I haven't gotten a crash since even after many minutes of scrolling. It seems to have properly resolved that file leak as far as I can tell.

**Comment by nico-abram** [comment]
Thanks for testing it
