### ISSUE TITLE
[Feature Request]: I would like to put an animation in the combo text

### ISSUE THREAD

**Issue by itsmekiller360** [etternagame/etterna#1156]
### Is there an existing issue for the feature?

- [x] I have searched the existing feature requests

### Describe the Feature

I have the rebirth theme in etterna and I have a doubt, and it is the following, and it is that I would like to put an animation of the text combo as in spawncamping wallhack of etterna or 02jam style and I have tried to find a way to do it, but no I find it, does anyone know how to put an animation to a theme?

### How Does The Feature Add To The Game?

i would propose an option that you have to put a combo animation option in the theme options for people who like to have a combo animation while playing

**Comment by poco0317** [comment]
in til death this is an option in theme options: 
![image](https://user-images.githubusercontent.com/2531164/207220660-7f50fd15-a34a-4297-9932-61299d0845b7.png)


i have added this as an option in in rebirth settings under gameplay elements for the next update:
![image](https://user-images.githubusercontent.com/2531164/207224345-68b137c3-1b3b-4336-a4ab-30795b41f665.png)

626cc92a789bef71dabd3d6d36e35fc3fc74da78
