### ISSUE TITLE
[Bug]: No background

### ISSUE THREAD

**Issue by succy1** [etternagame/etterna#1157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Windows

### Bug Behavior

Misread file location which lead to no background when playing

### Expected Behavior

Expected the game to read from Etterna/Songs/.../bg.jpg instead of Etterna/BackgroundEffects/Songs/...

### Reproduction Steps

Play any song

### Anything else?

![image](https://user-images.githubusercontent.com/104383733/165142966-47bf4264-40e4-4fe0-8f4b-f99d52d9ac45.png)

**Comment by poco0317** [comment]
this is one of those things where if you dont tell me how you triggered it i have no idea what happened and it will never be fixed

**Comment by succy1** [comment]
i just installed the game fresh, didn't touch any setting or folders except for songs folders.
game start > select a song > play > then this error pop up

**Comment by poco0317** [comment]
send preferences.ini from the /save/ folder

**Comment by poco0317** [comment]
fixed bfe659cdc8706f7527de19e26cca753fdebe0623
to resolve this issue temporarily, do not put songs directly in the Songs folder. they should be in a group.
`Songs/ccc2/song name/something.sm`
