### ISSUE TITLE
Using keyboard shortcuts to exit search trigger in search

### ISSUE THREAD

**Issue by DDMythical** [etternagame/etterna#117]
I.e. hitting Ctrl+1 to leave from search into general will type 1 into the search, potentially fucking up your search.

This is a really big annoyance for me as i pretty much only use keyboard commands to navigate etterna.

Suggested fix: While holding down CTRL trigger no input on search, so hitting CTRL + 1 will not trigger the input and take you off the screen normally.

**Comment by Nickito12** [comment]
I'm almost sure the current develop branch had a change to only allow numeric input during search while pressing control, and cancel tab-changing while pressing control (More or less the opposite of what you're proposing) so this should not be an issue next release

**Comment by DDMythical** [comment]
ah ok; sorry. close this or whatever
