### ISSUE TITLE
[Bug]: Weird crash inside OpenSSL functions for some OSX High Sierra users

### ISSUE THREAD

**Issue by bluebandit21** [etternagame/etterna#1186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version Info

Latest available release

### What operating system are you seeing the problem on?

macOS

### Bug Behavior

Multiple OSX High Sierra users have encountered a crash within OpenSSL when trying to open the game.

The crash is consistently within ssl3_write_bytes transitively called by DownloadManager::UpdateHTTP.

A workaround is having them disable their wifi when starting the game and re-enable it after it opens.

Attached below are some crash dumps that may or may not be helpful.

### Anything else?

* Discord user tomate:
[Troubleshooting history (Main Server)](https://discord.com/channels/339597420239519755/982839506141081690/982839554992128090)
[Crash dump](https://github.com/etternagame/etterna/files/8839248/crash1.txt)

* Discord user [IN]insanity435
[Troubleshooting history (Dev Server)](https://discord.com/channels/261758887152058368/344545197914456068/942520695852769340)
[Crash dump](https://github.com/etternagame/etterna/files/8839256/crash2.txt)

* Discord user Itsumi
[Troubleshooting history (Main Server)](https://discord.com/channels/339597420239519755/389194939881488385/957528646518734888)
[Crash dump](https://github.com/etternagame/etterna/files/8839265/crash3.txt)

**Comment by bluebandit21** [comment]
Encountered by another user just now (using 71.2)

Discord user jorgex_77osu
[Crash dump](https://discord.com/channels/339597420239519755/1058110411674767380/1058110411674767380)

**Comment by bluebandit21** [comment]
Some additional information:

The crash (at least for one El Capitan user on the EO server) appears to be caused by the symbol `____chkstk_darwin` not being present within `/usr/lib/libSystem.B.dylib`

Some online searching (https://github.com/nodegui/nodegui/issues/391) suggests that this might be caused by CMake targeting too recent a macOS version, with the configuration variable `CMAKE_OSX_DEPLOYMENT_TARGET` possibly offering a solution.

I attempted to use ^ but it did not seem to fix the problem for the user. (However, it's very possible I just incorrectly set it within the CMake files)

**Comment by bluebandit21** [comment]
Had an idea that might let us hackily + easily fix this. 

What's the **real** problem?
-- Dyld can't lazily bind `____chkstk_darwin` because it simply doesn't exist.
However, the function doesn't _do_ anything we care about; it's just to check for stack smashing occurring and abort if detected. It's a void(void) function!

What if we can make our own libSystem.B.dylib containing a stub `____chkstk_darwin` and use dynamic library preloading shenanigans to let our stub version be found when dyld tries to find the real version?

**Comment by poco0317** [comment]
related https://github.com/etternagame/etterna/issues/1330

**Comment by bluebandit21** [comment]
Oops- - this should have been closed when #1306 was merged...
