### ISSUE TITLE
[Bug]: Cannot map some keys on Turkish keyboard layout 

### ISSUE THREAD

**Issue by kaanyalova** [etternagame/etterna#1187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Reply to this issue 

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Linux (any distro)

### Bug Behavior

I cannot map to any of the "Turkish keyboard layout spesific keys" such as "Ö" , "Ç", "Ü", "Ğ", "Ş"  even after I change my keyboard layout to English. 

This is how Turkish keyboard layout looks like:
![](https://upload.wikimedia.org/wikipedia/commons/6/63/KB_Turkey.svg)

### Expected Behavior

Turkish spesific keys should be mapped like other keys.

### Reproduction Steps

1. Start the game with a keyboard with Turkish layout
2. Select Config Key/Joy Mappings 
3. Try to set any of the keys to a Turkish-specific character
4. Nothing happens

**Comment by poco0317** [comment]
related/duplicate #238

**Comment by poco0317** [comment]
to confirm, are you using the key config that can be found in the main menu options, or are you using the key config that can be found in the settings menu on music select? both mostly use the same system with some subtle differences

**Comment by kaanyalova** [comment]
> to confirm, are you using the key config that can be found in the main menu options, or are you using the key config that can be found in the settings menu on music select? both mostly use the same system with some subtle differences

I am using the one in main menu options

**Comment by poco0317** [comment]
bandaided by 2b5eab976476e026c61999ac3f7e7ce59ac41362 adc00bcace9b7728c5849210605dbf930443c432
