### ISSUE TITLE
[Build Issue]: 

### ISSUE THREAD

**Issue by jONALDjONALD** [etternagame/etterna#1189]
### Have you read through the build instructions before reading this?

- [X] I have read the build instructions

### What operating system are you seeing the problem on?

Linux (any distro)

### Describe the build issue

when attempting to run _make_ from master or develop my terminal outputs error 1&2 on LMDE 5.

### Relevant log output

```shell
jonald@big:~/etterna-master/build$ make
[  0%] Performing gn_configure step for 'crashpad_init'
Done. Made 76 targets from 27 files in 4ms
ninja: Entering directory `/home/jonald/etterna-master/build/gn_crashpad'
[15/207] ACTION //third_party/mini_chr...omium/build/config:gcc_like_toolchain)
FAILED: gen/build/chromeos_buildflags.h 
python ../../extern/crashpad/crashpad/third_party/mini_chromium/mini_chromium/build/write_buildflag_header.py --output build/chromeos_buildflags.h --rulename //third_party/mini_chromium/mini_chromium/build:chromeos_buildflags --gen-dir gen --definitions gen/build/chromeos_buildflags.h.flags
/bin/sh: 1: python: not found
[24/207] CXX obj/third_party/mini_chro...synchronization/base.lock_impl_posix.o
ninja: build stopped: subcommand failed.
make[2]: *** [extern/crashpad/CMakeFiles/crashpad_init.dir/build.make:105: gn_crashpad/src/crashpad_init-stamp/crashpad_init-gn_configure] Error 1
make[1]: *** [CMakeFiles/Makefile2:1847: extern/crashpad/CMakeFiles/crashpad_init.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

**Comment by poco0317** [comment]
missing python 2 installation

**Comment by jONALDjONALD** [comment]
how odd, terminal outputs I have python 2

**Comment by jameskr97** [comment]
Could you please post your output for:

```
$ which python
$ python -v
```

Thank you

**Comment by jONALDjONALD** [comment]
jonald@big:~$ python -v
Command 'python' not found, did you mean:
  command 'python3' from deb python3
  command 'python' from deb python-is-python3

These are the exact outputs so I decided to install from the package manager to show terminal outputs what is assumed to be installed. When I attempt to install _python2_ The output is thus:
 jonald@big:~$ sudo apt install python2
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python2 is already the newest version (2.7.18-3).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
and the same is with Python3 with version 3.9.2-3 if that is any help as well.

**Comment by poco0317** [comment]
the point of `which python` was to see what `python` points to. depot_tools is going to be looking for that to be pointing at your python2 install

**Comment by jONALDjONALD** [comment]
apologies, that seems to output nothing for me so I have nothing so I omitted it. but none the less here is what was in my terminal. 
```
jonald@big:~$ which python
jonald@big:~$ 
```

**Comment by poco0317** [comment]
i would also like to mention that there is a way to build without needing depot_tools and there is also a binary available for this game in the latest releases. since you are building master i assume you arent making changes to submit. 

to build without depot_tools (without crashpad ... no crash dumps will be generated by the game. although we will never be able to use them because you are building the game yourself)
https://github.com/etternagame/etterna/releases/download/v0.71.2/Etterna-0.71.2-Linux.tar.gz
example:
`cmake -DWITH_CRASHPAD=OFF -G "Unix Makefiles" ..`

or you can avoid needing to build by using the release binaries
https://github.com/etternagame/etterna/releases/download/v0.71.2/Etterna-0.71.2-Linux.tar.gz

**Comment by jONALDjONALD** [comment]
I have a successful build...somehow!
My Terminal commands are as follows using Ninja and the added cmake argument!  
```
git clone --depth=1 https://github.com/etternagame/etterna.git
cd etterna
git submodule update --init
mkdir Build
cd Build
cmake .. -DWITH_CRASHPAD=OFF -G 'Ninja'
ninja
```
That worked! 
_Now another issue has arisen..._ It will not run as Linux detects no known programs to run the Etterna file with it.
Once again I apologize for this, I feel as though I am coming off as an idiot Linux user asking for your help with all this.

**Comment by poco0317** [comment]
once you built the etterna executable (which may be named `etterna` or `Etterna` in the main folder of the game) you should just be able to run it from terminal with `./etterna` or `./Etterna` depending on its exact name

you probably may also have to set chmod 755 or whatever

**Comment by jONALDjONALD** [comment]
success! Thank you so much for your help!
