### ISSUE TITLE
[Bug]: Calibrate Audio Sync crashes if song filters are applied that don't match the calibration file

### ISSUE THREAD

**Issue by MandL27** [etternagame/etterna#1192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

MandL27#1732 or issue reply

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Windows

### Bug Behavior

When selecting Options ->Input Options -> Calibrate Audio Sync from the main menu, Etterna crashes if any filters were previously applied in song select that don't match the calibration file.

### Expected Behavior

The calibration file should open as normal.

### Reproduction Steps

* Launch Etterna
* Select Game Start
* Apply any filter that won't match the calibration file (I used Jumpstream 10-14)
* Exit song select and open Options
* Select Input Options, then Calibrate Audio Sync
* Game crashes

### Anything else?

![image](https://user-images.githubusercontent.com/10366615/176558083-ee2222a1-1ee4-40f1-99bb-9e3865bd431f.png)
![image](https://user-images.githubusercontent.com/10366615/176558161-3ab0a44a-5bf1-4937-8c18-313145fa4193.png)

**Comment by poco0317** [comment]
done 05d88c971d20c264d09e052fc6801a97b0c7c2c1
