### ISSUE TITLE
[Bug]: Not responding to mouse and keyboard input on macOS

### ISSUE THREAD

**Issue by 4li77l3n00b** [etternagame/etterna#1193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

just reply

### Version Info

Latest available release

### What operating system are you seeing the problem on?

macOS

### Bug Behavior

I've submitted the same issue before #1047 but I didn't provide logs that time.
The same issue still happens in the latest release (0.71.2).
Here is the log.
[2022_06_29-23_51_39.log](https://github.com/etternagame/etterna/files/9016221/2022_06_29-23_51_39.log)
Again I'm using a hackintosh setup, and I'm using a 2560x1440 screen.

**Comment by bluebandit21** [comment]
You might find https://gist.github.com/bluebandit21/d34d7b0b4f9137c34c167e607db63c03 helpful -- it's a guide I wrote that will fix a few of the more common reasons for input to be broken on macOS.

**Comment by 4li77l3n00b** [comment]
> You might find https://gist.github.com/bluebandit21/d34d7b0b4f9137c34c167e607db63c03 helpful -- it's a guide I wrote that will fix a few of the more common reasons for input to be broken on macOS.

ok it got fixed. Thanks for writing that guide.
