### ISSUE TITLE
Unnable to change lanecover height (tilldeath)

### ISSUE THREAD

**Issue by janSopi303** [etternagame/etterna#1195]
Unnable to change lane cover height via select+effectbuttons or via the customize gameplay option (select button doesn't seem to work even though it works on test input

Problem seems to be the select button being different that the default

video showing the problem (although less than a minute long had to use mediafire for file sharing)

https://www.mediafire.com/file/uadzszcp6amunb3/etterna_error.mp4/file

**Comment by poco0317** [comment]
While in customize gameplay, you should be pressing select + effectup/effectdown. It isn't obvious by the ingame instructions.
