### ISSUE TITLE
[Feature Request]: Add option to change F3 Menu to Toggle

### ISSUE THREAD

**Issue by senya0** [etternagame/etterna#1196]
### Is there an existing issue for the feature?

- [x] I have searched the existing feature requests

### Describe the Feature

Give user the ability to change F3 to toggle opening menu instead of being a momentary switch. 

### How Does The Feature Add To The Game?

Some keyboards, mainly those using membranes, have issues with inputting certain key combos due to hardware limitations of their keystroke detection. For example, on one of my keyboards, holding F3 and trying to decrease volume doesn't work because Q ghosts with F3 held.

**Comment by poco0317** [comment]
relevant code https://github.com/etternagame/etterna/blob/08773a50b4d42f4b787304e0d74483ce7520327d/src/Etterna/Screen/Others/ScreenDebugOverlay.cpp#L464-L553

**Comment by poco0317** [comment]
added as preference only accessible via preferences.ini
`DebugMenuButtonToggles=`
1ff87144b04c8b9cd499a8c97a9a5ca65589a40e
