### ISSUE TITLE
[Bug]: cursor freezes when reloading scripts

### ISSUE THREAD

**Issue by Krakenlord5** [etternagame/etterna#1197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Krakenlord#3460

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Windows

### Bug Behavior

When I press reload scripts (ctrl+F2) the cursor just freezes

### Anything else?

maybe it's just because of my laptop but idk

**Comment by poco0317** [comment]
temporary resolution:
when reloading scripts, use the combos in this order, 
- ctrl f2
- shift ctrl f2 (reloading the overlay screens will reload the cursor stuff)
- f3 f6 2 (restarting the screen will register the buttons again so that they work)

**Comment by poco0317** [comment]
fixed for 0.72.2 77ee5a694c5fecf0f3698ea71ed3b3d37febaec1
