### ISSUE TITLE
[Feature Request]: Add clear types to the help menu

### ISSUE THREAD

**Issue by g-robertson** [etternagame/etterna#1198]
### Is there an existing issue for the feature?

- [X] I have searched the existing feature requests

### Describe the Feature

Take the clear types (SDCB,MF,BF,WF,FC,PFC,MFC) and put the in the help menu

### How Does The Feature Add To The Game?

It would make there be a place in the game with all the clear type definitions to reference to

**Comment by poco0317** [comment]
db47b01cda85c12a027faff8242a3d0da6b65846
