### ISSUE TITLE
Noteskin glitch

### ISSUE THREAD

**Issue by Supbads** [etternagame/etterna#12]
If you don't have any noteskin in dance the game would crash when going to the theme/noteskin selection.

**Comment by martensm** [comment]
The only way I can reproduce a hard crash is by deleting the `NoteSkins` directory after the game has started, opening the "options" before selecting a song and then selecting a song.

Currently the `NoteSkins` directory not existing at startup or the `NoteSkins` directory being removed after startup _without_ going to the options menu is handled gracefully.

This should be handled consistently for different codepaths but it's not high priority ATM.

**Comment by MinaciousGrace** [comment]
dont know what fixed it but this doesnt crash anymore
