### ISSUE TITLE
Put CDTitle.png on the scorescreen

### ISSUE THREAD

**Issue by DDMythical** [etternagame/etterna#120]
Would help differentiate for files with multiple steps and it wouldn't take up much room on the screen.

minor feature request nothing major

**Comment by Nickito12** [comment]
Could you provide an image with where you would put it?
Also, shouldnt the pack/bg be enough?
Tbh I'm not sure if this should be done or not (If it should, its probably a simple theme change)

**Comment by DDMythical** [comment]
I think it would just be a minor thing that would just quickly show whos chart they were playing instead of checking the pack and stuff (since some charts use the same gfx)

**Comment by DDMythical** [comment]
in retrospect this would clog up the scorescreen unecessarily
