### ISSUE TITLE
[Feature Request]: Option to make Hold and Roll windows independent of the Judge Setting

### ISSUE THREAD

**Issue by Sarrg** [etternagame/etterna#1203]
### Is there an existing issue for the feature?

- [X] I have searched the existing feature requests

### Describe the Feature

Similar issue to [#650](https://github.com/etternagame/etterna/issues/650) but the other way around.
Could we get either
- a boolean Option that fixes the Hold and Roll windows to be the same as J4 regardless of the Judge in use
or
- a separate Judge Setting for Hold and Roll windows

### How Does The Feature Add To The Game?

Judges should not make the game harder but instead provide additional feedback for Acc Play. However having the Hold and Roll windows tied to the Judge Setting breaks this "Rule". Adding this option would make higher judges more accessible for files that utilizes these note types.

**Comment by poco0317** [comment]
rendered void by 37e56a80e8d4a2a9a87a5b8ee7c6b7c485549490 04f30d0ff209c24d78637e3e588537f2f89585a2
