### ISSUE TITLE
[Build Issue]: ogg/config_types.h: No such file or directory 

### ISSUE THREAD

**Issue by podd0** [etternagame/etterna#1210]
### Have you read through the build instructions before reading this?

- [X] I have read the build instructions

### What operating system are you seeing the problem on?

Linux (any distro)

### Describe the build issue

Make and ninja can't find ogg/config_types.h. I'm on Ubuntu. I already sudo apt updated and upgraded, tried both ninja and make, but I'm stuck here 

### Relevant log output

```shell
andrea@andrea-Aspire-A315-23:~/etterna/build$ ninja
[200/647] Building C object extern/newogg/CMakeFiles/ogg.dir/src/bitwise.c.o
FAILED: extern/newogg/CMakeFiles/ogg.dir/src/bitwise.c.o 
/usr/bin/cc  -I/home/andrea/etterna/extern/newogg/include -w -MD -MT extern/newogg/CMakeFiles/ogg.dir/src/bitwise.c.o -MF extern/newogg/CMakeFiles/ogg.dir/src/bitwise.c.o.d -o extern/newogg/CMakeFiles/ogg.dir/src/bitwise.c.o -c /home/andrea/etterna/extern/newogg/src/bitwise.c
In file included from /home/andrea/etterna/extern/newogg/include/ogg/ogg.h:25,
                 from /home/andrea/etterna/extern/newogg/src/bitwise.c:24:
/home/andrea/etterna/extern/newogg/include/ogg/os_types.h:143:12: fatal error: ogg/config_types.h: No such file or directory
  143 | #  include <ogg/config_types.h>
      |            ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
[209/647] Building C object extern/SQLiteCpp/sqlite3/CMakeFiles/sqlite3.dir/sqlite3.c.o
ninja: build stopped: subcommand failed.
```

**Comment by jameskr97** [comment]
I address this within the next 48 hours. @podd0 Can you provide your Ubuntu OS version?

**Comment by podd0** [comment]
I used:
`git clone https://github.com/etternagame/etterna.git
cd etterna/
mkdir build
cd build
cmake -DOPENSSL_ROOT_DIR="/usr/bin/openssl" -G "Ninja"  ..
ninja`
I'm on Ubuntu 22.04.1 LTS

**Comment by podd0** [comment]
I thought i had installed all the dependencies, sorry. I installed libogg-dev and now all works and the game starts. Thanks!
