### ISSUE TITLE
[Bug]: Inaccurate NPS when slowing song speed

### ISSUE THREAD

**Issue by TheEdumacator** [etternagame/etterna#1211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Discord birds#2164

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Windows

### Bug Behavior

when speeding up a song, the notes per second changes to be accurate with the chart but when slowing down the nps stays at what it is for 1x speed.

### Expected Behavior

the previewed nps is accurate to the speed of the chart when it's slowed down

### Reproduction Steps

run game
select "game start"
click on song
press space to preview chart
hover mouse over chart overview at top
press "-" to decrease song speed
look back to mouse to see if the nps of the song changed

**Comment by poco0317** [comment]
this was done on purpose and i cant remember why

fix eventually

**Comment by poco0317** [comment]
when removing the lower caps to the functions involved in this process, we get heap corruption crashes. and thats hell to debug so im going to let someone else try

**Comment by poco0317** [comment]
done i guess 14a84db64fee6183dfb435a24f44facc3ba25668
