### ISSUE TITLE
[Feature Request]: Add charter credit to gameplay splash

### ISSUE THREAD

**Issue by Samctuary** [etternagame/etterna#1213]
### Is there an existing issue for the feature?

- [X] I have searched the existing feature requests

### Describe the Feature

Just some text on the gameplay splash as you enter a chart listing the charter, potentially in a smaller font similar to the subtitle font

### How Does The Feature Add To The Game?

It lets charters be prouder of their work, and lets their names be displayed (without hovering), instead of just their cdtitle.

**Comment by poco0317** [comment]
done
b57764807c03a61ef83be8fdb1f2f97ff2f63a7a
10ed579efbabf25f7ae12880d9772ec8c8de86a1
