### ISSUE TITLE
[Feature Request]: Work around openssl1.1 being required but not easily available on modern Ubuntu derivatives

### ISSUE THREAD

**Issue by bluebandit21** [etternagame/etterna#1215]
### Is there an existing issue for the feature?

- [X] I have searched the existing feature requests

### Describe the Feature

Etterna dynamically links in libssl1.1 as a runtime dependency.

Unfortunately, as of Ubuntu 22.04, libssl1.1 is no longer easily available as they have fully deprecated it in favor of libssl3.

As a result, modern Ubuntu and all derivatives require something not easily obtainable even for users using our prebuilt Linux binary.

We should handle this in some fashion or other, either
a) Including instructions for acquiring libssl1.1 on modern Ubuntu derivatives
b) Trying to fix the root problem, that we require a now-ancient libssl version (can we statically link it in, or upgrade Etterna to use libssl3 instead?)

### How Does The Feature Add To The Game?

Currently, users using modern Ubuntu/Ubuntu derivatives are unable to easily build Etterna or even use our pre-built binary without having to obtain a runtime dependency that now requires some technical know-how to obtain.

This problem makes it much harder for new Linux players to be able to play the game.

**Comment by poco0317** [comment]
based on this https://cmake.org/cmake/help/latest/module/FindOpenSSL.html

we could probably move required cmake version to 3.19 and change this line with no other issues?
https://github.com/etternagame/etterna/blob/23bb8e90634183f998fea7bba83689e26eed9abb/CMakeLists.txt#L71

**Comment by bluebandit21** [comment]
An additional point of concern mentioned by #1326, is that OpenSSL1.1 will now no longer receive any security updates, as per https://openssl-corporation.org/post/2023-09-11-eol-111/

That means we should really be working on switching to OpenSSL3.x rather than trying to improve the ease of users installing OpenSSL1.1 after its deprecation.

**Comment by poco0317** [comment]
superceded by https://github.com/etternagame/etterna/issues/1330
