### ISSUE TITLE
BPMs no longer change based on rate adjustments

### ISSUE THREAD

**Issue by poco0317** [etternagame/etterna#1218]
this is a problem most likely introduced by #1217 

to reproduce: literally open the game and go to any file and change the music rate. the bpm should adjust accordingly to help the player pick which rate to play on. this no longer happens and damages the flow of menuing and picking the song you mean to play

**Comment by bluebandit21** [comment]
Discussed with Poco in Discord:

Problem is that SetFromSteps never actually used the currently set rate transitively determined from SetBpmFromSong by GetDisplayBpms.

The determined best solution was to make the song rate an optional parameter for the Lua binding and pass it down the chain appropriately.
(Also doing the same thing for SetBpmFromSong to make it more generally usable)

**Comment by poco0317** [comment]
eh

c8329f13c7f3fe33448affdc08d8e163da595052
