### ISSUE TITLE
[Bug]: BPMDisplay no longer supports random bpm

### ISSUE THREAD

**Issue by Malalaika** [etternagame/etterna#1230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Windows

### Bug Behavior

.sm files set to have a random BPM now display set BPM values in-game

### Expected Behavior

.sm files set to have a random BPM should be random; in 0.71 and below the values shuffled between 000, random numbers, and ???

### Reproduction Steps

1.) Check out any song that has random bpm enabled; Reso*nyan*ce Fever should have it.

**Comment by poco0317** [comment]
it does support random bpm, but the method we use to set the bpm in the default themes does not enable it.

https://github.com/etternagame/etterna/blob/5acb2a3be336bc6f92b96ef8dd73743f92e84552/src/Etterna/Actor/Menus/BPMDisplay.cpp#L177-L206

**Comment by poco0317** [comment]
this issue is a reminder to fix the steps specific function and evaluate the logic involved in populating that field for steps, because it may always be empty anyways

**Comment by poco0317** [comment]
checked the logic paths and it seems fine when loaded from disk or from cache, fixed for 0.72.2
24bb49bf929f72a23700bc70b36cd19c55442071
