### ISSUE TITLE
[Feature Request]: Disable windows key functionality during gameplay

### ISSUE THREAD

**Issue by ryandoesalot** [etternagame/etterna#1231]
### Is there an existing issue for the feature?

- [X] I have searched the existing feature requests

### Describe the Feature

While in gameplay, (playing a map), disable the windows key from functioning to prevent it from opening the Windows menu and disrupting gameplay.

### How Does The Feature Add To The Game?

I think everyone hates accidentally pressing the windows key while playing. You're playing the game and then you fat finger the windows key and now your dead because of it. Disabling the windows key during gameplay would make it a lot more fun playing the game, and would make things a lot easier to disable it since it'd be built-into the game.

**Comment by poco0317** [comment]
duplicate #938
