### ISSUE TITLE
[Bug]: General input lag issues on Linux specifically

### ISSUE THREAD

**Issue by daisukidaisy** [etternagame/etterna#1238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Please just reply right here.

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Linux (any distro)

### Bug Behavior

As someone who reads notes more visually than audibly, input lag greatly hinders my ability to play the game, and the "visual offset" setting doesn't help when the notes are clearly falling off what should be the timing window. Maybe it's just me, but I've been experiencing about 3 or 4 frames of input lag (60hz monitor). This didn't happen on my old computer, which ran Windows. My current computer is running Linux Mint (Cinnamon).

And before you ask: Yes, this IS specific to Etterna. Most FNF engines handle my inputs FLAWLESSLY on this OS.

### Expected Behavior

No noticeable input lag. Duh.

### Reproduction Steps

1. Run Linux Mint (Cinnamon) on some computer or virtual machine.
2. Download Etterna v0.72.1* for Linux.
3. Try to play the game.

**Comment by Spedzay** [comment]
Just making sure, is your compositor off?

**Comment by daisukidaisy** [comment]
it's fixed when fullscreen is on, forgot to edit

**Comment by irohia** [comment]
> Linux Mint (Cinnamon)

@daisukidaisy type <code>env vblank_mode=0</code> before <code>./Etterna</code> if you're going to want any chance at playing etterna on linux
i'm going to put that environment variable in my flatpak build eventually (if i ever run linux again), so that people don't need to place an issue

**Comment by irohia** [comment]
additionally, if you want vblank_mode to be 0 on boot, write <code>vblank_mode=0</code> to <code>/etc/environment</code> if you think your system won't break

**Comment by daisukidaisy** [comment]
ok that worked
