### ISSUE TITLE
Replay playback slightly off by a tiny amount

### ISSUE THREAD

**Issue by poco0317** [etternagame/etterna#1240]
2 greats in playback, pfc in local and online replay
online playback is correct

great 2:
v2 `18504 -0.007749 1`

id
```
1 0 248.712021 18504 -0.482755 1 3
2 1 248.737259 18456 -0.003902 1 3
3 1 248.913635 18468 0.006877 1 3
2 0 248.920654 18492 -0.218528 1 3
3 0 249.073242 18516 -0.339944 1 3
0 1 249.092834 18480 0.019673 1 3
0 0 249.221634 18552 -0.579572 1 3
2 1 249.235657 18492 0.006474 1 3
1 1 249.377029 18504 -0.007749 1 3
2 0 249.381210 18528 -0.235182 1 3
1 0 249.522583 18576 -0.595027 1 3
3 1 249.558960 18516 0.006997 1 3
2 1 249.710175 18528 -0.000207 1 3
3 0 249.746613 18540 -0.089384 1 3
3 1 249.878189 18540 0.004599 1 3
2 0 249.901978 18564 -0.208827 1 3
0 1 250.057358 18552 0.017373 1 3
3 0 250.072769 18588 -0.317241 1 3
```

https://etternaonline.com/song/view/103571#154228
https://etternaonline.com/score/view/Sdcbf00b32b1f08830b5985c1c70538dae09223e250483
https://www.youtube.com/watch?v=bcoWxVylsQI
[sxvxcxcv.zip](https://github.com/etternagame/etterna/files/10796198/sxvxcxcv.zip)

**Comment by daisukidaisy** [comment]
platform: linux if not all of them btw

**Comment by poco0317** [comment]
this is fixed by a thing that probably causes ghost taps to break other stuff but after testing random replays for a few minutes it looks fine
6a75685c1e2bfb413988af6946b90ed7bd5f4d48
