### ISSUE TITLE
[Bug]: i cannot click anything like dowload the bundles or anything like that

### ISSUE THREAD

**Issue by jaydenthetra** [etternagame/etterna#1241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

jaydencruz03210@gmail.com

### Version Info

Latest available release

### What operating system are you seeing the problem on?

macOS

### Bug Behavior

i cant click anything like the bundle dowloads or anything else like that.
<img width="1280" alt="Screen Shot 2023-02-22 at 9 19 04 PM" src="https://user-images.githubusercontent.com/125235787/220807492-1890c799-c5a4-4eef-aca8-a547ed892e2d.png">

### Expected Behavior

i should be able to click the bundle dowload.

### Reproduction Steps

1. dowload the game
2. open it
3. cant click anything

### Anything else?

https://user-images.githubusercontent.com/125235787/220807729-79b49305-6ab3-4bdd-bd6f-f8a43f1f9626.mov

**Comment by bluebandit21** [comment]
Hey! 

Can you try following the steps in https://gist.github.com/bluebandit21/d34d7b0b4f9137c34c167e607db63c03 and see if that fixes it?

That has steps that fix macOS inputs problems for most people :)

**Comment by jaydenthetra** [comment]
> Hey!
> 
> Can you try following the steps in https://gist.github.com/bluebandit21/d34d7b0b4f9137c34c167e607db63c03 and see if that fixes it?
> 
> That has steps that fix macOS inputs problems for most people :)

whenever i click the plus and add the eterna app it dosent appear on the input monitering

**Comment by bluebandit21** [comment]
Did you try the CFBundleIdentifier step as well?
Sometimes that's required before being able to add apps to Input Monitoring for reasons :tm: I still don't fully understand.

**Comment by jaydenthetra** [comment]
> Did you try the CFBundleIdentifier step as well? Sometimes that's required before being able to add apps to Input Monitoring for reasons ™️ I still don't fully understand

yea i did do that but it didnt do anything

**Comment by bluebandit21** [comment]
Do you have a Discord account by chance? Might be a little better for back-and-forth than this :)

First off -- just to double check, you're not running Etterna from inside of the disk image, right?
(You dragged the Etterna folder to somewhere else before trying to run it, and you're opening the Etterna.app on your computer rather than in the disk image?)

**Comment by jaydenthetra** [comment]
yes i

> Do you have a Discord account by chance? Might be a little better for back-and-forth than this :)
> 
> First off -- just to double check, you're not running Etterna from inside of the disk image, right? (You dragged the Etterna folder to somewhere else before trying to run it, and you're opening the Etterna.app on your computer rather than in the disk image?)

yes i have a discord and i have the folder in applications

**Comment by jaydenthetra** [comment]
the discord would be moonie#4688

**Comment by bluebandit21** [comment]
Sick. Mind going to #support in https://discord.gg/ZqpUjsJ ? :)
We'll debug more there :D

**Comment by poco0317** [comment]
proceeding conversation https://discord.com/channels/261758887152058368/344545197914456068/1078154573207838790

relevant related issue https://forums.etternaonline.com/t/etterna-not-taking-inputs-on-mac/3445/7

**Comment by aykk** [comment]
Hello, if you are still having this issue this worked for me:

1. Make sure Etterna is closed

2. Go to System Settings -> Privacy & Security -> Input Monitoring

3. Instead of adding Etterna.app, try going into the package contents of Etterna.app then Contents -> MacOS -> Etterna and add the exec file instead.

Try opening Etterna from the Applications like normal and it should work

**Comment by poco0317** [comment]
superceded by #1260
