### ISSUE TITLE
[Feature Request]: Add Mechanism for Deleting Songs

### ISSUE THREAD

**Issue by bluebandit21** [etternagame/etterna#1247]
### Is there an existing issue for the feature?

- [X] I have searched the existing feature requests

### Describe the Feature

Add a mechanism to allow for individual songs from within packs to be deleted in-game.

### How Does The Feature Add To The Game?

It would make it possible to remove songs in-game without having to manually go in a file explorer to the relevant pack and delete them manually.

**Comment by poco0317** [comment]
previously removed in 0.65.0 around these commits (primary commit lost to a squash) 22b9fd97267acb9d04d0222663825c7c9d435440 fc88c3369fbeddb25bde50d2d0048c464da5d68b
