### ISSUE TITLE
Til Death evaluation incorrectly recalcs cb stuff when picking scores

### ISSUE THREAD

**Issue by Darkmans1660** [etternagame/etterna#1248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Darkmans39#1440

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Windows

### Bug Behavior

In the evaluation screen, selecting a different score on the right side of the screen and changing your judgment causes the left/right cbs to update incorrectly, using the first score instead of the currently selected one.

The first score is the score you entered the evaluation screen with.

### Expected Behavior

The left/right cbs should update using the currently selected score, not the score you entered the evaluation screen with.

### Reproduction Steps

1. Enter the evaluation screen of a score
2. Select a different score on the right side of the screen
3. Change judgment

**Comment by poco0317** [comment]
fixed by #1249 and c8d84797ae0bc88c139b0d8493a19f19a4529bf8
