### ISSUE TITLE
FullProgressBar vertical position doesn't save

### ISSUE THREAD

**Issue by LastExceed** [etternagame/etterna#125]
If you turn on customize gameplay, move the FullProgressBar and then leave the song then in the next song the FullProgressBar will be back to its default position

**Comment by Nickito12** [comment]
https://github.com/etternagame/etterna/issues/92
It's supposed to be fixed already. What version did this happen on?

**Comment by LastExceed** [comment]
0.57.1

**Comment by caiohsr14** [comment]
This didnt go to an actual release yet, so wait for the next one

**Comment by LastExceed** [comment]
Alright then
