### ISSUE TITLE
[Feature Request]: "pack=" search prefix

### ISSUE THREAD

**Issue by OddBread** [etternagame/etterna#1256]
### Is there an existing issue for the feature?

- [X] I have searched the existing feature requests

### Describe the Feature

Along with the other search prefixes such as "artist=", there should be one that filters one pack or a group of packs using a "pack=" prefix, so that they can only see packs from 1 series, groups of packs that have important keywords (e.g "pack=chordjack" would should all packs with chordjack in the name), or only filter out a singular pack.

### How Does The Feature Add To The Game?

In Etterna, it is currently possible to search using a myriad of different specifications to narrow down the number of files available for them, which would be particular helpful for players who are picking songs with the randomize feature. Therefore, it only makes sense that the ability to filter with pack names to allow only one pack, or a group of packs with similar names, should be available to the player. 

### Additional Context

Unsure of what exactly must be changed to add this feature, but most likely could be copied and changed from one of the other existing filters.

**Comment by poco0317** [comment]
done 03889cbb24ca6baf4ce646b3ed450e49c8e8cb32 6d988dfa2a66452f426900b4e2d5f7891546244f
