### ISSUE TITLE
[Bug]: TapNoteNoteColorTextureCoordSpacingY missing from retrobar-razor_02 kb7 noteskin

### ISSUE THREAD

**Issue by Jolomann** [etternagame/etterna#1261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

discord: .jole

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Windows

### Bug Behavior

this should be in metrics
`TapNoteNoteColorTextureCoordSpacingY=0`
when it's not there it falls back on 0.125 so it divides textures that shouldn't be divided, causing misaligned and sometimes invisible notes

### Expected Behavior

TapNoteNoteColorTextureCoordSpacingY=0

### Reproduction Steps

use retrobar-razor_02 on a chart with varied snaps
???
houdini notes

**Comment by poco0317** [comment]
aae7aae8c9fa866233d3e7f1b71b76d921c8f88f
