### ISSUE TITLE
[Build Issue]: Missing python 2 dependency on Steam Deck

### ISSUE THREAD

**Issue by felleg** [etternagame/etterna#1265]
### Have you read through the build instructions before reading this?

- [X] I have read the build instructions

### What operating system are you seeing the problem on?

Linux (any distro)

### Describe the build issue

When running `cmake -G "Unix Makefiles"`, the error is 
```
-- Could NOT find Python2 (missing: Python2_EXECUTABLE Interpreter) 
    Reason given by package: 
        Interpreter: Wrong major version for the interpreter "/usr/bin/python"
```

### Relevant log output

```shell
[...]
Processor: x86_64
Enabling x86 SIMD support.
-- Version: 7.0.3
-- Build type: RelWithDebInfo
-- CXX_STANDARD: 20
-- Required features: cxx_variadic_templates
-- Could NOT find Python2 (missing: Python2_EXECUTABLE Interpreter) 
    Reason given by package: 
        Interpreter: Wrong major version for the interpreter "/usr/bin/python"

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find X11 (missing: X11_X11_INCLUDE_PATH)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindX11.cmake:481 (find_package_handle_standard_args)
  CMake/Helpers/CMakeLinux.cmake:12 (find_package)
  CMakeLists.txt:122 (include)


-- Configuring incomplete, errors occurred!
See also "/home/deck/etterna/CMakeFiles/CMakeOutput.log".
See also "/home/deck/etterna/CMakeFiles/CMakeError.log".
```
```


### Anything else?

CMakeErrors: https://pastebin.com/HNd7XwNt

CMakeOutput: https://pastebin.com/2SfQ3SVB

**Comment by nico-abram** [comment]
@felleg try adding `-DWITH_CRASHPAD=OFF` to your cmake invocation (I suggest you clear the cmake folder first to avoid cache issues)

**Comment by felleg** [comment]
Hi @nico-abram , thanks for the quick turnaround! My "new" error is the following:

```
-- Required features: cxx_variadic_templates
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find X11 (missing: X11_X11_INCLUDE_PATH)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindX11.cmake:481 (find_package_handle_standard_args)
  CMake/Helpers/CMakeLinux.cmake:12 (find_package)
  CMakeLists.txt:122 (include)
```

**Comment by poco0317** [comment]
`sudo pacman -S libx11` would typically resolve this but i am seeing evidence that steam has done something that wont let that work as it should

**Comment by nico-abram** [comment]
From this reddit thread https://www.reddit.com/r/SteamDeck/comments/11m1j9m/problem_with_cmake_when_building_melonds_from/ it seems valve stripped header files for the steam deck libx11 package

**Comment by felleg** [comment]
Still an issue :'(

**Comment by poco0317** [comment]
is there a particular reason you need to build the game on steam deck instead of using the prebuilt linux binary? steam deck seems like it wont allow building the game simply because of the x11-dev dependency

**Comment by jameskr97** [comment]
@felleg Please keep in mind, that the steam deck wasn't built to compile code. In order to do build applications, you would have to set your sudo password, download the arch linux repo gpg keys (as the device does not have the by default), and remount the filesystem as read-write, as using pacman won't work to install some packages with it's by-default read-only filesystem. Steam themselves even instructs their developers to [use mini-pc's to develop and test their games for steam decks](https://partner.steamgames.com/doc/steamdeck/testing).
 
Bearing that in mind, the following may help you in your journey to compile Etterna on the steam deck (assuming your sudo password is set):

```bash
# Essential to be able to install packages without issue on the steam deck.
sudo pacman-key --init
sudo pacman-key --populate archlinux

# This may fail if you certain directories of your file system are mounted read only.
sudo pacman -S libx11 
```

I have a Steam Deck, and I tested our linux binary, it works without issue. I would recommended using that for building on the steam deck.

The problem here is not with our build script, but with the platform being used to build the application. @poco0317 I will leave it open in-case you would like to review it more, but I would consider this issue closed.

**Comment by poco0317** [comment]
i did not know but i did assume the game was likely functional on steam deck if you figured out how to run it. i think some people would be interested to see a picture of gameplay

**Comment by jameskr97** [comment]
As requested:
![Screenshot_20230808_202747](https://github.com/etternagame/etterna/assets/6078824/7c59e0c1-952e-4a83-bbac-4f40915bddc2)
![Screenshot_20230808_202813](https://github.com/etternagame/etterna/assets/6078824/1f030071-ffc8-4aea-9f21-b71cc2b25663)

**Comment by poco0317** [comment]
neat

**Comment by felleg** [comment]
I confirm that downloading the *.tar.gz just works. My apologies for unnecessarily going into this rabbit hole, and thank you for taking the time to show me the proper way of getting the game to run.
