### ISSUE TITLE
[Bug]: Pack download cannot be cancelled if at 0KB/s

### ISSUE THREAD

**Issue by Jolomann** [etternagame/etterna#1267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

discord: .jole

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Windows

### Bug Behavior

If downloads for whatever reason are at 0KB/s, the cancel download action is unresponsive. Tested in both Rebirth and Til Death. While there's active download traffic, cancel applies instantly as you'd expect

Found out after trying to test theme edits with extremely long downloads, intentionally slowing the speed to a halt through preferences

### Expected Behavior

Cancel regardless of current download speed

### Reproduction Steps

1. Set `maximumBytesDownloadedPerSecond` to something stupidly low like under 50 to get effectively 0KB/s
2. Can't cancel download if speed is showing 0KB/s

**Comment by poco0317** [comment]
done bb09eb1010a68bf9112e343a88388e3e4a9be257
