### ISSUE TITLE
[Bug]: Consistent crash on metrics reload after increasing NumWheelItems under [MusicWheel]

### ISSUE THREAD

**Issue by Jolomann** [etternagame/etterna#1271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

discord: .jole

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Windows

### Bug Behavior

Increasing `NumWheelItems` while in `ScreenSelectMusic` can consistently crash the game after reloading metrics without any traceable reason in logs. Decreasing the value does not appear to cause any issues. When the crash happens, the log file ends with this:

`[2023-08-19 08:09:18][INFO]: Reloaded metrics
`

This behaviour also checks out for rebirth but I don't see why you would be changing this in rebirth's context because it doesn't really use a metrics wheel

### Expected Behavior

Not crash or at the very least provide a reason for the crash

### Reproduction Steps

1. Use a theme with metrics songwheel (Til Death for example, but technically rebirth will work for this too)
2. Go to `ScreenSelectMusic`
3. Open metrics.ini, find `[MusicWheel]`, increase `NumWheelItems=` by at least 1, save
5. Reload metrics
6. Game go poof

**Comment by poco0317** [comment]
done 0f5185c844d6f08976d5abfc2b56cd056bee197e 7ccaf31ada33d25f93d56961d91158c797264b6d
