### ISSUE TITLE
[Bug]: creating a tag on rebirth gives you the ability to press enter on packs/filters and play them as songs, crashing the game

### ISSUE THREAD

**Issue by velaachlorine** [etternagame/etterna#1272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version Info

Latest available release

### Bug Behavior

upon creating a tag you can enter the currently hovered element in the songwheel, regardless of if it's a song, pack or filter
also carries over to the search menu, which does the above when pressing enter instead of searching

**Comment by poco0317** [comment]
done f2678fe1992ab83a3dd6c38395acfc57793cc9d4
