### ISSUE TITLE
[Feature Request]: Aggregate failed sections of a song and generate tracks which repeat that section for practicing

### ISSUE THREAD

**Issue by jebarpg** [etternagame/etterna#1284]
### Is there an existing issue for the feature?

- [X] I have searched the existing feature requests

### Describe the Feature

I'm pretty sure my idea has already been thought of but I wasn't able to find any request for it or any resources which are similar to my idea. Sorry in advance if there is already something like this and I just haven't done enough research to find it. 

First have an option to select whether or not you would like to have this feature enabled for the current song you are playing.
Second select the threshold of what consists of a break for you, i.e. Lowest note score: "Good" which means you want to track sections which you get Good note scores in. 
Third: How do we determine where the pattern is that needs to be repeated? I don't have the perfect answer for this but I have some ideas: 1) Take an arbitrary range of notes surrounding the missed note and make a repeated section of that... range could be 5 notes behind and 5 notes ahead. 2) Take the time signature of the song and create repeated patterns based on the 3 bars around the section you missed the note. 1st bar is the bar you failed the note in and the two other bars are the before and after sections.
Fourth: Auto Generate an infinite map which repeats through the identified sections.

### How Does The Feature Add To The Game?

I believe it will help allow for people to have a more focused practice sessions for specific sections they are having a hard time with. It will hopefully reduce the amount of time spent having to replay the entire song over again just to get to that one part and fail.

**Comment by poco0317** [comment]
was thinking about this for a while, about how its questionable to splice audio and charts internal to the game and spit out a new one .. then i realized i did this for practice mode which released in 2019. open practice mode on a chart and then right click the graph in 2 spots. this sets up a loop region in the song that repeats the desired section. also keep in mind that repeating the same pattern over and over is highly likely to mindblock you which sucks worse than being bad at a pattern.
