### ISSUE TITLE
[Feature Request]: Add information about playing Osu charts in Etterna to Rebirth help screen

### ISSUE THREAD

**Issue by bluebandit21** [etternagame/etterna#1293]
### Is there an existing issue for the feature?

- [X] I have searched the existing feature requests

### Describe the Feature

Create a quick summary detailing how Etterna can natively load Osu charts that explains to users how to do so in the Rebirth help page.

### How Does The Feature Add To The Game?

Lots of people want to play Osu charts in Etterna and ask for help with how to do so on the Discord.
This would either helpfully prevent some of those requests in the first place, or at least make helping those requests into "Look at XYZ page in the Rebirth help menu"

**Comment by poco0317** [comment]
#1295
