### ISSUE TITLE
[Bug]: Pack banners with uppercase file extensions are not loaded

### ISSUE THREAD

**Issue by niet-dev** [etternagame/etterna#1303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Reply to the issue, or Discord: nietscape

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Windows

### Bug Behavior

If a pack banner has an uppercase file extension, the banner is not loaded. This is uncommon, but true for some packs that are downloaded in-game.

### Expected Behavior

The banner should be displayed as if it had a lowercase file extension.

### Reproduction Steps

1. Open the game
2. Download a pack like NBJS2 or midare megapack 5
3. Notice the pack banner does not appear
4. Go to the pack directory, change the file extension to lowercase (bn.PNG > bn.png, bn.JPG > bn.jpg)
5. Restart etterna, pack banner appears

### Anything else?

This is only true of pack banners. Chart banners with uppercase file extensions are loaded just fine (see Blockbuster, Comsten from NBJS2).

**Comment by poco0317** [comment]
the problem is right here https://github.com/etternagame/etterna/blob/9a0b9fb94ea0c1f4d24b707bd00fad24d94d22ec/src/RageUtil/Utils/RageUtil.cpp#L1000-L1012

if nobody fixes it in 6 hours im going to fix it

**Comment by poco0317** [comment]
7bc8e6e30963845b2fd736b5cb1666df84be592a
