### ISSUE TITLE
[Bug]: Noteskins throw errors when in windowed mode

### ISSUE THREAD

**Issue by vmthook** [etternagame/etterna#1309]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Contact Details

aarch64@skiff.com; discord: @aimcutie

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Windows

### Bug Behavior

Getting errors when transitioning to the song select menu and when starting the song. Happens only in windowed or borderless fullscreen mode.

> Error: The NoteSkin element "_mine Key" could not be found in any of the following directories:
> NoteSkins/dance/tatatatata/, NoteSkins/common/common/,
> NoteSkins/dance/default/, NoteSkins/common/common/
> Correct this and click Retry, click Abort to crash, or click Ignore to attempt to continue.

### Expected Behavior

No errors.

### Reproduction Steps

1. Run the game
2. Make sure that the game is running either in windowed or borderless fullscreen
3. Select "Game Start"
4. Get 4 errors described higher
or:
1. In the song select menu, select the chart
2. Get exact same 4 errors

### Anything else?

![Screenshot_8](https://github.com/etternagame/etterna/assets/171326971/baabc681-e577-4337-8b97-17bfb5de1150)

**Comment by poco0317** [comment]
this is a problem with your noteskin, not the game
