### ISSUE TITLE
[Bug]: theres lag spike mid song

### ISSUE THREAD

**Issue by whydog1117** [etternagame/etterna#1312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

whydogcantspeed (discord)

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Windows

### Bug Behavior

mid playing it just freeze for like 2 ticks but the song is still playing and its like playing ez SV maps with little speed veriations 

### Expected Behavior

its shouldnt freeze i guess

### Reproduction Steps

idk its only on my end or ppl has this issue as well

### Anything else?

gl

**Comment by poco0317** [comment]
a nonreproducible issue is a non issue. thanks to the lack of detail you presented, i cant give directly helpful advice. try to get better hardware. try closing discord and chrome while playing the game. try lowering the framelimit of the game. try not recording videos/streaming while playing the game. try plugging in your laptop. 

dont make garbage github issues
