### ISSUE TITLE
[Bug]: Rebirth, Network issue.

### ISSUE THREAD

**Issue by Lektuur** [etternagame/etterna#1315]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

lektuur (discord)

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Windows

### Bug Behavior

The Bug I have is that I can't Login into Etterna: Rebirth(I've tried with an Email and I'm logged in on a site too) and can't download bundles in the game as well as the Pack Downloader.

### Expected Behavior

I should Login and download Bundles and packs.

### Reproduction Steps

1. Run the game
2. Select Bundle Downloader/Downloades in the game
3. You will see on the image attached

### Anything else?

![image](https://github.com/user-attachments/assets/b7efcbdd-cd12-4b9b-a23b-dc24b4da128d)
![image](https://github.com/user-attachments/assets/73fd57b1-93e2-4ae5-8451-4b778b624f3f)

**Comment by poco0317** [comment]
not a client issue
https://community.etternaonline.com/t/new-website-is-in-beta-what-you-need-to-know/313

**Comment by bluebandit21** [comment]
Hi Lektuur, 

Currently we're in the middle of transitioning between the old website and a new one that's been in development for quite a long time.

The end result is going to be pretty exciting (brand new shiny website!), but in the interim various online services are down or require using an experimental beta client to access.

For more information, you can see a FAQ post we wrote about it at https://etternaonline.com/news/new-website-is-in-beta
