### ISSUE TITLE
[Feature Request]: Scroll wheel input debouncing

### ISSUE THREAD

**Issue by DashDashDashDashDash** [etternagame/etterna#1319]
### Is there an existing issue for the feature?

- [X] I have searched the existing feature requests

### Describe the Feature

Add debouncing to scroll wheel inputs (specifically?)

### How Does The Feature Add To The Game?

Currently the scrollable menus are very harsh to navigate with a mouse, given one scroll event scrolls a whole page in most (if not all) cases. In addition, some mice (like mine) are annoying and will often give double or triple scrolls on a singular motion, making navigation even more confusing.
Adding debouncing would alleviate this issue and additionally make menus feel more rigid giving more QoL to the user interface.

**Comment by poco0317** [comment]
#1318
