### ISSUE TITLE
[Bug]: Login issue

### ISSUE THREAD

**Issue by Andrew284646** [etternagame/etterna#1327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

andrew.siller2012@gmail.com

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Windows

### Bug Behavior

Hey, whenever i login it just keeps failing on the Etterna game. I put in the correct Account name and Password. Can you help me with this issue?

### Expected Behavior

What should've happened instead was that it should've logged me in instead of failing.

**Comment by CreoSm** [comment]
Make sure you are using the latest 0.73 client from the [Etterna Online](https://etternaonline.com/) announcements section, the latest post currently is new clients part 4

**Comment by poco0317** [comment]
the version of the client available in the release section of this github repo is not compatible with online play and you have to find it from the front page of the etternaonline website instead. it's a test version that will hopefully be released before the end of time. it explains in more detail why login failures might occur
