### ISSUE TITLE
[Bug]: Displayed XMod Scroll Speed not Correctly Accounting for Song Rates

### ISSUE THREAD

**Issue by hitonisan** [etternagame/etterna#1334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

hitotsu234.oboe@gmail.com, hitotsuoboe on Discord

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Windows

### Bug Behavior

When in the player options menu when attempting to enter a song, the player has the opportunity to change the scroll speed and song rate of the song they are about to play.

However, if Xmod scroll rate is in use and the song rate is changed, the Xmod scroll rate will not update in kind. Changing scroll modes or scroll multiplier will not affect this, and continue to use the song rate that was selected prior to entering the options menu. (The actual scroll speed is correct when playing the song, though this speed will not match what the song options displayed.)

Additionally, when entering the player options menu, if the initially selected song rate is not 1x, Xmod scroll speeds will not be calculated correctly.

These issues were encountered in version 0.74.0 of Etterna using the Til Death theme.

### Expected Behavior

1. When changing song rate while in the song options menu, Xmod scroll speed rate should be calculated based on the newly changed rate rather than the rate that was initially given when entering the song options menu.
2. When entering player options or song options with a song rate that is not 1x, Xmod scroll speeds should correctly calculate based on the song BPM modified by the song rate.

### Reproduction Steps

1. Start the game, and enter Song Select
2. Move to a song of your choosing. For the most clarity, please have your current song rate speed set to 1x before continuing
3. Choose the song, and hit Enter twice to enter song options
4. Change your scroll type to Xmod, if necessary
5. Change the song rate - the Xmod scroll speed should not change
6. Save your player/song options by any means (e.g. entering the song), then return to song select
7. Note the current BPM of the song on Song Select with the song rate applied. Then, enter player options or song options again without changing the song rate
8. Note the current Xmod scroll speed based on the rate-modified BPM - this won't be calculated correctly

### Anything else?

This appears to be a partial reversion of the fixes for #1136 , which also dealt with Xmod scroll speeds not correctly responding to song rate changes.

The images that follow are an example showcase of the bugs described. The song used for testing here is Last Knight in Charting Secret Santa 2024 - this song is 193 BPM at 1x song rate, and has no BPM changes:

![Last Knight Base BPM](https://github.com/user-attachments/assets/74d843a0-b9eb-4863-94f0-e8259318f0ad)

Entering song options for Last Knight, we can see that the Xmod scroll speed is currently correctly accounting for the song's 193 BPM at 1x song rate (193 * 5.25 = 1013.25):

![Last Knight 1x Scroll Speed](https://github.com/user-attachments/assets/208920db-ac83-4a18-91d8-8809161b1f0c)

However, if we change the song rate while still in this options menu, the Xmod scroll speed won't update to account for it:

![Last Knight 0 75x Scroll Speed Before Leave](https://github.com/user-attachments/assets/fef82a7c-249d-4e8b-ab66-42faa24887ca)

After entering the song and leaving to save the song options, Last Knight is now at 0.75x song rate, with a display BPM of 145 (193 * 0.75 = 144.75):

![Last Knight 0 75x BPM](https://github.com/user-attachments/assets/75af4085-24a9-49c5-9a09-d070710686d8)

Entering song options again with Last Knight at 0.75x song rate gives me an Xmod scroll speed of 571 with a scroll modifier of 5.25x in use, which is not correct (145 BPM * 5.25x scroll mod = 761.25):

![Last Knight 0 75x Scroll Speed on Return](https://github.com/user-attachments/assets/6c6a36ea-f435-4793-b7b0-fee4a493a38a)

**Comment by poco0317** [comment]
weird

**Comment by poco0317** [comment]
a97aaf67c2460cdc3bd1d219d223d90b7839b973
