### ISSUE TITLE
[Bug]: Changing Song Rate in Player Options Doesn't Update Visuals Until Changing Selected Song

### ISSUE THREAD

**Issue by hitonisan** [etternagame/etterna#1335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

hitotsu234.oboe@gmail.com, hitotsuoboe on Discord

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Windows

### Bug Behavior

While in Song Select, it is possible to choose Player Options to set options to use for the song. If the song rate is changed in this fashion, when going back to Song Select, the song that was previously being hovered won't have its visual elements (displayed song rate, MSD, BPM, song duration) updated based on the new rate. Song audio, however, will be adjusted based on the new rate.

These effects end once a new song is hovered over and the original song is scrolled back to. This issue also does not seem to occur if it is done through song options (i.e. hitting Enter twice on the song, changing song rate, then exiting back to Song Select without entering the song).

This bug was encountered in Etterna version 0.74.0 using the Til Death theme.

### Expected Behavior

After returning from Player Options after updating the song rate, the displayed visual elements describing the song should update based on the newly chosen song rate.

### Reproduction Steps

1. Start the game, and enter Song Select
2. Hover over a song of your choosing
3. Open Player Options (not song options - don't attempt to start the song), and change the song rate
4. Return to Song Select - visual elements for the song like BPM and MSD should still be based on the original song rate. Song audio, however, should be correctly based on the newly chosen song rate
5. Scroll to another song in Song Select, then return to your original song - the visuals should be correctly updated based on the newly chosen BPM now

### Anything else?

The following video showcases an example of this bug occurring. I start out hovering over Last Knight with a 1x song rate. Using the Player Options button on Song Select, I change the song rate to 0.75x. When I return to Song Select, the descriptions for Last Knight are still those for a 1x song rate. I then scroll to another song then back to Last Knight, at which point the descriptions are updated based on the new song rate.

I then repeat this process going from 0.75x back to 1x song rate, with the same effects occurring.

[https://youtu.be/BSf4SZM1PRw](https://youtu.be/BSf4SZM1PRw)

**Comment by poco0317** [comment]
a97aaf67c2460cdc3bd1d219d223d90b7839b973
