### ISSUE TITLE
[Bug]: Etterna intermittently seg faulting when starting/stopping certain charts

### ISSUE THREAD

**Issue by BetaMaster1** [etternagame/etterna#1337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

betamaster on discord

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Linux (any distro)

### Bug Behavior

When starting May I Help You, 9 times out of 10 it seg faults and crashes. It shows the error `malloc(): invalid size (unsorted)` most of the time, but sometimes it doesn't. _Very_ occasionally, it crashes only when ending the song and not when starting it, but I only got that once, and not on recording. It gave no errors in the terminal though, just seg faulting.
This did not happen with any 0.73 builds, nor does it happen with any other charts.

https://github.com/user-attachments/assets/6a517746-1a29-42af-9987-33e077c0e0d4

[2024_12_26-15_59_11.log](https://github.com/user-attachments/files/18253944/2024_12_26-15_59_11.log)

### Expected Behavior

For it to... not crash

### Reproduction Steps

1. Run the game (preferably in a terminal, so you can see errors)
2. Select Game Start and find May I Help You? in Anime Extravaganza 2
3. Observe crash, unless you got lucky, in which case try again

**Comment by BetaMaster1** [comment]
A lot of other people are saying that this is a known bug. Whoops.

**Comment by poco0317** [comment]
no idea of the cause. attempts:
805992e2673991d7a19bb108a40c3bb5aa265a29
012ebbf9406e638e47ed1dfa624ac2c1cb0de12d
