### ISSUE TITLE
can;t build current release on debian buster

### ISSUE THREAD

**Issue by hamishmaku** [etternagame/etterna#139]
fails on compilation, error as follows: 

../extern/liblua-5.1.a(loslib.c.o): In function `os_tmpname':
loslib.c:(.text+0x1a5): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
CMakeFiles/StepMania.dir/StepMania.cpp.o: In function `ShutdownGame()':
StepMania.cpp:(.text+0x134b): undefined reference to `Discord_Shutdown'
CMakeFiles/StepMania.dir/GameState.cpp.o: In function `GameState::discordInit()':
GameState.cpp:(.text+0x6937): undefined reference to `Discord_Initialize'
CMakeFiles/StepMania.dir/GameState.cpp.o: In function `GameState::updateDiscordPresence(StdString::CStdStr<char> const&, StdString::CStdStr<char> const&, StdString::CStdStr<char> const&, long)':
GameState.cpp:(.text+0x69c9): undefined reference to `Discord_RunCallbacks'
GameState.cpp:(.text+0x69d5): undefined reference to `Discord_UpdatePresence'
CMakeFiles/StepMania.dir/GameState.cpp.o: In function `GameState::updateDiscordPresenceMenu(StdString::CStdStr<char> const&)':
GameState.cpp:(.text+0x6a29): undefined reference to `Discord_RunCallbacks'
GameState.cpp:(.text+0x6a35): undefined reference to `Discord_UpdatePresence'
collect2: error: ld returned 1 exit status
src/CMakeFiles/StepMania.dir/build.make:9809: recipe for target '../stepmania' failed
make[2]: *** [../stepmania] Error 1
CMakeFiles/Makefile2:380: recipe for target 'src/CMakeFiles/StepMania.dir/all' failed
make[1]: *** [src/CMakeFiles/StepMania.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2`

able to provide any other information, running 64 bit.

thanks.

**Comment by satorialist** [comment]
seconding this, I'm getting the same linking error on my 64bit Arch Linux install (so far no luck trying to put the lib in extern and including the headers for discord-rpc)

**Comment by Nickito12** [comment]
Iirc one or both of you asked for help in the EDG discord server and managed to build with some help from theropfather?
If you are still having trouble building this please mention which release you are trying to build (If it's one of the experimental ones then its likely it had a static lib like luaJIT or discord rpc only for windows, and the linux libs were still not there. Iirc currently the only branch with both of these which should work on linux is expRelease, which is an experimental/development branch which isnt stable, and no release has them).
If there is no response within ~2 weeks I might close this.

**Comment by TheROPFather** [comment]
Closed since AFAIK the issue has since been resolved.
