### ISSUE TITLE
NoteSkin Missing Graphics?

### ISSUE THREAD

**Issue by MattMcManis** [etternagame/etterna#150]
Default install.

Is this what it's supposed to look like? [https://i.imgur.com/ekr4Iw9.png](https://i.imgur.com/ekr4Iw9.png)

Compared to StepMania it's missing Freeze graphic and the Arrow Hit animation.

**Comment by Jousway** [comment]
yes thats how its supposed to look like, if you dont like it there is https://etternaonline.com/noteskins with a ton of noteskins to use 👍
