### ISSUE TITLE
Pump mode hold crash

### ISSUE THREAD

**Issue by Sophia2329** [etternagame/etterna#167]
Experimental Etterna 0.57.1 in pump mode crashes upon releasing a hold (and maybe other hold events)
(Playing cmd skin)
[crashinfo.txt](https://github.com/etternagame/etterna/files/2087657/crashinfo.txt)

**Comment by nico-abram** [comment]
I think this is a duplicate of https://github.com/etternagame/etterna/issues/158

This has been fixed iirc on the /develop/ branch
