### ISSUE TITLE
Correctly add check for "failing out" of a beginner chart.

### ISSUE THREAD

**Issue by DDMythical** [etternagame/etterna#188]
my reasoning being that, as of now, it causes a multitude of bugs, and some may be potentially used (in very extreme scenarios) to fake scores.

aside from (seemingly) randomly crashing the game, if a song has a break long enough for you to exit by holding down enter (hitting a note cancels this), your score will save and count for MSD. Technically (although I know of no charts that support this), given a chart with a 2 second break and an easy enough intro, you can get a score on it which counts as playing the whole file, but you have actually only played a segment of it (side note: you must have gotten enough % on the chart to break the 'vibro-dismissal' line; of which it must be broke with the initial calculations - the initial calculations take in all notes, but the calculations for msd take in only the notes you've hit/missed - not the ones you have skipped with the enter-exit. Basically, your MSD acc will be higher, but your overall acc still has to pass the vibro threshold as-if you'd never hit the notes you skipped.)

this is a massive edge case but whatever: https://i.imgur.com/mARRRUX.png image proof

**Comment by TheROPFather** [comment]
Correctly add check for "failing out" of a beginner chart.

**Comment by DDMythical** [comment]
I'm not sure why you've renamed the issue to this because that isn't what this issue was about; it was about exiting a song with the enter button causing absurd issues - it had absolutely nothing to do with the beginner/easy difficulty failings.

**Comment by TheROPFather** [comment]
That's what I meant by "failing out", basically holding enter. Me and Nick knew what it meant - and the original title was inaccurate.

**Comment by DDMythical** [comment]
Apologies, I misunderstood - however this issue has nothing to do with beginner/easy difficulties as it can be performed on any difficulty.

**Comment by MinaciousGrace** [comment]
2e5dfd47e8dd4016e5bf714073e37d9014104a4b should fix the issue by force flagging anything 'given up' on as fail grade
