### ISSUE TITLE
[0.57.1+?] Some charts cannot be failed

### ISSUE THREAD

**Issue by DeltaEpsilon7787** [etternagame/etterna#189]
This bug is difficult to predict and seems to appear at random, however I managed to screenshot one occurrence: ![bug](!https://vgy.me/G251lB.png)

UPD: Apparently this particular chart cannot be failed.
UPD: There is a whole bunch of charts that can't be failed. Some can be failed, others not. This needs further investigation.

Some charts that can be failed: ![Unfucked_charts.zip](https://mega.nz/#!e8UGlahJ!EnssAXzYBzUS1VjXAvCsP5lz9gCmZY8u4i5EjXBcgbw)
Some charts that **cannot** be failed: ![Fucked_charts.zip](https://mega.nz/#!fodmjI7J!vP8B09SpBDAU62pC6dlsqYF1HR0GzQaFeCF0iaRPHJI)

**Comment by TheROPFather** [comment]
Both the charts you have provided as examples are beginner difficulty, and thus not being able to fail out is the expected behavior. Closing unless you can provide examples that are not Beginner or Easy difficulties.
