### ISSUE TITLE
0.56 - Ubuntu 16.04 Sound doesn't work

### ISSUE THREAD

**Issue by PawelA** [etternagame/etterna#190]
Program output log:

$ ./stepmania
Etterna0.56-UNKNOWN
Compiled 20180709 @ 18:48:41 (build UNKNOWN)
Log starting 2018-07-09 21:18:44
OS: Linux ver 040400
Crash backtrace component: x86 custom backtrace
Crash lookup component: backtrace_symbols
Runtime library: glibc 2.23
Threads library: NPTL 2.23
libavcodec: 0x395964 (3758436)
ALSA: Advanced Linux Sound Architecture Driver Version k4.4.0-130-generic.
ALSA Driver: 0: HDA ATI HDMI [HDMI], device 3: HDMI 0 [HDMI 0], 1/1 subdevices avail
ALSA Driver: 1: HD-Audio Generic [Generic], device 0: ALC3227 Analog [ALC3227 Analog], 1/1 subdevices avail
ALSA: dsnd_pcm_hw_params_set_access: Invalid argument
Couldn't load driver ALSA-sw: SetHWParams failed
Couldn't load driver OSS: RageSoundDriver_OSS: Couldn't open /dev/dsp: No such file or directory
Sound driver: Null
Video renderers: 'opengl'
Display: :0 (screen 0)
X server vendor: The X.Org Foundation [1.18.4.0]
Server GLX vendor: SGI [1.4]
Client GLX vendor: Mesa Project and SGI [1.4]
Paletted textures disabled: GL_EXT_paletted_texture missing.
Direct rendering: yes
OGL Vendor: X.Org
OGL Renderer: AMD Radeon R6 Graphics (CARRIZO / DRM 3.1.0 / 4.4.0-130-generic, LLVM 6.0.0)
OGL Version: 3.0 Mesa 18.0.5
OGL Max texture size: 16384
OGL Texture units: 8
GLU Version: 1.3
OGL Extensions:
  GL_AMD: conservative_depth, draw_buffers_blend, performance_monitor, pinned_memory, 
    seamless_cubemap_per_texture, shader_stencil_export, shader_trinary_minmax
  GL_ANGLE: texture_compression_dxt3, texture_compression_dxt5
  GL_APPLE_packed_pixels
  GL_ARB: ES2_compatibility, ES3_compatibility, arrays_of_arrays, base_instance, bindless_texture, 
    blend_func_extended, buffer_storage, clear_buffer_object, clear_texture, clip_control, color_buffer_float, 
    compressed_texture_pixel_storage, compute_shader, compute_variable_group_size, conditional_render_inverted, 
    conservative_depth, copy_buffer, copy_image, cull_distance, debug_output, depth_buffer_float, depth_clamp, 
    depth_texture, derivative_control, draw_buffers, draw_buffers_blend, draw_elements_base_vertex, 
    draw_instanced, explicit_attrib_location, explicit_uniform_location, fragment_coord_conventions, 
    fragment_program, fragment_program_shadow, fragment_shader, framebuffer_no_attachments, framebuffer_object, 
    framebuffer_sRGB, get_program_binary, get_texture_sub_image, half_float_pixel, half_float_vertex, 
    instanced_arrays, internalformat_query, internalformat_query2, invalidate_subdata, map_buffer_alignment, 
    map_buffer_range, multi_bind, multisample, multitexture, occlusion_query, occlusion_query2, 
    pipeline_statistics_query, pixel_buffer_object, point_parameters, point_sprite, polygon_offset_clamp, 
    program_interface_query, provoking_vertex, query_buffer_object, robust_buffer_access_behavior, robustness, 
    sample_shading, sampler_objects, seamless_cube_map, seamless_cubemap_per_texture, separate_shader_objects, 
    shader_atomic_counter_ops, shader_atomic_counters, shader_ballot, shader_bit_encoding, shader_clock, 
    shader_draw_parameters, shader_group_vote, shader_image_load_store, shader_image_size, shader_objects, 
    shader_precision, shader_stencil_export, shader_storage_buffer_object, shader_texture_image_samples, 
    shader_texture_lod, shading_language_100, shading_language_420pack, shading_language_packing, shadow, 
    stencil_texturing, sync, texture_barrier, texture_border_clamp, texture_buffer_object, 
    texture_buffer_object_rgb32, texture_buffer_range, texture_compression, texture_compression_bptc, 
    texture_compression_rgtc, texture_cube_map, texture_cube_map_array, texture_env_add, texture_env_combine, 
    texture_env_crossbar, texture_env_dot3, texture_filter_anisotropic, texture_float, texture_gather, 
    texture_mirror_clamp_to_edge, texture_mirrored_repeat, texture_multisample, texture_non_power_of_two, 
    texture_query_levels, texture_query_lod, texture_rectangle, texture_rg, texture_rgb10_a2ui, texture_stencil8, 
    texture_storage, texture_storage_multisample, texture_swizzle, texture_view, timer_query, transform_feedback2, 
    transform_feedback3, transform_feedback_instanced, transform_feedback_overflow_query, transpose_matrix, 
    uniform_buffer_object, vertex_array_bgra, vertex_array_object, vertex_attrib_binding, vertex_buffer_object, 
    vertex_program, vertex_shader, vertex_type_10f_11f_11f_rev, vertex_type_2_10_10_10_rev, window_pos
  GL_ATI: blend_equation_separate, draw_buffers, fragment_shader, meminfo, separate_stencil, 
    texture_compression_3dc, texture_env_combine3, texture_float, texture_mirror_once
  GL_EXT: abgr, bgra, blend_color, blend_equation_separate, blend_func_separate, blend_minmax, blend_subtract, 
    compiled_vertex_array, copy_texture, depth_bounds_test, draw_buffers2, draw_instanced, draw_range_elements, 
    fog_coord, framebuffer_blit, framebuffer_multisample, framebuffer_multisample_blit_scaled, framebuffer_object, 
    framebuffer_sRGB, gpu_program_parameters, memory_object, memory_object_fd, multi_draw_arrays, 
    packed_depth_stencil, packed_float, packed_pixels, pixel_buffer_object, point_parameters, polygon_offset, 
    polygon_offset_clamp, provoking_vertex, rescale_normal, secondary_color, separate_specular_color, 
    shader_integer_mix, shadow_funcs, stencil_two_side, stencil_wrap, subtexture, texture, texture3D, 
    texture_array, texture_compression_dxt1, texture_compression_latc, texture_compression_rgtc, 
    texture_compression_s3tc, texture_cube_map, texture_edge_clamp, texture_env_add, texture_env_combine, 
    texture_env_dot3, texture_filter_anisotropic, texture_integer, texture_lod_bias, texture_mirror_clamp, 
    texture_object, texture_rectangle, texture_sRGB, texture_sRGB_decode, texture_shared_exponent, texture_snorm, 
    texture_swizzle, timer_query, transform_feedback, vertex_array, vertex_array_bgra
  GL_IBM: multimode_draw_arrays, rasterpos_clip, texture_mirrored_repeat
  GL_INGR_blend_func_separate
  GL_KHR: context_flush_control, debug, no_error, robust_buffer_access_behavior, robustness
  GL_MESA: pack_invert, shader_integer_functions, texture_signed_rgba, window_pos
  GL_NVX_gpu_memory_info
  GL_NV: blend_square, conditional_render, depth_clamp, fog_distance, light_max_exponent, packed_depth_stencil, 
    primitive_restart, texgen_reflection, texture_barrier, texture_env_combine4, texture_rectangle, vdpau_interop
  GL_OES: EGL_image, read_format
  GL_S3_s3tc
  GL_SGIS: generate_mipmap, texture_border_clamp, texture_edge_clamp, texture_lod
  GL_SUN_multi_draw_arrays
OpenGL Windowed 854x480 16 color 16 texture 60Hz NoVsync SmoothLines
LinuxEvent: Couldn't open /dev/input/event0: Permission denied.
LinuxEvent: Couldn't open /dev/input/event1: Permission denied.
LinuxEvent: Couldn't open /dev/input/event2: Permission denied.
LinuxEvent: Couldn't open /dev/input/event3: Permission denied.
LinuxEvent: Couldn't open /dev/input/event4: Permission denied.
LinuxEvent: Couldn't open /dev/input/event5: Permission denied.
LinuxEvent: Couldn't open /dev/input/event6: Permission denied.
LinuxEvent: Couldn't open /dev/input/event7: Permission denied.
LinuxEvent: Couldn't open /dev/input/event8: Permission denied.
LinuxEvent: Couldn't open /dev/input/event9: Permission denied.
LinuxEvent: Couldn't open /dev/input/event10: Permission denied.
LinuxEvent: Couldn't open /dev/input/event11: Permission denied.
LinuxEvent: Couldn't open /dev/input/event12: Permission denied.
LinuxEvent: Couldn't open /dev/input/event13: Permission denied.
LinuxEvent: Couldn't open /dev/input/event14: Permission denied.
LinuxEvent: Couldn't open /dev/input/event15: Permission denied.
LinuxEvent: Couldn't open /dev/input/event16: Permission denied.
LinuxJoystick: Opened /dev/input/js0
/////////////////////////////////////////
WARNING: Font import recursion detected
WARNING: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: /Themes/_fallback/Fonts/Common default.ini
WARNING: /Themes/Til Death/Fonts/_16px fonts.ini
WARNING: Current font: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
/////////////////////////////////////////
/////////////////////////////////////////
WARNING: Font /Themes/Til Death/Fonts/_16px fonts.ini has no characters
/////////////////////////////////////////
[mp3 @ 0x7fca50012f60] Could not update timestamps for skipped samples.
[mp3 @ 0x7fca50011a80] Could not update timestamps for skipped samples.
[mp3 @ 0x7fca50034820] Could not update timestamps for skipped samples.
[mp3 @ 0x7fca500135a0] Could not update timestamps for skipped samples.
/////////////////////////////////////////
WARNING: Font import recursion detected
WARNING: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: /Themes/_fallback/Fonts/Common default.ini
WARNING: /Themes/Til Death/Fonts/_16px fonts.ini
WARNING: Current font: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
/////////////////////////////////////////
/////////////////////////////////////////
WARNING: Font /Themes/Til Death/Fonts/_16px fonts.ini has no characters
/////////////////////////////////////////
Paletted textures disabled: GL_EXT_paletted_texture missing.
/////////////////////////////////////////
WARNING: Font import recursion detected
WARNING: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: /Themes/_fallback/Fonts/Common default.ini
WARNING: /Themes/Til Death/Fonts/_16px fonts.ini
WARNING: Current font: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
/////////////////////////////////////////
/////////////////////////////////////////
WARNING: Font /Themes/Til Death/Fonts/_16px fonts.ini has no characters
/////////////////////////////////////////
[mp3 @ 0x7fca50013a60] Could not update timestamps for skipped samples.
Mixing 3962.192627 ahead in 68211 Mix() calls
Mixing underruns: 1153
Players joined: P1
Language: en
Current renderer: OpenGL
Theme: Til Death

**Comment by TheROPFather** [comment]
You can change your sound driver in preferences.ini, try jack or pulse and see if that works.

**Comment by PawelA** [comment]
WARNING: Removed unusable sound driver jack
same with pulse
rest of log is the same as before

just to make sure i'm doing it right:
Save/Preferences.ini:
SoundDevice=
SoundDrivers=jack

**Comment by TheROPFather** [comment]
The latest development build has been tested on 16.04 and worked successfully, for now I will close the issue. There should be a new official release very soon, if when you test that you have the same problem - feel free to comment and I will reopen the issue.
