### ISSUE TITLE
Pump holds count as misses

### ISSUE THREAD

**Issue by nico-abram** [etternagame/etterna#216]

**Comment by poco0317** [comment]
Playing in pump mode, everything acts kind of normally, except for holds and rolls.
Holds cause the following problems (that I have found so far) with m_bTickHolds set to true:
1. Theme error bar ends up with permanent ghost judgements
2. Ghost judgements on the score screen graph (maybe intended)
3. Incorrect lifebar in score screen (more specific to rolls)
4. Each "checkpoint" (TNS_CheckpointHit) on holds and rolls are considered full on misses in wife. They do not appear as misses, but the percentage calculates as if they are misses.

[Here](https://github.com/poco0317/etterna/tree/pump_hold_fix1) I have a fork with some changes that fixes the 4th issue somewhat. There is still a problem with it, though. In random cases, hitting a hold or roll slightly late at the head results in a missed note/hold judgement. I'm not sure of the exact cause or as to why it only happens sometimes.
