### ISSUE TITLE
Goals created while logged out will never be added to EO

### ISSUE THREAD

**Issue by foxfire667** [etternagame/etterna#220]
**A minor issue regarding the usage of goals**
If you are logged out and create a goal, it will not be added to EO under any condition, including beating the goal while logged in at a later date. 

**To Reproduce**
- Log out of the client
- Create any goal
- You now have a bugged goal!

**Expected behavior**
When you log back in, goals not uploaded should be added to the site. Preferably Etterna would know when a goal failed to upload, and try to reupload it as soon as possible. 

**Screenshots**
![image](https://user-images.githubusercontent.com/7039995/44281669-8e05c580-a226-11e8-93c4-1a841bfca9b5.png)
![proof 2](https://user-images.githubusercontent.com/7039995/44281605-5a2aa000-a226-11e8-9dba-4e05ffaac6aa.PNG)
![proof](https://user-images.githubusercontent.com/7039995/44281606-5a2aa000-a226-11e8-906e-e0a39c4f8e63.PNG)

**Comment by poco0317** [comment]
this is resolved with the upcoming eo2 changes, as all goals not present online are uploaded immediately upon login
eeb18e627a1ec842a0a814d7a0a41bfc00558aba
