### ISSUE TITLE
Some pack downloads just crash the game

### ISSUE THREAD

**Issue by poco0317** [etternagame/etterna#229]
There are various reasons for this occurring. The most usual causes involve file structure, incorrect filetype, bad link, or no link.

**Comment by TheROPFather** [comment]
Links are slowly getting fixed. Bad file structures should be reported to @foxfire667 on https://discord.gg/etternaonline - and missing links will be added in the next day or so.

I will update you when all links are added, so you can perform further testing.

Thanks for the report.

**Comment by MinaciousGrace** [comment]
structural crashes should be handled by fefadeb5344f82098804cd71c3fdf8abaca6a1a4 (https://github.com/etternagame/etterna/pull/325)

other issues have been handled already
