### ISSUE TITLE
Make color config support direct number/letter/arrow input.

### ISSUE THREAD

**Issue by Herkkupala** [etternagame/etterna#231]
Currently you are able to change a hex code in color config with **bound Left/Right/Up/Down** keys.
A support for direct number/letter/arrow input would make changing these easier and less confusing.
![hexconfig](https://user-images.githubusercontent.com/15342856/44297965-0a5dde80-a2e3-11e8-80c7-bc91011b39d9.png)

**Comment by poco0317** [comment]
Arrow key input is the new way to input on this screen as of 0.64.
Additional changes will be made in the future.

**Comment by poco0317** [comment]
Handled in #695
