### ISSUE TITLE
[0.60.0] Some online scores not showing when Current Rate is selected

### ISSUE THREAD

**Issue by robartpond** [etternagame/etterna#237]
When viewing online scores in the Score tab on the songwheel, selecting Current Rate fails to display all of the scores on the server. For example, [when viewing Everybody Dies In Their Nightmares on 1.0](https://i.imgur.com/Hwzv5T7.png), the client fails to display the top four scores visible [on the site](https://etternaonline.com/song/view/63628). Since all four players whose scores don't appear also have scores on higher rates with higher MSDs, it appears that the client only displays scores on the selected rate that are also the players' top score on the file. This overwhelmingly affects players whose scores on the selected rate would appear higher on the list (for obvious reasons).

**Comment by nico-abram** [comment]
It appears the problem is when we get the leaderboard for a chart we're storing only the top scores. Then lua is filtering those by rate (We should store all of them and have lua filter top scores).

https://github.com/etternagame/etterna/blob/develop/src/DownloadManager.cpp#L1141

**Comment by poco0317** [comment]
This is fixed and improved upon for the next update.
New functionality still behaves the same by default, but allows toggling between Top Scores and All Scores similar to how Etternaonline currently works.
