### ISSUE TITLE
International keyboard layout/locales don't function well

### ISSUE THREAD

**Issue by poco0317** [etternagame/etterna#238]
Depending how different the layout is from the assumed default US layout, results on many input or binding screens may vary. 
For example, the ` key functions as = in some layouts, or an unknown button in others.

**Comment by YChvanov** [comment]
You not only can't use hotkeys but can't input any text such as password in multiplayer (99% sure that in the chat, too - can't test it as I can't login with my input language) or song name in search
As I mentioned in my duplicated thread, temporary solution is to restart the game with normal US layout

**Comment by kangalioo** [comment]
This also means that it's impossible to use the `artist=`/`subtitle=`/etc. feature in song search on German keyboard layouts (and probably more layouts)

**Comment by poco0317** [comment]
mitigated until someone finds out why the change sucks
2b5eab976476e026c61999ac3f7e7ce59ac41362 adc00bcace9b7728c5849210605dbf930443c432
