### ISSUE TITLE
0.60.0 - Reloading after changing name of .mp3 file, and then playing the same file causes a crash.

### ISSUE THREAD

**Issue by Wessl** [etternagame/etterna#243]
**Bug description**

While editing a file in Arrowvortex, I changed the name of the .mp3 path associated with the .sm file, then I saved the file. Then I went into Etterna and reloaded (ctrl + q), and when you preview the file, no music plays. When I tried to start playing the file, the game crashes. 

**Essentially**, I think that reloading the game with ctrl + q doesn't reload the name of the .mp3 path and is trying to load the *old* .mp3 name. If this *old* .mp3 file has been deleted or doesn't exist, the game crashes. 

Restarting the game doesn't cause the game to load the correct path either. 

 - OS: Win10

(Side note I've never submitted a bug before, I can provide additional information if necessary).

**Comment by TheROPFather** [comment]
The solution for this is to be on the file in the music wheel.

Then hit `ctrl+shift+r`. This will reload the file.

This should be handled better in the future, but this is the current solution.

**Comment by TheKamilia** [comment]
can you post the crash log please

**Comment by MinaciousGrace** [comment]
https://github.com/etternagame/etterna/pull/315
