### ISSUE TITLE
Practice Mode

### ISSUE THREAD

**Issue by eSZettt** [etternagame/etterna#252]
**Feature request!**
A different 'mode' of play, intended for practicing particular parts of a chart.

**Enabling:** User presses a button (i.e. ctrl+p, something hard to press accidentally) to enable ingame, and/or as an additional toggle in the options menu.

A **'bookmark'** feature, wherein the user can press a button to set a bookmark while in the chart, **then** a subsequent button to jump back (or ahead) to that bookmark.

A **'rewind'** feature, allowing the user to go rewind the chart (with audio?) and replay a previous section.

A **'fastforward'** feature, allowing the user to speed up the chart (with audio?) to reach the section they want to practice.

Scores would not be kept after completion, or even reset with every jump.
Combo would be reset with every jump.
Misses don't 'combo' during the jump.

**Optional:** A way to **change the rate** (and have it stay at that rate) while in the chart, in practice mode, to streamline the learning process.
**Optional:** A **'pause'** feature, to compliment the rewind and fastforward. Allowing for precision bookmarking!
**Optional:** **Exponential rewind/fastforward** - rate starts slow and gets faster the longer the skip is held, up to a maximum speed (like a vcr tape type deal.)

**Comment by DeltaEpsilon7787** [comment]
This would be extremely useful for charting.

**Comment by poco0317** [comment]
practice mode dceede9e806e73e7772b35696fce89ab3992a3b9
practice mode pausing and rate change 9748144fd62878bb9699e95ad0ee3973789f48c7
bookmark included
