### ISSUE TITLE
[0.60.0] Numpad input binds should override the number keys that switch tabs

### ISSUE THREAD

**Issue by handbeezy** [etternagame/etterna#277]
With a layout e.g. using Up and Right for NUM2 and NUM3 scrolling down the song list will work but also switch the view to the Scores (3rd) tab, and trying to switch diffs using Up doesn't work at all because it switches to the MSD (2nd) tab. This happens regardless of Numlock being on/off.

OS: Windows 7

**Comment by MinaciousGrace** [comment]
fixed by 4ec28b75d84b2664e2e22394fcfcb8990380e0f8 and if people want to be able to use numpad to swap tabs while numlock is on that'll have to be added later
