### ISSUE TITLE
[0.60.0] Client crashes on Show Replay Data of new scores

### ISSUE THREAD

**Issue by WWRS** [etternagame/etterna#283]
**Describe the bug**
Clicking "Show New Scores" crashes the client if the score was set after the update (but not if the score was set before)

**To Reproduce**
1) Game Start
1.1) [Select song and diff]
2) Scores
3) Show Replay Data

**System info:**
 - OS: Win10

**Additional context**
Theme is default Til Death
Updated from 0.56.2-CalcOnly via the 0.60.0 exe

**Comment by poco0317** [comment]
There are a couple of reasons this crash occurs, and I can't remember exactly why.
The good news is, this is fixed for whenever the next update comes out.
