### ISSUE TITLE
SM5 Scroll feature doesn't work anymore, possibly others as well

### ISSUE THREAD

**Issue by DeltaEpsilon7787** [etternagame/etterna#294]
Yo wtf, did you stop supporting SM5 gimmicks completely or something?

Regular BPM changes and stops still work.

Test chart: https://mega.nz/#!3gkESKrY!GoXTK3jUrMX7a3RlpvtviZCsiSHRCsj0vR0KMQTNnBk

Version: 0.60.0

**Comment by poco0317** [comment]
There is not enough description given here.
I tested this file on release (master) on both Cmod 780 and Xmod 5.8x (for about 780 cmod speed) and it runs fine.

What is the issue here?

**Comment by DeltaEpsilon7787** [comment]
No speed ups/speed down.
It's supposed to work just like in o!m, that is, scale the notefield accordingly.

**Comment by DeltaEpsilon7787** [comment]
Compare in 0.57.1 if you need.

**Comment by MinaciousGrace** [comment]
this was done intentionally as per our discussion on the topic and you've frittered away the last of my willingness to entertain putting it back
