### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by KaseyAnn95** [etternagame/etterna#296]
**Describe the bug**
When I select play game, it brings me to the screen to select the mode I want. Novice, beginner, etc... Once I select, it immediately tells me program crash.

**To Reproduce**
1. Go to play game
2. Click on beginner
3. Game crashes

**Expected behavior**
I hope I can fix it so that it doesn't crash and I can play.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by nico-abram** [comment]
What os are you using?

**Comment by KaseyAnn95** [comment]
Windows 10

**Comment by nico-abram** [comment]
Could you share your crashinfo? It should be in /Logs/

**Comment by poco0317** [comment]
Since we have not been given additional information, we are assuming this issue was related to pack downloads crashing the game. This should be fixed in .61. If it is not, let us know.
