### ISSUE TITLE
Pack Downloads in 0.60.0 no longer works.

### ISSUE THREAD

**Issue by BrokenGale** [etternagame/etterna#297]
The pack downloading tab no longer works.

**To Reproduce**
1. Go to packs
2. Click download on any pack not currently loaded
3. The command registers but the download does not start
4. Furthermore, if you use bundle select to download a large number of packs it can crash.

**Expected behavior**
The pack added to a download queue.

**Desktop (please complete the following information):**
 - OS: Windows 7 SP1
 - Version: Etterna 0.60.0

**Additional context**
This was not a problem when 0.60.0 was released.

**Comment by nico-abram** [comment]
Closing this since it's fixed in the develop branch
