### ISSUE TITLE
Removing notes

### ISSUE THREAD

**Issue by Quary1805** [etternagame/etterna#303]
When you remove notes (Little, Jumps, etc..) it still has same difficulty as not removing any at all. Using this method, you can top leaderboard in no time.

1. Make sure you use theme including removing notes in song options
2. Select any song and go to song options
3. Remove some notes (Little, Jumps, etc..)
4. Play it and in grade screen you see the results, it also saves to the site, removing little notes in low bpm songs is an overkill, where you can get AAA on 35+ songs

https://prnt.sc/l0l0xi
https://prnt.sc/l0l1mz

Windows 7
Version 0.60.0

**Comment by poco0317** [comment]
These options are not available in the default theme Til Death, but should be accounted for on new scores made in the next release.
