### ISSUE TITLE
Not downloading in-game packs, just cache

### ISSUE THREAD

**Issue by Astion13** [etternagame/etterna#316]
When I try to download a pack in-game, it just downloads the cache, not the pack itself

1. Open Etterna
2. Play
3. Go to "Packs" tab
4. Click Download

I just expected to download some packs, thats it lol

https://gyazo.com/7f24ba7f2545be6e71931604f6376b62
https://gyazo.com/e20de4af64c7002818c7604e439b80a6

Windows 10 Pro
Build 1803

**Comment by poco0317** [comment]
Fixed for the next release.
