### ISSUE TITLE
Add rival system alongside global/country leaderboards

### ISSUE THREAD

**Issue by Jolomann** [etternagame/etterna#318]
With the addition of global and country leaderboards, it would be cool to also have a rivals leaderboard on an additional tab, so you can compare scores between a specific set of users. Since the game already grabs info from etternaonline, perhaps the site could be used to choose a list of rivals - kind of like a friends system I suppose.

Currently the discord bot kind of supports rivals but a) you can only have one rival and b) it's limited to profile rating only. Having a comparison per song would be pretty neat
![udklip](https://user-images.githubusercontent.com/33073129/46575354-36791000-c9b4-11e8-9d74-a403e2d4101d.PNG)

**Comment by TheROPFather** [comment]
This has been implemented server side and will be client side soon.
