### ISSUE TITLE
You can switch the song when starting by entering search tab while the chart loads up

### ISSUE THREAD

**Issue by DeltaEpsilon7787** [etternagame/etterna#327]
Basically select a song, press Enter and while it's in the transition black screen, press 4 to activate song search and enter anything and amazingly, the chart you picked changes.

Demonstration: https://www.youtube.com/watch?v=R9jJI3Whd2E

**Comment by MinaciousGrace** [comment]
you can fix this and submit a pr but pending that we can all just pretend it's intentional because _nobody cares_
