### ISSUE TITLE
Remap the keys for tab switch to unfuck typing digits in Search

### ISSUE THREAD

**Issue by DeltaEpsilon7787** [etternagame/etterna#328]
Whose idea it was to map tabs like MSD, search or scores to numbers?

This makes typing digits in search tab uncomfortable.
Switch them up: Ctrl+1, Cltr+2... should open the tab.

**Comment by MinaciousGrace** [comment]
you switch tabs more frequently than you type numbers into search

ergo the former uses the more accessible shortcut
