### ISSUE TITLE
Crash on reloading out from options to loading screen (main menu)

### ISSUE THREAD

**Issue by Expl0sive** [etternagame/etterna#329]
Etterna0.61-git-07270e6a76 crash report (build 07270e6a76, 20181012 @ 07:07:49)
--------------------------------------

Crash reason: Access Violation

Unknown thread
        RageFileDriverDirectHelpers.cpp:230 C:/Games/Etterna/Songs/hi19hi19 Pack 4 - Modern Keyboardsmash/Be-Music Polyphony (hi19hi19)/*
        RageFileDriverDirectHelpers.cpp:230 C:/Games/Etterna/Songs/Minty Fresh Pack 1/Everything At Once (Cataclysm)/*
        RageFileDriverDirectHelpers.cpp:230 C:/Games/Etterna/Songs/hi19hi19 Pack 5 - Streams and Memes/Overture (hi19hi19)/*
        RageFileDriverDirectHelpers.cpp:230 C:/Games/Etterna/Songs/hi19hi19 Pack 4 - Modern Keyboardsmash/Heterochromia Iridis (hi19hi19 & TC_Halogen)/*
        RageFileDriverDirectHelpers.cpp:230 C:/Games/Etterna/Songs/boiled egg/Total Eclipse of the Sun (riktoi)/*
Thread: Main thread
        IniFile.cpp:22 Reading 'NoteSkins/dance/subtractbyzero/metrics.ini'
        IniFile.cpp:22 Reading 'NoteSkins/dance/DivideByZero/metrics.ini'
        IniFile.cpp:22 Reading 'NoteSkins/common/common/metrics.ini'
        IniFile.cpp:22 Reading 'NoteSkins/dance/default/metrics.ini'
        IniFile.cpp:22 Reading 'NoteSkins/common/common/metrics.ini'
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:233 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:233 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:233 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:233 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:233 Processing the sound while buffers are available.
Thread: Mixer thread
Thread: Music thread
        RageFileDriverDirectHelpers.cpp:230 C:/Games/Etterna/Themes/_fallback/Sounds/*
        RageFileDriverDirectHelpers.cpp:230 C:/Games/Etterna/Themes/_fallback/Sounds/*
        RageFileDriverDirectHelpers.cpp:230 C:/Games/Etterna/Themes/_fallback/Sounds/*
        RageFileDriverDirectHelpers.cpp:230 C:/Games/Etterna/Themes/_fallback/Sounds/*
        RageFileDriverDirectHelpers.cpp:230 C:/Games/Etterna/Themes/_fallback/Sounds/*
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:873 
3f8d754d: Etterna!3f260000

Static log:
Etterna0.61-git-07270e6a76
Compiled 20181012 @ 07:07:49 (build 07270e6a76)
Log starting 2018-10-13 05:01:16
Loading window: win32
Windows 6.1 (Win7) build 7601 [Service Pack 1]
Memory: 12207mb total, 24412mb swap (21983mb swap avail)
Video driver: Intel(R) HD Graphics 5500 [Intel Corporation]
              20.19.15.4963, 2-21-2018 [pci\ven_8086&dev_1616&subsys_f8401179]
Drive: "TOSHIBA MQ01ABD100" Driver: iaStorA DMA: N/A
Drive: "TSSTcorpCDDVDW SU-208GB TF01" Driver: iaStorA DMA: N/A
Sound device 0: Speakers (Conexant SmartAudio H, 6.1, MID 1, PID 100 
WaveOut software mixing at 44100 hz
Sound driver: WaveOut
Attempting to connect to: , Port: 8765
WARNING: SMOProtocol failed to connect
Video renderers: 'd3d, opengl'
WARNING: RageDisplay_D3D::TryVideoMode( 1, 960, 720, 32, 0, 0 )
D3D Windowed 960x720 32 color 32 texture 60Hz NoVsync SmoothLines
DInput: Enumerating device - Type: 0x00000413 Instance Name: "Keyboard" Product Name: "Keyboard"
DInput: Enumerating device - Type: 0x00000112 Instance Name: "Mouse" Product Name: "Mouse"
Found 2 DirectInput devices:
   0: 'Keyboard' axes: 0, hats: 0, buttons: 256 (buffered)
   1: 'Mouse' axes: 2, hats: 0, buttons: 3 (buffered)
WARNING: Font import recursion detected
WARNING: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: /Themes/_fallback/Fonts/Common default.ini
WARNING: /Themes/Til Death/Fonts/_16px fonts.ini
WARNING: Current font: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: Font /Themes/Til Death/Fonts/_16px fonts.ini has no characters
WARNING: The graphic 'Assets/Avatars/takemetothepromisedland.png' has frame dimensions that aren't a multiple of 2.
WARNING: The entire image is 762x647 and frame size is 762.0x647.0.
WARNING: Image quality will be much improved if you resize the graphic to 762x648, which is a frame size of 762x648.
WARNING: Font import recursion detected
WARNING: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: /Themes/_fallback/Fonts/Common default.ini
WARNING: /Themes/Til Death/Fonts/_16px fonts.ini
WARNING: Current font: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: Font /Themes/Til Death/Fonts/_16px fonts.ini has no characters
WARNING: RageDisplay_D3D::TryVideoMode( 1, 800, 600, 32, 0, 0 )
WARNING: Font import recursion detected
WARNING: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: /Themes/_fallback/Fonts/Common default.ini
WARNING: /Themes/Til Death/Fonts/_16px fonts.ini
WARNING: Current font: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: Font /Themes/Til Death/Fonts/_16px fonts.ini has no characters
WARNING: Font import recursion detected
WARNING: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: /Themes/_fallback/Fonts/Common default.ini
WARNING: /Themes/Til Death/Fonts/_16px fonts.ini
WARNING: Current font: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: Font /Themes/Til Death/Fonts/_16px fonts.ini has no characters
WARNING: RageDisplay_D3D::TryVideoMode( 1, 1024, 768, 32, 0, 0 )
WARNING: Font import recursion detected
WARNING: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: /Themes/_fallback/Fonts/Common default.ini
WARNING: /Themes/Til Death/Fonts/_16px fonts.ini
WARNING: Current font: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: Font /Themes/Til Death/Fonts/_16px fonts.ini has no characters
WARNING: HID devices changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: HID devices changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: HID devices changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: Font import recursion detected
WARNING: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: /Themes/_fallback/Fonts/Common default.ini
WARNING: /Themes/Til Death/Fonts/_16px fonts.ini
WARNING: Current font: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: Font /Themes/Til Death/Fonts/_16px fonts.ini has no characters
WARNING: RageDisplay_D3D::TryVideoMode( 1, 1024, 768, 32, 0, 0 )
WARNING: Font import recursion detected
WARNING: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: /Themes/_fallback/Fonts/Common default.ini
WARNING: /Themes/Til Death/Fonts/_16px fonts.ini
WARNING: Current font: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: Font /Themes/Til Death/Fonts/_16px fonts.ini has no characters
WARNING: Font import recursion detected
WARNING: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: /Themes/_fallback/Fonts/Common default.ini
WARNING: /Themes/Til Death/Fonts/_16px fonts.ini
WARNING: Current font: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: Font /Themes/Til Death/Fonts/_16px fonts.ini has no characters
WARNING: RageDisplay_D3D::TryVideoMode( 1, 800, 600, 32, 0, 0 )
Mixing underruns: 1
Players joined: P1
Lost focus to: (NULL), Etterna.exe, Explorer.EXE
Language: en
Current renderer: Direct3D
Theme: Til Death

Partial log:
669:42.796: Load script "NoteSkins/common/common/NoteSkin.lua"
669:42.796: Load script "NoteSkins/dance/DivideByZero/NoteSkin.lua"
669:42.796: LoadNoteSkinDataRecursive: subtractbyzero (NoteSkins/dance/subtractbyzero/)
669:42.796: LoadNoteSkinDataRecursive: DivideByZero (NoteSkins/dance/DivideByZero/)
669:42.796: LoadNoteSkinDataRecursive: common (NoteSkins/common/common/)
669:42.796: LoadNoteSkinDataRecursive: default (NoteSkins/dance/default/)
669:42.796: LoadNoteSkinDataRecursive: common (NoteSkins/common/common/)
669:42.796: Load script "NoteSkins/common/common/NoteSkin.lua"
669:42.796: Load script "NoteSkins/dance/default/NoteSkin.lua"
669:42.796: Load script "NoteSkins/common/common/NoteSkin.lua"

-- End of report

**Comment by poco0317** [comment]
I'm not too sure what you mean here, and the crash log doesn't tell me much other than that you might have a controller plugged in and your specs are kind of low.

Did you go into Options, back out to the main menu, and it just crashed? What exactly is happening?

**Comment by Expl0sive** [comment]
Yes, I did, that's exactly what happened...

**Comment by poco0317** [comment]
Is this crash consistent? I cannot reproduce this on our develop version.

**Comment by MinaciousGrace** [comment]
none of us can reproduce this under a variety of circumstances and nobody else seems to be reporting a similar issue so the conditions for this are either extremely specific or you crashed for a reason completely unrelated to exiting from options back to title screen, while happening to exit from options back to title screen

either way we need more information and we can't get that until someone else can reproduce this

**Comment by Expl0sive** [comment]
I'll let you know if it happens again. Seemed like something just out of
the blue, probably wasn't even Etterna the game itself that caused it.

Thanks,
Explo
