### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by faxrotial** [etternagame/etterna#331]
Etterna0.61-git-07270e6a76 crash report (build 07270e6a76, 20181012 @ 07:07:49)
--------------------------------------

Crash reason: Access Violation

Unknown thread
        RageFileDriverDirectHelpers.cpp:230 C:/Games/Etterna/Songs/O!M to SM Pack 3 by NightBunny8/(Fullerene- & Wafles) AiAe/*
        RageFileDriverDirectHelpers.cpp:230 C:/Games/Etterna/Songs/osu!mania Ranked to StepMania Pack 1 by NightBunny8/(Protastic101) Exit This Earth's Atomosphere/*
        RageFileDriverDirectHelpers.cpp:230 C:/Games/Etterna/Songs/O!M to SM Pack 4 by NightBunny8/(Wh1teh) ETERNAL DRAIN/*
        RageFileDriverDirectHelpers.cpp:230 C:/Games/Etterna/Songs/O!M to SM Pack 4 by NightBunny8/(Starry-) overcomplexification/*
        RageFileDriverDirectHelpers.cpp:230 C:/Games/Etterna/Songs/O!M to SM Pack by NightBunny8/([ A v a l o n ]) Triumph & Regret/*
Thread: Main thread
        RageSurface_Load_PNG.cpp:253 00000191314E7960
        RageSurface_Load_PNG.cpp:23 Reading the png file.
        RageSurface_Load_PNG.cpp:23 Reading the png file.
        RageSurface_Load_PNG.cpp:23 Reading the png file.
        RageSurface_Load_PNG.cpp:23 Reading the png file.
Thread: Decode thread
Thread: Mixer thread
Thread: Music thread
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:897 
        InputHandler_DirectInput.cpp:873 
        InputHandler_DirectInput.cpp:891 
        InputHandler_DirectInput.cpp:897 
        InputHandler_DirectInput.cpp:873 
c35051cb: Etterna!c30c0000

Static log:
Etterna0.61-git-07270e6a76
Compiled 20181012 @ 07:07:49 (build 07270e6a76)
Log starting 2018-10-16 00:54:46
Loading window: win32
Windows 6.2 (Win8) build 9200 []
Memory: 16365mb total, 32365mb swap (26016mb swap avail)
Video driver: AMD Radeon R9 200 Series [Advanced Micro Devices, Inc.]
              23.20.15002.11, 12-6-2017 [pci\ven_1002&dev_6939&rev_00]
WARNING: RegOpenKeyEx(80000002,HARDWARE\DEVICEMAP\Scsi) error (The system cannot find the file specified.)
Sound device 0: Speakers (2- Corsair HS40 USB G, 1.0, MID 65535, PID 65535 
WaveOut software mixing at 44100 hz
Sound driver: WaveOut
WARNING: Main title or music file for '/Songs/EightMinus 3rd Pack -Final-/borderland/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/EightMinus 3rd Pack -Final-/ezanai no sui tei óªIriya mie Lip-Auraóª/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/EightMinus 3rd Pack -Final-/fly away t.p.s/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/EightMinus 3rd Pack -Final-/HesitationSnow/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/EightMinus 3rd Pack -Final-/Hosisora no Ima/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/EightMinus 3rd Pack -Final-/koi boudou/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/EightMinus 3rd Pack -Final-/moetabi120%/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/EightMinus 3rd Pack -Final-/mousousyoujyoA/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/EightMinus 3rd Pack -Final-/Muzuryokuaria/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/EightMinus 3rd Pack -Final-/Naisho no Hanashi/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/EightMinus 3rd Pack -Final-/nibbon egao hyakku kei/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/EightMinus 3rd Pack -Final-/Seizin no Tou/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/EightMinus 3rd Pack -Final-/Signal graph/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
Attempting to connect to: , Port: 8765
WARNING: SMOProtocol failed to connect
Video renderers: 'd3d, opengl'
WARNING: RageDisplay_D3D::TryVideoMode( 1, 1920, 1080, 32, 0, 0 )
D3D Windowed 1920x1061 32 color 32 texture 59Hz NoVsync SmoothLines
DInput: Enumerating device - Type: 0x00000413 Instance Name: "Keyboard" Product Name: "Keyboard"
DInput: Enumerating device - Type: 0x00000112 Instance Name: "Mouse" Product Name: "Mouse"
Found 2 DirectInput devices:
   0: 'Keyboard' axes: 0, hats: 0, buttons: 256 (buffered)
   1: 'Mouse' axes: 3, hats: 0, buttons: 6 (buffered)
Language: en
Current renderer: Direct3D
Theme: Til Death

Partial log:
00:09.083: Load script "NoteSkins/common/common/NoteSkin.lua"
00:09.083: Load script "NoteSkins/dance/DivideByZero/NoteSkin.lua"
00:09.083: Load script "NoteSkins/dance/subtractbyzero/NoteSkin.lua"
00:09.109: ScreenManager::ThemeChanged
00:09.109: RageSound: Load "/Themes/Til Death/Sounds/Common value.ogg" (precache: 0)
00:09.112: RageSound: Load "/Themes/_fallback/Sounds/Common Coin.ogg" (precache: 1)
00:09.116: RageSound: Load "/Themes/_fallback/Sounds/Common Cancel.ogg" (precache: 1)
00:09.119: RageSound: Load "/Themes/_fallback/Sounds/Common invalid.ogg" (precache: 0)
00:09.121: RageSound: Load "/Themes/_fallback/Sounds/Common screenshot.ogg" (precache: 0)
00:09.121: Loading screen: "ScreenSystemLayer"

-- End of report

**Comment by poco0317** [comment]
Unfortunately stepmania/etterna's crash logs are often not useful for telling us all the information we need.
Based on past crashing symptoms (and the reason shown at the top of the log here), associated with the fact that you are on d3d and crashing on startup I assume you are running 64 bit windows.

Read the changelog found on the .61 release page for assistance on this issue, or continue to read this comment: To fix this crash, find Preferences.ini in your Save folder and change VideoRenderers=d3d to VideoRenderers=opengl. If that still does not work, download the 32 bit version (i386 exe).

A hotfix release may come soon which will solve this exact issue entirely.
If I am incorrectly assuming you are crashing on startup using the Windows 64 bit version on d3d, let me know. (Another crash is related to multithreading.)
