### ISSUE TITLE
Selected avatar is not present on profile select screen

### ISSUE THREAD

**Issue by PPProviden** [etternagame/etterna#332]
**Describe the bug**

After any avatar is chosen, it will not be properly shown on the profile select screen, it will only show the default 'no avatar' placeholder.

**To Reproduce**
1. Go to profile select screen with a profile that has an avatar.

**Screenshots**

https://cdn.discordapp.com/attachments/395382822837157898/502840293050155008/2018-10-19_214712.png

**Comment by MinaciousGrace** [comment]
217509a666d3aa098d094354c0012f66071317e9
