### ISSUE TITLE
Access violation upon quitting to main menu from profiles screen

### ISSUE THREAD

**Issue by Daikyi** [etternagame/etterna#334]
**Description**
Upon entering the select profile screen (assuming multiple profiles to select from), if the player instead quits back to the menu, the game crashes.

**To Reproduce**
1. Have more than 1 profile
2. Enter the Game Start option
3. Do not select a profile, instead hit Escape to pull up the "Press start to join" prompt
4. Press escape again, and the game crashes

**Expected behavior**
The game should properly hit the main menu without crashing

**Comment by poco0317** [comment]
Fixed in latest develop, for the next release.
