### ISSUE TITLE
Code Page Error

### ISSUE THREAD

**Issue by xNihil0** [etternagame/etterna#336]
**Describe the bug**
Download and extraction don't work when dealing with non-ascii characters.

**To Reproduce**
Download any pack contains those characters.
For example, Einar Final.

**Expected behavior**
We encounter an error while extracting the files.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1803

**Comment by nico-abram** [comment]
@xNihil0 Do you know if this is still an issue? And if so, do you know any smaller packs than Einar Final that can be used to reproduce the problem? That one's 1200+MB

**Comment by poco0317** [comment]
This is temporarily resolved by a recent change which replaces these characters with _ if they appear in the path. This may break some .sm metadata pointers, but the auto resolution the game does should be able to cope. If this change creates a new issue, let us know
