### ISSUE TITLE
Crash on profile saving when the chart is changed

### ISSUE THREAD

**Issue by DeltaEpsilon7787** [etternagame/etterna#339]
**Describe the bug**
Etterna crashes on "saving profile" screen if you play and then edit a chart in a single session, reload it and play it again. Possibly related to chart hash keys.

**To Reproduce**
0. All in one session
1. Create a test chart
2. Add a note to it
3. Play it.
4. Change anything in the chart
5. Ctrl-Shift-R it.
6. Play it again
7. Crash on "saving profile" screen.

**Expected behavior**
The usual.

**Desktop:**
 - OS: Win7
 - Version: 61.1

**Additional info**
[crashinfo.txt](https://pastebin.com/tKRjrV7m)

**Why should you care, Mina edition**
Playtesting is annoying when you have to restart Etterna after every little change.

**Comment by MinaciousGrace** [comment]
60e28cad6cb6a1eb693f02881f7c993fc5622f34
