### ISSUE TITLE
Add Pack Refresh

### ISSUE THREAD

**Issue by Sklitterbeer** [etternagame/etterna#341]
**Describe the bug**
If one were to be working on a pack in Etterna, the only way to add songs to the pack to work on them afterwards is renaming the pack to force a separate entry in the cache. Obviously this clutters a lot and isn't very practical for mappers.

**To Reproduce**
1. Make a new pack with at least one song
2. Close Etterna and add a new file to this pack
3. Reload Etterna, new file isn't present
4. Close Etterna, rename the pack
5. New cache entry is added and file is playable

**Expected behavior**
That with sanity checking, the files be added automatically.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
Talked about this in the server, a plausible solution may be whitelist certain packs to sanity check or add an in-game pack refresh button (like we have a ctrl shift r for single files now).

**Comment by Sklitterbeer** [comment]
edit: I installed my etterna on stepmania 5 which is what likely caused the problem. however, after making changes, ctrl q only displays newly added songs. removed songs are shown with a purple background. either way, after restarting etterna once, it thinks I have no files at all. after restarting twice, it works normally.

**Comment by MinaciousGrace** [comment]
aa9445054cc2afc2a5fb76d64c47ce6af33b65dd
