### ISSUE TITLE
[Score Screen] full combos are displayed as clears sometimes

### ISSUE THREAD

**Issue by PPProviden** [etternagame/etterna#345]
**Describe the bug**
When songs are cleared with full combos, they are displayed as FC under the grade in the scoreboard, but if i produce another score, the first score's fc will get displayed as  just CLEAR.

**To Reproduce**
1. FC a song
2. play through the song again
3. go to the results screen

**Expected behavior**
FCs stays as FCs across any plays on the same song.

**Screenshots**
![2018-11-02_214837](https://user-images.githubusercontent.com/31165158/47918969-1a03c100-dee9-11e8-9bd4-026861b4f5db.png)
the 2nd to 4th scores are all fcs but they are not displayed as so

**Desktop (please complete the following information):**
 - OS: win10
 - Version: 0.61.1

**Comment by MinaciousGrace** [comment]
9b8dbeb12ce5e8636b8036b7339a836cdb929f0c
