### ISSUE TITLE
[Feature Request] Show cleartype in song select screen general tab

### ISSUE THREAD

**Issue by PPProviden** [etternagame/etterna#346]
**Feature requested**
Make the PB cleartype visible directly in the general tab.

**Reason**
The current cleartype for songs are not directly viewable without clicking on the score tab, Doing this will make transitioning from other VSRGs easier, similar to features like clearlamps on bms.

**Screenshot**
https://cdn.discordapp.com/attachments/390537998913110016/508275643167801354/2018-11-03_214437.png

**Comment by MinaciousGrace** [comment]
1446cba91f6c15b3bb4b99b6cd59716a302349e7
