### ISSUE TITLE
Add judge and life level

### ISSUE THREAD

**Issue by mspstommy** [etternagame/etterna#351]
i wanna see judge and life level in score in game
 like the rate 1.0 1.05 than i can filter scores
maybe it can cooperate with rate
![2018-11-07_170025](https://user-images.githubusercontent.com/44832675/48121034-d1645300-e2ae-11e8-94a5-a2d368f87d0d.jpg)

**Comment by MinaciousGrace** [comment]
judge display added by 212995defcdcd24f54fbcba70150fad4dbbd2084
life level's aren't tracked
adding a judge filter for scores seems a bit excessive, i don't think it's worth it

**Comment by mspstommy** [comment]
how about just display on every scores
