### ISSUE TITLE
insong leaderboard percentage color does not match current scoretype

### ISSUE THREAD

**Issue by PPProviden** [etternagame/etterna#356]
**Describe the bug**
If the insong leaderboard is enabled, your percentage color will remain gold even if your current score is not an aaa.

**To Reproduce**
1. Enable leaderboard in song.
2. Get score below aaa

**Expected behavior**
The color should match your current scoretype(99.98% gives the color pale blue for aaaa, >93% gives the green color for aa)

**Screenshots**
![2018-11-11_223229](https://user-images.githubusercontent.com/31165158/48316727-6a35fe00-e622-11e8-8695-6c074f1f4e26.png)

**Comment by MinaciousGrace** [comment]
28d63b500fda09bda64f620ff6ba63aba4617928
