### ISSUE TITLE
Favoriting a song can sometimes crash the game

### ISSUE THREAD

**Issue by pball0010** [etternagame/etterna#358]
**Describe the bug**
I liked a song and wanted to favorite it in Etterna. So I used ctrl + F to favorite and Etterna crashed. Opened it back up and was able to favorite and unfavorite it only a few times before it crashed again.

**To Reproduce**
1. Open Etterna
2. Log in (or use an online profile)
3. Ctrl + F a bit
4. Crash maybe?

**Expected behavior**
Expected to give it a heart + favorite the track

**Screenshots**
Might be able to replicate on a twitch stream sometime maybe? Otherwise, hard to screenshot as it wasn't graphical.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version Windows 10

**Additional context**
I think its literally because the Charted song in particular wasn't in the Etterna online database and it gave a 404 about it
[log.txt](https://github.com/etternagame/etterna/files/2582924/log.txt)

**Comment by MinaciousGrace** [comment]
can you post your crashlog.txt as well we're having trouble reproducing this

**Comment by Jousway** [comment]
may I ask why you are still using 0.60, and reporting a bug for the old 0.60 version while 0.62 is released, also what is "Til Lapras"?

**Comment by pball0010** [comment]
I couldn't figure out how to get .62 to update and .6 is the one that the website still packages. Also, Til Lapras is just me playing around with the theme to personalize Til Death a bit to make the color scheme more blue

Sent from Yahoo Mail on Android 
 
  On Wed, Nov 14, 2018 at 6:56 PM, Alexander Griffin<notifications@github.com> wrote:   
may I ask why you are still using 0.60, and reporting a bug for the old 0.60 version while 0.62 is released, also what is "Til Lapras"?

**Comment by nico-abram** [comment]
If you've done any modifications to the contents of the Til Death folder, please mention them (Sometimes doing that makes updating buggy).

Could you try downloading the latest version in a fresh install and checking if the error still happens? If it works, and you're interested, feel free to ask for help migrating your profile and config to the new install in the etternaonline discord. (Should be as simple as moving /Save/ to the new folder, pointing to the songs folder in /Save/preferences.ini AdditionalSongsFolder and copying your noteskins MAKING SURE you don't copy common noteskins which are sometimes modified through versions and could break all your noteskins if you copy it)

Downloads are here: https://github.com/etternagame/etterna/releases

**Comment by pball0010** [comment]
Hi I updated as you told me to do, and I still got the error. I could favorite, but if I did it fast repeatedly, it crashed.

Most of the mods I've made have just been either graphical (making things look blue as I'd like to have it blue and not purple) and minor personal quirks (adding my own quotes to the beginning thing). I could try downloading the program fresh in another etterna folder and see if the second instance crashes like the first one does.

*Update* I think I found my issue: I must've left out a comma in my beginning quotes to where it somehow affected favoriting. After I updated that, there weren't any issues, but as soon as I added commas I forgot in the beginning dialogues, it got fixed. Don't know what favoriting has to do with the beginning, but /shrug
Patrick Ball (not Jack Bobblson like it says) 

    On Friday, November 23, 2018, 10:10:10 AM CST, Nicolas <notifications@github.com> wrote:  
 
 
If you've done any modifications to the contents of the Til Death folder, please mention them (Sometimes doing that makes updating buggy).

Could you try downloading the latest version in a fresh install and checking if the error still happens? If it works, and you're interested, feel free to ask for help migrating your profile and config to the new install in the etternaonline discord. (Should be as simple as moving /Save/ to the new folder, pointing to the songs folder in /Save/preferences.ini AdditionalSongsFolder and copying your noteskins MAKING SURE you don't copy common noteskins which are sometimes modified through versions and could break all your noteskins if you copy it)

Downloads are here: https://github.com/etternagame/etterna/releases

**Comment by MinaciousGrace** [comment]
well it seems odd that a theme error of that kind could cause the game to crash, crash-proofing lua binds in general is a legitimate broader issue, but this particular case doesn't have anything to do with the base theme
