### ISSUE TITLE
Crash after playing a song

### ISSUE THREAD

**Issue by YChvanov** [etternagame/etterna#359]
**Describe the bug**
Crash after playing a song

**To Reproduce**
I've done nothing special, was just casually playing

**Expected behavior**
Just continue playing and don't restart the game?

**Desktop:**
 - OS: Windows 10 1607
 - Version 0.62.0

**Additional context**
> Very VERY rare crash when saving profile after a play. Please report any instances of this, especially if you get the special crash message I placed where I think it's happening.

> Crash reason: congrats you just confirmed the cause of a rare non-repdroducible bug. pd: 3

There is no issue for this? As you said to report this here it is. Hope this helps.
[crashinfo.txt](https://github.com/etternagame/etterna/files/2582938/crashinfo.txt)

**Comment by MinaciousGrace** [comment]
we had blind fixed for the hotfix with 2c81ea0fa82819ab4a0aadaffffb32300c24d79f

however this log along with a couple of others received today pretty strongly indicate the source of the problem, which is failed lookup/conversion of old difficulty names to new enums (every song that has crashed in this way has had a difficulty of "hard", but also an old dwi file where the difficulty was listed as "MANIAC"

why the conversion failure seems to be inconsistent I'm not sure but we've got a good place to start looking in now
