### ISSUE TITLE
Chart Previewer & Chord Density Graph Bugs

### ISSUE THREAD

**Issue by poco0317** [etternagame/etterna#368]
(Basically notes for development)

~Seeking forward is nonfunctional when you turn off the preview, switch songs, then turn it back on.~
~A file with a sample music start position beyond the final note causes the chart previewer to not work at all, basically.~
~Chart previewer shows up for 1 frame if you exit the screen after turning off chart preview.~
Chart preview causes a serious stutter when changing keymodes.
Chart preview reappears if you turn it off then switch keymodes.
~Chart preview may not set the start position quick enough (we really need to rewrite the section that triggers/starts the music for ScreenSelectMusic in general tbh)~
~Verify that there are no memory leaks. It is possible we leak the music pointers or notedata related items.~
~Notefield/Notefield background is off center on 4:3.~
Some files don't allow the ability to seek near the beginning of them. Not sure what causes it.
Some files are very out of sync consistently.

~Chord Density Graph does not scale for rates.~
~The generator for the graph errors out on 3 panel files (im surprised that this is still in the game and functions...)~
Does not function completely correct for files above 4k.
The bar coloring function can probably be changed so it is more compatible with keymode.

**Comment by MinaciousGrace** [comment]
8b10acab090ddbc074c5d30094e95caa04e468f2 and a couple other commits enables cd graph scaling with rates

**Comment by MinaciousGrace** [comment]
the bulk of these are done and those that arent are more significant to fix and should probably have their own issue
