### ISSUE TITLE
Timestamps in Multichat

### ISSUE THREAD

**Issue by Nekonab3** [etternagame/etterna#392]
Title says it all, Suggestion to add timestamps to Multiplayer chat.

**Comment by nico-abram** [comment]
This should be a 1-3 liner, and i think only lua. I *might* look into it this week if no one else does. Is there a reason to make this optional or should it be hardcoded? If it is made optional, where exactly should i put the option.

**Comment by nico-abram** [comment]
Also, I'm guessing the timestamp should only be time of day (No date, and no milisecond, something like hh:mm:ss). And maybe not even second? Thoughts? What color should the timestamp be? Should it be part of color config? (A new entry or an existing one?)

**Comment by nico-abram** [comment]
https://github.com/etternagame/etterna/blob/develop/Themes/_fallback/BGAnimations/ScreenChatOverlay%20overlay.lua#L206
This is probably the place to do it

**Comment by nico-abram** [comment]
Done
