### ISSUE TITLE
Game crash when changing noteskin

### ISSUE THREAD

**Issue by Miz0re** [etternagame/etterna#395]
Game crashes when you change the noteskin in player options and change songs while having the file preview on.

1. Toggle Preview
2. Go to Player options using the button
3. Change noteskin and save
4. Change song
5. Crash

build d25f4e5b73

[Crashinfo.txt](https://cdn.discordapp.com/attachments/395382822837157898/518338386441011221/crashinfo.txt)

**Comment by poco0317** [comment]
Weak fix but does not solve the problem completely: #396

**Comment by nico-abram** [comment]
Tagging this as mantainance since it's "fixed"

**Comment by poco0317** [comment]
Rewrites to chart preview and other previous changes fixed this
