### ISSUE TITLE
Crash leaving evaluation screen on Linux

### ISSUE THREAD

**Issue by Miz0re** [etternagame/etterna#399]
After clearing a song and leaving the song evaluation screen crashes the game.

[Valgrind log](https://github.com/etternagame/etterna/files/2637994/gdb.txt)

**Comment by MinaciousGrace** [comment]
![jpg jpg](https://user-images.githubusercontent.com/13737743/49498376-d3331f00-f838-11e8-9459-5996845071f0.jpg)
