### ISSUE TITLE
Compile on linux failes because of MinaCalc.a

### ISSUE THREAD

**Issue by Pazzaz** [etternagame/etterna#4]
I'm using
- Ubuntu 17.04
- cmake 3.7.2
- make 4.1
- g++ 7.01

When trying to build everything goes smoothly except on the very last step when linking the executable.
````
[100%] Linking CXX executable ../../stepmania
/usr/bin/ld: ../../extern/MinaCalc/MinaCalc.a(MinaCalc.cpp.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
CMakeFiles/StepMania.dir/PlayerStageStats.cpp.o: In function `PlayerStageStats::GenerateValidationKeys(HighScore&) const':
PlayerStageStats.cpp:(.text+0xb47): undefined reference to `GenerateWeakValidationKey[abi:cxx11](int const*, int const*)'
/usr/bin/ld: final link failed: Symbol needs debug section which does not exist
collect2: error: ld returned 1 exit status
src/CMakeFiles/StepMania.dir/build.make:9837: recipe for target '../stepmania' failed
make[2]: *** [../stepmania] Error 1
CMakeFiles/Makefile2:380: recipe for target 'src/CMakeFiles/StepMania.dir/all' failed
make[1]: *** [src/CMakeFiles/StepMania.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
````

I don't really get how I would recompile it and/or where the flag -fPIC would be applied. Am I doing something wrong?

**Comment by MinaciousGrace** [comment]
the calc is closed source and needs to recompiled for each platform whenever I update it, and since I work on windows the .a doesn't get recompiled with every calc change

it's undergoing frequent tuning at the moment and hasn't been updated in a little while, I'll get it recompiled and committed later today

**Comment by MinaciousGrace** [comment]
linux calc has been updated, it won't always be cutting edge up to date but I'll try to get it recompiled every time new functions are added so that builds don't fail due to missing symbol links

it -should- work now

**Comment by Pazzaz** [comment]
Well it still isn't working on my end, even after the changes.
It still ends with the error about MinaCalc like so:
```
[100%] Linking CXX executable ../../stepmania
/usr/bin/ld: ../../extern/MinaCalc/MinaCalc.a(MinaCalc.cpp.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
src/CMakeFiles/StepMania.dir/build.make:9837: recipe for target '../stepmania' failed
make[2]: *** [../stepmania] Error 1
CMakeFiles/Makefile2:380: recipe for target 'src/CMakeFiles/StepMania.dir/all' failed
make[1]: *** [src/CMakeFiles/StepMania.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by RGates94** [comment]
@Pazzaz As these changes were only pushed to the working branch 'Etternalmemestatus', if you are compiling from master you will still have trouble.  Please try compiling from this branch if you have not done so.  If you are still having trouble compiling on this branch we will investigate further.

**Comment by Pazzaz** [comment]
I've been compiling from Etternalmemestatus all along.

**Comment by ledoge** [comment]
So how is keeping the calc closed source not a GPL violation?

**Comment by RGates94** [comment]
Calc is 100% original code, can not be included by terms of MIT licence any more than any closed source external library.

**Comment by MinaciousGrace** [comment]
someone else has successfully compiled on g++ 7.1.1, so I'd try that pending other compiler related error fixes

**Comment by Pazzaz** [comment]
Using g++ 7.1 worked, thanks for the help.
