### ISSUE TITLE
Rolls [green noodles] followed by a close note force bads unless manipped

### ISSUE THREAD

**Issue by DeltaEpsilon7787** [etternagame/etterna#401]
**Describe the bug**
Seems like unlike holds, roll bodies don't hold priority when determining which note is hit. So if you tap a roll near its end and there is a note that follows less than the timing window away, you'll hit the note instead of the roll forcing a bad judgement. Coupled with a stupidly low allowed tap rate, this makes rolls near unusable in most scenarios.

**To Reproduce**
1. Make a chart
2. Add a roll to any lane
3. Add a hold, note or even another roll less than 180 ms away from the first roll's end
4. Play

**Expected behavior**
Same as holds, until a roll ends it should be hit.

**Comment by Kangaroux** [comment]
I think this should have a higher priority. This is incredibly annoying.

**Comment by nico-abram** [comment]
*Maybe* removing the second part of the or here fixes this? https://github.com/etternagame/etterna/blob/13267c3a4bfcf1c0713b77496ff1a4361e1ce4ed/src/Player.cpp#L981-L983

**Comment by poco0317** [comment]
7939f488440b3532a69bf4c9deef9fc1839ebd85
