### ISSUE TITLE
Packs don't download fully on slow connections.

### ISSUE THREAD

**Issue by RaymondTracer** [etternagame/etterna#402]
**Describe the bug**
When you try to download packs on a slow connection, the download stops part way through and a new download starts (if there are anymore queued).

**To Reproduce**
1. Go to the pack downloader on a slow connection.
2. Queue up a bunch of packs.

**Expected behavior**
The download to complete before moving to the next item.

**Screenshots**
![image](https://user-images.githubusercontent.com/6290310/49512327-b999e200-f8e1-11e8-8f0d-90fdcf123f40.png)
![image](https://user-images.githubusercontent.com/6290310/49512402-f82f9c80-f8e1-11e8-91b4-cb0f23803b9e.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 x64 SP1
 - 0.63.0 x64

**Additional context**
N/A

**Comment by Kangaroux** [comment]
Are you on wifi? My guess is this is due to an unstable connection rather than a slow connection (though the two aren't mutually exclusive)

**Comment by RaymondTracer** [comment]
No, I'm connected to my router via Ethernet.

**Comment by Kangaroux** [comment]
Open a command prompt and run `ping east.stepmania-online.com -n 100`, and let it go until it's finished, then paste the summary at the end, which looks something like this:

```
Ping statistics for 208.113.201.33:
    Packets: Sent = 10, Received = 10, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 30ms, Maximum = 31ms, Average = 30ms
```

**Comment by RaymondTracer** [comment]
The mirror did work better, thanks for the help. Perhaps the mirror should be an option for first time installations.

**Comment by MinaciousGrace** [comment]
bundle download options for new installs always using non-mirror links is an oversight on our part
good observation

**Comment by nico-abram** [comment]
Accomplished by https://github.com/etternagame/etterna/commit/49bcaa357d3e96f3c7a853efc3ceb05c5850d454
