### ISSUE TITLE
CMake Configure Issue

### ISSUE THREAD

**Issue by jmaster23** [etternagame/etterna#41]
Every time I click on configure on CMake 3.9.0 I get this error:

'CMake Error at CMakeLists.txt:3 (project):
  Failed to run MSBuild command:
    MSBuild.exe
  to get the value of VCTargetsPath:
Configuring incomplete, errors occurred!
See also "D:/Games/etterna-master/Build/CMakeFiles/CMakeOutput.log".'

My source code is: D:/Games/etterna-master
My build location is : D:/Games/etterna-master/Build
I downloaded MSBuild again to make sure but I keep getting the same error.
If you can help me that would be great.

**Comment by Nickito12** [comment]
<a href="https://github.com/Nickito12/etterna/wiki/Building-Etterna">This </a> might help.
Make sure you have the visual studio version you're configuring for installed(If you do you might want to search in google for the error "Failed to run MSBuild command: MSBuild.exe"). 
Also, make sure you're using the etternalmemestatus branch.
