### ISSUE TITLE
Ingame asset selectors

### ISSUE THREAD

**Issue by nico-abram** [etternagame/etterna#413]
Make some kind of ingame selector for toasties and judgments. They could be a separate thing or simply a row in options (I'm not sure which is best). It'd be nice to have the config part of it in _fallback, and store the settings globally per profile (Not per-theme) so the judgment and toasty stays the same across themes. Toasties should maybe go in a folder each (Since it's 2 files). It also might be a good idea to add an optional lua file for toasties, that's maybe a function that operates on the toasty sprite, so it can do whatever it wants. Something like:
```
    return {InitCommand = function(self) end, ToastyMessageCommand = function(self)  end}
```

**Comment by MinaciousGrace** [comment]
duplicate https://github.com/etternagame/etterna/issues/380

**Comment by nico-abram** [comment]
This was actually the original

**Comment by nico-abram** [comment]
Also wait thats a pr not an issue, how Is this a duplicate

**Comment by poco0317** [comment]
r u hi
