### ISSUE TITLE
Seeking the song preview on the menu doesn't always work correctly

### ISSUE THREAD

**Issue by Kangaroux** [etternagame/etterna#416]
**Describe the bug**
When you open the song preview on the menu (where it shows the notes being played), sometimes when you try to seek to a specific part of the song, the playback resets to the start position instead of where you selected.

It seems this only happens the first time you select a song after switching to a new pack. It only resets the playback if you select a part of the song that's after where the audio preview would normally end. For example, if the song preview is from 0:30 to 0:45, I can select any time from 0:00-0:30 but I can't select a time past 0:45 (it resets back to 0:30).

**To Reproduce**
1. Switch to a new pack
2. Select a song and open the preview
3. Try to seek the preview near the end of the song, it shouldn't work
4. Now switch to another song in the same pack and try again, it should work now

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.64.0

**Comment by MinaciousGrace** [comment]
413a61fea9b1b4c5eb849e3302227f8a3e5eb558
