### ISSUE TITLE
adjusting offset directly ingame in options

### ISSUE THREAD

**Issue by PPProviden** [etternagame/etterna#418]
Currently the visual delay is directly adjustable by opening the f3 debug menu and pressing e and r keys, but you can only change the machine offset by entering a song and pressing shift+alt+f11/f12. Both are difficult and obscure for beginners. In Options screens, the calibration options should display the offset value directly, and allow c-mod like adjustment.

Another very useful feature would be to allow a complete reset of both your visual and machine offset.

**Comment by poco0317** [comment]
Added to the debug menu for 0.66 by 5738f17fdb04350bb708ca945e4306b186a65310
Will add to the regular options menu, probably later.

**Comment by poco0317** [comment]
moved visual delay to graphics options in 0.70 or 0.71.
changed it to a numerical thing that you can change with finer increments, and also added global offset to that menu in 0.72.
