### ISSUE TITLE
Disable Alt + Enter and windows key during game play

### ISSUE THREAD

**Issue by SharpnelXu** [etternagame/etterna#419]
These two shortcuts constantly interrupt my game play, so I think it would be a nice feature to have them disabled on `ScreenGameplay`.

I understand windows key might be a system level thing, so I don't expect too much on that one, but `Alt + Enter` should be a program related shortcut. (If it isn't then I will just delete the issue.)

**Comment by MinaciousGrace** [comment]
810b76d77d10bac8aabdbc6ca543607f25b965db
