### ISSUE TITLE
Playlist courses resets notefield position

### ISSUE THREAD

**Issue by SharpnelXu** [etternagame/etterna#422]
**Describe the bug**
If you play a playlist with multiple courses, the note field position will be reset to default after the first song is finished.

**To Reproduce**
1. Create a new playlist with multiple songs
2. Adjust notefield position so the change will be obvious
3. Play the play list and wait till the first song finishes
4. Notefield position will be reset to default immediately after

**Expected behavior**
Notefield position should use/apply changes from profile rather than reset to default.

**Screenshots**
[Before](https://puu.sh/Cptrs/f1df1c0465.png)
[After first song](https://puu.sh/Cptrw/8cbc75041c.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 0.64

**Comment by MinaciousGrace** [comment]
54c390b8ead4e9221c2e928031550051c25dd42b

i did not test this extensively so if this doesn't completely fix it let me know
