### ISSUE TITLE
more specific sound options

### ISSUE THREAD

**Issue by Bakuretsue** [etternagame/etterna#425]
hi

I find it bothering how you can adjust your receptor size  by the exact percentage but this was not implementen for sound options. I'm dealing with a broken headset and it plays sound volume at 100% I can't adjuist this with windows mixer and it has to do with my headset, I'll be getting a new one soon but I think dividing sound options by portions of 10% isn't specific enough to make difference for me. Just like the Receptor size I think it would be handier if a player was able to use arrow keys to increase or decrease their volume with 1% every time an arrow is pressed.

bye

**Comment by poco0317** [comment]
e2c5288a7f1a4792e109e683800447b57b604e13
