### ISSUE TITLE
Arch Linux - No sound

### ISSUE THREAD

**Issue by LoPij** [etternagame/etterna#426]
On start sound is ok. But after for example opening a web-browser with playing music or got notification in discord. Sound is permanently disappear. Tried to switch to pulse, jack, alsa in `Save/Preferences.ini` but nothing helped. Any ideas?

**Comment by poco0317** [comment]
We may need more information such as what exact distro and version you are on.

**Comment by kangalioo** [comment]
For me, it works flawlessly. I'm using Etterna 0.64 on Arch Linux 4.19.2 with PulseAudio 12.2.

**Comment by LoPij** [comment]
Arch Linux 4.20
PulseAudio 12.2
Etterna 0.64

**Comment by LoPij** [comment]
Tried fix this by enabling dmix. But not helped too

**Comment by LoPij** [comment]
Okay i found the problem. First of all i remove pulseaudio and installed jack and now everything working fine. Sorry for wasting your time.
