### ISSUE TITLE
Items of favorites doesn't delete

### ISSUE THREAD

**Issue by YChvanov** [etternagame/etterna#428]
**Describe the bug**
I can't delete some items in 'Favorites' playlist

**To Reproduce**
1. Start the game, open up playlists, Favorites, delete any
2. Exit the game
3. Upload Etterna.xml to etternaonline.com
3.1. Check favorites to make sure everything stayed the same
4.  Start the game, open up playlists, Favorites, see that nothing changed

**Expected behavior**
Items in list to delete

**Screenshots**
[A video instead](https://youtu.be/QMKleyAthD8)

**Desktop**
 - OS: Windows 10 LTSB 1607
 - Version: 0.64.0

**Additional context**
I retried like 15 times, but no success on these two
They can't be deleted using CTRL+F, too
I've tried adding and deleting an other song - it works, but not always at first try

**Comment by YChvanov** [comment]
Oh, oh! I don't understand how, but I deleted them by pressing CTRL+F and then deleting "Favorites" playlist

**Comment by MinaciousGrace** [comment]
seems like there's some awkward interaction with the favorites playlist and the favorites system, and how the favorites save/load probably has to do with it as well

i can look into it later but it's not super high priority and it may well get fixed by overhauling the favorites/playlists etc. save/load systems anyway

**Comment by MinaciousGrace** [comment]
you need to save your profile in order for a bunch of profile changes to persist, including this one, however i'll just disable the delete button on the favorites playlist to hopefully avoid confusion about how you're supposed to manage it

**Comment by MinaciousGrace** [comment]
20e94f0ab3368a87c577e6e7826dae1863d39c10
