### ISSUE TITLE
Creating a second goal of the same chart difficulty remakes the old one with given speed modifier

### ISSUE THREAD

**Issue by YChvanov** [etternagame/etterna#432]
**Describe the bug**
I have a 1.0x goal which is a few months old. Now I wanted to make 0.9x one, but it also remakes 1.0x with 0.9x modifier and new creation date.

**To Reproduce**
1. Select a song and press CTRL+G (make 1.0x goal)
1.1. Check that you made one 1.0x goal
2. Press "-" and then CTRL+G (make 0.9x goal)
3. See two 0.9x goal with the same creation time

**Expected behavior**
Make a new 0.9x goal without touching 1.0x one

**Screenshots**
[Video is better, sure?](https://youtu.be/jO01Krio9Zk)

**Desktop (please complete the following information):**
 - OS: Windows 10 1607 LTSB
 - Version: 0.64.0

**Additional context**
It doesn't apply between difficulties

**Comment by MinaciousGrace** [comment]
well this is disconcerting

**Comment by MinaciousGrace** [comment]
2083d82098e8d71823fb8e7675646856d3db63eb

**Comment by YChvanov** [comment]
sorry about that, I was just lazy to unclick one click-box :grimacing:
