### ISSUE TITLE
Separating the multiple Difficulties of a single .sm file so they can be sorted.

### ISSUE THREAD

**Issue by BrokenGale** [etternagame/etterna#443]
Currently all difficulties belonging to a .sm file is grouped and sorted together. The current sorting system only accounts for the highest difficulty in that .sm file. For example Trickstarz only sorts and filters by its highest difficulty (MSD 27.52) while it has vastly different "child" charts of lower difficulty that are not sorted. Higher skill level players may not notice/care about this but it is a serious problem for lower level players who cannot find charts that they are able to play.

**Comment by MinaciousGrace** [comment]
this will be handled when moving to the lua music wheel

**Comment by poco0317** [comment]
handled by ... something...
multiple things...
lua wheel is in place on a new theme which employs this and recent changes to filtering works on a per chart level rather than a per song level
