### ISSUE TITLE
Edits in simfile lengths not reflected in game

### ISSUE THREAD

**Issue by InfiniteRealm** [etternagame/etterna#445]
On saturday, I was making my own simfile for a song I really like. After around about an hour, I got halfway through making the song... So I decided to test it out in-game. The file loaded perfectly and played just as it should have. I decided to leave it there and call it a day. The next day, I went back into the ArrowVortex editor and finished mapping the song. I saved the file and went into Etterna to give it a go without paying any attention to the details of the song that the game gives you about a particular simfile. I start to play and all of the updates I made that day were reflected in the game. That is until I got halfway through the song... I could see the extra notes that I had added to complete the song however, the game decided that I had finished. That's when I noticed that the length of the song had not been updated in game (said 2:16 but was actually 3:38) and then I realised that the reason the song ended prematurely was because it thought that the song was the same length as when I played it the previous day. My first thought was to click refresh songs, when I clicked it, the game froze up for a few seconds like usual when you press it but the time had not changed. I played the song to see if it was just a graphical error but the song once again ended prematurely. At this point I was a little confused... I tried renaming the pack that I had created to put the song in thinking that the game would recoginise it as a new pack and reset all of the song information. However, this was not the case, it changed nothing except the name of the pack. At this point, I was stumped... I tried renaming the actual file name -  did nothing. I tried removing the song, reloading the game, then exiting, moving the song back in, relad the game - nothing happened. An hour after the problem had arised I had figured out how to solve the issue.. As it turns out, I had to alter the properties of the song (I changed the name to have capitals on the words that don't need them (Of and The)). When I did this, the song had popped up as a new song and everything was as it should be.

To reproduce this:
1) Make a simfile- not fully completed
2) Test it in game 
3) Finish simfile (or extend to be longer than original)
4) Test updated simfile in game
5) The simfile will end prematurely to the actual song

What I think should happen:
When the refresh songs button is clicked, all of the songs and all of their properties should be reloaded or maybe their could be a refresh pack button which does only that pack.

Unfortunately, I did not take any screenshots at the time, sorry.

Desktop:
OS: Windows 10
Version: 1803

**Comment by MinaciousGrace** [comment]
```could be a refresh pack button which does only that pack.```
ctrl shift p
ctrl shift r will force reload that song specifically

you were just using the wrong bind for the situation
