### ISSUE TITLE
[Linux] Game crash on startup

### ISSUE THREAD

**Issue by Miz0re** [etternagame/etterna#446]
The game crashes instantly after running.

OS: Debian 9.7 stretch
Kernel: 4.9.0-8

Currently running on this commit https://github.com/etternagame/etterna/commit/644d3b22bc8874b9a08556f65d0ee5cb292bb6ff in the develop branch.

[info.txt](https://github.com/etternagame/etterna/files/2903217/info.txt)
[crashinfo.txt](https://github.com/etternagame/etterna/files/2903196/crashinfo.txt)

**Comment by MinaciousGrace** [comment]
assuming this is a duplicate of https://github.com/etternagame/etterna/issues/449
