### ISSUE TITLE
Judge in select doesn't update if you change it in Player Options

### ISSUE THREAD

**Issue by YChvanov** [etternagame/etterna#447]
**Describe the bug**
When i change judge not by pressing ENTER twice, but opening "Player Options", old judge value is being showed

**To Reproduce**
1. Check you current judge in selects bottom
2. Open "Player Options" menu
3. Change your judge and exit options
4. See that in select your old, but newly changed, is still being displayed

**Expected behavior**
Display newly changed judge in select menu

**Screenshots**
I can't describe it by photos, so i made a [video](https://youtu.be/ol2fYsNdcQc) instead

**Desktop**
 - OS: Windows 10 LTSB 1607
 - Version: 0.64.0

**Additional context**
Temporary workaround: just enter and exit playfield

**Comment by MinaciousGrace** [comment]
5a45f292a956e4c895f4d84af1065d72b43e3a8b
