### ISSUE TITLE
(Linux, 0.65) Segmentation fault on startup since pull request #420 (because of libpng?)

### ISSUE THREAD

**Issue by kangalioo** [etternagame/etterna#449]
Etterna crashes on startup, with two warnings and an error from libpng. This happens with every build since commit 3311ff2 where pull request #420 was merged. Before that merge, there were no warnings or errors at all from libpng.

**To Reproduce**
Steps to reproduce the behavior on a Linux system:
1. Download 0.65 source code
2. Create "Build" directory and navigate into it
2. Build using `cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_FULL_RELEASE=1 && cmake .. && make -j6` (it's reproducible with `cmake .. && make` as well)
3. Execute the etterna executable

**Expected behavior**
I would expect that libpng doesn't throw an error, that there's no segmentation fault and that Etterna properly launches.

**Screenshots**
[Terminal output](https://pastebin.com/UX4qRbqu)
[Stack trace from gdb](https://pastebin.com/yhwU1JHZ)
[Terminal output from a working commit](https://pastebin.com/Vy4rCBFx)

**Desktop**
- x64 Arch Linux 4.20.11
- libpng 1.6.36-1
- glibc 2.28
- libavcodec: 0x372765 (3614565)

**Comment by MinaciousGrace** [comment]
libpng has been replaced with an image library from the this decade but i guess not unlinking it was an oversight, doing so may fix the seg fault?

**Comment by kangalioo** [comment]
How would I unlinking libpng? I've never done something like that

**Comment by nico-abram** [comment]
Remove this folder: https://github.com/etternagame/etterna/tree/a4515afd3ef6c421067a381aa63231268f0ccb37/extern/libpng
These 3 lines: https://github.com/etternagame/etterna/blob/b8e69ffa4e083be265bf2501021cc9dbc90ea65b/src/CMakeLists.txt#L646
This line: https://github.com/etternagame/etterna/blob/b8e69ffa4e083be265bf2501021cc9dbc90ea65b/src/CMakeLists.txt#L332
These 2 línea: https://github.com/etternagame/etterna/blob/a4515afd3ef6c421067a381aa63231268f0ccb37/src/CMakeProject-texture.cmake#L45 and https://github.com/etternagame/etterna/blob/a4515afd3ef6c421067a381aa63231268f0ccb37/src/CMakeProject-texture.cmake#L54
This file: https://github.com/etternagame/etterna/blob/a4515afd3ef6c421067a381aa63231268f0ccb37/extern/CMakeProject-png.cmake
And this line: https://github.com/etternagame/etterna/blob/b8e69ffa4e083be265bf2501021cc9dbc90ea65b/extern/CMakeLists.txt#L23
Unless Im missing something that should unlink it. But there Will probably be compiler errors. Remember to rerun cmake after( And clear the cmake caché)

**Comment by kangalioo** [comment]
The problem does come from libpng. Unlinking didn't directly work unfortunately but I followed the instructions Nick12 gave on the Discord, which disabled the PNG library and made Etterna 0.65 start:

> oh
> i think its being used for screenshot saving as png
> i can show you how to probably fix the error but without saving it
> simply removing the code
> change everything in https://github.com/etternagame/etterna/blob/07270e6a76cf63f88420ec0ef0e2d007205cc20f/src/RageSurface_Save_PNG.cpp to
> ```
> #include "global.h"
> #include "RageFile.h"
> #include "RageLog.h"
> #include "RageSurface.h"
> #include "RageSurfaceUtils.h"
> #include "RageSurface_Save_PNG.h"
> #include "RageUtil.h"
> bool RageSurfaceUtils::SavePNG(RageSurface* pImg, RageFile& f, RString& sError) {
>     return true;
> }
> ```

Though, as Nick12 said, that's only a temporary fix and will need to be redone when updating. It also disables the screenshot functionality.

**Comment by MinaciousGrace** [comment]
oh right i forgot to make screenshots use stb image

**Comment by nico-abram** [comment]
stb image needs a separate header for writing https://github.com/nothings/stb/blob/master/stb_image_write.h

**Comment by poco0317** [comment]
#458 via 3047db410bed28c2731848905025a72574ae7fb1 should handle this
