### ISSUE TITLE
Error when compiling on Linux

### ISSUE THREAD

**Issue by mainlygreen** [etternagame/etterna#45]
Been trying to compile stepmania but I keep getting this error.
I run cmake . then run make -j 16 then I get this error.

[  1%] Built target glew
[  1%] Built target ffmpeg
[  2%] Built target jsoncpp
[  6%] Built target lua-5.1
[  8%] Built target png
make[2]: *** No rule to make target 'extern/MinaCalc/MinaCalc.a', needed by 'GtkModule.so'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:418: src/CMakeFiles/GtkModule.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 25%] Built target tommath
[ 46%] Built target tomcrypt
make: *** [Makefile:152: all] Error 2

Any idea on what is going wrong?

Kernel 4.12.8
Cmake 3.9.1
Make 4.2.1

**Comment by RGates94** [comment]
Linux is currently not working, we are aware of this issue and will hopefully have a solution by the next official release.  (no promises but people are working on it)

**Comment by martensm** [comment]
In the future please report bugs against the development branch (`etternalmemestatus`). `master` hasn't been updated in some time now.

**Comment by mainlygreen** [comment]
Sounds good. Etterna with Wine works fine for now so i'll use it until it can be compiled on linux.
