### ISSUE TITLE
In KB7 the CB counter doesnt count properly

### ISSUE THREAD

**Issue by Void345** [etternagame/etterna#452]
**Describe the bug**
It counts everything except column 1 and 2 as right hand

**To Reproduce**
1. Go on KB7
2. Miss on column 3
3. Recieve right hand cb

**Expected behavior**
It should say that you cb'd on your left hand

**Screenshots**
Score screen from my test file: https://i.imgur.com/csQT6Wv.png
Test file in question: https://drive.google.com/file/d/1VSyZZCCO6Vgxzk0aRcy3Xgfqy8yQjAVu/view?usp=drivesdk

**Desktop (please complete the following information):**
 - OS: window 10
 - Version 0.65

**Additional context**
Shoutout to my 3 kb7 players

**Comment by Void345** [comment]
the same thing also happens on solo

**Comment by MinaciousGrace** [comment]
good catch

should be fixed by cf0c5e7123df17545624de3a039e2a147bd6ce01 but i did not test it extensively so if something is still wrong let me know
