### ISSUE TITLE
Still Says 0.64 - Downloaded/installed 0.65

### ISSUE THREAD

**Issue by potasium56** [etternagame/etterna#453]
Title sums it up, downloaded the new version 0.65 and installed it into my directory and didn't have to make a backup of my save or songs....It installed perfectly, but when i run the exe inside the directory it says its still the .64 version 

![image](https://user-images.githubusercontent.com/13303466/53928928-348da880-4049-11e9-9d3b-4378674d1e1a.png)

**Comment by poco0317** [comment]
You may have downloaded from Etternaonline. At the moment, the direct link located on the site points to the .64 downloads. You will want to find .65 from the releases page here. 
https://github.com/etternagame/etterna/releases

**Comment by potasium56** [comment]
This you are right, so what i did now is make a new folder inside my f drive and title it ettenra .65 and deleted the songs, save and noteskins folder inside and replaced it with the same folders from .64 folder....was woundering do i need to drag over cache folder inside my 64 version?

**Comment by poco0317** [comment]
There were cache changes from .64 to .65 which will require a regeneration. Even if you did drag it over, the cache would be forcibly regenerated.
There will be another regeneration in .65.1.

(so to answer your question, no)

**Comment by potasium56** [comment]
Okay, So everything should be good? even if i just brang over songs, and save folder? so i need to bring over any other folders?

**Comment by poco0317** [comment]
It should be fine as long as you didn't make any direct modifications to the theme that you want to keep. By direct modifying I mean literally opening the lua or ini files and messing with them. Also, you will want to move your noteskins if you have any other than the default ones.

**Comment by potasium56** [comment]
Yeah i moved songs, notskins and save folder into the new version...also can't login on etterna online website? i get this werid shit  

![image](https://user-images.githubusercontent.com/13303466/53929549-4bcd9580-404b-11e9-804e-537755604574.png)

**Comment by potasium56** [comment]
nvm its fixed thanks, you can close this issue now or mark it as fixed
