### ISSUE TITLE
Double Click Enter On A Song Crashes

### ISSUE THREAD

**Issue by potasium56** [etternagame/etterna#454]
Sorry, for the back to back issues. 

I can't play a song! lawls 

when i double click enter it crashes the client

**Comment by poco0317** [comment]
I need an associated crashlog.txt.

**Comment by potasium56** [comment]
> Etterna0.65-git-b8e69ffa4e crash report (build b8e69ffa4e, 20190301 @ 07:35:54)
> --------------------------------------
> 
> Crash reason: NoteSkins has no choices
> 
> Unknown thread
>         RageFileDriverDirectHelpers.cpp:230 F:/Etterna .65/Songs/Bemani/Kansas - Carry On My Wayward Son/*
>         RageFileDriverDirectHelpers.cpp:230 F:/Etterna .65/Songs/Yume's 1st Restart Pack/[Z] Collaboration Simfile/*
>         RageFileDriverDirectHelpers.cpp:230 F:/Etterna .65/Songs/Yume's 1st Restart Pack/[Z] MAD Billy Simfile/*
>         RageFileDriverDirectHelpers.cpp:230 F:/Etterna .65/Songs/Bemani/Megadeth - Hangar 18/*
>         RageFileDriverDirectHelpers.cpp:230 F:/Etterna .65/Songs/Yume's 1st Restart Pack/[Z] Secret Simfile/*
> Thread: Main thread
>         RageTextureManager.cpp:168 RageTextureManager::LoadTexture(/Themes/_fallback/Graphics/_blank.png).
>         RageFileDriverDirectHelpers.cpp:230 F:/Etterna .65/Save/GamePrefs/*
>         FontManager.cpp:67 FontManager::UnloadFont(/Themes/Til Death/Fonts/_bokutachinogothic2bold 24px.ini).
>         FontManager.cpp:67 FontManager::UnloadFont(/Themes/Til Death/Fonts/_bokutachinogothic2bold 24px.ini).
>         OptionRow.cpp:162 NoteSkins has no choices
> Thread: Decode thread
>         RageSoundDriver_Generic_Software.cpp:235 Processing the sound while buffers are available.
>         RageSoundDriver_Generic_Software.cpp:235 Processing the sound while buffers are available.
>         RageSoundDriver_Generic_Software.cpp:235 Processing the sound while buffers are available.
>         RageSoundDriver_Generic_Software.cpp:235 Processing the sound while buffers are available.
>         RageSoundDriver_Generic_Software.cpp:235 Processing the sound while buffers are available.
> Thread: Mixer thread
> Thread: Music thread
> Thread: DirectInput thread
>         InputHandler_DirectInput.cpp:907 
>         InputHandler_DirectInput.cpp:883 
>         InputHandler_DirectInput.cpp:901 
>         InputHandler_DirectInput.cpp:907 
>         InputHandler_DirectInput.cpp:883 
> Thread: Streaming sound buffering
> 89988275: Etterna!89500000
> 
> Static log:
> Etterna0.65-git-b8e69ffa4e
> Compiled 20190301 @ 07:35:54 (build b8e69ffa4e)
> Log starting 2019-03-06 20:14:16
> 	Verbosity: 1
> Windows 6.2 (Win8) build 9200 []
> Attempting to connect to: multi.etternaonline.com, Port: 8765
> Server Version: 0 
> Video renderers: 'd3d, opengl'
> WARNING: RageDisplay_D3D::TryVideoMode( 1, 1600, 900, 16, 60, 0 )
> D3D Windowed 1600x900 16 color 16 texture 60Hz NoVsync NoSmoothLines
> WARNING: NoteSkin "easyv2" references skin "default" that is not present
> WARNING: NoteSkin "wafles1" references skin "default" that is not present
> WARNING: NoteSkin "wafles2" references skin "default" that is not present
> WARNING: NoteSkin "wafles4" references skin "default" that is not present
> WARNING: NoteSkin "wonderful3" references skin "default" that is not present
> WARNING: Font import recursion detected
> WARNING: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
> WARNING: /Themes/_fallback/Fonts/Common default.ini
> WARNING: /Themes/Til Death/Fonts/_16px fonts.ini
> WARNING: Current font: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
> WARNING: Font /Themes/Til Death/Fonts/_16px fonts.ini has no characters
> WARNING: NoteSkin "easyv2" references skin "default" that is not present
> WARNING: NoteSkin "wafles1" references skin "default" that is not present
> WARNING: NoteSkin "wafles2" references skin "default" that is not present
> WARNING: NoteSkin "wafles4" references skin "default" that is not present
> WARNING: NoteSkin "wonderful3" references skin "default" that is not present
> Players joined: P1
> Current renderer: Direct3D
> 
> Partial log:
> 00:17.576: PlayMode not set, setting as regular.
> 00:17.576: MusicWheel sorting took: 17.576000
> 00:17.625: MusicWheel sorting took: 17.625999
> 00:18.149: 31 FPS, 31 av FPS, 4389 VPF, D3D
> 00:18.222: Loaded replay data at Save/ReplaysV2/S15033c535d9144bf66a3b93507873a2a45ef2199
> 00:18.816: Loaded replay data at Save/ReplaysV2/Sca4e52ddf94425e05de9da387057c3f3914dea13
> 00:19.153: 59 FPS, 45 av FPS, 4371 VPF, D3D
> 00:19.392: MusicWheel::Select()
> 00:19.392: WheelBase::Select()
> 00:20.128: ScreenOptions::InitMenu()
> 
> -- End of report
>

**Comment by potasium56** [comment]
I also just tried going into appearance and the game just closed

**Comment by potasium56** [comment]
[log.txt](https://github.com/etternagame/etterna/files/2939359/log.txt)

**Comment by poco0317** [comment]
It seems you are either missing some or all of the Noteskins folder. And crashing in the Appearance screen should be the same reason.

**Comment by potasium56** [comment]
I have my note skins folder with my note skins inside it

**Comment by potasium56** [comment]
![image](https://user-images.githubusercontent.com/13303466/53930089-3eb1a600-404d-11e9-9b86-b97b3bcecdf0.png)

![image](https://user-images.githubusercontent.com/13303466/53930095-440ef080-404d-11e9-8daf-96434a37954c.png)

**Comment by poco0317** [comment]
The default noteskin is missing and none of the noteskins load in the game. Since none of them load, you have no noteskins and you crash. You still require the default noteskin in the dance folder.

**Comment by potasium56** [comment]
so reinstall another version and copy and paste the default note skin inside this one?

**Comment by poco0317** [comment]
Sure, but the default noteskin should not have disappeared in the first place. Did you just replace the dance folder with your own folder of noteskins?

**Comment by potasium56** [comment]
Yes, this is probably what cause the issue

**Comment by potasium56** [comment]
Yeah that seem to fix the issue, personal fyi always keep the default note skin folder
