### ISSUE TITLE
Make sure we reset all filters when multi song is not found

### ISSUE THREAD

**Issue by nico-abram** [etternagame/etterna#460]
We probably just need to reset everything in FILTERMAN in https://github.com/etternagame/etterna/blob/develop/src/ScreenNetSelectMusic.cpp#L111 and https://github.com/etternagame/etterna/blob/develop/src/ScreenNetSelectMusic.cpp#L150 (Before the reload)

It seems to cause crashes if someone starts a song not in the current wheel because of filters (But that you actually have)

**Comment by poco0317** [comment]
done (fixed related crashing) f19b1686a09aead81a32856368c16127b2cf18f3 17dcfbc4d0f54cb81bd7c26110a6939f31760c62
