### ISSUE TITLE
"RageSurface_Save_JPEG.cpp: ‘TRUE’ was not declared in this scope" on v0.65.1

### ISSUE THREAD

**Issue by komaeda** [etternagame/etterna#467]
**Describe the bug**
When compiling v0.65.1 from source:

```
[ 72%] Building CXX object src/CMakeFiles/Etterna.dir/RageSurfaceUtils_Zoom.cpp.o
/home/lu/code/etterna/src/RageSurface_Save_JPEG.cpp: In function ‘jpeg::boolean empty_output_buffer(jpeg::j_compress_ptr)’:
/home/lu/code/etterna/src/RageSurface_Save_JPEG.cpp:46:9: error: ‘TRUE’ was not declared in this scope
  return TRUE;
         ^~~~
/home/lu/code/etterna/src/RageSurface_Save_JPEG.cpp:46:9: note: suggested alternative:
In file included from /usr/include/jpeglib.h:27:0,
                 from /home/lu/code/etterna/src/RageSurface_Save_JPEG.cpp:13:
/usr/include/jmorecfg.h:317:27: note:   ‘TRUE’
 typedef enum { FALSE = 0, TRUE = 1 } boolean;
                           ^~~~
```

**To Reproduce**

I'm using Gentoo with clang 7.0.0 and gcc 7.4.1. This occurs when running:

```
git clone https://github.com/etternagame/etterna --depth=1
cd etterna
git checkout v0.65.1
mkdir Build; cd Build
cmake .. -G 'Unix Makefiles'
make -j4
```

**Expected behavior**
I would have expected the build to succeed.

**Desktop (please complete the following information):**
 - OS: Gentoo (Funtoo) 1.3
 - Version: 0.65.1
 - clang 7.0.0, gcc 7.4.1, git 2.19.1
 - libjpeg 9c

**Comment by poco0317** [comment]
Feel free to edit the source yourself to try to see if this solves the issue:
Change each instance of `TRUE` in RageSurface_Save_JPEG.cpp to `jpeg::TRUE`

**Comment by komaeda** [comment]
@poco0317 Thanks, editing that fixed the build! Do you reckon it's because I'm using a newer version of GCC/Clang or libjpeg than for example Travis uses?

I can push a pull request to fix this if you want.

**Comment by jameskr97** [comment]
I don't think that's a good idea. I'm pretty sure it's only certain linux distros that present this issue.

**Comment by poco0317** [comment]
I'm honestly not sure but this is the same fix involved in #362 which we coincidentally closed 12 hours ago because we thought the issue kind of disappeared since nobody else had it.
Without considering any ramifications (because I really have no idea) I think we should move to STB's jpeg stuff for this.

**Comment by nico-abram** [comment]
Using STB sounds good imo. I'm curious though, does it break on the systems that it currently works if we use jpeg::TRUE? If it doesnt there's really no reason not to replace it (Until we replace the library)

**Comment by jameskr97** [comment]
@nico-abram It breaks on Ubuntu. Maybe it could be the compiler too? It's such a strange namespace bug to see on only some non-mainstream linux distros.

It would've been nice to know what distro #362 was using.

**Comment by jameskr97** [comment]
No longer an issue since #489.
