### ISSUE TITLE
Duplicate difficulties seem to crash the game

### ISSUE THREAD

**Issue by poco0317** [etternagame/etterna#471]
Needs more investigation and cases.
This has been confirmed for Nuclear Fusion from Xoon 2. The Edit diff ingame is actually a duplicate Challenge diff with very slight changes. The metadata loads fine, but the notedata fails. Gameplay crashes.

**Comment by MinaciousGrace** [comment]
ii am awesomoe

**Comment by poco0317** [comment]
fixed by 833e886d6b499d5b2db9017ac8305fdf13ab88cc
