### ISSUE TITLE
Allow rates down to 0.5x (at least locally)

### ISSUE THREAD

**Issue by Kangaroux** [etternagame/etterna#473]
This would be extremely helpful for beginner and intermediate players who are starting to dive into some harder charting styles but can't find charts in the right difficulty range.

Using myself as an example, I want to start practicing handstream since it's my lowest rating. However, pretty much any "true" handstream song will be rated at 14-15, even at 0.7x. When your handstream skill level is around a 12, this simply doesn't work.

**Comment by poco0317** [comment]
The calc is clamped to [0.7, 3.0]. If we allow this (which we actually do in Practice Mode) then it would have to be a widely reaching change.

**Comment by Kangaroux** [comment]
@poco0317 I figured that would be the case (hence the "at least locally" bit). I would be totally fine with not having those plays be ranked or tracked on the site if it meant being able to use it sooner. My current solution is either manually slowing the file which is a pain, or I import it into quaver which supports down to 0.5x, which is also a pain because it means I'm switching games.

The one issue with practice mode is that I don't think it deducts your score for misses (at least that's what it seemed like was happening)

**Comment by MinaciousGrace** [comment]
9a03a39deb22a8cd76061eb715c155faa9467127
opening player options while the rate is set to 0.5 will clamp it back to 0.7 but apart from that this should work as expected on the local level
