### ISSUE TITLE
Practice mode forces you back to the menu when the song is done

### ISSUE THREAD

**Issue by Kangaroux** [etternagame/etterna#474]
In practice mode, if you reach the end of the song (i.e. passed the last note) the interface locks you out from pressing backspace or clicking the note graph. If you want to practice the end of a song you need to hit backspace before the last note to avoid this.

**Comment by poco0317** [comment]
Slight oversight due to most screens including gameplay locking nearly all input when transitioning.

**Comment by MinaciousGrace** [comment]
8045bcee99fde317a1c504a0885eaf830c335a17
