### ISSUE TITLE
Fail Mode is reset to Immediate after enabling and then disabling practice mode

### ISSUE THREAD

**Issue by kangalioo** [etternagame/etterna#476]
When practice mode is turned off, the fail mode switches to "Immediate", no matter which fail mode was selected before practice mode. That's a bit annoying because I always play with "Fail at end", but practice mode keeps resetting it.

1. Set fail mode to anything except "Immediate" (e.g. "Fail at end") and save settings
2. Enable practice mode and save settings
3. Disable practice mode and save settings
4. Fail mode is now set to "Immediate", even though it was something else before

I would expect the game to remember the fail mode setting on enabling practice mode, and restore it on disabling.

**Comment by poco0317** [comment]
This is partially intended but also the result of a hack. It could be done better like you mention.

**Comment by foxfire667** [comment]
It's not just practice mode, fail sets to immediate every time you reload the game, or enter the song select screen from the title menu. FailAtEnd and FailOff should just be permanent settings at all times, where FailOff would give no rating if the user actually fails of course.

**Comment by MinaciousGrace** [comment]
6271e50c139369373a7bb8e56a3eccfa3fbb89aa
