### ISSUE TITLE
Show J4 judgement counts on the global scores 

### ISSUE THREAD

**Issue by Kangaroux** [etternagame/etterna#483]
Viewing global scores for a song will show the percents as they are in J4 but the judgement counts are based on whatever judge was used to play the song.

This makes it hard to compare your score with others if not everyone is using J4. It also looks incredibly strange for accuracy players who use Justice:

![image](https://user-images.githubusercontent.com/2302541/54664152-ccfc4200-4ab9-11e9-814d-4e47f777538f.png)

**Comment by Kangaroux** [comment]
In addition to normalizing the judgements to J4 it would be nice to have a toggle to switch between J4 and the original judge, with some indication of what judge was being used. This seems like a pretty low priority feature, though.

**Comment by poco0317** [comment]
Part of the solution to this involve editing the theme. Part of the solution to this may involve changing the way the site stores data.

**Comment by nico-abram** [comment]
I think we can calcularse the judge counts client side for scores with replay data. I dont know if theres a way to fix legacy scores

**Comment by poco0317** [comment]
this is resolved with the upcoming eo2 changes, as all uploaded scores will be sending the normalized judgments (which are j4 as long as the replays were available at time of upload) fb617b0a786c140a8d7291d101fa66c381aa7fb2
