### ISSUE TITLE
Visual delay affected by rates

### ISSUE THREAD

**Issue by Durvin** [etternagame/etterna#485]
**Describe the bug**
Whenever i enter a song with a rate different than 1.0x, my visual delay gets affected. Via testing i've found it to act as if the visual delay is divided by the rate.

**To Reproduce**
1. Increase visual delay with F3 to a "large" number (my standard was 0.060)
2. Enter a song and watch the mean ms offset.
3. Increase the rate by atleast 1.3x
4. Notice how the mean ms offset is far more negative

**Expected behavior**
Visual delay does not get affected by rates

**Screenshots**
![2019-02-09_135227](https://user-images.githubusercontent.com/48808622/54783702-56c71f00-4c22-11e9-9b4f-7317d1060a3d.png)

**Desktop (please complete the following information):**
 - Etterna version 0.64.0
 - no notes for a fix from neither 0.65 nor 0.65.1

**Comment by nico-abram** [comment]
I think we might be able to easily and hackily fix the visual delay changing with rate thing multipliying by rate in https://github.com/etternagame/etterna/blob/07270e6a76cf63f88420ec0ef0e2d007205cc20f/src/SongPosition.cpp#L38

**Comment by MinaciousGrace** [comment]
349efa18f80d20e4407f9f576abbe6f25d66e14f
