### ISSUE TITLE
Mini progress bar position gets saved with a slight offset

### ISSUE THREAD

**Issue by Kangaroux** [etternagame/etterna#488]
If I move the mini progress bar, the position it gets saved to is actually a bit up and to the right of where I placed it. No matter where I place it on the screen, the offset appears to be the same.

I'm on a fresh install of 0.65.1, win10 x64

The top image is where I intended to place it, and the bottom is where it got saved.

![image](https://user-images.githubusercontent.com/2302541/54861739-a7af4400-4d04-11e9-88fc-76533bc99136.png)

**Comment by MinaciousGrace** [comment]
3b27bf6fca39997732767a28b287040d31faa9f3 should fix this
