### ISSUE TITLE
Autosync Crashed Game When Saving (Yes)

### ISSUE THREAD

**Issue by SpoOkyMagician** [etternagame/etterna#493]
**Game crashes after saving a autosynced song/chart.**
So, I was autosyncing a chart in etterna 0.65.1 (Master Branch) and after it asked me to save, etterna crashed. I was curious if it was just this song/chart or other songs/charts and it turned out, it happened with 3 different songs/charts. So likely, this is something new introduced. Note that I am using a external hard drive. (Which has write permission. I checked.)

**To Reproduce**
1. Start Etterna.
2: Select Song/Chart. (Options as needed.)
3: Press F6 to start autosync. (or turn on in options.)
4: Play the chart to sync.
5: Say 'Yes' to save.
6: Crash.

**Expected behavior**
I expect it to save/update the chart like it always did.

**Screenshots**
(If you really need one, let me know. Otherwise, skipping this.)

**Desktop (please complete the following information):**
 - OS: Windows 10 64 Bit.
 - Version 0.65.1 (Master Branch)

**Additional context**
Possibly related: #290 and/or #307

Edit: Here are two crash logs. Might help.

Etterna0.65-git-5cedfe2 crash report (build 5cedfe2, 20190317 @ 01:17:44)
--------------------------------------

Crash reason: StepsType 1065353216 < NUM_StepsType (27)

Thread: Main thread
        GameSoundManager.cpp:579 92.767548, delta 0.012120
        GameSoundManager.cpp:579 92.779617, delta 0.012438
        RageFileDriverDirectHelpers.cpp:165 J:/stuff/songs/DDR AC 4thMix Japan/IN THE HEAT OF THE NIGHT/chart_1.sm.old
        RageFileDriverDirectHelpers.cpp:165 J:/stuff/songs/DDR AC 4thMix Japan/IN THE HEAT OF THE NIGHT/chart_2.ssc.old
        GameManager.cpp:1957 StepsType 1065353216 < NUM_StepsType (27)
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:235 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:235 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:235 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:235 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:235 Processing the sound while buffers are available.
Thread: Mixer thread
Thread: Music thread
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:907 
        InputHandler_DirectInput.cpp:883 
        InputHandler_DirectInput.cpp:901 
        InputHandler_DirectInput.cpp:907 
        InputHandler_DirectInput.cpp:883 
Thread: Streaming sound buffering
010ff300: ???!01000000
001f6384: Etterna!uS::Socket::write [00170000+6fa70+16914]
003f4c63: Etterna!uWS::WebSocket<0>::send [00170000+d3b40+1b1123]
003f0b7f: Etterna!uWS::WebSocket<0>::send [00170000+d3b40+1ad03f]
003f0e78: Etterna!uWS::WebSocket<0>::send [00170000+d3b40+1ad338]
003d9b2f: Etterna!uWS::WebSocket<0>::send [00170000+d3b40+195fef]
77b41f3e: ntdll!RtlAllocateHeap [77b00000+41f00+3e]
77b41f3e: ntdll!RtlAllocateHeap [77b00000+41f00+3e]
77b450a0: ntdll!RtlFreeHeap [77b00000+44ec0+1e0]
007d83a3: Etterna!uWS::HttpSocket<0>::upgrade [00170000+41df80+24a423]
007bf3bb: Etterna!uWS::HttpSocket<0>::upgrade [00170000+41df80+23143b]
003d963a: Etterna!uWS::WebSocket<0>::send [00170000+d3b40+195afa]
003f8bf3: Etterna!uWS::WebSocket<0>::send [00170000+d3b40+1b50b3]
00525414: Etterna!uWS::WebSocket<0>::send [00170000+d3b40+2e18d4]
0053bcf8: Etterna!uWS::WebSocket<0>::send [00170000+d3b40+2f81b8]
001e5c60: Etterna!uS::Socket::write [00170000+6fa70+61f0]
6b975f61: DINPUT8!GetdfDIJoystick [6b960000+100b0+5eb1]
6b975f61: DINPUT8!GetdfDIJoystick [6b960000+100b0+5eb1]
001deb5a: Etterna!uS::Node::`default constructor closure' [00170000+6d750+140a]
001df25c: Etterna!uS::Socket::allocMessage [00170000+6f120+13c]
001e9bad: Etterna!uS::Socket::write [00170000+6fa70+a13d]
77b3b684: ntdll!LdrGetProcedureAddressForCaller [77b00000+3b310+374]
77b3b8b4: ntdll!LdrGetProcedureAddressForCaller [77b00000+3b310+5a4]
77b4b1d2: ntdll!LdrLoadDll [77b00000+4b120+b2]
0055f536: Etterna!uWS::WebSocket<0>::send [00170000+d3b40+31b9f6]
0079abde: Etterna!uWS::HttpSocket<0>::upgrade [00170000+41df80+20cc5e]
77b665fd: ntdll!RtlGetAppContainerNamedObjectPath [77b00000+66540+bd]

Etterna0.65-git-5cedfe2 crash report (build 5cedfe2, 20190317 @ 01:17:44)
--------------------------------------

Crash reason: Access Violation

Thread: Main thread
        GameSoundManager.cpp:579 99.205666, delta 0.012820
        GameSoundManager.cpp:579 99.218460, delta 0.012279
        GameSoundManager.cpp:579 99.230659, delta 0.012618
        RageFileDriverDirectHelpers.cpp:165 J:/stuff/songs/DDR AC 4thMix Japan/KICK THE CAN/chart_1.sm.old
        RageFileDriverDirectHelpers.cpp:165 J:/stuff/songs/DDR AC 4thMix Japan/KICK THE CAN/chart_2.ssc.old
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:235 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:235 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:235 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:235 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:235 Processing the sound while buffers are available.
Thread: Mixer thread
Thread: Music thread
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:907 
        InputHandler_DirectInput.cpp:883 
        InputHandler_DirectInput.cpp:901 
        InputHandler_DirectInput.cpp:907 
        InputHandler_DirectInput.cpp:883 
Thread: Streaming sound buffering
0038e79f: Etterna!uWS::WebSocket<0>::send [00170000+d3b40+14ac5f]
003f0961: Etterna!uWS::WebSocket<0>::send [00170000+d3b40+1ace21]
003d9b36: Etterna!uWS::WebSocket<0>::send [00170000+d3b40+195ff6]
77b41f3e: ntdll!RtlAllocateHeap [77b00000+41f00+3e]
77b41f3e: ntdll!RtlAllocateHeap [77b00000+41f00+3e]
77b450a0: ntdll!RtlFreeHeap [77b00000+44ec0+1e0]
007d83a3: Etterna!uWS::HttpSocket<0>::upgrade [00170000+41df80+24a423]
007bf3bb: Etterna!uWS::HttpSocket<0>::upgrade [00170000+41df80+23143b]
003d963a: Etterna!uWS::WebSocket<0>::send [00170000+d3b40+195afa]
003f8bf3: Etterna!uWS::WebSocket<0>::send [00170000+d3b40+1b50b3]
00525414: Etterna!uWS::WebSocket<0>::send [00170000+d3b40+2e18d4]
0053bcf8: Etterna!uWS::WebSocket<0>::send [00170000+d3b40+2f81b8]
001e5c60: Etterna!uS::Socket::write [00170000+6fa70+61f0]
6b975f61: DINPUT8!GetdfDIJoystick [6b960000+100b0+5eb1]
6b975f61: DINPUT8!GetdfDIJoystick [6b960000+100b0+5eb1]
001deb5a: Etterna!uS::Node::`default constructor closure' [00170000+6d750+140a]
001df25c: Etterna!uS::Socket::allocMessage [00170000+6f120+13c]
001e9bad: Etterna!uS::Socket::write [00170000+6fa70+a13d]
77b3b684: ntdll!LdrGetProcedureAddressForCaller [77b00000+3b310+374]
77b3b8b4: ntdll!LdrGetProcedureAddressForCaller [77b00000+3b310+5a4]
77b4b1d2: ntdll!LdrLoadDll [77b00000+4b120+b2]
0055f536: Etterna!uWS::WebSocket<0>::send [00170000+d3b40+31b9f6]
0079abde: Etterna!uWS::HttpSocket<0>::upgrade [00170000+41df80+20cc5e]
77b665fd: ntdll!RtlGetAppContainerNamedObjectPath [77b00000+66540+bd]

**Comment by SpoOkyMagician** [comment]
Well crap... I checked the song directory again and it was set to read only in that directory. (Not sure how/when that happened though.) I will change it to writeable now and see if it fixes the problem. However, it should be fixed to prevent crash.

**Comment by poco0317** [comment]
Are the charts that crash with this issue consistent?
Does it happen when you run the game as admin?
If you get a call stack when debugging, we usually know how to decipher it unless you didn't load the symbols (by compiling on RelWithDebug). Go ahead and send that if you have it.

**Comment by SpoOkyMagician** [comment]
1: Yes.
2: My user account is admin. (I can try it though.)
3: RelWithDebug? Interesting. I tried the debug option but it will not compile. I can give that one a try. Give me a few minutes or so... I will edit this post when I find out more info...

**Comment by poco0317** [comment]
It seems that the cause of this crash is the fact that the files in question have a Couple difficulty. Since we removed support for that, it skips loading them. Somewhere along the process though, when it skips, the timing data gets a little out of line. And one way or another it ends up being null when trying to reload the song while setting the sync.

**Comment by poco0317** [comment]
for by 2d53f58bd38968d9932d3af2448de18cf0c0af67
for sm, ssc, and sma files
