### ISSUE TITLE
Reset judgements & percentage in practice mode when changing position in the song

### ISSUE THREAD

**Issue by Kangaroux** [etternagame/etterna#495]
It's hard to track how accurate you are in practice mode since the judgement counts never reset, and due to the miss bug your percentage is often some negative number.

It would be great if instead, any time you changed position in the song (either by clicking the graph or hitting backspace to return to a save point) your judgements reset and your percent went back to 0%.

**Comment by poco0317** [comment]
Current behavior is the result of laziness. Should be handled better down the line.

**Comment by MinaciousGrace** [comment]
4a5968d8c50436c04af278eec29d30078d7343d7
72dbeb0e8730ea7dbe84c7d47f91203db132793c
