### ISSUE TITLE
In practice mode, ease into the song when resetting back to the bookmark similar to Clone Hero

### ISSUE THREAD

**Issue by Kangaroux** [etternagame/etterna#497]
This is how practice mode works in Clone Hero if you are familiar with it.

When you reset to the start of a section, it starts playing the song a couple seconds before the section starts, but any part of the chart that came before the beginning the section are omitted.

The ease-in time could be configurable, anywhere from 0-5s. That way players can opt out and go back to the original functionality if they don't care about the judgement counts and just want to quickly reset back to the bookmark. Players more comfortable with the game might choose a 0.5s reset time whereas newer players may prefer 2-3s.

As an example, say I wanted to start practicing the section marked by the red line:

![image](https://user-images.githubusercontent.com/2302541/55026229-f7c62900-4fd8-11e9-8b2a-8bd5508b16d9.png)

What the player would see when resetting back to the bookmark is that the song starts at the blue line and any notes prior to the beginning of the section are no longer there:

![image](https://user-images.githubusercontent.com/2302541/55026454-6d31f980-4fd9-11e9-981c-b0cc8db41e7f.png)

How far back the blue line is from the bookmark would be the configurable option I mentioned above.

**Comment by poco0317** [comment]
Practice mode now has a 1-2 second pre-delay when resetting to the beginning of a loop region or jumping to a set bookmark/loop start. This is a part of gameplay rewrite.

closed when pr merged
