### ISSUE TITLE
Issues with refresh rate capping and Discord

### ISSUE THREAD

**Issue by Kangaroux** [etternagame/etterna#498]
Windows 10 x64. Not sure if this is an issue with Windows or if it can be fixed somehow.

With Discord running on my 60Hz monitor and Etterna on my 144Hz, anytime Discord is playing an animation (such as a video or the loading icon when someone posts an image) my game suddenly feels like I'm playing on a 60Hz monitor.

Manually adjusting the refresh rate in the settings to 150Hz doesn't appear to have any effect in fullscreen or windowed mode. 

Screensharing also causes this issue even if I move Discord to my main monitor. I don't have this issue with Streamlabs/OBS.

**Comment by poco0317** [comment]
This is a Windows 10 issue.
I'll let someone else verify, explain more, and/or close this.

Basically, just look this up and you can find the exact issue you are describing. The best thing you can do is move any animated things off of the lower refresh rate monitor. Playing in fullscreen may help (even if you say it doesn't).
