### ISSUE TITLE
Hitting ESC when on the pack download page should bring you to the previous menu instead of unselecting the search box

### ISSUE THREAD

**Issue by Kangaroux** [etternagame/etterna#500]
This makes it so you have to hit escape twice to get back. Since there isn't any visual feedback that the search box is selected it just feels like the game is eating the keystroke.

**Comment by MinaciousGrace** [comment]
this has tangentially been fixed by 17ae528b5a43da20c13cdddebf021091ff2793c1 which auto focuses the pack search, however if you don't know this and actually click on the search bar to focus it, it still requires two inputs to cancel screen, so i guess ill fix that

**Comment by MinaciousGrace** [comment]
24492955bc87adee045be1e19477b86db926056c
