### ISSUE TITLE
Lobby Selection options and Wheel stay on screen with the Select Music Screen when loading into a lobby

### ISSUE THREAD

**Issue by Raze009SM** [etternagame/etterna#501]
Loading into a new lobby on Etterna, the Lobby Select menu was still on screen in the background with the Music Select screen when in the lobby. When I hit ESC to back out, the game proceeded to crash. Looking in the logs and crash info provided no good evidence as to what happened during the crash.

![ScreenMusicSelect bug Showcase](https://user-images.githubusercontent.com/49098146/55277462-93ec7a80-52ce-11e9-907d-f019b3b7d4e3.png)

**Comment by poco0317** [comment]
Known issue since 0.64.

**Comment by MinaciousGrace** [comment]
i remember looking into this and im pretty sure i knew what the issue was at the time, but i can't remember :s

**Comment by MinaciousGrace** [comment]
nick fixed this but i couldnt find the commit that did it within 2 minutes
