### ISSUE TITLE
Etterna 0.64 Crash at startup 

### ISSUE THREAD

**Issue by joalex79** [etternagame/etterna#502]
Crash reason: Access Violation

Unknown thread
        ragefiledriverdirecthelpers.cpp:230 D:/Etterna/Songs/In The Groove/Bend Your Mind/*
        ragefiledriverdirecthelpers.cpp:230 D:/Etterna/Songs/In The Groove/Utopia/*
        ragefiledriverdirecthelpers.cpp:230 D:/Etterna/Songs/In The Groove/Oasis/*
        ragefiledriverdirecthelpers.cpp:230 D:/Etterna/Songs/In The Groove/Tell/*
        ragefiledriverdirecthelpers.cpp:230 D:/Etterna/Songs/In The Groove/Charlene/*
Thread: Main thread
        inifile.cpp:22 Reading '/Save/LocalProfiles/00000001/Type.ini'
        inifile.cpp:22 Reading '/Save/LocalProfiles/00000000/Type.ini'
        xmlprofile.cpp:944 Loading the general node.
        xmlprofile.cpp:1079 Loading the player scores node.
        inifile.cpp:22 Reading '/Save/LocalProfiles/00000000/Editable.ini'
Thread: Decode thread
Thread: Mixer thread
Thread: Music thread
073f7a16: Etterna!07160000

Static log:
Etterna0.64-git-4c0339daf4
Compiled 20181205 @ 03:26:12 (build 4c0339daf4)
Log starting 2019-03-30 19:46:37
	Verbosity: 1
Windows 6.2 (Win8) build 9200 []

Partial log:
00:02.170: Song file "/Songs/My Song/Springtime/" has an invalid Fake at beat 0.000000, beats to skip 0.000000.
00:02.171: Song file "/Songs/My Song/Springtime/" has an invalid #DELAYS value "44.500000=0.08300045.000000=0.08300045.500000=0.08300046.000000=0.08300046.250000=0.04100046.500000=0.04100046.750000=0.04100047.000000=0.04100048.000000=0.248000300.500000=0.083000301.000000=0.083000301.500000=0.083000302.000000=0.083000302.250000=0.041000302.500000=0.041000302.750000=0.041000303.000000=0.041000303.250000=0.041000303.500000=0.041000303.750000=0.041000304.000000=0.041000" (must have exactly one '='), ignored.
00:02.171: Song file "/Songs/My Song/Springtime/" has an invalid #TICKCOUNTS value "0.000000=4384.000000=8" (must have exactly one '='), ignored.
00:02.171: Song file "/Songs/My Song/Springtime/" has an invalid Fake at beat 0.000000, beats to skip 0.000000.
00:02.171: Song file "/Songs/My Song/Springtime/" has an invalid #TICKCOUNTS value "0.000000=4384.000000=8" (must have exactly one '='), ignored.
00:02.171: Song file "/Songs/My Song/Springtime/" has an invalid Fake at beat 0.000000, beats to skip 0.000000.
00:03.647: Song "/Songs/FFR Community Pack 4/...In A Movie (Charlo)/" has no SSC, SM, SMA, DWI, BMS, KSF, or OSU files.
00:03.647: Song "/Songs/FFR Community Pack 4/...In A Movie (Charlo)/" has no music file either. Ignoring this song directory.
00:04.067: Profile::LoadAllFromDir( /Save/LocalProfiles/00000000/ )
00:04.346: Calculating stats from scores

**Comment by Kangaroux** [comment]
@joalex79 have you tried 0.65.1?

**Comment by joalex79** [comment]
> @joalex79 have you tried 0.65.1?

i will try it

**Comment by Kangaroux** [comment]
@joalex79 Are you still having this issue on the newest release?

**Comment by Kangaroux** [comment]
@poco0317 I think this issue can be closed

**Comment by poco0317** [comment]
Closed due to old client, lack of response, and the high likelihood (I am guessing) that this is related to threaded startup. Access violation in pre .65.1 startup is very often related to a non-threadsafe checkpoint in the logger.
