### ISSUE TITLE
Add "Now Playing" thing for streamers

### ISSUE THREAD

**Issue by ProjectDIVAPlayer** [etternagame/etterna#507]
A "Now Playing" thing would be really nice for streamers to use while streaming or recording gameplay. Personally I think the "Now Playing" thing should appear like this (doesn't have to be like this):
"Song Name
Artist
Difficulty / Difficulty Number"
as an example:
"KILL THIS LOVE
BLACKPINK
generic pack name
HARD / 13"

**Comment by MinaciousGrace** [comment]
2015e2bd39505ca1aa4a66285f03931c6020f83e
22b8522c982f383c22bf14b274ef10e3b995cdb1
