### ISSUE TITLE
Fade notes in/out when using hidden/sudden

### ISSUE THREAD

**Issue by Kangaroux** [etternagame/etterna#508]
Holds fade in/out correctly but the taps themselves just instantly appear/disappear. It's a little jarring how the notes just flash on and off of the screen which kind of defeats the purpose of using hidden/sudden to reduce visual strain. Maybe this could be an option but I don't think it's intended.

Currently looks like **A**, should (in my opinion) look like **B**

![image](https://user-images.githubusercontent.com/2302541/55677682-305be180-58ba-11e9-9b43-e3e8259c8808.png)

**Comment by poco0317** [comment]
fixed e12144ea68f5c147a38ba1accf6c63851cbb068c
