### ISSUE TITLE
Add an option to enable/disable lifts when loading osu songs

### ISSUE THREAD

**Issue by Kangaroux** [etternagame/etterna#510]
The osu song loader adds a lift to the end of each hold. I think by default this should be OFF and the user has the option to turn it ON. The purpose of converting should be to play the song as you would in Etterna.

**Comment by poco0317** [comment]
done 315cca5b071d58370354a982da6cf5b5a25360d9 4bfada032c155f514e8fd5e14c82dcd20b3221e6
added as an option to debug menu F8 as well 339b91b3b30403e1ca35d9a192e23e636d90f6fc
