### ISSUE TITLE
crashing when downloading large packs from the pack downloader

### ISSUE THREAD

**Issue by Sooph** [etternagame/etterna#511]
**Describe the bug**
Etterna is crashing when I download any pack larger than 2gb from the pack downloader menu

**To Reproduce**
1. Go to the pack downloader
2. Download a pack larger than 2gb
3. Game crashes

**Expected behavior**
The pack should have downloaded and imported normally

**Screenshots**
https://imgur.com/a/9Klob3G not much, the game crashed. i will attach a crash log though
[crashinfo.txt](https://github.com/etternagame/etterna/files/3123348/crashinfo.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Build 17134

**Additional context**
any other pack download works fine but bigger packs crash the game for some reason

**Comment by poco0317** [comment]
This has been reported multiple times but I can't find any of the reports.

I feel like this is related to integer overflow which if true is pretty funny, but if not I'm confused. We will look into this soon.

**Comment by poco0317** [comment]
Upon further investigation we have concluded that the cause of this crash is in fact 32 bit signed integer overflow. But only when unzipping. So we can bandaid this issue by not forcing a crash, but that would require the player to manually unzip the file downloaded to the cache.

A more preferable solution may be to replace much of RageFile/RageFileObj with something that doesnt use signed ints and 32 bit unsigned ints everywhere (streaming compression/decompression with zlib comes to mind).

**Comment by MinaciousGrace** [comment]
2deae2db37c581cb4bc7f52aae66658a5a73dc0a
564e041d20dd99eb10900395df8ca3a8fb77a6f9
e8281404528635cbe675515c3d8ce7ea0afe7da9

clicking the download link for files that would have previously crashed upon finishing dl will now download via your browser instead
