### ISSUE TITLE
Crash on pressing "Player Options" when the selected chart is a pack

### ISSUE THREAD

**Issue by YChvanov** [etternagame/etterna#512]
**Describe the bug**
Game crashes when you press "Player Options" when the selected chart is a pack, but not a song

**To Reproduce**
1. Select a pack, but not a song
2. Press "Player Options"
3. See the crash

**Expected behavior**
I expected opening player options menu just like when you do this with a song selected

**Screenshots**
This is hard to explain using screenshots so I made a [video](https://youtu.be/QKbI-1uN9v0) (youtube link) 

**Desktop (please complete the following information):**
 - OS: Windows 10 LTSB 1607 64-bit
 - Version: 0.65.1

**Additional context**
Logs: [crashinfo.txt](https://github.com/etternagame/etterna/files/3123883/crashinfo.txt) ; [log.txt](https://github.com/etternagame/etterna/files/3123884/log.txt)

**Comment by MinaciousGrace** [comment]
fixed by e42c3049a1f6a563304e3a12030767cc2c368811
