### ISSUE TITLE
Add adjustable Hiddenoffset and Suddenoffset options in game

### ISSUE THREAD

**Issue by LR2Zangoose** [etternagame/etterna#518]
The process for adjusting this is currently tedious and cryptic, especially if you are having to reload the metrics each time just to see where it is positioned again. The setting could probably be placed into Advanced Settings so it does not clutter the mod menu up for those who don't use it.

**Comment by poco0317** [comment]
Related #509 
Advice for reloading metrics: Use shift+F2 instead of just F2. F2 by itself reloads textures and so on, freezing the game. Reloading metrics does not.

**Comment by poco0317** [comment]
handled in #1006
