### ISSUE TITLE
Old files with only .dwi sometimes use wrong image for song banner

### ISSUE THREAD

**Issue by flodinl** [etternagame/etterna#521]
Some old files that only have a .dwi and not .sm or .ssc don't specify the file path to the song banner. It seems like Etterna tries to fall back by grabbing some other image from the folder, but it doesn't always grab the correct one. I think the desired behavior should be to first try and fall back to another image in the song folder that has the word "banner" in the file name, as I think specifying which image was which using the file name used to be the common practice.

Example: Red Zone in KBC3. The .ogg itself has some associated artwork (album cover?), and Etterna uses this image as the banner rather than the actual banner, which has "banner" in the file name.

**Comment by poco0317** [comment]
You described exactly what the game does. It's the original charter's fault in most instances that this happens. So our first instinct is to not care. However, a little bit of effort will be taken to see if particular cases like these are easy to fix and common without slowing down the whole load process.

**Comment by MinaciousGrace** [comment]
the game should already be falling back to files with 'banner' in the file name if none is specified in the dwi/sm/ssc

if it isn't then something broke the last time changes to the loading process were made

**Comment by MinaciousGrace** [comment]
ok i found the problem but fyi when you put "banner" in quotes, to a programmer that explicitly means the word "banner", not "bn" (which is what it was in the case of red zone) or some other synonym

**Comment by MinaciousGrace** [comment]
edf8a7257c0955f503c3aa31c5b42e73ed948b4a
