### ISSUE TITLE
etterna doesnt like my refresh rate

### ISSUE THREAD

**Issue by jacwib** [etternagame/etterna#523]
**Describe the bug**
aight, so i have my monitor overclocked to 72hz for maximum tryhard
so i set the default refreshrate to 72hz in windows and what not
now in etterna i have a nice option to change it to 72hz in the settings
and this works... until i close the game and relaunch it.
and it resets to 60hz.
so i tried changing save/Preferences.ini RefreshRate=59 to RefreshRate=72
and it just resets whenever i launch the game.
having to go into settings every time i boot the game up... is a slight bit annoying.
please fix.

**To Reproduce**
1. have your monitor set to (not 60hz, probably has to be above 60 tho)
2. in etterna, change your refresh rate to (said refresh rate)
3. close the game
4. open game, note that its now 60hz again

alternatively:

1. open save/Preferences.ini
2. change RefreshRate=59 to RefreshRate=(anything else, probably has to be above 60 tho)
3. open game
4. note that it back in save/Preferences.ini!!!!111

**Expected behavior**
uh. the game saves that i want it to run in 72hz. and doesnt reset it to 60 every time i relaunch.

**Desktop (please complete the following information):**
 - OS: windows 10 1607
 - Version: 0.65.1

**Additional context**
if it matters, vsync is off.
attached is an entire dump of my Preferences.ini, cause why not? (renamed to .txt so github doesnt complain)
[Preferences.txt](https://github.com/etternagame/etterna/files/3169113/Preferences.txt)

**Comment by MinaciousGrace** [comment]
so this probably has something to do with sm5s fantastic system of overriding your graphics settings if you are doing things they don't like, e.g. setting custom window resolutions which get forcibly snapped back to your aspect ratio

this is different and my best guess is during initialization 72hz isn't being detected as a valid display mode by d3d for ??? reasons

try swapping to opengl first in your preferences.ini

if that doesn't work then we're going to need a lot more information about specific hardware and software (monitor/gpu/os, etc) and your log.txt after starting up and having your desired refresh rate overwritten

**Comment by jacwib** [comment]
well, heck, that worked just fine
thanks d3d?!?!?! and thanks for telling me how to fix it, based
(and uh. chances are i missed it, but if not, maybe throw it in some faq or something? maybe i should put it on the wiki page?)
