### ISSUE TITLE
Readd Roulette/Random Functionality

### ISSUE THREAD

**Issue by poco0317** [etternagame/etterna#524]
It's beginning to be requested now that it's been gone for about 3 years. I would imagine it's not hard to implement. The challenge lays in how seriously it should be implemented. By that I mean it could immediately be a "pick a random chart from the list" deal or it could be some obscure generalization of picking a random song.

**Comment by nico-abram** [comment]
```lua
math.randomseed(os.time())
local t = SONGMAN:GetAllSongs()
local random_song = t[math.random(#t)]
```
Something like this would probably be enough if we go with a pure lua implementation (Possibly with a similar thing on the song's charts). I remember doing something like this when testing the audio visualizer.

**Comment by MinaciousGrace** [comment]
26fa5ef3e8aac33f52fcf8dfcaa404060d1a0ea7

i tied them to the select music/group name headers to prevent further visual clutter
