### ISSUE TITLE
Add a "sort" button to activate the sorting selection on the song wheel

### ISSUE THREAD

**Issue by Kangaroux** [etternagame/etterna#525]
Most people don't know you can change the sorting with up/down arrow keys. Adding an explicit button that activates the sorting would be helpful.

**Comment by MinaciousGrace** [comment]
it would add to the existing clutter on the screen and largely be redundant with a new lua wheel but i guess i can do this in the meantime

**Comment by Kangaroux** [comment]
It doesn't necessarily have to be a button. It could be a link at the
bottom of the screen like how there is one for refresh songs.

**Comment by MinaciousGrace** [comment]
that's a button
added with a1dbd4515ecca6e2e0f3266a0bb03b3ceb945468
