### ISSUE TITLE
Crashing upon encountering Certain packs are installed Linux

### ISSUE THREAD

**Issue by BrokenGale** [etternagame/etterna#528]
**Describe the bug**
Crashing upon loading packs whether it is downloaded from within the client or downloaded from the website and extracted to the song folder.

**To Reproduce**
1. Build the develop branch
2. Download a pack like Dark Chancellor's Pack or Community Keyboard Megapack 1
3. If downloaded from website you will see something like this when trying to launch:
https://pastebin.com/7fku6dea
4. If downloaded from within the client you will see the terminal spit out errors like this:
https://pastebin.com/j47dgbrU

**Expected behavior**
Loading the pack within the game.

**Desktop (please complete the following information):**
 - OS: Pop_OS 
 - Version: 18.04 LTS

**Comment by jameskr97** [comment]
This bug has been fixed in #514.
