### ISSUE TITLE
Changing devices (plugging or removing) causes game stutter

### ISSUE THREAD

**Issue by poco0317** [etternagame/etterna#537]
This is due to "Polling for Joystick Changes" usually, which lasts for 60 seconds.
Something should be done to either stop this or subdue the stuttering.

Relevant section of code (good old 10+ year old code): https://github.com/etternagame/etterna/blob/develop/src/arch/InputHandler/InputHandler_DirectInput.cpp#L841

Possibly related: #484

**Comment by nico-abram** [comment]
Fixed in https://github.com/etternagame/etterna/pull/539
