### ISSUE TITLE
Use the same json library everywhere

### ISSUE THREAD

**Issue by nico-abram** [etternagame/etterna#544]
Right now we're shipping/including/using 3 different json libraries (JsonCpp, nlohmann json for modern c++, and rapidjson). JsonCpp was used by Stepmania already, as far as I know only for the (unused?) json simfile format. Rapidjson is used by discord-rpc. Nlohmann is the one we use in NSMAN and DLMAN (EO api response parsing and multi json message parsing). Since the only one we can't ditch is rapidjson, and since it's the fastest one (As far as I know), that's what we're going to keep. This issue involves both rewiring dependencies in cmake so that rapidjson is a direct dependency of etterna and that same copy is used by discord-rpc, and then rewriting all the places that we use json in (Or maybe just removing in the case of the json simfile note format) to use it.

**Comment by zelbrium** [comment]
I'm not sure if this is related to this Issue, but it seems Etterna can not be built from `bloated` (and probably `master`) right now because the `json` and `SQLiteCpp` repositories (required submodules) have been removed from the etternagame account. (Currently building to test #475 by copying the two submodules from an older clone I have and hoping it works!)

**Comment by nico-abram** [comment]
That's weird. On both develop and bloated SQliteCpp should be a subtree (Which is part of the repo and doesnt require initialization like a submodule) (See https://github.com/etternagame/etterna/tree/bloated/extern/SQLiteCpp , it's part of the repo). And `json` was removed from `bloated` (It should only require `rapidjson`).

**Comment by nico-abram** [comment]
Are you in the development discord? Hidden is trying to reproduce the hanging issue (And it doesn't seem to be happening). Maybe you could help us: https://discord.gg/XjxQRyU

**Comment by jameskr97** [comment]
This issue is being worked on in #547.

**Comment by martensm** [comment]
Done in #547.
