### ISSUE TITLE
More decimal points for ingame scoretab leaderboard

### ISSUE THREAD

**Issue by PPProviden** [etternagame/etterna#548]
![image](https://user-images.githubusercontent.com/31165158/58546520-1beff180-8238-11e9-887c-bbea1b8f8fd7.png)

As per title.
Add more decimal points for scores that are quads and aaa's.

**Comment by poco0317** [comment]
In addition to this we need to: increase decimal precision for all 99.00%+ scores anyways, add a CCOn filter toggle, and sort the leaderboard by percent strictly when viewing by current rate.

**Comment by nico-abram** [comment]
This might do it:
```self:settextf("%05.2f%%", hs:GetWifeScore() * 10000 / 100):diffuse(byGrade(hs:GetWifeGrade()))```
to
```self:settextf((hs:GetWifeScore() > 0.99 and "%05.4f%%" or "%05.2f%%"), hs:GetWifeScore() * 10000 / 100):diffuse(byGrade(hs:GetWifeGrade()))```
in
https://github.com/etternagame/etterna/blob/develop/Themes/Til%20Death/BGAnimations/superscoreboard.lua#L522

**Comment by MinaciousGrace** [comment]
mouseover solution, same as eval

02da394ea4bbe9754d50d260df057bc45d9e62dc
