### ISSUE TITLE
Password input field in multiplayer is on top of text

### ISSUE THREAD

**Issue by YChvanov** [etternagame/etterna#554]
**Describe the bug**
After inputting a wrong password in multiplayer login input field is being placed on top of text

**To Reproduce**
1. Press 'Multiplayer' text-button in main menu
2. Accept profile
3. Press 'Login' in bottom
4. Enter anything, but the password, in the text field and accept
5. Enter anything but don't accept
6. See the problem

**Expected behavior**
I think the wrong-password-text should be under the input field

**Screenshots**
![2019-06-01_230053](https://user-images.githubusercontent.com/25438100/58753047-92ebeb00-84c1-11e9-9637-e8e4240a2eb8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 LTSB 1607
 - Version: 0.65.1

**Additional context**
There's a already a big bunch of commits in the 'develop' branch so it may already be fixed
Putting it here as I couldn't find an issue for that problem

**Comment by nico-abram** [comment]
I dont think this Is currently fixed. A hacky fix might be as simple as moving it after the "enter password" and adding a couple newlines inbetween

**Comment by poco0317** [comment]
fixed 7340889485d602d796b37e78088f6f39bb00a28e
