### ISSUE TITLE
Access violation when deleting a profile.

### ISSUE THREAD

**Issue by Osteos** [etternagame/etterna#562]
Occasionally, the game crashes upon deleting a playlist.

**To Reproduce**
1. Go to "Playlists"
2. Delete a Playlist

**Expected behavior**
The game should not crash when deleting a playlist.

Attached is the crashinfo.txt and log.txt
[crashinfo.txt](https://github.com/etternagame/etterna/files/3255149/crashinfo.txt)
[log.txt](https://github.com/etternagame/etterna/files/3255150/log.txt)

Happens on Windows 10 64bit

**Comment by poco0317** [comment]
fixed by 7f0b4a6b27a74ffb69245572a59c1acea06b9b0f probably
