### ISSUE TITLE
[Cmake] INSTALL_DIR missing in CPackSetup.cmake in source code release v0.66 

### ISSUE THREAD

**Issue by StepinSlience** [etternagame/etterna#563]
Hello.
I have downloaded the etterna v0.66 source code release(tarball). But I have a cmake issue because in the release tarball there is some code missing in 'CMake/Helpers/CPackSetup.cmake'.
The missing part is
```cmake
# Custom Variables
set(INSTALL_DIR "Etterna")
```

**To Reproduce**
1.Download the source code release using wget(I downloaded tar.gz release).
2.Use tar to extract it and enter the directory.
3.Create a build folder and start configurations.
4.CMake will complain
```
CMake Error at CMake/Helpers/CPackSetup.cmake:51 (install):
  install FILES given no DESTINATION!
Call Stack (most recent call first):
  CMakeLists.txt:112 (include)

```

**Expected behavior**
CMake should create the Makefile without issues.

**Desktop (please complete the following information):**
 - OS: Fedora 30 x86_64 with KDE

**Comment by jameskr97** [comment]
This is fixed in latest develop.
