### ISSUE TITLE
 crash game after the end of the song "Unhandled Microsoft C ++ Exception"

### ISSUE THREAD

**Issue by 1NANI1** [etternagame/etterna#576]
crashinfo.txt
/-----------------------------------------------------------------/
Etterna crash report (build ,  @ )
--------------------------------------

Crash reason: Unhandled Microsoft C++ Exception

Thread: Main thread
        GraphicsWindow.cpp:63 00000000001203B4, 256, 00000041, 001e0001
        GraphicsWindow.cpp:63 00000000001203B4, 257, 00000041, c01e0001
        GraphicsWindow.cpp:63 00000000001203B4, 257, 00000053, c01f0001
        ScreenGameplay.cpp:2048 HandleScreenMessage(SM_DoNextScreen)
        StageStats.cpp:671 Uploading score with replaydata.
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:235 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:235 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:235 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:235 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:235 Processing the sound while buffers are available.
Thread: Mixer thread
Thread: Music thread
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:891 
        InputHandler_DirectInput.cpp:867 
        InputHandler_DirectInput.cpp:885 
        InputHandler_DirectInput.cpp:891 
        InputHandler_DirectInput.cpp:867 
Thread: Streaming sound buffering
debug resource file 'C:\Games\Etterna 0.66.0\Program\Etterna.vdi': CreateFile failed (Не удается найти указанный файл.).

Static log:
Etterna
Compiled  @  (build )
Log starting 2019-06-15 13:16:36
	Verbosity: 1
Windows 6.1 (Win7) build 7601 [Service Pack 1]
Attempting to connect to: multi.etternaonline.com, Port: 8765
Server Version: 0 
Video renderers: 'd3d, opengl'
WARNING: RageDisplay_D3D::TryVideoMode( 0, 1366, 768, 32, 0, 0 )
D3D Fullscreen 1366x768 32 color 32 texture 60Hz NoVsync SmoothLines
WARNING: Font import recursion detected
WARNING: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: /Themes/_fallback/Fonts/Common default.ini
WARNING: /Themes/Til Death/Fonts/_16px fonts.ini
WARNING: Current font: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: Font /Themes/Til Death/Fonts/_16px fonts.ini has no characters
Players joined: P1
Top Screen: ScreenGameplay
Current renderer: Direct3D

Partial log:
01:08.684: Attempted to load a non-existing mod '2.3xMusic' for the Player. Ignoring.
01:08.684: Attempted to load a non-existing mod '2.3xMusic' for the Player. Ignoring.
01:08.759: Attempted to load a non-existing mod 'savescore' for the Player. Ignoring.
01:08.759: Attempted to load a non-existing mod 'savescore' for the Player. Ignoring.
01:08.759: Attempted to load a non-existing mod 'savescore' for the Player. Ignoring.
01:08.759: Attempted to load a non-existing mod 'savescore' for the Player. Ignoring.
01:08.760: ScreenOptions::~ScreenOptions()
01:08.769: Unloading replaydata.
02:08.128: bAllReallyFailed = 0 bIsLastSong = 1, m_gave_up = 0, m_skipped_song = 0
02:13.132: saving stats and high scores

-- End of report
/____________________________________________________________________________/
Log
/____________________________________________________________________________/
00:00.016: Etterna
00:00.016: Compiled  @  (build )
00:00.016: Log starting 2019-06-15 13:16:36
00:00.016: 	Verbosity: 1
00:00.016:  
00:00.016: Reading 'Data/Defaults.ini' failed: No such file or directory
00:00.018: Reading 'Data/Static.ini' failed: No such file or directory
00:00.018: Reading 'Data/Static.ini' failed: No such file or directory
00:00.383: Windows 6.1 (Win7) build 7601 [Service Pack 1]
00:00.399: Reading 'Themes/Til Death/Languages/ru.ini' failed: No such file or directory
00:00.410: Reading 'Themes/_fallback/Languages/ru.ini' failed: No such file or directory
00:00.427: Reading 'Themes/_fallback/ThemeInfo.ini' failed: No such file or directory
00:00.435: Reading 'Themes/Til Death/ThemeInfo.ini' failed: No such file or directory
00:01.990: Loaded 1 songs from "Songs/Helblinde"
00:02.618: Profile::LoadAllFromDir( /Save/LocalProfiles/00000000/ )
00:02.618: Error opening /Save/LocalProfiles/00000000/Etterna.xml: No such file or directory
00:02.737: Attempting to connect to: multi.etternaonline.com, Port: 8765
00:02.737: Could not create ettp connection because: Connection creation attempt failed
00:04.171: Connected to ett server: multi.etternaonline.com
00:04.172: Server Version: 0 
00:04.172: C:\projects\etterna\src\RageUtil\File\RageFileDriverDirect.cpp:167: remove 'C:/Games/Etterna 0.66.0/Cache/Downloads/Helblinde.zip'
00:04.196: C:\projects\etterna\src\RageUtil\File\RageFileDriverDirect.cpp:167: remove 'C:/Games/Etterna 0.66.0/Cache/Downloads/new.Cirque du Lykan.zip.new'
00:04.224: Video renderers: 'd3d, opengl'
00:04.225: RageDisplay_D3D::RageDisplay_D3D()
00:04.258: Driver: aticfx64.dll
00:04.258: Description: AMD Radeon HD 6520G
00:04.258: Max texture size: 16384
00:04.258: Alpha in palette: no
00:04.258: 
00:04.258: This display adaptor supports the following modes:
00:04.269:   640x480 60Hz, format 22
00:04.269:   800x480 60Hz, format 22
00:04.269:   800x600 60Hz, format 22
00:04.269:   1024x600 60Hz, format 22
00:04.269:   1024x768 60Hz, format 22
00:04.269:   1280x720 60Hz, format 22
00:04.269:   1280x768 60Hz, format 22
00:04.269:   1360x768 60Hz, format 22
00:04.269:   1366x768 60Hz, format 22
/////////////////////////////////////////
00:04.269: WARNING: RageDisplay_D3D::TryVideoMode( 0, 1366, 768, 32, 0, 0 )
/////////////////////////////////////////
00:04.269: Testing format: display 20, back buffer 20, windowed 0...
00:04.269: Testing format: display 22, back buffer 22, windowed 0...
00:04.269: This will work.
00:04.282: Testing format: display 20, back buffer 20, windowed 0...
00:04.282: Testing format: display 22, back buffer 22, windowed 0...
00:04.282: This will work.
00:04.282: Present Parameters: 1366, 768, 22, 1, 8, 1, 1180596, 0, 1, 80, 0, 0, -2147483648
00:04.716: D3D Fullscreen 1366x768 32 color 32 texture 60Hz NoVsync SmoothLines
/////////////////////////////////////////
00:11.059: WARNING: Font import recursion detected
00:11.059: WARNING: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
00:11.059: WARNING: /Themes/_fallback/Fonts/Common default.ini
00:11.059: WARNING: /Themes/Til Death/Fonts/_16px fonts.ini
00:11.059: WARNING: Current font: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
/////////////////////////////////////////
/////////////////////////////////////////
00:11.059: WARNING: Font /Themes/Til Death/Fonts/_16px fonts.ini has no characters
/////////////////////////////////////////

**Comment by poco0317** [comment]
Without further details other than the crash reason, which tells us that it may be related to Lua, we cannot determine any issue or fix here.
Please provide more information in the future and follow the bug reporting format.
