### ISSUE TITLE
.ssc gimmicks not working properly on preview

### ISSUE THREAD

**Issue by Ulti-FD** [etternagame/etterna#579]
Already known as I've already mentioned this in the #testing channel, but I thought putting in an issue for it would be good.

**To Reproduce**
-Play any song with, for example, scroll changes
-Exit out of song
-Look at any other song on preview, gimmicks from song played will now apply

The inverse also works. Play a file with no such gimmicks and the preview for a file with gimmicks will look completely normal.

**Example**
https://cdn.discordapp.com/attachments/395382822837157898/559459965870407806/Etterna_2019-03-24_20-27-26-279.mp4

(Done on win64 build of .66.1, though I believe I've seen this happening since .65.0 or so)

**Comment by poco0317** [comment]
done 1c01aa3ce2c876ea28059de2cdfca51c33c3482b
