### ISSUE TITLE
Difficulty List Moves in unintended ways related to Chart Preview

### ISSUE THREAD

**Issue by PCBoyGames** [etternagame/etterna#581]
On certain resolutions, switching between a doubles chart preview and a singles chart preview will cause the difficulties panel to move further into an abyss. [See this video I posted on YT for more details.](https://youtu.be/SKPNBHJDkww)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by poco0317** [comment]
I knew this existed but forgot about it at some point and never experienced it in regular gameplay. Should be simple to fix.

**Comment by poco0317** [comment]
was not as simple to fix as expected so i slapped something together and called it a day (this works)
fixed by 4e839336cecf1474b9421093398b421998fddaa1
