### ISSUE TITLE
Add receptor spacing as an customise gameplay option

### ISSUE THREAD

**Issue by PPProviden** [etternagame/etterna#582]
Receptor spacing is a pretty often used feature in other VSRGs and should also be an option in Etterna. Currently there are no way for the user to customize it directly ingame, and it would be very convenient if there is one.

**Comment by CODE-itsjakesm** [comment]
Yeh please push this for next update, seems like such a big customisation option to have it not be added yet. FFR had this banging option for like 10 years now or something, get your head in the game!

**Comment by poco0317** [comment]
#822
