### ISSUE TITLE
Lifebar graph in evaluation screen doesn't dynamically adapt to judgement changes

### ISSUE THREAD

**Issue by kangalioo** [etternagame/etterna#588]
When changing the judgment in the evaluation screen, the lifebar graph in the top left stays the same, even though the lifebar and also the combo counter below would be affected by the judgment changes.

**To Reproduce**
1. Play a chart
2. Change judgment by pressing EffectUp and EffectDown keys (+ and - for me)
3. Look at the lifebar graph in the top left

I expect the lifebar graph it to dynamically adapt to whatever judgment is currently selected, as all other elements of the screen do as well.

**Comment by poco0317** [comment]
I've gotta say this is probably one of the most complicated minor features that could possibly exist if going with its current implementation. The current lifebar is made up of a big list of time points and life values. Recalculating these on the fly would be wild.

**Comment by poco0317** [comment]
Recalculating these on the fly is not a pipe dream and this is something we can easily do with Replay Data.
In the current gameplay rewrite, Replays are capable of doing this themselves. Just have to extend this to work with all judgment windows and be recalculated on command.

**Comment by poco0317** [comment]
Done in gameplay rewrite pr by 1d6aff4b602e238cfb1ab5cef65cca87f32918fa a7bee3d09181b882faf88a4d0efa9f7c8caa8760
closed when merged
