### ISSUE TITLE
Use SSRNormPercent instead of WifeScore for local sort and songwheel grades. 

### ISSUE THREAD

**Issue by foxfire667** [etternagame/etterna#590]
![SSRNorm Percent](https://user-images.githubusercontent.com/7039995/60407383-8aea9e00-9b88-11e9-846b-61130714860e.png)

Within a a profile's Etterna.xml, there are two percentages which are stored: **WifeScore** and **SSRNormPercent**

WifeScore is simply the number spit out based on the judge you played, while SSRNormPercent is the J4 normalized value. This means that if we were to use this value instead, we could have a clear and simple way to sort local leader boards, as well as display the J4 earned grade on the song wheel to give quick reference of what was actually done. 

This would be useful for a few reasons, examples being: 
- Getting Etterna up to speed with EO in normalizing wife percents on scores
- Allowing users to freely switch judges locally and play the same files without having their personal bests be sorted incorrectly. 
- Allow users to quickly identify their earned grades on song wheel (e.g. having J7 quad runs actually showing on client as quads and not AAs/AAAs). 
- Incentivizing people to actually utilize higher judges for accuracy feedback, due to the above changes. 

While it would be nice, this wouldn't change the listed judgements received. However, proper sorting and listed grades being normalized is a great step in the right direction I feel. It'd be a lot less headache for anyone trying to explore accuracy and swapping judges.

**Comment by poco0317** [comment]
Handled in #698
