### ISSUE TITLE
Add different health systems

### ISSUE THREAD

**Issue by lotushomerun** [etternagame/etterna#593]
Different health systems would be a useful quality of life feature for the client.
# Proposing Health Systems
I propose 4 new health systems, batteries, non-regenerating health, hit-bar, and a accuracy threshold
## Batteries
Batteries work like their DDR/SM5 counterparts (You get a CB and you lose a battery. Batteries cannot be gained back in the same play, run out of batteries and you fail the file)
Normally, in SM5, you can only choose between 1-4 batteries
A slider like how you pick Cmod can solve this issue, by allowing you to pick from an unlimited range. You can have 1 battery, or 1,000,000 batteries
They're should also be multiple types of batteries:

- CB Batteries (CB = Lose a battery, like normal batteries)
- Perfect Batteries (Perfect or lower = Lose a battery)
- Great Batteries (Great or lower = Lose a battery)

These types of batteries will allow you to pick what score your going for (like are you going for a PFC?)

Oh and while we're at it, something like what issue #487 is proposing can be implemented too

## Non-Regenerating Health
This functions like Hard mode from LR2

- You start with 100% health
- CBs make you lose health (Affected by your Life setting)
- You cannot gain back health.

May be useful as an alternative to batteries

## Hit-Bar
A hit bar works like this

- You start with 0% 
- Hitting notes (NOT CBs) raises the bar, CBing drops the bar, but not as much as if you had a normal health bar (But is still affected by your Life setting).
- You must have 75% or higher bar to pass.

(Works like the way Sound Voltex does Effective Rate)

## Accuracy Threshold
An original idea that popped on my head:

- When you are below the accuracy threshold (Assuming that 5 or more notes have been played), a 5 second countdown will start. If you are below the accuracy threshold when the timer ends, you will fail the file
- You can select the accuracy threshold like how you can set the goal percentage in the goal tracker
- The accuracy threshold is for the judge your playing on. You can get a 92% on Justice and fail if your accuracy threshold is 93%, even though on J4, it would be a high wife AAA/low wife quad

# Conclusion
This might be doable on the theme, since it involves adding options to the theme and implementing them.
We are also bringing back SM5 features. That's cool, I guess

**Comment by poco0317** [comment]
As a note, these features were previously in the game and were removed due to lack of use and feature bloat.

Related: #487

**Comment by DeltaEpsilon7787** [comment]
Real question: why? Life meter has no bearing on the score whatsoever besides invalidating it if you fail. There is no reason for this feature and practically nobody cares about life meters.

**Comment by MinaciousGrace** [comment]
i don't think there is a scenario where anything alternative life systems are trying to achieve couldn't be done better in another way and as poco said they used to exist and were removed due to lack of meta use and code bloat

also as you pointed out this can actually be done entirely in the theme and if someone wants it badly enough they can write it up and pr it and i might merge it, barring that this is not going to be a thing
