### ISSUE TITLE
Lua Hooks

### ISSUE THREAD

**Issue by nico-abram** [etternagame/etterna#60]
I'm opening this issue as a place to discuss the somewhat likely addition of lua hooks to Lua in Etterna(Eventually).

Heres my thoughts on it:
 - It should not break any compatibility whatsoever.
 - ~~They would work similar to how branches do right now. For example, there's a table called Hooks in which there are a series of functions which are called from C++ at certain points. This table could be extended in the `Scripts` directory of a theme.~~ So branches apparently work using _fallback and metrics. That is definetely not what i mean to address in this issue
 - The syntax I'd like to have is something like Hooks:Add("EventName(Like 'OnSongReload' )", "Unique Identifier(So you can remove the hook later)", hookfunction)
 - My first idea for the implementation is a Hooks manager in fallbacks /Scripts/ which has a table with functions or something similar for each hook(Probably a table of tables, accessed by key, which would be the event name). ~~Then there's a function for each hook that simply calls all of the hooks added by the hooks manager to its respective table of functions, and the c++ core only calls these functions.~~ Then ere'd be a Hooks.Run("event", args) function that runs the hooks, which is called from c++ with the proper event name.

Please leave your ideas on possible hooks or their implementation here.

**Comment by martensm** [comment]
I would like feedback from theme writers about what their current pain points are in terms of boilerplate code they have to implement themselves due to limitations with the current Lua bindings that are in place.

**Comment by Nickito12** [comment]
[00 hooks.txt](https://github.com/etternagame/etterna/files/1275903/00.hooks.txt)
I'm just gonna drop this here, a first idea/concept on how this could be done (The lua code would go in fallback's scripts, and the example in a theme, while the c++ call would go in the proper event for each hook)
