### ISSUE TITLE
Hiding the Judgment Text causes an Error

### ISSUE THREAD

**Issue by lotushomerun** [etternagame/etterna#612]
**Describe the bug**
When playing a file with the judgement texts off, the game throws an error with the description
```
: invalid Class ""
```

**To Reproduce**
1. Allow errors to be shown by toggling "Show Errors" on. (Hold F3 -> F6 -> 8)
2. Hide the judgment text/image (Player Options -> Judgment Text -> Hide)
3. Play a file

**Expected behavior**
No error is meant to appear

**Screenshots**
![](https://i.imgur.com/9Z9KRx5.png)

**Etterna Version:**
0.66.1 (x64)

**Additional context**
This is a problem relating a script in the C++, as it would state which script caused the error if it was a .lua script

**Comment by poco0317** [comment]
How to fix (this is a race for anyone who can do it before I feel like submitting the code myself)

Replace the following line https://github.com/etternagame/etterna/blob/cce9555823b0e2e5fdcaa92b632f42d27a41db94/Themes/Til%20Death/Graphics/Player%20judgment/default.lua#L85
with the following code
`return Def.ActorFrame {}`

**Comment by poco0317** [comment]
you were too slow

Fixed in #604 (will close when PR merged)
