### ISSUE TITLE
Favorites playlist doesn't store rates

### ISSUE THREAD

**Issue by kangalioo** [etternagame/etterna#613]
When saving a chart to a playlist, usually the rate is saved with it. That's handy because it allows a playlist's charts to be down- or uprated to match the player's skill level.

That's not the case when favoriting a chart with Ctrl+F though. Favorites are stored as 1.00x, no matter which rate is active at the time. I think it would be more consistent and logical to add that feature to the favorites playlist as well.

**Comment by poco0317** [comment]
This is intended behavior. The favorites playlist is merely one of the ways to access your list of Favorited Songs. The playlist itself does not exist in your xml. Favorites are stored as a list of chartkeys rather than playlist entries.
