### ISSUE TITLE
Small bug when starting preview while music is paused

### ISSUE THREAD

**Issue by kangalioo** [etternagame/etterna#614]
When starting the song preview while the music is paused, the "Paused" text remains, but the music and preview start nevertheless. The previewed notes are running directly above the "Paused" text.

**To Reproduce**
1. Pause music with right-click
2. Start preview with space
3. See scrolling notes even though the preview is supposedly paused

**Expected behavior**
I expect the game to either:

1. unpause completely when starting the preview
2. not starting the preview when brought up, until player unpauses

**Screenshots**
![2019-08-03_185555](https://user-images.githubusercontent.com/21220820/62414762-63bc3c00-b620-11e9-8ed5-d09517b0bbae.png)

**Comment by poco0317** [comment]
Fixed in gameplay rewrite pr by c7be2763b2933ca0631c511ced50933674a2239f
closed when merged
