### ISSUE TITLE
Displayed chart length is wrong if .ssc file has separate BPM's per chart

### ISSUE THREAD

**Issue by kangalioo** [etternagame/etterna#615]
Some .ssc stepfiles have different BPM's for each chart. That means that there is no general BPM information in the .ssc header. Etterna seemingly handles this by wrongly assuming 60 BPM for every chart with this gimmick. This causes the displayed chart length to be wrong as well.

**To Reproduce**
Steps to reproduce the behavior (every file from Thirdstyle Pack also has this):
1. Find a .ssc stepfile
2. Move the BPM tag from the header into the chart section
3. Load the file in Etterna and see wrong BPM and chart length

**Expected behavior**
I expect the game to show the correct BPM and chart length, depending on which chart is selected.

**Screenshots**
![Screenshot_20190803_191230](https://user-images.githubusercontent.com/21220820/62415011-9287e180-b623-11e9-9750-213b14127117.png)

**Comment by MinaciousGrace** [comment]
https://github.com/etternagame/etterna/pull/827
takes care of the length display

split bpms use a bpm range to display instead of a single value which i guess is technically still wrong and should be changed

**Comment by bluebandit21** [comment]
I think this can be safely closed now unless I'm missing anything else(?)

**Comment by poco0317** [comment]
superceded by #1218
