### ISSUE TITLE
Hitting fake notes can result in scores over 100%

### ISSUE THREAD

**Issue by kangalioo** [etternagame/etterna#616]
Hitting fake notes in a chart makes the score higher - with good accuracy sometimes over 100%. This error is only local though, in EtternaOnline the score seems correct.

**To Reproduce**
1. Play a chart with fakes that you can play accurately (like >99%)
2. Hit the fakes accurately as well
3. Watch the score rise to over 100%

**Expected behavior**
I would expect the game to totally ignore hitting fakes.

**Screenshots**
![Screenshot_20190801_140750](https://user-images.githubusercontent.com/21220820/62415066-5acd6980-b624-11e9-81da-4bc20bd77781.png)

**Comment by poco0317** [comment]
Fakes are completely impossible to hit in gameplay rewrite.
Fake notes are ignored by the calculator, but taps within fake regions are not. Still needs work.
Primary issue fixed by 140af604678120ed17322bdc6ec92786d0b972ef
closed when merged
