### ISSUE TITLE
Improve fullscreen support

### ISSUE THREAD

**Issue by zedeus** [etternagame/etterna#618]
On Linux (X11), fullscreen support is awful. When using multiple monitors, the first monitor is used and the others go black. Playing with windowed mode enabled seems to limit the refresh rate to around 50Hz which results in choppy gameplay.

Related Stepmania issues: [#176](https://github.com/stepmania/stepmania/issues/176) [#428](https://github.com/stepmania/stepmania/issues/428) [#447](https://github.com/stepmania/stepmania/issues/447) [#1385](https://github.com/stepmania/stepmania/issues/1385)

I found [this PR](https://github.com/stepmania/stepmania/pull/1018) which seems like it got merged after etterna was forked. It (optionally) uses libXrandr to query output information.

**Comment by poco0317** [comment]
Somewhat handled by #697 but cannot test as I don't have an environment to do so which encompasses the scope of this issue.

**Comment by zedeus** [comment]
From my testing it seems to have been fully fixed now. Multi-monitor support works fine (both exclusive and borderless) without the faults from before, and the game actually displays at 60 fps now which makes a huge difference. Thank you so much for working on it
