### ISSUE TITLE
Scroll gimmicks can persist through chart previews

### ISSUE THREAD

**Issue by PCBoyGames** [etternagame/etterna#624]
https://youtu.be/KJaJ4w3beHs

When I sent Owem GLITCH MANIAXXXX to show him how easy it is to break limits in SM5, it ended up breaking further boundaries in Etterna as well. After playing GLITCH MANIAXXXX, Owem, without turning off M-Mod, went to several different files, and the same gimmick from the middle of the file he last played persisted through chart previews in King of Sales, I, and Hatsune Miku’s Head Exercises, none of which contain the same gimmick.

GLITCH MANIAXXXX: https://cdn.discordapp.com/attachments/354343979371986945/611273685046657031/PCBoyGames_GLITCH_MANIAXXXX.zip

Again, I understand from a previous issue I posted that chart preview was rather whipped up. #587, I think it was. But this time, it could be an issue with chart preview where we actually have a bit of a problem understanding what’s next in gimmick files.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by poco0317** [comment]
I don't think the combo thing at the end actually cause any issues but the actual bug being demonstrated is probably a sign of a more serious underlying issue we haven't noticed.

**Comment by Ulti-FD** [comment]
I already opened an issue for this https://github.com/etternagame/etterna/issues/579

**Comment by poco0317** [comment]
done 1c01aa3ce2c876ea28059de2cdfca51c33c3482b
