### ISSUE TITLE
Cannot Launch: Entry Point Not Found

### ISSUE THREAD

**Issue by tmwbook** [etternagame/etterna#625]
**Describe the bug**
When attempting to launch Etterna (0.66.1, 0.66.0, 0.65.1), a Windows error pops up immediately: Entry Point Not Found "The procedure entry point D3DXVec3Normalize could not be located in the dynamic link library D:\Path\To\Etterna\Program\Etterna.exe.

This is a fresh install of Windows 10 with up to date drivers and DirectX (see below for details).

**To Reproduce**
1. Install Etterna using a provided installer for 64 bit Windows
2. Do not add Etterna to PATH
3. Launch Etterna from the program folder
4. Windows error

**Expected behavior**
The game starts.

**Screenshots**
Error:
![image](https://user-images.githubusercontent.com/5827837/63231720-e979e300-c1ed-11e9-93ed-13a4d0b67a4e.png)

**Desktop (please complete the following information):**

DXDiag
![image](https://user-images.githubusercontent.com/5827837/63231736-2cd45180-c1ee-11e9-818e-9bfd70dd6b32.png)

Driver info
![image](https://user-images.githubusercontent.com/5827837/63231740-3e1d5e00-c1ee-11e9-80ac-83bc31780eec.png)

 - OS: Windows 10
 - Version KB4512508
 - 64bit

**Comment by poco0317** [comment]
Try this if you still have the issue: https://www.microsoft.com/en-us/download/details.aspx?id=8109

**Comment by tmwbook** [comment]
I think you were the one helping me over at reddit. Closing this issue in case anyone else finds it later: Some combination of installing the extra runtime linked above, adding the DX CAB files to the PATH, and switching to the 32-bit version of Etterna fixed the issue. Thanks!
