### ISSUE TITLE
Pack downloads on macOS are extremely slow

### ISSUE THREAD

**Issue by slice** [etternagame/etterna#626]
**Describe the bug**
Downloading packs is extremely slow on macOS. Download speeds peak at around 80 KB/s.

**To Reproduce**
1. Go to 'Pack Downloader'
2. Click on a pack to download it

**Expected behavior**
Downloads happen at full speed.

**Screenshots**
[Video](https://cdn.discordapp.com/attachments/228317351672545290/613467614525653086/etterna_mac_bug.mp4)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Version: 0.660
 - 64bit

**Additional context**
Packs can be downloaded at full speed through the website.

**Comment by slice** [comment]
Reproducible under 0.66.1.

**Comment by jxu** [comment]
same for ubuntu build

**Comment by osjuga** [comment]
Just want to note that this is still an issue; I just built on Linux Mint and my downloads thru the game are capped at 80-83KBs.

**Comment by poco0317** [comment]
fixed by #1200 for all platforms, will be in next release
