### ISSUE TITLE
Hold and roll body stretches instead of tiling

### ISSUE THREAD

**Issue by JapanYoshi** [etternagame/etterna#627]
**Describe the bug**
Hold and roll body graphics should tile. Etterna stretches them.

**To Reproduce**
1. Use any noteskin with hold or roll tails
2. Play any chart with holds or rolls (ideally long holds or rolls)
3. See error

**Expected behavior**
Hold and roll note bodies should tile.

**Screenshots**
Self-explanatory

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: May 19 update
 - 64bit

**Additional context**
Just why?

**Comment by JapanYoshi** [comment]
Has this been received? Perhaps it is a long weekend where you live. It is Tuesday here.

**Comment by JapanYoshi** [comment]
Is it the lack of screenshots why you're not responding? If so, here they are.

### Hold notes on Etterna (wrong):
![2019-08-27_233004](https://user-images.githubusercontent.com/8707990/63775553-eb951d80-c922-11e9-9c4d-7aed18593f84.png)
### Hold notes on Stepmania 5 (correct):
![mD8NYbBrtb](https://user-images.githubusercontent.com/8707990/63775584-fe0f5700-c922-11e9-901e-c143ad8c213f.png)
### Roll notes on Etterna (wrong):
![2019-08-27_233007](https://user-images.githubusercontent.com/8707990/63775558-ecc64a80-c922-11e9-8e33-d59c4aa92b69.png)
### Roll notes on Stepmania 5 (correct):
![QDPlslZPxY](https://user-images.githubusercontent.com/8707990/63775588-ff408400-c922-11e9-92c9-7cdca19d11ff.png)

Has anybody even looked at this yet?

**Comment by PPProviden** [comment]
https://github.com/etternagame/etterna/pull/199
implemented by jousway as a feature, should be toggable if you go into the metrics.ini and turn it off.

**Comment by JapanYoshi** [comment]
Oh God. By what metric is that handled, and in which metric.ini?

**Comment by JapanYoshi** [comment]
I can't find `UseStretchHolds` or `UseShrinkHolds` in `Etterna\Noteskins\common\common\metrics.ini`. I used Visual Studio Code to search all files within `Etterna\Noteskins` for "UseStretchHolds", but it's nowhere to be seen. Am I just supposed to add in those lines somewhere, and if so, under which header?

**Comment by JapanYoshi** [comment]
Okay, to recap, Etterna adds new metrics to noteskins and you have to set those to 0, if globally, in common/common/metrics.ini, and if for one noteskin, in that metrics.ini.
