### ISSUE TITLE
Ubuntu 19.04 no sound upon launching the game

### ISSUE THREAD

**Issue by Natsukiii11** [etternagame/etterna#633]
Hi there! I was bored and decided to give this game a go. However, after compiling it (using the instructions on the etterna wiki) and attempting to launch the game, I am met with no sound. After doing some research I came to the conclusion that it may have to do with audio drivers. You see, if I launch the game from a command file, I get the following output: 

`Etterna
Compiled  @  (build )
Log starting 2019-09-19 19:55:01
	Verbosity: 1
OS: Linux ver 050000
Crash backtrace component: x86 custom backtrace
Crash lookup component: backtrace_symbols
Runtime library: glibc 2.29
Threads library: NPTL 2.29
ALSA: Advanced Linux Sound Architecture Driver Version k5.0.0-29-generic.
ALSA Driver: 0: HDA ATI HDMI [HDMI], device 3: HDMI 0 [HDMI 0], 1/1 subdevices avail
ALSA Driver: 1: HD-Audio Generic [Generic], device 0: ALC887-VD Analog [ALC887-VD Analog], 1/1 subdevices avail
ALSA Driver: 1: HD-Audio Generic [Generic], device 1: ALC887-VD Digital [ALC887-VD Digital], 1/1 subdevices avail
ALSA: dsnd_pcm_hw_params_set_access: Invalid argument
Couldn't load driver ALSA-sw: SetHWParams failed
Couldn't load driver OSS: RageSoundDriver_OSS: Couldn't open /dev/dsp: No such file or directory
Attempting to connect to: multi.etternaonline.com, Port: 8765
[2019-09-19 19:55:02] [fatal] Required tls_init handler not present.
Server Version: 0 
Video renderers: 'opengl'
Display: :0 (screen 0)
X server vendor: The X.Org Foundation [1.20.4.0]
Server GLX vendor: SGI [1.4]
Client GLX vendor: Mesa Project and SGI [1.4]
Paletted textures disabled: GL_EXT_paletted_texture missing.
Direct rendering: yes
OpenGL Windowed 1200x900 16 color 16 texture 60Hz NoVsync SmoothLines`

After research, it seems that my problem would be the fact that ALSA would not load, for whatever reason. So, my first thought was to change the "SoundDrivers=" line in the text file. I tried "pulse", "pulseaudio", "jack", "ALSA", "alsa" and none of them worked. However, after every time I launched the game, the same output would pop up in my terminal window and the line in the text file would revert back to "SoundDrivers="

If anyone knows how to fix this, that would be fantastic!

For reference here is my neofetch output:

`OS: Ubuntu 19.04 x86_64
Host: 7200-5401A
Kernel: 5.0.0-29-generic
Uptime: 3 hours, 42 mins
Packages: 2692 (dpkg), 18 (snap)
Shell: bash 5.0.3
Resolution: 1920x1080
WM: i3
Theme: Adwaita [GTK3]
Icons: Adwaita [GTK3]
Terminal: gnome-terminal
CPU: AMD A10-9700 RADEON R7 4C+6G (4) @ 3.500GHz
GPU: AMD ATI Radeon R5/R6/R7 Graphics
Memory: 4588MiB / 7404MiB`

**Comment by Miz0re** [comment]
Have you tried SoundDrivers=Pulse with the capital P?

**Comment by Natsukiii11** [comment]
> Have you tried SoundDrivers=Pulse with the capital P?

Yes I have. Same problem happens. The text file seems to erase the "Pulse" from the file completely upon launching the game

**Comment by Jousway** [comment]
seems like you havent compile with pulse support

**Comment by smug-dev** [comment]
huh, still no working solution :(

**Comment by poco0317** [comment]
no replies since 2019
