### ISSUE TITLE
If Windows Aero is turned off, game won’t open

### ISSUE THREAD

**Issue by KisaragiEffective** [etternagame/etterna#637]
**Describe the bug**
When the window isn’t in aero mode, game won’t work fine

**To Reproduce**
1. Launch game
2. Wait about 1 hours (Usually, normal games are don’t take so long)
3. Will get no menu

**Expected behavior**
A clear and concise description of what you expected to happen

**Screen shoots**
Just black screen, so omitted.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Windows 7
 - Version [e.g. 22]: 0.66.1
 - 64bit or 32bit: 64bit

**Additional context**
Turn on and reboot, works fine
Turn off and reboot, Doesn’t work fine
Mmm...?

**Comment by nico-abram** [comment]
@KisaragiEffective Do you know if this is still an issue?

**Comment by KisaragiEffective** [comment]
@nico-abram No, because I don't have Windows license anymore.
