### ISSUE TITLE
Access Violation when selecting song

### ISSUE THREAD

**Issue by KisaragiEffective** [etternagame/etterna#638]
**Describe the bug**
Crash with Access Violation:
[crashinfo.txt](https://github.com/etternagame/etterna/files/3662767/crashinfo.txt)

**To Reproduce**
1. Launch
2. Enter song selecting screen

**Expected behavior**
Normally select and play

**Screenshots**
*ommited since hard to show by image*

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 7
 - Version [e.g. 22] 0.66.1
 - 64bit or 32bit 64bit

**Additional context**

**Comment by poco0317** [comment]
There are several ways to crash when on music select. I need you to be more specific.

**Comment by KisaragiEffective** [comment]
Mmm, just was trying pick music...
But if you still need, I will take a movie that shows this

**Comment by poco0317** [comment]
If no video or further description is provided for the next couple of days, I will have to close this issue.
