### ISSUE TITLE
Left/Right cb counts and error highlights are misleading above 4k (excluding pump)

### ISSUE THREAD

**Issue by Jolomann** [etternagame/etterna#639]
**Describe the bug**
The Left/Right cb counts and error highlights seem to only take 4 columns into account rather than, say, 7 on kb7 files. Several hits on the error plot remain dim when cycling highlights, but I'm not sure exactly what columns are ignored or displayed properly. Issue present on kb7, solo, and doubles. Pump works as it should

**To Reproduce**
Play >4k file (note: not pump)
Press down arrow on result screen to cycle highlights

**Expected behavior**
Show hits correctly

**Screenshots**
![alt text][left]

[left]: https://cdn.discordapp.com/attachments/389194939881488385/629395725746176054/unknown.png "left"

![alt text][right]

[right]: https://cdn.discordapp.com/attachments/389194939881488385/629395734856204288/unknown.png "right"

**Comment by poco0317** [comment]
You mention CB counts but only give an example of hand highlighting.
This was fixed in 0.65.1: https://github.com/etternagame/etterna/commit/cf0c5e7123df17545624de3a039e2a147bd6ce01

**Comment by Jolomann** [comment]
Woops, little oversight

**Comment by poco0317** [comment]
fixed and handled by a563a8febe5f047892317802e4b07cef895bdc8d cae1e35063f88e5941b31bde69cefaba0af12c86
