### ISSUE TITLE
BPM and rate text on gameplay screen not movable with customize gameplay.

### ISSUE THREAD

**Issue by MatsushimaMichiru** [etternagame/etterna#644]
The bpm and rates text in gameplay screen is not movable in any way other than removing the code from lua files. Some people do not like that and I had to guide them to remove the code which sucks.
Adding a option to move it anywhere with customize gameplay sounds smart.

**Comment by poco0317** [comment]
done in gameplay rewrite pr by 7f1d23aab1f3a068ddfeddeb5c9fed43252debe6

closed when merged
