### ISSUE TITLE
Game crash at end of song

### ISSUE THREAD

**Issue by Pianist7137** [etternagame/etterna#647]
**Describe the bug**

**To Reproduce**
1. Install Game
2. Add a songpack
3. Start game
4. Press start > create profile > select song > speed 550 and Reverse
5. Start song and complete
6. song ends, game crash

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10
[crashinfo.txt](https://github.com/etternagame/etterna/files/3784594/crashinfo.txt)

 - 64bit

**Additional context**

**Comment by poco0317** [comment]
duplicate #603
