### ISSUE TITLE
Judges lower than J4 cause rolls and holds to be more lenient

### ISSUE THREAD

**Issue by Ulti-FD** [etternagame/etterna#650]
Fully aware that this isn't a bug and is working as intended.

This potentially creates issues with players using lower judges on charts with hard to play holds or rolls (see: anything from Delta Experimental, "LN" shit, etc ) in order to great diminish the difficulty of the chart. Taps are not an issue as they get converted perfectly fine regardless of judge. Holds are arguably *already* lenient on j4, being able to make them easier shouldn't be possible.

**Comment by MinaciousGrace** [comment]
2bdf90b21431454b7205b459860716042079abb2
