### ISSUE TITLE
Utility of "Grade" and "Length" sorts limited

### ISSUE THREAD

**Issue by hitonisan** [etternagame/etterna#653]
**Describe the bug**
The "Grade" and "Length" sorts within Etterna have traits to them that make them much harder to follow than they need to be.

The "Grade" sort orders songs by the letter grade the player has achieved on that song. However, there are currently two problems with it. First is the fact that the entire songlist is still put into a single group, rather than having separate groups for each letter grade. Secondly, the sorting itself is very peculiar. Instead of ordering the grades by % accuracy, Etterna uses what I can only best describe as a fragmented alphabetical sort within each letter grade:

![Grade Sort Odd Alphabetical Order](https://user-images.githubusercontent.com/37351790/69665146-5f90b000-104f-11ea-9e44-93eb73e9be14.png)

This image seems to capture both a small bit of alphabetical sorting of numbers, but also alphabetical sorting of "UVW" on the same screen. Not only is the above very difficult to comb through for song titles, but the lack of sorting by accuracy means grades with massive differences in accuracy can be placed right next to each other.

The "Length" sort groups songs by the minutes needed to complete them, but also doesn't go in order of the actual listed chart length. Instead, it uses the length of the music file, even if parts of that music aren't included in the chart. This leads to conflicts with the listed chart lengths, and can disorganize song placements. The following song, Chiptune Superstar, uses an MP3 file that is 4 minutes, 3 seconds in length:

![Length Sort Confusion 2a](https://user-images.githubusercontent.com/37351790/69667610-f5c6d500-1053-11ea-894c-69a3e2a089e0.png)

![Length Sort Confusion 2b](https://user-images.githubusercontent.com/37351790/69667620-f9f2f280-1053-11ea-9a4c-f319e768b191.png)

**Desktop:**
 - OS: Microsoft Windows 10 Home
 - Version 10.0.18362
 - 64-bit architecture

**Additional context**
Based on observations made in Etterna 0.66.1.

**Comment by poco0317** [comment]
Related #394 #376
Vaguely related #228

**Comment by MinaciousGrace** [comment]
a8728a28dc70563000480cc9f9457cb5298d0f30
b3c2724f6d2bc7aa103e4abbf287c6fdfa90dede
fix length

grade sort not being grouped was fixed a while ago, then the sort itself was broken, then it was fixed recently but i cba to look up the commit

the sort within grades is still kinda broken, but i don't think i want to fix it if we are just going to replace the music wheel
