### ISSUE TITLE
Goal Tracker should ignore Failed Scores

### ISSUE THREAD

**Issue by poco0317** [etternagame/etterna#664]
this is about the goal tracker being set to PB mode. a failed score, even with like -300% would be tracked if it was the only PB. this is obviously easily able to be passed in any scenario. same goes for a higher failure like a 90%. maybe you don't want to compare to a failure?

or should it? i think maybe
someone else agrees

but who disagrees?

to accomplish this, a few things could be done and on a surface level im not sure which is best to do

**Comment by foxfire667** [comment]
If it can be determined the score was an F, I can't really see why anyone would want it tracked. Realistically the only way a person is going to HP fail is through either mines, mash tier play, or a mega CB rush chain. I'm fairly confident this information wouldn't be useful to someone who thinks it's worth it to play the file again.

**Comment by poco0317** [comment]
#1045
