### ISSUE TITLE
Toasty image only appears once in practice mode

### ISSUE THREAD

**Issue by Kangaroux** [etternagame/etterna#669]
**Describe the bug**
If you get multiple toasties you will only see the toasty image the first time. The audio always works but the image only appears for the first one.

**To Reproduce**
Use a toasty that has audio.

1. Enter practice mode
2. Set a bookmark
3. Get a toasty
4. Press backspace to return to bookmark
5. Get another toasty

**Expected behavior**
Toasty image always appears.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.67.0
 - 64bit

**Comment by poco0317** [comment]
Fixed in hotfix by 66642bacf66af709f73f0ad3fcf3f4e7e38a2e6a
Closed when merged
