### ISSUE TITLE
Cancelling creating a playlist mutes music until the selection of a different song

### ISSUE THREAD

**Issue by senya0** [etternagame/etterna#676]
Actioning to create a playlist, then cancelling, mutes music when the screen returns to song select. If  playfield preview was open before creating playlist, it will continue previewing the chart after closing the playlist creation, just with no music. Selecting a different song afterwards always resumes music. Sometimes, opening/closing playfield preview can resume the music after quitting playlist creation.

1. Go to song select
2. Press Ctrl+P to create new playlist
3. Press Esc to quit out of playlist creation
4. Jazz music stops

Expected Behavior:
After quitting out of playlist creation, music should resume normally. 

Windows 10 Home 64 bit Build 18362
Etterna 0.67.1

**Comment by MinaciousGrace** [comment]
7c0ddb993a2cbfb72e0a6635e61ebe5b5547596e
