### ISSUE TITLE
make a new option for FPS counter that shows only the FPS in an unintrusive manner

### ISSUE THREAD

**Issue by PPProviden** [etternagame/etterna#69]
The current show stats shows too much unwanting info if i want to see only my fps

**Comment by MinaciousGrace** [comment]
you can set showskips=0 in the preferences.ini to remove the 'lagbox' in the bottom right

imo having current fps without average fps is kind of pointless for any real benchmarking and the rendering engine display is a useful thing for us when we get screenshots for bug reports etc

not saying it can't be done but it can be just as easily achieved with any one of the dozens of third party fps programs which will give you a more accurate read anyway

**Comment by PPProviden** [comment]
tried showskips=0 and it worked!
thanks
