### ISSUE TITLE
Making a screenshot makes gameplay freezy

### ISSUE THREAD

**Issue by n13omou** [etternagame/etterna#692]
Sometimes when I make a screenshot the game freezes for 12 seconds (no more or less than 12) without allowing me to do anything. After this, the gameplay becomes hard to read because it acts like it is constantly having microfreezes. Also, the screenshot will not appear in the Screenshots folder.

This bug stopped appearing as I've installed 0.67.1 version but it appeared again today. If this bug happens once in a session it means that every attempt to make a screenshot in the current session will be like this. It happens both if I've just ran the game and made screenshot and if I was playing for few hours.

 - OS: Windows 10
 - 0.67.1 but was appearing in the previous versions
 - 64bit

**Comment by MinaciousGrace** [comment]
is this still happening?

**Comment by nico-abram** [comment]
Closing this because of the lack of a response in ~2 years
