### ISSUE TITLE
The game crashed after leaving the game

### ISSUE THREAD

**Issue by WinterIsPretty** [etternagame/etterna#706]
**Describe the bug**
The game crashed right after I left the game, idk if this is fixed for 0.68 but this happened when I left on version 0.67

**To Reproduce**
I played a few maps
I left the game

**Expected behavior**
Not to crash

**Screenshots**
[log.txt](https://github.com/etternagame/etterna/files/4217162/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.67
 - 64bit

**Comment by poco0317** [comment]
Update to 0.68 before reporting this type of issue (unexplainable crash)

**Comment by WinterIsPretty** [comment]
I tried but when i went to update it did 0.67 again

**Comment by poco0317** [comment]
Do a clean install.

**Comment by WinterIsPretty** [comment]
Idk it probably got updated but when I downloaded the install file it said 0.67 in the name too

**Comment by poco0317** [comment]
https://github.com/etternagame/etterna/releases/tag/v0.68.0

**Comment by WinterIsPretty** [comment]
You're nicer than peppy when I report an overlook lol, which is my only impression of bug reporting... just an observation

Thanks for helping me I'll make sure to only report for the latest version

**Comment by WinterIsPretty** [comment]
it says 0.68 in the etterna website but you can only download 0.67

**Comment by poco0317** [comment]
Not a game issue.

**Comment by foxfire667** [comment]
The site download link isn't tied to github, it probably just hasn't been manually changed yet. I will post about it on the EO discord.
