### ISSUE TITLE
Customize gameplay applies to ScreenGameplaySyncMachine

### ISSUE THREAD

**Issue by Jolomann** [etternagame/etterna#709]
**Describe the bug**
Leaving customize gameplay on in player options makes it apply to the screen for calibrating audio sync as well. It counts as a gameplay screen which I believe is why customize gameplay shows up. Though I'm not sure if this is intended for the sync screen

**To Reproduce**
1. Go to player options
2. Enable customize gameplay
3. Go to options -> input options -> calibrate audio sync
4. Customize gameplay visuals appear and are functional

**Expected behavior**
Customize gameplay is meant to be used in gameplay. If a user goes to the offset wizard, I doubt they'd be customizing their gameplay elements. If they enter the screen with customize gameplay, they have to go all the way back to player options, turn it off, and then go back to the offset wizard again. Bit of an edge case but still annoying

**Screenshots**
![Customize gameplay in sync wizard](https://cdn.discordapp.com/attachments/389194939881488385/679750465394966569/2020-02-19_190404.png)

**Comment by poco0317** [comment]
87216ffd1b812b910bd172e8a37af9f422a244a5 in #704
