### ISSUE TITLE
Fullscreen causes monitor error to appear.

### ISSUE THREAD

**Issue by SalterDog** [etternagame/etterna#711]
Changing to fullscreen causes my monitor to display: "Incorrect cable. Please use the dual link DVI cable that came with your monitor."
Alt+Enter or changing in Graphics/Sound options yields the same result.
I've tested with other games such as League of Legends, Osu, and Monster Hunter World. Those games run as expected in fullscreen.
Windows 10 64bit.
v.0.68.1
![etternaerror](https://user-images.githubusercontent.com/61293654/74976899-a5afa280-53f7-11ea-9296-8a992a8a6a9f.png)
Poor quality image but you get the point. Message pops up over the fullscreen game.

**Comment by poco0317** [comment]
In the graphics settings, pick a resolution that is the same size as your monitor when using fullscreen, as this will reduce issues with toggling fullscreen itself.

You may also try changing renderers: `/Save/Preferences.ini` -> `VideoRenderers=` and swap the choices

Alternatively, use borderless fullscreen and pick your fullscreen resolution. You may notice typical windowed input lag when doing this, however.

**Comment by SalterDog** [comment]
Changing res to monitor size works great, thanks a lot for the help. 👍
