### ISSUE TITLE
Crashes right after launching the game

### ISSUE THREAD

**Issue by Kkweco** [etternagame/etterna#715]
**Describe the bug**
after launching the game, this image pops up:
![image](https://user-images.githubusercontent.com/61855904/76042498-3eb5f000-5f98-11ea-8c65-e340dd363f4d.png)
briefly followed by this message:
![crash](https://user-images.githubusercontent.com/61855904/76042514-4c6b7580-5f98-11ea-9329-83c5e73759e7.png)

**To Reproduce**
launch the game

**Expected behavior**
not crash and start the game

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.68.1, i think
 - 64bit

**Additional context**

Crash report:

Etterna0.68.1 crash report (build )
--------------------------------------

Crash reason: Access Violation

Thread: Main thread
        IniFile.cpp:22 Reading 'Themes/_fallback/metrics.ini'
        IniFile.cpp:22 Reading 'Themes/_fallback/Languages/en.ini'
        IniFile.cpp:22 Reading 'Themes/_fallback/Languages/ko.ini'
        IniFile.cpp:22 Reading 'Themes/_fallback/ThemeInfo.ini'
        IniFile.cpp:22 Reading 'Themes/Til Death/ThemeInfo.ini'
debug resource file 'C:\Users\kevin\Desktop\게임\Etterna\Program\Etterna.vdi': CreateFile failed (지정된 파일을 찾을 수 없습니다.).

Static log:
Etterna0.68.1
(build )
Log starting 2020-03-06 10:52:49
	Verbosity: 1
Windows 6.2 (Win8) build 9200 []
WARNING: Selected theme '_fallback' not found.  Trying Theme preference default value '_fallback'.
WARNING: Theme preference defaults to '_fallback', which cannot be used.  Trying DefaultTheme preference 'Til Death'.

Partial log:
00:00.010: Reading 'Data/Static.ini' failed: No such file or directory
00:00.392: Windows 6.2 (Win8) build 9200 []
00:00.482: Reading 'Data/Static.ini' failed: No such file or directory
00:00.484: WARNING: Selected theme '_fallback' not found.  Trying Theme preference default value '_fallback'.
00:00.484: WARNING: Theme preference defaults to '_fallback', which cannot be used.  Trying DefaultTheme preference 'Til Death'.
00:00.487: Reading 'Themes/Til Death/Languages/ko.ini' failed: No such file or directory
00:00.492: Reading 'Themes/_fallback/Languages/ko.ini' failed: No such file or directory
00:00.510: Reading 'Themes/_fallback/ThemeInfo.ini' failed: No such file or directory
00:00.518: Reading 'Themes/Til Death/ThemeInfo.ini' failed: No such file or directory
00:00.616: Error reading cache db: unable to open database file

-- End of report

Log:

00:00.009: Etterna0.68.1
00:00.009: (build )
00:00.009: Log starting 2020-03-06 10:52:49
00:00.009: 	Verbosity: 1
00:00.009:  
00:00.009: Reading 'Data/Defaults.ini' failed: No such file or directory
00:00.010: Reading 'Data/Static.ini' failed: No such file or directory
00:00.392: Windows 6.2 (Win8) build 9200 []
00:00.482: Reading 'Data/Static.ini' failed: No such file or directory
/////////////////////////////////////////
00:00.484: WARNING: Selected theme '_fallback' not found.  Trying Theme preference default value '_fallback'.
/////////////////////////////////////////
/////////////////////////////////////////
00:00.484: WARNING: Theme preference defaults to '_fallback', which cannot be used.  Trying DefaultTheme preference 'Til Death'.
/////////////////////////////////////////

**Comment by poco0317** [comment]
All signs point to your themes folder being messed up or not opening the game as admin while it is installed in a weird location.

**Comment by Kkweco** [comment]
Thanks, I didn't know installing it on a different place would affect the program. It works after moving the files to the correct place.
