### ISSUE TITLE
Expose curwifescore and maxwifescore to JudgmentMessageCommand and PlayerStageStats.

### ISSUE THREAD

**Issue by ca25nada** [etternagame/etterna#72]
Just as reference:
- `curwifescore`  Current (raw value, not percentage) wife score at a given time.
- `maxwifescore`  Maximum possible wife score at a given time.
- `totalwifescore`  Maximum possible wife score for the entire file.

Currently the WifePercent,Diffrential, etc. are calculated from `curwifescore` and `maxwifescore` on the C++ side for performance reasons and those are sent as a parameters to `JudgmentMessageCommand` for displaying stuff like ghostscore and avgscore, etc during gameplay. 

But this prevents implementing some features theme side that requires the original `curwifescore` and `maxwifescore` values during gameplay. So they should be included in the parameter table as well.

Similarly, only `fWifeScore` (which is basically `curwifescore/maxwifescore`) is exposed to `PlayerStageStats` and `HighScores`. both `curwifescore` and `maxwifescore` should be available in `PlayeStageStats` and the *final* `curwifescore` value should also be saved to `Highscores`.

**Comment by MinaciousGrace** [comment]
done 77852c3a946dc91e5f0cf12a9f8e5805344d9869
done cd4fbed84fad52f724cf4cee4255fea49cf7d41e
and done 880275fff6add1ab355c5fea3739920cdef1327b
