### ISSUE TITLE
Default Failtype OptionRow crashes when entering Advanced Options

### ISSUE THREAD

**Issue by vlsaurus1** [etternagame/etterna#720]
**Describe the bug**
When I try to access the "Advanced Options" in the "Options" Menu, the game crashes.

**To Reproduce**
1. Go to 'Main Menu'
2. Click on 'Options'
3. Scroll down to 'Advanced Options'

**Expected behavior**
When I click on "Advanced Options," it's supposed to go to that menu.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Etterna 0.68.1
 - 64bit

**Additional context**
Crash Info:

`Etterna0.68.1 crash report (build )
--------------------------------------

Crash reason: 2/2

Thread: Main thread
        FontManager.cpp:67 FontManager::UnloadFont(/Themes/Til Death/Fonts/_bokutachinogothic2bold 24px.ini).
        FontManager.cpp:67 FontManager::UnloadFont(/Themes/Til Death/Fonts/_bokutachinogothic2bold 24px.ini).
        FontManager.cpp:67 FontManager::UnloadFont(/Themes/Til Death/Fonts/_bokutachinogothic2bold 24px.ini).
        FontManager.cpp:67 FontManager::UnloadFont(/Themes/Til Death/Fonts/_bokutachinogothic2bold 24px.ini).
        OptionRowHandler.cpp:107 2/2
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:235 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:235 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:235 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:235 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:235 Processing the sound while buffers are available.
Thread: Mixer thread
Thread: Music thread
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:884 
        InputHandler_DirectInput.cpp:860 
        InputHandler_DirectInput.cpp:878 
        InputHandler_DirectInput.cpp:884 
        InputHandler_DirectInput.cpp:860 
debug resource file 'C:\Games\Etterna\Program\Etterna.vdi': header doesn't match.

Static log:
Etterna0.68.1
(build )
Log starting 2020-03-23 21:01:54
	Verbosity: 1
Windows 6.2 (Win8) build 9200 []
WARNING: Main title or music file for '/Songs/Community Keyboard Megapack - Volume 4/(GLoVE) Eternal Nocturne/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
Attempting to connect to: multi.etternaonline.com, Port: 8765
Server Version: 0 
Video renderers: 'd3d, opengl'
WARNING: RageDisplay_D3D::TryVideoMode( 0, 1920, 1080, 32, 70, 1 )
D3D Fullscreen 1920x1080 32 color 32 texture 70Hz Vsync SmoothLines
WARNING: Font import recursion detected
WARNING: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: /Themes/_fallback/Fonts/Common default.ini
WARNING: /Themes/Til Death/Fonts/_16px fonts.ini
WARNING: Current font: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: Font /Themes/Til Death/Fonts/_16px fonts.ini has no characters
Players joined: P1
Top Screen: ScreenOptionsAdvanced
Current renderer: Direct3D

Partial log:
00:08.935: Missing download link in packlist element: {"type":"pack","id":"85243","attributes":{"name":"High-speed Happiness Vol.3","average":8.0998,"download":"","mirror":"","size":0}}
00:08.935: Missing download link in packlist element: {"type":"pack","id":"85232","attributes":{"name":"Highflyer's Overstepped Nonsense","average":13.5127,"download":"","mirror":"","size":0}}
00:08.935: Missing download link in packlist element: {"type":"pack","id":"63067","attributes":{"name":"Kirby 64 - The Crystal STREAMS","average":15.0383,"download":"","mirror":"","size":0}}
00:08.937: Missing download link in packlist element: {"type":"pack","id":"85228","attributes":{"name":"Notice Me Benpai","average":7.4608,"download":"","mirror":"","size":0}}
00:08.937: Missing download link in packlist element: {"type":"pack","id":"84878","attributes":{"name":"Notice Me Benpai 2","average":6.86515,"download":"","mirror":"","size":0}}
00:08.937: Missing download link in packlist element: {"type":"pack","id":"84910","attributes":{"name":"RAR's Compressed Pack 3","average":24.0463,"download":"","mirror":"","size":0}}
00:08.937: Missing download link in packlist element: {"type":"pack","id":"85068","attributes":{"name":"The Really Shitty gold stinger Pack that NO ONE will ProbAblY play V9","average":19.3776,"download":"","mirror":"","size":0}}
00:14.960: ScreenOptions::InitMenu()
00:17.583: ScreenOptions::~ScreenOptions()
00:17.610: ScreenOptions::InitMenu()

-- End of report`

Also I have no programming experience whatsoever, I just came here to report the issue. Let me know if I am missing anything.

**Comment by poco0317** [comment]
Can you provide a copy of your `/Save/Preferences.ini` and the `/Themes/_fallback/metrics.ini` ?

**Comment by vlsaurus1** [comment]
[Files.zip](https://github.com/etternagame/etterna/files/4372626/Files.zip)
Here you go!

**Comment by poco0317** [comment]
It seems to be failing when loading the default failtype row. As a temporary fix, you can find `[ScreenOptionsAdvanced]` in `/Themes/_fallback/metrics.ini` and then change the `LineNames=` line to this:
`LineNames="3,4,SI,SM,HN,11,SSR,14,30,OsuLifts,ReplayMods,PR"`
Alternatively you can find the default failtype in your preferences and reset it.

A better fix will be done sooner or later.

**Comment by vlsaurus1** [comment]
Thank you! This fixed the issue.

**Comment by poco0317** [comment]
0742f62b0a378b51285d8d825ac9c006428eecd7
