### ISSUE TITLE
[Feature Request] Invalidating scores ingame 

### ISSUE THREAD

**Issue by droptable0133** [etternagame/etterna#722]
I guess we need ingame feature of validating / invalidating for arbitrary scores easily, other than right clicking in 'profiles' tab.

**Comment by Raze009SM** [comment]
I think making an in-game bind for it like Ctrl-i would be a good key combo for invalidating scores on the song wheel, but there should be an option to invalidate from the local scores section on the scores tab. But that's just my preference and I don't expect that to be added into the next version of Etterna.

**Comment by poco0317** [comment]
ad11e2b9b56a3c5421c5b8dd35350877ab4aa459 allows for invalidating via the recent scores tab if its worth anything so far

**Comment by poco0317** [comment]
775c39c82b1e69e10a9a5a49f40f0475f082df1a
