### ISSUE TITLE
CB Highlight doesn't respect perspective changes

### ISSUE THREAD

**Issue by Kangaroux** [etternagame/etterna#723]
Perspective is set to distant but the CB highlight shows up as of I was using overhead

![image](https://user-images.githubusercontent.com/2302541/77836047-16e62200-7129-11ea-8ee1-b6771b756e8f.png)

**Comment by poco0317** [comment]
I believe the solution to this is to attach the highlights to the notefield board actor instead of just existing on the screen like the cover. Haven't tried it. Spawncamping-wallhack does that but of course I haven't checked to see if it fixes it.

**Comment by poco0317** [comment]
a5906053fbd17d7e3cd3c1aafc20f35fe2275f4b
