### ISSUE TITLE
Game drops to 35 fps during gameplay

### ISSUE THREAD

**Issue by vlsaurus1** [etternagame/etterna#724]
The game drops to around 30-35 fps during gameplay. I have my monitor set to 70hz and vsync set to 70. The song select menu runs at a straight 70 fps (as expected), but during gameplay, there is a significant frame drop. This doesn't happen every time I open the game, but it's sort of an on/off kind of thing. I have played the game at 70 fps before, so I know it's not a hardware issue. I've also tried turning off vsync. Turning of vsync makes it smooth_er_, however the fps varies, making it a bit janky. I'm thinking it might be a memory leak of some sort (idk). I attached a screenshot of my monitor resolution/refresh rate for a bit of context. This is Etterna 0.68.1 running on Windows 10 64-bit. 

![image](https://user-images.githubusercontent.com/62578321/77857088-86abe980-71c9-11ea-947f-837b22f3d234.png)

Thank you!

**Comment by poco0317** [comment]
No memory leak.
What framerate does the game normally run at in gameplay with vsync off?

**Comment by vlsaurus1** [comment]
With vsync off, it hangs around the 57-58 fps at 70 hz during gameplay

**Comment by vlsaurus1** [comment]
also just as a note the game runs fine at 60hz with vsync

**Comment by nico-abram** [comment]
Am I misunderstanding something or is that not just kinda how vsync is supposed to work? You might want to tweak your game settings until you can reach a stable 100+ fps without vsync (I'm not really sure which options would help the most but I think a smaller resolution, a dark background image, and a chart without many notes, may make a good test case) and then try it again

**Comment by vlsaurus1** [comment]
I'm providing a video to put this issue into context. https://youtu.be/7YqkIP3_5Qs

**Comment by poco0317** [comment]
What kind of framerate do you get with vsync off, default refresh rate?

**Comment by vlsaurus1** [comment]
Update: I turned off BG's in the song select and turned bg brightness down to zero and that seemed to fix the issue. I can run at 70fps with vsync and about 172 fps without vsync. Thanks for the suggestion
