### ISSUE TITLE
Error message when entering Advanced Input Options

### ISSUE THREAD

**Issue by Wanny** [etternagame/etterna#725]
**Describe the bug**
When entering Advanced Input Options, the following message appears if playing in windowed mode:

![image](https://user-images.githubusercontent.com/569307/77873052-33fd1c80-721f-11ea-9ac8-833c9a1de140.png)
(My Windows is in Spanish, bear with me)

The source of the problem is an overlook in the _fallback theme metrics:
```
[ScreenOptionsInput]
Fallback="ScreenOptionsServiceChild"
NextScreen="ScreenOptionsService"
PrevScreen="ScreenOptionsService"
LineNames="1,2,3,AH,4,5,6,7,8"
Line1="conf,AutoMapOnJoyChange"
Line2="conf,OnlyDedicatedMenuButtons"
Line3="conf,DelayedBack"
LineAH="conf,AllowHoldForOptions"
Line5="conf,ThreeKeyNavigation"
Line6="conf,MusicWheelSwitchSpeed"
Line7="conf,InputDebounceTime"
Line8="conf,AxisFix"
```
There's a 4 in LineNames but there's no Line4 defined afterwards.

**Comment by poco0317** [comment]
Removed the line when cleaning arcade references, didn't test, and didn't remove the reference to the reference.
Fix: remove the `4`

**Comment by poco0317** [comment]
74da12993c19be8ea448d65ee26b3dbf210c0058
