### ISSUE TITLE
Files starting with notes next to receptors

### ISSUE THREAD

**Issue by tatost** [etternagame/etterna#726]
https://www.reddit.com/r/Etterna/comments/fn7uok/abrupt_file_start/
Issue is shown on the reddit post above. This occurs on all files for me, and doesn't seem to be affected by scroll / receptor size (which for some reason changes the height at which the notes normally come from, but that isn't much of an issue).

**Comment by poco0317** [comment]
I need your `/Save/Preferences.ini` and the `/Save/LocalProfiles/00000000/Til Death_settings/playerConfig.lua`

I recommend logging out ingame before sending the player config.

**Comment by tatost** [comment]
https://drive.google.com/drive/folders/12CGAI71XB-JEqLFztAj8kxuR2Svhl0xw?usp=sharing

**Comment by poco0317** [comment]
This is intended behavior.
In `/Themes/_fallback/metrics.ini` find the section labelled `[Player]` and then find `DrawDistanceBeforeTargetsPixels=`
Set this to a larger number. SCREEN_HEIGHT is usually a consistent 480 or whatever is defined at the top of the file in `[Common]`. You can change it to something such as `SCREEN_HEIGHT * 2`
Changing this to an extremely large number will dramatically drop your framerate to a likely unplayable state.

**Comment by nico-abram** [comment]
@tatost were you able to solve your issue with poco's feedback?
