### ISSUE TITLE
Merge headless branch into develop

### ISSUE THREAD

**Issue by nico-abram** [etternagame/etterna#727]
It doesn't have to be a merge, you can make a commit from scratch if you want. Changes are here: https://github.com/etternagame/etterna/commit/a0dfc5d13187fbc741de08db79785451bbcb676a

It is probably untested with d3d/directx, the only changes that matter seem to be in Stepmania.cpp, NetworkSyncManager.cpp and RageDisplayOGL.cpp (I think the others are just formatting or debugging)

If I recall correctly, the point of the change is that when building the notedatacache (Via a command line parameter) the game doesn't need a window and can run headless (Enabling it to run without a graphical desktop environment or whatever, "headless"). It's only really been needed on a linux system, but it would probably be good to have it also work on windows. That being said, odds are  a pull request for it would be merged even if it only works on linux (Assuming it doesnt break anything related to the normal behaviour when that switch is not passed)

**Comment by poco0317** [comment]
tested on windows
may cause oddities in graphics preferences, indicates a need for better sanitizing or automatic detection of those parameters (game instant crashes because of "0 bit color depth not supported")
3538d16d4024323721fc4308983a4ac2c7631405
