### ISSUE TITLE
Skillset list in ScreenSelectMusic is seemingly aligned to the bottom sometimes

### ISSUE THREAD

**Issue by kangalioo** [etternagame/etterna#729]
**Describe the bug**
In ScreenSelectMusic in the General tab, there is this text box containing the major skillsets:
<img src="https://user-images.githubusercontent.com/21220820/79138293-94aa5e80-7db4-11ea-8e6c-784704ab21b6.png" width="100">

Those skillsets are supposed to be aligned to the top. However, in some cases they're seemingly aligned to the bottom instead:
<img src="https://user-images.githubusercontent.com/21220820/79138819-742ed400-7db5-11ea-9a60-fc4295c9abc6.png" width="100">

After digging around for a while, I found out the core issue lies in src/Etterna/Models/StepsAndStyles/Steps.cpp, more precisely [GetRelevantSkillsetsByMSDRank](https://github.com/etternagame/etterna/blob/ad135f144aff93b7979e68200574f0c7a1b6cbc2/src/Etterna/Models/StepsAndStyles/Steps.cpp#L832-L859) and [SortSkillsetsAtRate](https://github.com/etternagame/etterna/blob/ad135f144aff93b7979e68200574f0c7a1b6cbc2/src/Etterna/Models/StepsAndStyles/Steps.cpp#L372-L382).

Citing [what I wrote into the EtternaOnline discord today](https://discordapp.com/channels/339597420239519755/389194939881488385/699259633113628844):
> ah I know where the bug comes from
happens when there are two skillsets with identical values
there is a map, mapping skillset value to skillset identifier
in my example both jumpstream and handstream have the value 20.73
because the value is the map key, SortSkillsetsAtRate tries to insert both Skill_Jumpstream and Skill_Handstream to the exact same key
leading to one of them being dropped
which causes weird issues [i.e. skillsets at the bottom] later down the road

It turns out the skillsets aren't actually "at the bottom" at all. Instead, there really are three skillsets, but the top one is not displayed. That's due to the fact that `GetRelevantSkillsetsByMSDRank` falsely returns skillset is `Skillset_Invalid` instead of the actual skillset (which is in turn a consequence of what I wrote above).

I guess the issue and its consequence is pretty clear to people who have a bit more experience with C++ than I have. If not, I can try to explain in more detail where the issue comes from and how it links to the ScreenSelectMusic skillset list display bug.

**To Reproduce**
1. Download [this zipped chart](https://github.com/etternagame/etterna/files/4470418/Break.My.Heart.zip)
2. Navigate to that chart in ScreenSelectMusic
3. Observe on the left side "_\<blank\>_  Technical  Stream"

**Expected behavior**
I expect the skillsets to be aligned to the top always

**Desktop (please complete the following information):**
 - OS: Linux 64bit
 - Etterna 0.69 76d77af1a7

**Comment by MinaciousGrace** [comment]
yeah this should really use proper comparators instead of the stupid hackjob i did because i didn't want to spend time learning them

but uhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh i dont feel like doing this now or probably any time within the next 6 months

**Comment by MinaciousGrace** [comment]
e75be89e9db973f5a7d8cf356d28a37795ef2eee
