### ISSUE TITLE
Notes parameter still sent as if it's a chord even when CC is off during JudgementMessageCommand

### ISSUE THREAD

**Issue by ca25nada** [etternagame/etterna#73]
The Notes parameter contains a table where the indices correspond to the to the columns ingame. It can either be nil (no notes) or contain a TapNote object corresponding to the note (which I'll just display as a string for the following examples for simplicity).

So as an example we have a chord like this.
```←↓ →```

Back when CC was the norm in SM, since there is only 1 `JudgmentMessageCommand` for the entire chord, There should be a single `JudgmentMessageCommand` containing the following as its `Notes` parameter: 

```lua
{'TapNoteType_Tap', 'TapNoteType_Tap', nil, 'TapNoteType_Tap'}
```

Now that CC is disabled by default, there *should* be 3 `JudgmentMessageCommands` each with 1 note in the `Notes` parameter like the following.

```lua
{'TapNoteType_Tap', nil, nil, nil}
{nil, 'TapNoteType_Tap', nil, nil}
{nil, nil, nil,'TapNoteType_Tap'}
```

But currently, what happens now with CC is off is: the 3 `JudgmentMessageCommands` gets sent for each note, but the `Notes` parameter still contains all three notes as if they were a chord.

```lua
{'TapNoteType_Tap', 'TapNoteType_Tap', nil, 'TapNoteType_Tap'}
{'TapNoteType_Tap', 'TapNoteType_Tap', nil, 'TapNoteType_Tap'}
{'TapNoteType_Tap', 'TapNoteType_Tap', nil, 'TapNoteType_Tap'}
```

**Comment by Nickito12** [comment]
Im almost sure https://github.com/etternagame/etterna/pull/109 fixes this
