### ISSUE TITLE
Loading certain BMS files crash Etterna on startup

### ISSUE THREAD

**Issue by GreatAtomLabs** [etternagame/etterna#739]
Using the starter pack from GENOSIDE 2018 (https://nekokan.dyndns.info/~lobsak/genocide/grade.html), certain charts do not load properly. In particular, if you try to load GENOSIDE 2018 in a pack, "[ikaruga_nex]we are the" will prevent Etterna from loading. Removing "[ikaruga_nex]we are the" will have all of the files properly loaded. 

This issue becomes bigger when trying to load extremely large packs like the entire Insane BMS torrent. 

[crashinfo.txt](https://github.com/etternagame/etterna/files/4498084/crashinfo.txt)

**Comment by poco0317** [comment]
related #599

**Comment by poco0317** [comment]
The reason for this crash is a failed Assertion (hold length is 0). Honestly, I'd blame the charter.
We might be able to come up with a solution but it isn't a good thing to do probably.

**Comment by poco0317** [comment]
fixed e9970e3d6e60afa72d17170b7ee23bcdc1d22284
