### ISSUE TITLE
Get msvc to build with clang-sanitizer

### ISSUE THREAD

**Issue by nico-abram** [etternagame/etterna#742]
VS has experimental support for clang sanitizer, it'd be nice to be able to use it. I think the biggest problem is the /MT flag, and in order to change that I think we might need to either add a new set of binaries for all the libraries that we store binary objects and dlls for, or, what would be nicer, make them all compile from source so we can easily change those settings.

I think the only libs that currently have such binaries are:
 - libcurl
 - ffmpeg
 - MinaCalc

**Comment by jameskr97** [comment]
So currently, everything you listed there builds from source. AFAIK, there aren't anymore binaries in use in the codebase.

I wouldn't mind adding this, but it's only available in x86 right now. Maybe waiting until it's no longer experimental would be better?

**Comment by nico-abram** [comment]
MSVC support for ASan is no longer experimental, and just compiling with `/fsanitize=address /Zi` seems to work now. Closing this
