### ISSUE TITLE
Random Lock-ups in Config Keybinds menu

### ISSUE THREAD

**Issue by Raze009SM** [etternagame/etterna#748]
So I went into the keybind config menu to change my keybinds for a certain chart that I was going to play since I feel more comfortable on a certain keyset for said chart. And upon editing my keybinds, the game randomly locks up on me and did not crash out after waiting for the game to crash. I kill the game with task manager and restart, and upon restarting the game and going into the keybind config menu, the game locks up again in the same way as before. After killing it again with task manager I went as fast as possible to change the keybinds before the game would lock up.
https://www.twitch.tv/videos/598566387 The video linked showcases the issue that happened on my stream just recently.
This happened on Windows 10 on Etterna version 0.68.1. And I am currently on the latest version of Windows 10.

**Comment by poco0317** [comment]
attempt to reproduce on the latest version and with the default theme

**Comment by poco0317** [comment]
no response
