### ISSUE TITLE
Game crash on startup, error 'No NoteSkins found'

### ISSUE THREAD

**Issue by Jedgji** [etternagame/etterna#750]
I've seen this issue a lot on mac-os specific computers but have yet to see it on any windows os. I'm running windows 10 and have just downloaded the game.

**Comment by poco0317** [comment]
Open the game from the directory it is installed and dont move the program out of the program folder.

**Comment by Jedgji** [comment]
I am. I didn't install it into the C:/Etterna directory, however, and instead installed in into a folder in my downloads. Should i reinstall?

**Comment by poco0317** [comment]
You need to install it in a location you have permission and run the game from that location every time. Verify that the exe you are running is precisely the one that points to the Program folder within your Etterna install.

**Comment by prokube** [comment]
Hey, so I'm getting this on an ACTUAL mac? What do i do lol

**Comment by bluebandit21** [comment]
Mind moving over to the Discord for support? 
http://discord.gg/etternaonline

This is a very common problem with known solutions :)
