### ISSUE TITLE
0.68.1 Client & Connectivity Issues

### ISSUE THREAD

**Issue by truenoh** [etternagame/etterna#752]
I play on x64bit Windows 10.

There isn't really a pattern to the issues I've experienced. Ever since I downloaded 0.68.1 (I've tried reinstalling it and nothing new happened), this is what has occurred from time to time:
1. Random crashing. 
[crashinfo.txt](https://github.com/etternagame/etterna/files/4541473/crashinfo.txt)
2. This issue stopped happening as often, but it used to not sync my new plays with the website very well.
3. Today, I logged on to see "Logged in as trueno (0.00: #0) or something like that. I logged out, and tried signing back in to no avail. The pack downloader also wasn't working at this time. After restarting the client several times (along with a few crashes), I was able to log back in and the pack downloader resumed regular function.

**Comment by MinaciousGrace** [comment]
idk about the crashes but the connectivity is probably due to the fact that that the site has just been down somewhat frequently recently

**Comment by poco0317** [comment]
the crashlog shows that you were in the process of closing the game and no further information is given

try on the current version after the site stops being overloaded with stuff

**Comment by poco0317** [comment]
inactive issue
either user related or site related
