### ISSUE TITLE
"No Play" Results Hiding Scores After Non-Best Plays

### ISSUE THREAD

**Issue by hitonisan** [etternagame/etterna#754]
**Describe the bug**
On the results screen after completing a song, a bar on the right details the player's previous scores on that song, numbered 1, 2, 3, and so on.

Currently, if a player plays a song they've recorded a score for at least once before (and that data is on the machine), plays that song again, and doesn't beat their best score, a "No Play" score will show up in the ranking bar. This can also occur if a replay is watched to completion on any song that has at least two local scores recorded.

This bug causes minimal issues, as the score used to produce the glitch is still recorded properly, and simply pressing the arrow keys to scroll through scores removes the "No Play" score.

Here's an example of me playing a song I've played once before, with me failing to beat my previous best and producing the "No Play" bar:

![2020-05-04_012111](https://user-images.githubusercontent.com/37351790/80940976-d40e0e80-8da6-11ea-9297-22034d908116.png)

Pressing the left and right arrow keys reveals my score on the bar. The "No Play" bar seemingly can't be recovered:

![2020-05-04_012115](https://user-images.githubusercontent.com/37351790/80941013-edaf5600-8da6-11ea-865c-0063c320fbaa.png)

If I then decide to watch a replay of **either** of my scores on the song, a blank result gets produced again:

![2020-05-04_013245](https://user-images.githubusercontent.com/37351790/80941157-454dc180-8da7-11ea-85e0-8208ebe57f25.png)

The replay method can produce multiple blank results depending on how many scores existed. For instance, this is what was produced after watching one of the replays I have on Chronon, for which I have five scores:

![2020-05-04_013545](https://user-images.githubusercontent.com/37351790/80941285-ba20fb80-8da7-11ea-9212-3c802c554dd0.png)

**To Reproduce**

If reproducing by play:
1. Pick any song you already have a local score recorded for.
2. Play that song to completion without setting a new personal best.
3. Observe the score listing on the results screen. Avoiding hitting the arrow keys during this time, as this will correct the bug.

If reproducing by replay:
1. Pick any song you have at least two local scores for. Having more than two will increase the bug's effects.
2. Watch the replay through to completion (i.e. let the replay reach its end and fade out to the results screen; you can just fast forward to the end).
3. Observe the score listing on the result screen. Hitting the arrow keys will still completely end the bug.

**Desktop:**
 - OS: Windows 10
 - Etterna version 0.68.1
 - 64-bit architecture

**Comment by poco0317** [comment]
Fixed immediately after 0.68.1 release by eccd24beb79a66d10a836ebd3d3698188fac6364
Though with this change, the page sometimes initializes wrong. Will have to look into that later as well.
