### ISSUE TITLE
Move external picosha2 library to extern folder

### ISSUE THREAD

**Issue by nico-abram** [etternagame/etterna#757]
The extern folder holds third party libraries. This file https://github.com/etternagame/etterna/blob/develop/src/Etterna/Globals/picosha2.h is a header only library and should be in extern. This will involve making a folder for it in extern, writing the cmake for it (Which as a single header file should be simple) and then changing the #include's to point to the new location (I'm not sure what path we should use, might want to search for an example usage of the library)

**Comment by poco0317** [comment]
#830
