### ISSUE TITLE
Clicking still works during song load

### ISSUE THREAD

**Issue by DDMythical** [etternagame/etterna#76]
Whilst loading a song if you click elsewhere it will pick another song in relevance to where you clicked.

if you do this late enough it will load the wrong file over the wrong song and it's just strange.

This happens on v0.55.1, v0.55 but did not happen on v0.54.1

**Comment by Nickito12** [comment]
Does this still happen on the last experimental version?
@DDMythical

**Comment by DDMythical** [comment]
It doesn't work but I don't have both monitors to test properly

**Comment by Nickito12** [comment]
@DDMythical 
When you say "It doesnt work", do you mean the problem doesnt happen or the game doesnt work and it crashes?

**Comment by TheROPFather** [comment]
Closing due to a lack of response, if the issue isn't actually fixed please open another PR @DDMythical with more information.
