### ISSUE TITLE
Game loads cdtitles for packs

### ISSUE THREAD

**Issue by DDMythical** [etternagame/etterna#77]
if you switch difficulties on a file and then move onto a pack, it will show a cdtitle for the pack.

did not happen on v0.54.1, does happen and is reproducable on v0.55 and v0.55.1

edit: Also reads the MSD for the file over the pack.
https://i.imgur.com/FD5otYB.png

**Comment by Nickito12** [comment]
Fixed by https://github.com/etternagame/etterna/pull/107
