### ISSUE TITLE
Replace tomcrypt with openssl

### ISSUE THREAD

**Issue by nico-abram** [etternagame/etterna#774]
As far as I understand, we're already depending on openssl because libcurl uses it, so we might want to remove the tomcrypt dependency and use openssl instead. I think all we're using it for is sha1, md5, and sha256.

**Comment by poco0317** [comment]
The entirety of CryptManager and CryptHelpers is dependent on libtomcrypt

**Comment by nico-abram** [comment]
When I made this issue I skimmed both of those and all I saw was the stuff I mentioned here (and iirc a random bytes function which had a fallback using std). It's possible I missed something though

**Comment by poco0317** [comment]
done: #872
