### ISSUE TITLE
game crashing when i try to download beatmap from pack downloader 

### ISSUE THREAD

**Issue by positonix** [etternagame/etterna#775]
**Describe the bug**
i tried to download a beatmap pack called "'c**t" (i think). the game crashed immediately.

**To Reproduce**
im not sure exactly what caused this, but im assuming it's the fact that i have over 44k charts. what i did:
1. Go to beatmap downloader
2. Click on download on 'c**t

this happened under different circumstances another time:

1. Go to pack dowloader
2. Download any beatmap, queue 'c**t in the pack
3. Wait for download to finish

again, this might be because i have 44k charts.

**Expected behavior**
either the game crashes as soon as i press download or it crashes after the download is done

 - OS: windows
 - Version 10
 - 64bit

**Comment by poco0317** [comment]
duplicate #762
