### ISSUE TITLE
Music occasionally doesn't play when selecting a new song on song select

### ISSUE THREAD

**Issue by senya0** [etternagame/etterna#776]
**Describe the bug**
When scrolling to a new chart on song select, (can happen when first selecting a new chart from a different pack as well), the background music will not play. 

**To Reproduce**
1. Go to song select
2. Hover over a song
3. Scroll down to another song
4. Background music may not play. Error does not happen every time. 

**Expected behavior**
Background music should always play when selecting a new song.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 10.0, build 18362
 - 64 bit 

**Additional context**
Error happens on 0.69.1 public release, but has happened since 0.67

**Comment by poco0317** [comment]
This is an inconsistent, hard to reproduce issue. It's mostly Lua related but the intention was to try to find a way to move a lot of the logic over to SelectMusic C++ sooner or later. The General tab of Til Death holds most of the logic for Chart Preview, which is the reason the music may or may not play.
Part of this also has to do with framelag in the game itself when switching between songs, the way the songs are switched (by clicking, using the mouse, clicking a song via another tab, searching) and whether or not you are using the calc debug menu.

Largely relevant: https://github.com/etternagame/etterna/blob/7337df6b39e341bc17b9c4f6cac4f33cc7e47f84/Themes/Til%20Death/BGAnimations/ScreenSelectMusic%20decorations/wifeTwirl.lua#L185-L213

**Comment by poco0317** [comment]
This commit, while fixing another issue, should also directly cause this issue to never be possible as well.
0434bf6f50aa0c5a97e24e08f18afb958f16b006
