### ISSUE TITLE
Filters within the dance game mode incorrectly include songs with solo mode charts matching the filter

### ISSUE THREAD

**Issue by bluebandit21** [etternagame/etterna#781]
**Describe the bug**
When filtering songs in the dance game mode, songs which have solo maps which match the search parameters will be included in the results, even if none of the 4key maps of the song  meet them.

**To Reproduce**
1) Find a song which has charts in both solo and dance
"smooooch" from the Dark Chancellors pack is an example of one such song.
2) Select dance as the game mode
3) Apply a filter which applies to a solo chart of the song, but does not match any of the 4key maps for it. 
For the above example, applying the filter of 19-20 stamina will result in the song showing up, despite having no dance charts matching the query.

**Expected behavior**
Filters should only return songs containing charts from the current game mode meeting its parameters.
**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Version: commit dbac6cf47a864dc54d7812eb018b87d4e20a3154 (built from source)
 - 64bit

**Additional context**
Oddly enough, the reverse isn't the case, as filters in the solo game mode only match solo mode charts. 
I would have to assume this is remnant behavior from before solo and 4key were split.

**Comment by poco0317** [comment]
reproduced

**Comment by poco0317** [comment]
#795
