### ISSUE TITLE
Ingame Pack Downloader resets scroll after pack loads

### ISSUE THREAD

**Issue by senya0** [etternagame/etterna#792]
**Describe the bug**
Ingame pack downloader resets the scroll when every pack is finished downloading, making it frustrating to download several smaller packs in succession. 

**To Reproduce**
1. Go to Pack Downloader tab ingame.
2. Begin downloading at least 1 pack. 
3. Scroll off of the first page of packs. 
4. When the selected pack is finished downloading, the game will load the pack, which resets the UI, thus setting the scroll back to the default page. 

**Expected behavior**
After the pack is done downloading, the game should remember which page you had scrolled down to, and load that page specifically. This could also apply to the song select wheel. 

**Desktop:**
 - OS: Windows 10 Pro N, Build 18363
 - 64bit

Etterna 0.69.1 Public Release

**Comment by poco0317** [comment]
Can be reproduced at any given moment by pressing Ctrl+Q

**Comment by poco0317** [comment]
fixed on the musicwheel 2a7c41a8bb7959e50c8b4118de649085f881d4b2
fixed on the pack downloader 5768ab01ffc839e694d19d24c5fec226cebb4b82
