### ISSUE TITLE
Filters only look at the highest MSD chart of a song for each skill type

### ISSUE THREAD

**Issue by bluebandit21** [etternagame/etterna#794]
**Describe the bug**
Filters will not include songs that have matching charts if the matching chart within the song does not contain the highest-rated MSD of the song's charts for the filter's skill type.

**To Reproduce**
1) Find a song with multiple charts. POTATOE from Bursts of a Teitoku is one such song.
2) Apply a filter which matches a chart from the song that is *not* the highest difficulty of the song's charts.
In the above example, applying a filter of "Overall 22-23" should include the song, because it's hard chart matches this query, but does not.

**Expected behavior**
Filters should include songs in the results if any of the song's charts match the filter parameters, not only just the highest-MSD one.

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Version: Commit c258f715876e37759f3987bccbd9ba65c11d12bd (develop branch)
 - 64bit

**Additional context**
This is due to the way filtering is implemented in 
`MusicWheel::FilterBySkillsets(vector<Song*>& inv)`
I'm currently trying to fix this issue.

**Comment by bluebandit21** [comment]
Oh, and I feel I should specify. 
This occurs with Highest-Only off, which I believe is supposed to toggle this behavior.

**Comment by nico-abram** [comment]
I don't know if highest only is about this or about the highest skillset for each chart only

This function seems to handle the MSD search:
https://github.com/etternagame/etterna/blob/423a0fb9cdb85676dd4f76a33f770cef7063d226/src/Etterna/Actor/Menus/MusicWheel.cpp#L719
Specifically the calls to IsSkillsetHighestOfAnySteps I think

@MinaciousGrace do you know if this was intentional? How should this be fixed in your opinion?

**Comment by bluebandit21** [comment]
It only looks at the highest MSD for each skill, within all charts.
`val = inv[i]->GetHighestOfSkillsetAllSteps(ss, currate);` (ss=skill, currate=rate modifier)


The fix I'm currently trying to do is to make filters look through all combinations of every chart and rate, to see if *any at all* match the filter queries. (Which would make sense from a logical standpoint, you're usually using a filter to look for charts matching parameters, not just to look at the highest chart on a song)

IsSkillSetHighestOfAnySteps actually does something different, which is works properly as far as I can tell.

**Comment by bluebandit21** [comment]
Ok, I think I've got a good fix to this. I'll make a PR once my other filter PR gets approved.

**Comment by poco0317** [comment]
#795
