### ISSUE TITLE
Pressing 3 while on online scores tab flashes the local scores tab for a split second

### ISSUE THREAD

**Issue by senya0** [etternagame/etterna#797]
**Describe the bug**
Pressing 3 while looking at online scores shows the local scores tab for a brief moment, notably flashing the difficulty indicator on screen. This doesn't seem to load the entire local scores tab, but only the background and difficulty indicator. 

**To Reproduce**
1. Go to Scores tab on song select, specifically online scores. Bug appears on unranked and ranked charts. 
2. Press 3. Holding down 3 makes the local page flash onscreen repeatedly.

**Expected behavior**
Pressing 3 here should either do nothing, or return the user to the local scores tab, not both. 

0.69.1 public release

**Comment by poco0317** [comment]
fixed 315db149e346880216114cf4f4cbd5d4cade0ac8
