### ISSUE TITLE
No long note graphics on Linux build

### ISSUE THREAD

**Issue by TheROPFather** [etternagame/etterna#8]
After compiling when playing any chart the long note graphics do not appear. The long note can still be hit however by simply knowing where a long note is and holding, there is no tail to the graphic though making it impossible to know what notes should be long notes. 

**Operating System:** Ubuntu 16.04
**Compiler Version:** g++ 5.4.0 
**OpenGL Version:** 3.0 Mesa 12.0.6
**OpenGL Renderer:** Gallium 0.4 on SVGA3D; build; RELEASE; LLVM;
**Runtime Library:** glibc 2.23

Gist of command line output[ available here](https://gist.github.com/TheROPFather/737923ae61b176c934fa06b19d61f7b8) (Includes a few errors with GTK)

**Comment by xwidghet** [comment]
Occurs on windows as well when using the OpenGL renderer. I'll get this fixed soon.

**Comment by xwidghet** [comment]
Fixed as of commit 51bcae372ecedfc698b651a8dd2667b781683546.
