### ISSUE TITLE
Broken Timing Window

### ISSUE THREAD

**Issue by JKGAMER1337** [etternagame/etterna#802]
**Describe the bug**
When I change the Aspect Ratio after I play the song the timing window is broken and failed.

**To Reproduce**
1. Change any Aspect Ratio
2. Play any songs
3. Try it

**Desktop**
 - Windows 8
 - Version 0.69.1
 - 32bit

**Comment by poco0317** [comment]
I'll admit I don't know what this means. Can you provide diagrams or a video? More explanation?
