### ISSUE TITLE
Etterna crash MacOS Catalina

### ISSUE THREAD

**Issue by h3xccp** [etternagame/etterna#803]
Process:               Etterna [5755]
Path:                  /Users/USER/Downloads/*/Etterna.app/Contents/MacOS/Etterna
Identifier:            ???
Version:               ??? (???)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Etterna [5755]
User ID:               501

Date/Time:             2020-06-07 21:33:09.914 -0400
OS Version:            Mac OS X 10.15.5 (19F101)
Report Version:        12
Anonymous UUID:        AD9752D2-DF93-2308-0420-1FCF1C507846

Sleep/Wake UUID:       9FA94377-1653-471D-9C28-E7062344E22A

Time Awake Since Boot: 37000 seconds
Time Since Wake:       1400 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
  Referenced from: /Users/USER/Downloads/*/Etterna.app/Contents/MacOS/Etterna
  Reason: image not found

Binary Images:
       0x10b0c4000 -        0x10c313fe7 + (??? - ???) <448068A8-3727-3780-AB4E-4C8473675DD6> /Users/USER/Downloads/*/Etterna.app/Contents/MacOS/Etterna
       0x11c089000 -        0x11c11aeff  dyld (750.5) <E4698FBD-806A-3396-B279-E685BA37430B> /usr/lib/dyld
    0x7fff2fd7b000 -     0x7fff2fd7bfff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <E51DCB3C-CF4F-320B-AC86-D445E30C0891> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff3051b000 -     0x7fff3051bfff  com.apple.Carbon (160 - 162) <4F1F60CB-6C1E-3D79-832E-8D606601F282> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff30dee000 -     0x7fff312f7ffb  com.apple.audio.CoreAudio (5.0 - 5.0) <62BEE4B7-8A26-3951-9D78-4E193617AF7A> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff34692000 -     0x7fff34736ff3  com.apple.framework.IOKit (2.0.2 - 1726.121.1) <A0F54725-036F-3279-A46E-C2ABDBFD479B> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff3c417000 -     0x7fff3c426ff7  com.apple.opengl (17.10.22 - 17.10.22) <D5BF32A8-2E0A-345D-80A3-7CA7C2CF748D> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff68bdc000 -     0x7fff68be8fff  libbz2.1.0.dylib (44) <BF40E193-8856-39B7-98F8-7A17B328B1E9> /usr/lib/libbz2.1.0.dylib
    0x7fff6958c000 -     0x7fff695f1ff7  libcurl.4.dylib (118.120.2) <F2C246F3-460E-31A7-B900-2A9560533730> /usr/lib/libcurl.4.dylib
    0x7fff696dc000 -     0x7fff697ccfff  libiconv.2.dylib (59) <F58FED71-6CCA-30E8-9A51-13E9B46E568D> /usr/lib/libiconv.2.dylib

Model: MacBookAir7,2, BootROM 194.0.0.0.0, 2 processors, Dual-Core Intel Core i5, 1,8 GHz, 8 GB, SMC 2.27f2
Graphics: kHW_IntelHDGraphics6000Item, Intel HD Graphics 6000, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x802C, 0x4D5435324C3531324D3332443250462D3130
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x802C, 0x4D5435324C3531324D3332443250462D3130
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1610.1)
Bluetooth: Version 7.0.5f6, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0128G, 121,33 GB
USB Device: USB 3.0 Bus
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Air, Apple Inc., 27.2

**Comment by poco0317** [comment]
Missing openssl/libssl

`brew install openssl`

**Comment by h3xccp** [comment]
thanks, nice!
