### ISSUE TITLE
Lag spikes and stutters when entering Fullscreen mode

### ISSUE THREAD

**Issue by AmeTheDragon** [etternagame/etterna#805]
**Describe the Issue**
Whenever I enter full screen mode in the game in order to use V-Sync to help with ghosting issues, the game suffers random large freezes and stutters, but otherwise runs great. Sometimes these stutters last for whole seconds.

**To Reproduce**
Go to Options
Go to Graphics/Sound Options
Change game mode from Windowed to Fullscreen

**Expected Behavior**
Given the specifications of my PC 
Radeon RX480 8GB Graphics
Intel(R) Core(TM) it-7600 CPU @ 3.50GHz, 3501Mhz, 4 Core(s)
24 GB of installed RAM 

I would expect the game to be able to run completely fine, given I can run AAA titles like Doom 2016 just fine on a mixture of High/Ultra settings without any stutters and consistently remain at at least 100 FPS without similar stutters.

**Screenshots** 
N/A

**Desktop Information**
OS: Microsoft Windows 10 Pro 
Version: 10.0.17763 Build 17763 (Expired License)

**Additional Information**
Using software such as MSI Afterburner showed no spikes in CPU or GPU usage during these spikes, and setting priority of game to High in Task Manager made no difference. I have not checked RAM, but I highly doubt that 24 GB of RAM would have any issues dealing with this game.

**Comment by AmeTheDragon** [comment]
Also, I have uninstalled and reinstalled graphical drivers (for unrelated issues), and this has not affected the issue at all. The issue has been persisting for months, perhaps even a year at this point.

**Comment by MinaciousGrace** [comment]
is this only after moving from windowed to fullscreen during one play session, and not loading into full screen? can you be more specific about the exact operation you are doing

**Comment by nico-abram** [comment]
@AmeTheDragon Is this still a problem?

I'm going to close this for now since you haven't answered Mina's question in ~2 years, feel free to ping me with a comment here if this is still an issue.
