### ISSUE TITLE
Eval page in multi shows all players played the same rate even when they didn

### ISSUE THREAD

**Issue by senya0** [etternagame/etterna#806]
**Describe the bug**
title

**To Reproduce**

1. create a multi lobby and have at least 2 players in it
2. play a song with each player picking a different rate
3. at eval, select the other player(s)'s score 
4. observe that the rate has not changed, and ssr/msd seems to scale with the falsely shown rate

**Expected behavior**
The game should display the actual rate each player plays

0.69.1

**Comment by poco0317** [comment]
fixed at an unknown point during either 0.70 or 0.71 development
