### ISSUE TITLE
occasionally chart preview will not allow you to click to any other part of the song than what is chosen for preview

### ISSUE THREAD

**Issue by senya0** [etternagame/etterna#810]
when viewing chart previewer, attempting to skip to any portion of the song other than either the currently displayed section or the default starting position for the music results in the previewer jumping to wherever the default starting position is. it may be more common on unorthodox/long/asian files

**To Reproduce**
hard to reproduce
1. Go to song select
2. select a song
3. look at preview
4. hope it happens

**Expected behavior**
skipping to a place on chart previewer should let you skip to that place

0.69.1

**Comment by poco0317** [comment]
This happens when chart preview fails to properly execute. Specifically, the action which resets the sample music and replaces it with the full song loop does not run. The cases that cause this are usually not consistent but have consistent reproduceable methods.

**Comment by poco0317** [comment]
Solved this in a neat way allowing for basically seamless chart preview (re)opening that should just kind of always work now.
Actually I couldn't reproduce the issue at all but I'm willing to believe that the changes here fixed it somehow. Look out for the issue popping back up.

43d7d14330cae73adde3f4fbbd8d50180049449c 9bbbe64b7b6b6d328a1994fb65ae5027addb81ce 0434bf6f50aa0c5a97e24e08f18afb958f16b006 373667a53bce24875a8e078f4b43289ff35694a9
