### ISSUE TITLE
game crashes on startup when using nonstandard resolution

### ISSUE THREAD

**Issue by senya0** [etternagame/etterna#812]
**Describe the bug**
title. dont know why it started happening, worked fine just hours before

**To Reproduce**
1. Change resolution to one that isnt contained in Etterna's defaults
2. Attempt to open the game
3. See error

**Expected behavior**
The game should open with no issues

Windows 10 Pro N 64-bit build 18363
Etterna 0.69.1
Monitor set to 1080p@75hz, bug does not happen when set to 60hz

[crashinfo.txt](https://github.com/etternagame/etterna/files/4843580/crashinfo.txt)

**Comment by MinaciousGrace** [comment]
was fixed cba to find commit
![avatar1905489_53](https://user-images.githubusercontent.com/13737743/86893637-ec184c00-c0cf-11ea-99fc-902c25e033e6.jpg)
