### ISSUE TITLE
Solo scores show up in local profile while not in solo mode

### ISSUE THREAD

**Issue by lemonguy94** [etternagame/etterna#819]
**Describe the bug**
My solo scores show up in my local profile when I am not in the solo game mode.  This makes it impossible to look through my local profile for non-solo scores, because solo scores are rated quite a bit higher than 4k scores and they also use every skillset category.  

**To Reproduce**
1. Go to Game Start (in dance mode for 4k)
2. Click on Profile
3. Assuming you have solo scores, they show up in your profile

**Expected behavior**
Local scores should be separated by the game mode chosen; 4k scores normally, and solo scores when in the solo game mode.  

**Screenshots**
https://cdn.discordapp.com/attachments/669257865038397456/729279912573141002/unknown.png

**Desktop (please complete the following information):**
 - Windows 10
 - 0.70.0
 - 64bit

**Comment by poco0317** [comment]
41c5f6f3859e690e5e794457c656bd7ad5068176 8c2f738c024e40ef0274dbbe6f2667b654ae8ec1 df361ea8427c5147250e51974efb142036a56bda
