### ISSUE TITLE
Linux build crashes building song cache, unusable 

### ISSUE THREAD

**Issue by Kangaroux** [etternagame/etterna#820]
While building the song cache, Etterna crashes with the message:

```
ptrace failed: Operation not permitted
ptrace failed: Operation not permitted
ptrace failed: Operation not permitted

Etterna has crashed. Debug information has been output to

    /tmp/crashinfo.txt
```

The crash looks to happen because of loading `Save/Keymaps.ini`, I thought it was because of my save file so I removed the Save folder but the crash still happened.

[crashinfo.txt](https://github.com/etternagame/etterna/files/4875101/crashinfo.txt)

```
$ neofetch --off
jessie@home 
----------- 
OS: Ubuntu 20.04 LTS x86_64 
Kernel: 5.4.0-40-generic 
Uptime: 22 hours, 21 mins 
Packages: 2558 (dpkg), 27 (snap) 
Shell: bash 5.0.16 
Resolution: 2560x1440, 1920x1080 
DE: GNOME 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: LoginIcons [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 7 1800X (16) @ 3.600GHz 
GPU: NVIDIA GeForce GTX 1070 Ti 
Memory: 7522MiB / 32043MiB
```

**Comment by Kangaroux** [comment]
I should note that the Linux build is currently unusable because of this.

**Comment by poco0317** [comment]
Does latest develop give any different result?

**Comment by nico-abram** [comment]
Crash reason:   Unhandled exception: std::bad_alloc

🤔 

Could you try to get a call stack of the crash by debugging @Kangaroux ?

**Comment by Kangaroux** [comment]
I'll try the `develop` branch first.

**Comment by Kangaroux** [comment]
So if I do a fresh build and just launch it as-is it's fine, but as soon as I add in the songs from my old etterna folder it crashes again.

[crashinfo.txt](https://github.com/etternagame/etterna/files/4881663/crashinfo.txt)

**Comment by Kangaroux** [comment]
@nico-abram Can you walk me through how I would do that on Linux? I don't really know the C++ ecosystem

**Comment by nico-abram** [comment]
According to the crashinfo it crashed here https://github.com/etternagame/etterna/blob/develop/src/Etterna/Globals/MinaCalc/Ulbu.h#L380
@MinaciousGrace does that make sense?

Also @Kangaroux are you compiling debug? I don't think that ASSERT should be triggered on release builds, but I could be mistaken
I'm not sure how to debug, I'm not much of a linux person (You can probably either use an IDE like clion or codeblocks or qt creator with a debugger (which iirc are usually front ends to gdb) or use the command line gdb. I could be wrong though)

**Comment by poco0317** [comment]
Build under release.
