### ISSUE TITLE
Right-Clicking Does Not Work With MacOS

### ISSUE THREAD

**Issue by bluebandit21** [etternagame/etterna#829]
Right-clicking filter rate values should lower them.
However, in MacOS right-clicking does not work.

**To Reproduce**
Open the filter tab and right-click a rate value while running Etterna on MacOS.

**Expected behavior**
Filter rate values should decrease.

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Version 70.1 develop (commit 1b941b47c63f0e0e24469d8b98e70b0c2873d856)

**Comment by nico-abram** [comment]
@bluebandit21 do you remember if we've made any progress on this?

**Comment by poco0317** [comment]
superceded by #1260

**Comment by bluebandit21** [comment]
> @bluebandit21 do you remember if we've made any progress on this?

Unfortunately, we haven't to my knowledge 0_0
