### ISSUE TITLE
F4 in practice mode causes bpm changes to revert after live reload

### ISSUE THREAD

**Issue by Ulti-FD** [etternagame/etterna#834]
1. Go into practice mode on a file
2. Change bpm(s) of that file, save
3. Ctrl+shift+r
4. File reverts to previous bpm(s). Info such as bpm text and rating do not change back

Windows 10 64-bit, Etterna .70.1 x64

Examples:
https://cdn.discordapp.com/attachments/395382822837157898/730978018687713391/2020-07-10_04-43-20.mp4
https://cdn.discordapp.com/attachments/395382822837157898/730979630722449448/2020-07-10_04-49-31.mp4

**Comment by poco0317** [comment]
fixed 8ab274bad110cd8bc3f61d7042ea324b7bf75b81
