### ISSUE TITLE
ssc scrolls don't update after live reload in practice mode

### ISSUE THREAD

**Issue by Ulti-FD** [etternagame/etterna#835]
1. Go into practice mode on a file
2. Change ssc scrolls, save file
3. Ctrl+shift+r
4. No visible changes

I have tested practically everything else that I can (excluding ticks/combo cause I'm not 100% certain what those do and label cause that has no ingame effect) and scrolls are the only ssc-specfic data that get affected by this. Delay, warp, time sigs, speeds and fakes all update as they should upon live reload. This is irrespective of the data being diff-specific or applied to the whole file.

Win 10, Etterna 0.70.1 x64

**Comment by poco0317** [comment]
done 6bf2c26912cbed47d214abc703637f546bb98a17
