### ISSUE TITLE
UI Bug when selecting song sort mode

### ISSUE THREAD

**Issue by bluebandit21** [etternagame/etterna#836]
**Describe the bug**
Music wheel sort options are misaligned in the UI.
<img width="1024" alt="Screen Shot 2020-07-10 at 1 01 01 AM" src="https://user-images.githubusercontent.com/32799046/87123161-3d514880-c254-11ea-89a7-7670bcbbe377.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Version 70.1 (develop commit 4fd82c413c3806b562bfea11b917d69f384972fa)

**Additional context**
Via git-bisect, I was able to determine that commit 3b966ebe82f8576f7c2bc0a6e0f6303efed26d2e is the commit which caused this bug.

**Comment by poco0317** [comment]
fa81da68f5780253b4aaa9bb22d352ea9f199c95
