### ISSUE TITLE
F Ranks break the "Top Grades" sort

### ISSUE THREAD

**Issue by hitonisan** [etternagame/etterna#839]
Based on comments in #653 and the titles of some relevant commits, this might either be known or irrelevant, but I'll put this here anyways just in case. Just close this if there's no need for it to exist.

**Describe the bug**
As the title suggests, if you have any F ranks saved on the local machine, the "Top Grades" sort will break around them. Each individual F rank will be given its own sort category, and unranked songs will be split into categories around those. A broken alphabetical sort appears within those unranked categories.

**To Reproduce**
1. If you currently don't have any F ranks saved on your local machine, obtain some. At least 3 should suffice to show the effects.
2. Open the sort menu, and use the "Top Grades" sort.
3. Go to the F rank and ??? sort sections, and open them to see their contents.

**Screenshots**
With several F ranks, here's what a sample "Top Grades" sort looks like:

![2020-07-12_165440](https://user-images.githubusercontent.com/37351790/87257592-c7223100-c461-11ea-86d6-8ff0cfd8b543.png)

Opening a F rank section reveals its contents, as well as the contents of any other F rank sections on the screen:

![2020-07-12_165444](https://user-images.githubusercontent.com/37351790/87257600-dc975b00-c461-11ea-9e8e-b500d20ccdf4.png)

Nearby unranked sections will contain broken alphabetical sorts, sometimes related to the F rank songs:

![2020-07-12_170419](https://user-images.githubusercontent.com/37351790/87257610-f9cc2980-c461-11ea-89ea-1f3b3b589b63.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Etterna version 0.70.1
 - 64-bit architecture

**Comment by poco0317** [comment]
known but needed an issue

**Comment by poco0317** [comment]
337277fa4f8d57519e4ff3aeb5051f93a35dbf62 breaks it less
