### ISSUE TITLE
Japanese locale garbled installer

### ISSUE THREAD

**Issue by Sophia2329** [etternagame/etterna#841]
**Describe the bug**
The Etterna 0.70.1 x64 Windows installer contains garbled text due to bad encoding on a Win10 Japanese locale, presumably due to the underlying installation software. The license is left intact.

**Conditions:** Updating from version 0.70.0, previously installed under English (US) locale.

**Priority:** Low

**Screenshots**:
![etterna_installer_garbled_1](https://user-images.githubusercontent.com/12881223/87329887-0327c580-c538-11ea-91d5-615c30323946.png)
 ![etterna_installer_garbled_2](https://user-images.githubusercontent.com/12881223/87329894-0622b600-c538-11ea-9c27-6f76200228ee.png)

**Comment by MinaciousGrace** [comment]
ZbgAbv!

**Comment by nico-abram** [comment]
@Sophia2329 do you know if this is still an issue with the latest installers?

**Comment by poco0317** [comment]
lack of activity
