### ISSUE TITLE
Game crashes when making a room for online

### ISSUE THREAD

**Issue by galatixa** [etternagame/etterna#844]
I am trying to create a room for online play and it seems when create it it crashes and i get this log. 

Etterna0.70.1 crash report (build )
--------------------------------------

Crash reason: Unhandled Microsoft C++ Exception

Thread: Main thread
        FontManager.cpp:70 FontManager::UnloadFont(/Themes/Til Death/Fonts/_bokutachinogothic2bold 24px.ini).
        FontManager.cpp:70 FontManager::UnloadFont(/Themes/Til Death/Fonts/_bokutachinogothic2bold 24px.ini).
        FontManager.cpp:70 FontManager::UnloadFont(/Themes/Til Death/Fonts/_bokutachinogothic2bold 24px.ini).
        FontManager.cpp:70 FontManager::UnloadFont(/Themes/Til Death/Fonts/_bokutachinogothic2bold 24px.ini).
        RageTextureManager.cpp:168 RageTextureManager::LoadTexture(__blank__).
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:237 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:237 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:237 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:237 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:237 Processing the sound while buffers are available.
Thread: Mixer thread
Thread: Music thread
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:893 
        InputHandler_DirectInput.cpp:868 
        InputHandler_DirectInput.cpp:887 
        InputHandler_DirectInput.cpp:893 
        InputHandler_DirectInput.cpp:868 
debug resource file 'C:\Games\Etterna\Program\Etterna.vdi': CreateFile failed (The system cannot find the file specified.).

Static log:
Etterna0.70.1
(build )
Log starting 2020-07-13 20:07:24
	Verbosity: 1
Windows 6.2 (Win8) build 9200 []
DirectSound sample rates: 100..200000 (continuous)
Software mixing at 44100 hz
WARNING: Main title or music file for '/Songs/92 Solo Files/History of the Moon (Solo)/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
Attempting to connect to: multi.etternaonline.com, Port: 8765
Server Version: 0 
Video renderers: 'd3d, opengl'
WARNING: RageDisplay_D3D::TryVideoMode( 1, 1066, 600, 32, 0, 0 )
D3D Windowed 1066x600 32 color 32 texture 59Hz NoVsync NoSmoothLines
WARNING: Font import recursion detected
WARNING: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: /Themes/_fallback/Fonts/Common default.ini
WARNING: /Themes/Til Death/Fonts/_16px fonts.ini
WARNING: Current font: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: Font /Themes/Til Death/Fonts/_16px fonts.ini has no characters
WARNING: Error playing command:/Themes/Til Death/BGAnimations/_PlayerInfo.lua:147: attempt to call global 'easyInputStringWithFunction' (a nil value)
WARNING: /Themes/Til Death/BGAnimations/_PlayerInfo.lua:147: unknown(self = nil,(*temporary) = nil,(*temporary) =  Choose a profile display name
WARNING: Clicking your name will allow you to change it:,(*temporary) = 64,(*temporary) = nil,(*temporary) = nil,(*temporary) = attempt to call global 'easyInputStringWithFunction' (a nil value))
Players joined: P1
Top Screen: ScreenNetSelectMusic
Current renderer: Direct3D

Partial log:
05:24.337: ScreenOptions::InitMenu()
05:25.483: [ScreenSMOnlineLogin::HandleScreenMessage] GoToNextScreen
05:32.535: ScreenOptions::~ScreenOptions()
05:32.729: RoomWheel::Load('RoomWheel')
05:32.736: WARNING: Error playing command:/Themes/Til Death/BGAnimations/_PlayerInfo.lua:147: attempt to call global 'easyInputStringWithFunction' (a nil value)
05:32.736: WARNING: /Themes/Til Death/BGAnimations/_PlayerInfo.lua:147: unknown(self = nil,(*temporary) = nil,(*temporary) =  Choose a profile display name
05:32.736: WARNING: Clicking your name will allow you to change it:,(*temporary) = 64,(*temporary) = nil,(*temporary) = nil,(*temporary) = attempt to call global 'easyInputStringWithFunction' (a nil value))
05:39.513: PlayMode not set, setting as regular.
05:39.513: MusicWheel sorting took: 339.513977
05:39.523: MusicWheel sorting took: 339.523010

-- End of report

**Comment by poco0317** [comment]
The warnings at the end are interesting but not your fault.
Try to describe the exact steps and reproduce the crash, though.

**Comment by galatixa** [comment]
I had to previously uninstall both step mania 5  and etterna for crashing during launch. Reinstalled both. 
I logged in online and created a room and once im done creating it crashes. im able to play offline but im not able to see the bombs/mines on some songs
