### ISSUE TITLE
The "Reset" button on the filter tab does not actually reset the filter rate

### ISSUE THREAD

**Issue by bluebandit21** [etternagame/etterna#847]
**Describe the bug**
Pushing the Reset button on the filter tab resets the numerical values, but does *not* reset the following:
*Max Rate, Min Rate, Mode, and Highest-Only*

This would be a very minor bug on its own, save for the fact that right-clicking does not work on MacOS within Etterna right now, making it impossible to lower a rate value once increased without restarting the game.

**To Reproduce**
Increase the *Max Rate* or *Min Rate* on the filter tab.
Press the *Reset* button.

**Expected behavior**
All filter values should be reset, or at a minimum, the skillset range values and the rate range values.

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Version 70.2

**Comment by nico-abram** [comment]
I think this is the lua code that handles that button click:
https://github.com/etternagame/etterna/blob/develop/Themes/Til%20Death/BGAnimations/ScreenSelectMusic%20decorations/filters.lua#L458-L472

ResetSSFilters calls into this: https://github.com/etternagame/etterna/blob/57c8961b5f12dacad4015f4b026865d7c7f38d1e/src/Etterna/Singletons/FilterManager.cpp#L51-L59

I'm not very familiar with the filter code so I'm not sure what the exact or best fix is but these links should give some direction to anyone looking to fix this (There seems to be a FILTERMAN:SetMaxFilterRate and SetMinFilterRate, maybe we need to use those to reset them)

**Comment by poco0317** [comment]
f12ce12f2875615d21c3651302f0412cf83cf7ac
