### ISSUE TITLE
Occasionally the game "locks" into sudden mode and has strange behavior

### ISSUE THREAD

**Issue by Kangaroux** [etternagame/etterna#851]
Unfortunately I don't have a repro for this. It happened on Windows in earlier versions and it's happening now on Ubuntu as well. I don't know what causes this but the game seems to get stuck in this weird state.

I use sudden + suddenoffset. 

Here's what happens:

Very rarely when I enter a song the fade-in effect for sudden (where notes gradually fade in when they go past the sudden cover) stops working when I'm also using sudden offset. If I turn off sudden offset, the fade in works, but now the cover is in the wrong spot. If I turn off sudden AND the offset, it still uses the sudden+offset mod visually but doesn't say I'm using it, and I still have the no fade-in issue.

So to summarize,

- With NO sudden+offset OR sudden+offset there is no fade-in.
- With sudden and NO offset there is fade-in.

ADDTIONALLY, the sudden cover is affected by my scroll speed. That is to say, the lower my scroll speed is, the larger the cover is on the screen, and vice versa. This happens regardless if I'm using the offset or not.

Here's C1180:
![image](https://user-images.githubusercontent.com/2302541/87740037-39bb4580-c7af-11ea-9f60-2e643b86dac1.png)

And C400:
![image](https://user-images.githubusercontent.com/2302541/87740059-43dd4400-c7af-11ea-9601-5a5f6d4c2d93.png)

User prefs (as a .txt cause I can't upload .ini):
[Preferences.txt](https://github.com/etternagame/etterna/files/4935314/Preferences.txt)

**Comment by Kangaroux** [comment]
Restarting the game doesn't fix the issue. Neither does reloading metrics or textures.

**Comment by Kangaroux** [comment]
The only line that I've modified in the metrics is 455 to use 140% offset.
[metrics.txt](https://github.com/etternagame/etterna/files/4935319/metrics.txt)

**Comment by poco0317** [comment]
What is the earliest version thought to have had this problem?

**Comment by Kangaroux** [comment]
I really can't say with much certainty because I haven't been using sudden all that long.

**Comment by poco0317** [comment]
Before 0.70.0?

**Comment by Kangaroux** [comment]
Yes. Again, can't say with 100% certainty, but I probably had the issue in .67

**Comment by Kangaroux** [comment]
When was the fade-in introduced? I remember requesting that a while back.

**Comment by poco0317** [comment]
0.66.0 introduced the preference for NoGlow, while it has actually existed since 0.61.0

**Comment by poco0317** [comment]
Is there anything you can do to make the issue stop or reset? Rebooting is not off the table. As well as making a new profile or resetting the save folder.

**Comment by Kangaroux** [comment]
@poco0317 I put my pc to sleep last night and when I started it back up today it was working fine. No more scroll issues and the fade in is working

![image](https://user-images.githubusercontent.com/2302541/87825358-fd3a2900-c844-11ea-98bd-8aab41d51084.png)

**Comment by Kangaroux** [comment]
I actually think it might have something to do with the "I'm Blue" song I was testing it on before. I think the high BPM is causing problems. I always have the issue on that song but never on any other songs.

**Comment by poco0317** [comment]
#846

**Comment by Kangaroux** [comment]
Yep that seems like the same issue. I'll close this then
