### ISSUE TITLE
muFFT Custom Allocator fails to compile in VS2019 on Debug target

### ISSUE THREAD

**Issue by poco0317** [etternagame/etterna#852]
An oddly specific issue.
Means exactly what it says in the title. 

Particularly, it dislikes using the cfloat struct in the MufftAllocator template.
![image](https://user-images.githubusercontent.com/2531164/87745135-bf8cc000-c7b2-11ea-8a01-27d356a32fb2.png)

https://github.com/etternagame/etterna/blob/6f112d05e3db71aa016af1a45415b11206ba7463/src/RageUtil/Sound/RageSound.h#L99-L111

https://github.com/etternagame/etterna/blob/6f112d05e3db71aa016af1a45415b11206ba7463/src/RageUtil/Sound/RageSound.h#L222

**Comment by hexptr** [comment]
I caused this :( I can't really help with fixing it though, sorry. I don't use Windows or VS.

If VS doesn't support custom allocators properly then we can always fall back on using raw pointers and manual allocation/freeing instead of vector.

**Comment by poco0317** [comment]
done: #868
