### ISSUE TITLE
Unify aggregation functions and rename for clarity

### ISSUE THREAD

**Issue by kangalioo** [etternagame/etterna#861]
Currently, there's three copy-pasted versions of the original AggregateSSRs function, all slightly tweaked, each with its own quirks and irregularities. It would be better to have one singular implementation of the algorithm, and call that algorithm in each of the three aggregation functions.

That also makes it easy to refactor the underlying algorithm implementation. In the code below, I already removed the (incredibly confusing) recursion. It might also be worth thinking about replacing the algorithm with a plain binary search.

Regarding the names: `AggregateSSRs`, `AggregateSkillsets` and `AggregateRatings` are pretty opaque names. I suggest renaming them to express _what_ they're supposed to accomplish, not _how_ they're accomplishing it:

```
AggregateSSRs -> CalculatePlayerSkillsetRating
AggregateSkillsets -> CalculateScoreOverall
AggregateRatings -> CalculatePlayerOverall
```
(Of course, these are merely suggestions)

On a side note, I do realize that the copy-pasting happened for a reason; to make it easier to tweak whatever needs to be tweaked. However, the same can be accomplished by adding parameters to the unified algorithm implementations.

I already went through the process of rewriting the methods and testing them for bit-accuracy to the original:

```c++
// bit-perfect to the original implementation
float generic_aggregate(std::vector<float> values, double delta_multiplier, float final_multiplier) {
	// float, to maintain accuracy to the original
	float rating = 0.F;
	float res = 10.24F;
	
	for (int i = 0; i < 11; i++) {
		double sum;
		do {
			rating += res;
			
			sum = 0.0;
			for (const auto& value : values) {
				sum += std::max(0.0, 2.F / erfc(delta_multiplier * (value - rating)) - 2);
			}
		} while (pow(2, rating * 0.1) < sum);
		
		rating -= res;
		res /= 2.F;
	}
	rating += res * 2;
	
	return rating * final_multiplier;
}

float AggregateSSRs(const std::vector<float>& ssrs) {
	return generic_aggregate(ssrs, 0.1, 1.05);
}

float AggregateSkillsets(const std::vector<float>& skillsets)  {
	return generic_aggregate(skillsets, 0.1, 1.125);
}

float AggregateRatings(const std::vector<float>& skillsets) {
	return generic_aggregate(skillsets, 0.25, 1.11);
}
```

**Comment by poco0317** [comment]
9a37e08a20e9d382acb3155f3e6eef1c1e4da3ea
