### ISSUE TITLE
Crash when entering ScreenGameplaySyncMachine while "solo" game is selected

### ISSUE THREAD

**Issue by Jolomann** [etternagame/etterna#877]
**Describe the bug**
If you have solo selected as a game and go to `options -> input options -> calibrate audio sync`, the game crashes due to a style issue.

Crash report gives this error
```
Etterna0.70.3 crash report (build )
--------------------------------------

Crash reason: Game has no Style that can be used with HowToPlay: solo
```

Since there's no solo chart for the sync screen, I tried adding a `dance-solo` chart to `ScreenGameplaySyncMachine music.ssc` in `_fallback` but that didn't work. Though I suppose that might be a good idea to add if and when this ends up working

**To Reproduce**
1. Go to 'options -> select game'
2. Select 'solo'
3. Go to 'options -> input options -> calibrate audio sync'
4. Game go poof

**Version:**
 - Etterna 0.70.3

**Comment by poco0317** [comment]
709f383eb329c5e054a04571ec6a8fb8c2226ded
