### ISSUE TITLE
Changing names or logging in affects song select preview music/equalizer

### ISSUE THREAD

**Issue by hitonisan** [etternagame/etterna#878]
**Describe the bug**
If you enter the name change or login screens within Etterna, upon returning to the song select screen, the following occur:
-The music preview is stopped, and right-clicking won't turn it back on. You can get it back by either switching to the chart display (Space by default) or selecting a new song.
-Until a menu besides song select, name change, or login is opened, the song select's equalizer will be deactivated.

**To Reproduce**
1. Enter either the name change or login screen by clicking on one of them within Etterna. (The name change screen is accessed by clicking your name in the lower left corner of the song select screen.)
2. Exit the screen you entered. You can either fill the forms out, or just exit out of them with ESC - both have the same effects.
3. On returning to song select, your current song's music should have stopped playing. You can try to right-click to bring it back, and this should have no effect. Bring up the chart preview or move to another song to bring the music back.
4. Select a different song. The music equalizer at the top of the song select menu should stop functioning.

**Screenshots**
Before initiating the bug, the equalizer at the top of the screen works without issues:

![2020-08-20_023528](https://user-images.githubusercontent.com/37351790/90731149-ebf29b00-e28e-11ea-8f75-ed0c692e5c97.png)

After triggering the bug and going into a song preview, it's apparent that the equalizer is no longer trying to match the current song and is just frozen in place:

![2020-08-20_023554](https://user-images.githubusercontent.com/37351790/90731232-0a589680-e28f-11ea-8ca3-3e9154dd19af.png)

Moving to a different song makes the equalizer bars collapse completely:

![2020-08-20_023600](https://user-images.githubusercontent.com/37351790/90731252-15132b80-e28f-11ea-9762-a3b36646f538.png)

**Desktop:**
 - Windows 10 Home, version 10.0.18363
 - Etterna version 0.70.3
 - 64-bit architecture

**Comment by poco0317** [comment]
this was fixed in 0.72.2 by 64d23efc643457b5a321d135843744d54be846bd 5a71afed147b1f7ce0289e6984f86f8089de9e00
