### ISSUE TITLE
Maybe change MinaCalc Chisel implementation to use binary search, for performance

### ISSUE THREAD

**Issue by kangalioo** [etternagame/etterna#881]
The [`Chisel`](https://github.com/etternagame/etterna/blob/0b7a28d2371798a8138e78e5789d0014b16b4534/src/Etterna/MinaCalc/MinaCalc.cpp#L523) function in MinaCalc, which takes up a big part of execution time as far as I know, is implemented in a potentially inefficient way. Performance would probably increase if the search algorithm was implemented using binary search instead.

I didn't thoroughly test the actual performance impact yet; although I did test how much it affected performance to introduce binary search in a Rust port of one of the Aggregate* functions - they share the same algorithm as Chisel in MinaCalc. The performance gain was +30%.

The downside of binary search over the current implementation is that binary search can only search a certain range, so `Chisel` wouldn't be able to return any value beyond, say, 163.84, or 327.68 (depending on the number of iterations and resolution). However, I think this is not that big of an issue because the calc is only designed for a certain scope of values anyways.

**Comment by poco0317** [comment]
#883 reopen or discuss if further changes needed
