### ISSUE TITLE
Results screen is blank

### ISSUE THREAD

**Issue by gcpreston** [etternagame/etterna#887]
**Describe the bug**
After playing a song, the result screen shows nothing. It looks like the score still saves correctly though.

**To Reproduce**
1. Play a song
2. Look at the result screen

**Expected behavior**
This score, comparison to other scores, and the timing map should show up.

**Screenshots**
![blank](https://user-images.githubusercontent.com/7387903/91325217-e9151000-e790-11ea-8e73-112670358f11.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 10.0.19041 Build 19041
 - 64bit

**Additional context**
I just upgraded to Etterna 70.3 and was met with this.

**Comment by bluebandit21** [comment]
Mind going to the Etterna Dev Discord so we can help you debug?
[The link](discord.gg/ZqpUjsJ)

**Comment by poco0317** [comment]
This is a clear indication you incorrectly updated. Do not touch the Themes folder when updating. Do not overwrite the Themes folder with any other Themes folder.
