### ISSUE TITLE
Game freezes when logging in

### ISSUE THREAD

**Issue by chhoke** [etternagame/etterna#889]
Running Etterna 0.70.1, tried logging in after making an account. Screen popped up with a Successfully Logged In panel at the top but then froze. Tried restarting the game, and it runs fine in the main menu, but when I click Game Start it freezes at the song select screen again, with the same Successfully Logged In panel at the top. The game doesn't respond to any inputs, and doesn't even quit unless using the Force Quit window.

<img width="1440" alt="Screen Shot 2020-08-26 at 6 59 22 PM" src="https://user-images.githubusercontent.com/70303345/91375662-23ea6880-e7d0-11ea-87c7-87ab5b5e08aa.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version macOS Mojave 10.14.6

**Comment by poco0317** [comment]
This *nix related issue should be fixed by 0.70.2+
Please only report issues if you are on the latest version of the game.

**Comment by chhoke** [comment]
I'm new to the game and didn't realize Etterna Online website was separate from the developers, didn't know there was a newer version on github :pepega:

**Comment by MinaciousGrace** [comment]
can you actively affirm for us that it is fixed when you update? we don't have too many mac users and every data point helps

**Comment by chhoke** [comment]
Yup, updated and redownloaded all the packs and it works fine now, even after logging in. Thanks for the help!
