### ISSUE TITLE
Came crashes when the Return key is held on song select.

### ISSUE THREAD

**Issue by Simply420** [etternagame/etterna#891]
**Describe the bug**
Etterna 70.3 crashes when the return key is held on the song select screen, as if you were going to change settings prior to starting the song.

**To Reproduce**
1. Go to song select
2. Scroll to a song
3. Hold down the return/enter key
4. Game crashes.

**Expected behavior**
Normally, the gameplay settings will appear before starting the song.

**Desktop (please complete the following information):**
 - OS: Win10
 - 64bit

**crashinfo.txt**

> [Etterna0.70.3 crash report (build )

--------------------------------------

Crash reason: DefaultNoteSkin has no choices

Thread: Main thread
        IniFile.cpp:22 Reading 'Themes/Til Death/ThemeInfo.ini'
        FontManager.cpp:70 FontManager::UnloadFont(/Themes/Til Death/Fonts/_bokutachinogothic2bold 24px.ini).
        FontManager.cpp:70 FontManager::UnloadFont(/Themes/Til Death/Fonts/_bokutachinogothic2bold 24px.ini).
        FontManager.cpp:70 FontManager::UnloadFont(/Themes/Til Death/Fonts/_bokutachinogothic2bold 24px.ini).
        OptionRow.cpp:169 DefaultNoteSkin has no choices
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:237 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:237 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:237 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:237 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:237 Processing the sound while buffers are available.
Thread: Mixer thread
Thread: Music thread
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:893 
        InputHandler_DirectInput.cpp:868 
        InputHandler_DirectInput.cpp:887 
        InputHandler_DirectInput.cpp:893 
        InputHandler_DirectInput.cpp:868 
debug resource file 'C:\Games\Etterna\Program\Etterna.vdi': CreateFile failed (The system cannot find the file specified.).

Static log:
Etterna0.70.3
(build )
Log starting 2020-08-30 18:09:50
	Verbosity: 1
Windows 6.2 (Win8) build 9200 []
WARNING: Main title or music file for '/Songs/Touhou Arrange 2nd Pack ~ Mystical Second Dreams/[Jin] Crazy Xenomorph(12-15)/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/Bunch of Files You Probably Don't Have 3/Moe Moe Kyunstep (VIKINGFJORDS)/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/KITUNEKOTEI/en/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/KITUNEKOTEI/missitu/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/KITUNEKOTEI/naki_oujyo/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/Dingles Finale/Bloody Tears (Dingles)/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/KITUNEKOTEI/sigosen/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/KITUNEKOTEI/syanhai/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/KITUNEKOTEI/tukihusiM/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
Attempting to connect to: multi.etternaonline.com, Port: 8765
Server Version: 0 
Video renderers: 'd3d, opengl'
WARNING: RageDisplay_D3D::TryVideoMode( 0, 2560, 1440, 32, 144, 0 )
D3D Fullscreen 2560x1440 32 color 32 texture 144Hz NoVsync SmoothLines
WARNING: NoteSkin "00110111" references skin "default" that is not present
WARNING: NoteSkin "morbular-jesse" references skin "MultiplyByZeroDoubleRes" that is not present
WARNING: NoteSkin "urso" references skin "default" that is not present
WARNING: NoteSkin "ursorolls" references skin "default" that is not present
WARNING: NoteSkin "uswcelett" references skin "common" that is not present
WARNING: NoteSkin "uswdefault9sm5" references skin "common" that is not present
WARNING: Font import recursion detected
WARNING: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: /Themes/_fallback/Fonts/Common default.ini
WARNING: /Themes/Til Death/Fonts/_16px fonts.ini
WARNING: Current font: /Themes/Til Death/Fonts/_open sans semibold 24px.ini
WARNING: Font /Themes/Til Death/Fonts/_16px fonts.ini has no characters
WARNING: NoteSkin "00110111" references skin "default" that is not present
WARNING: NoteSkin "morbular-jesse" references skin "MultiplyByZeroDoubleRes" that is not present
WARNING: NoteSkin "urso" references skin "default" that is not present
WARNING: NoteSkin "ursorolls" references skin "default" that is not present
WARNING: NoteSkin "uswcelett" references skin "common" that is not present
WARNING: NoteSkin "uswdefault9sm5" references skin "common" that is not present
Players joined: P1
Current renderer: Direct3D

Partial log:
00:11.121: WARNING: NoteSkin "ursorolls" references skin "default" that is not present
00:11.121: WARNING: NoteSkin "uswcelett" references skin "common" that is not present
00:11.121: WARNING: NoteSkin "uswdefault9sm5" references skin "common" that is not present
00:13.211: ScreenOptions::InitMenu()
00:14.809: ScreenOptions::~ScreenOptions()
00:14.819: ScreenOptions::InitMenu()
00:15.548: ScreenOptions::~ScreenOptions()
00:15.557: Reading 'Themes/bare-frames/ThemeInfo.ini' failed: No such file or directory
00:15.557: Reading 'Themes/Til Death/ThemeInfo.ini' failed: No such file or directory
00:15.557: ScreenOptions::InitMenu()

-- End of report
](url)

**Comment by poco0317** [comment]
What theme?

**Comment by Simply420** [comment]
Using 'Til death. Does Etterna no longer support symbolic links? I have my NoteSkins folder on another drive.

**Comment by Simply420** [comment]
Fixed the issue, reinstalled etterna 70.3 while keeping the NoteSkin folder hierarchy the same and copied old noteskins manually. Unsure if the folder structure has changed, or if the problem lies with my use of folder symbolic links.
