### ISSUE TITLE
Some songs are not selectable after changing locale

### ISSUE THREAD

**Issue by karastrinket** [etternagame/etterna#898]
**Describe the bug**
After changing my locale from English to Japanese, there are songs that are missing from various pack files. 

****To Reproduce**
Steps to reproduce the behavior:**
Download Mizuki simfiles pack from Etterna website.
Put Mizuki simfiles pack under songs folder in Etterna directory.
Boot Etterna and check that there are 800+ songs selectable from Mizuki simfiles pack.
Close Etterna.
Change system locale to Japanese.
Restart the computer.
Boot Etterna.
Check Mizuki simfiles pack in the game.

**Expected behavior**
Expected to see +800 songs under Mizuki simfiles.

**Screenshots**
[image](https://i.imgur.com/c04FhiQ.png)
The folder indicates there are 822 folders within Mizuki simfiles.
[image](https://i.imgur.com/I8qsrMV.png)
Etterna is only detecting 517 songs from the Mizuki simfiles folder.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro. (OS build 18362.1082)
 - Version 1903
 - 64 Bit

**Additional context**
I also noticed that song previews for certain songs would not play and I had to manually change the file name of the .mp3/.ogg file to English because the file name contained symbols and within .sm file, the #MUSIC: tag had a different file name. For example, 
[rose] Pure in Asia in SMOC 2 pack has "+f_O=_v_ⅵ Pure in Asia.mp3" file while the #MUSIC: tag in the .sm file is looking for a file called "無何有_化 ～ Pure in Asia.mp3". Herz and Herz from Hard Songs Megapack 11 and Volcanicu from ATTang's Bad Files had the same issue.

**Comment by poco0317** [comment]
related #484 
related #238

**Comment by poco0317** [comment]
superceded by #944
