### ISSUE TITLE
Unable change the process priority of Etterna.exe

### ISSUE THREAD

**Issue by CXgamer** [etternagame/etterna#899]
**Describe the bug**
When changing the priority of Etterna.exe through Task Managaer on Windows machines, it is consequently reverted when activating the game window.

**To Reproduce**
1. Open Etterna
2. Open Task Manager through CTRL + SHIFT + Escape
3. Details
4. Right click Etterna > Priority > Realtime
5. Activate Etterna's window
6. Open Task Manager again
7. Richt click Etterna > Priority
8. See that its priority is now not Realtime any more

**Expected behavior**
At step 8, it ought to have stayed on the Realtime setting.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.70.2
 - 64bit

**Additional context**
I'm getting an absurd amount of lag (a constant stream of 1ms to 4ms lags with additional spikes). Setting the Process' priority might help a bit.

**Comment by bluebandit21** [comment]
What do you mean by "activate Etterna's window"?

Do you mean alt-tabbing to it?

**Comment by poco0317** [comment]
Etterna controls the priority itself, changing it to Above Normal for Windows versions at least as new as XP (so basically all of them).
It changes priority to Normal when you unfocus from the game basically for power usage reasons. When you focus back into the game, it sets the priority again to Above Normal.

There is a preference that allows you to modify this yourself.
Find `/Save/Preferences.ini` and change `NeverBoostAppPriority=` to 1. This should allow you to control it on your own. Remember that changing this yourself in certain scenarios can break a lot of things so do it at your own risk.
