### ISSUE TITLE
Calculator generating inflated ratings for files on Linux

### ISSUE THREAD

**Issue by TheROPFather** [etternagame/etterna#9]
After compilation on Linux and adding a pack with known ratings (from the stable 0.54.1 build) the ratings do not match and are inflated vastly. 

As an example I will use the default file included Remembrance - the Single HD 10 chart of this file is given a rating of 22.90 on Linux with the Technical and Jumpstream skillsets. On the stable 0.54.1 Windows build the files is given a rating of 12.01 and only the Technical skillset is shown. When choosing the lower chart Single NM 6 the rating does go down to 17.00. 

Using the Single NM 6 with a rating of 17.00 and altering the rate produces further unusual behavior. At 0.9 and 0.8 the rating remains the same (17) where as at 0.7 the rating becomes 11.62. Increasing the rate only alters the rating once 2.0 is reached and subsequently 2.1 - 3.0 all alter the rating. 

Also for example on Windows if file 1 has a rating of 12 and file 2 has a rating of 15 file two is deemed to be harder. This relationship does not appear on Linux file 1 could be rated higher than file 2 - there is no correlation between difficulties.

**Operating System:** Ubuntu 16.04
**Compiler Version:** g++ 5.4.0
**OpenGL Version:** 3.0 Mesa 12.0.6
**OpenGL Renderer:** Gallium 0.4 on SVGA3D; build; RELEASE; LLVM;
**Runtime Library:** glibc 2.23

**Comment by lukeoftheaura** [comment]
I am having the same issue.
