### ISSUE TITLE
FirstTrack parameter sends the first index of the chord for misses in JudgmentMessageCommand with CC off.

### ISSUE THREAD

**Issue by ca25nada** [etternagame/etterna#90]
The `FirstTrack` parameter is included as a parameter during `JudgmentMessageCommand` where its value corresponds to the index of the first note of a chord in a notefield column.
(the values are 0-indexed so a `FirstTrack` value of 2 would correspond to L3)

With CC on, Hitting a chord of `↖↓→` (L2 L3 L6 in solo) would create 1 `JudgmentMessage` with a `FirstTrack` value of 1, corresponding to L2 being the first note of the chord.
```{FirstTrack=1, TapNoteScore="TapNoteScore_W1"}```

With CC off, Hitting the same chord creates 3 `JudgmentMessage` with each message having the `FirstTrack` value corresponding to each individual notes.
```{FirstTrack=1, TapNoteScore="TapNoteScore_W1"}```
```{FirstTrack=2, TapNoteScore="TapNoteScore_W1"}```
```{FirstTrack=5, TapNoteScore="TapNoteScore_W1"}```

However, with the miss judgments, the `JudgmentMessage` would have the `FirstTrack` value of the first note of the chord even when CC is off
```{FirstTrack=1, TapNoteScore="TapNoteScore_Miss"}```
```{FirstTrack=1, TapNoteScore="TapNoteScore_Miss"}``` should be 2
```{FirstTrack=1, TapNoteScore="TapNoteScore_Miss"}``` should be 5

This is true even if the player hits some of the notes in the chord. Say the player hits L3 but missed the rest of the chord.
```{FirstTrack=2, TapNoteScore="TapNoteScore_W1"}```
```{FirstTrack=1, TapNoteScore="TapNoteScore_Miss"}```
```{FirstTrack=1, TapNoteScore="TapNoteScore_Miss"}``` should be 5

**Comment by Nickito12** [comment]
Im almot sure https://github.com/etternagame/etterna/pull/109 fixes this
