### ISSUE TITLE
Mouse difficulty selection works improperly if difficulty selection scrolls

### ISSUE THREAD

**Issue by hitonisan** [etternagame/etterna#900]
**Describe the bug**
The mouse can be used to select a difficulty on the song selection screen by clicking on the difficulty you want. However, if the difficulty selection scrolls in response to a difficulty selected this way, the difficulty the game ends up picking may not be the one that the player wanted. In some cases, it could even pick a difficulty that wasn't on the screen yet.

**To Reproduce**
1. Go to song select.
2. Pick any song that has enough difficulties to require the difficulty selection to scroll to display them all. (If you need a song that matches these conditions, the "In the Groove" pack has many you can test.)
3. Using the mouse, click other difficulties to select them. Unexpected difficulties may be selected if the difficulty selection had to scroll in response.

**Expected behavior**
Depending on whether or not the difficulty selection scrolled or not, your difficulty selection may be correct, or may be offset in the direction of the scroll.

**Video example**
Please excuse the mouse offset in this - the true mouse position can be reflected in what difficulty is being highlighted at a given time.

https://youtu.be/r8YJakNExq8

**Desktop:**
 - Windows 10 Home, version 10.0.18363
 - Etterna version 0.70.3
 - 64-bit architecture

**Comment by poco0317** [comment]
In addition to this, the bug seems literally reproduced in our Lua reimplementation of the StepsDisplay.
At least in my instance of the reimplementation. Haven't tested on Til Death.

**Comment by MinaciousGrace** [comment]
this is already fixed in td
