### ISSUE TITLE
Overlapping fade tweens cause cropping

### ISSUE THREAD

**Issue by Jolomann** [etternagame/etterna#902]
**Describe the bug**
A combination of tweens for fading (fadetop(), fadebottom(), fadeleft(), faderight()) which have overlapping areas to fade will cause a complete crop of an element instead of a fade.

**To Reproduce**
1. Use two fade tweens on an element which have overlapping areas (ex. bottom/left, bottom/right)
2. It don't fade properly

**Expected behavior**
Ideally the fades should combine so they can be used in tandem. To avoid "overfading" in the overlapping area I guess the fades should be halved in the overlapping areas

**Screenshots**
Example with a quad here. `fadebottom(0.5)` and `fadeleft(0.5)` were used
![quad](https://bries.s-ul.eu/bmVIXQmW.png)

**Version:**
 - 0.70.3

**Comment by poco0317** [comment]
this is the best i got for now because there is some interesting quirk with how the game draws quads from vertices
1c24c89f3a3c55a7b46acb6dc3dec7156aaefa12
![image](https://github.com/etternagame/etterna/assets/2531164/1c7fd445-8107-4690-8eb6-4042e00b1a8d)

**Comment by poco0317** [comment]
bonus sprite 
![image](https://github.com/etternagame/etterna/assets/2531164/fd737f5c-5443-45c9-959c-792db1ac9be3)

**Comment by Jolomann** [comment]
Excellent, much better this way
