### ISSUE TITLE
FullComboOfScore() ignores last note when used in SongFinishedMessageCommand

### ISSUE THREAD

**Issue by Jolomann** [etternagame/etterna#904]
**Describe the bug**
`FullComboOfScore()` is usually used along with `SongFinishedMessageCommand` to reward the player with an animation for a certain score type (FC, MFC, other grades). It just so happens that the last note is ignored, so you can end up triggering an FC or MFC reward when you didn't get one. The easiest way to see this is on You Suffer (you know the one).

**To Reproduce**
1. Have a gameplay score reward somewhere in your theme
example:
```
Def.ActorFrame {
		Name="FC/MFC reward";
		SongFinishedMessageCommand=function(self)
		local checkStats = STATSMAN:GetCurStageStats():GetPlayerStageStats(pn);

		--Trigger on FC/MFC
			if checkStats:FullComboOfScore('TapNoteScore_W1') == true then
				ms.ok("Marvelous Full Combo!!!!!!!")
			elseif checkStats:FullComboOfScore('TapNoteScore_W3') == true then
				ms.ok("Full Combo!!!!!!!")
			end
		end,
	};
```
2. Play You Suffer
3. Hit the first 3 notes with greats or better
4. Miss the 4th note
5. Score reward is falsely triggered

**Expected behavior**
It shouldn't ignore the last note I guess

**Video**
https://streamable.com/1jl8ol

**Version:**
 - 0.70.3

**Comment by poco0317** [comment]
mitigated e9cd9d6f9bc4a652cdea9418ddbdfdac2d016f59
