### ISSUE TITLE
Background Movies for charts don't work when using OpenGL renderer

### ISSUE THREAD

**Issue by bluebandit21** [etternagame/etterna#914]
**Describe the bug**
Background Movies don't seem to play at all on macOS or Linux (at least specifically arch, as confirmed by 
Instead, if the chart background is set to default, a single color is shown as the background instead of the movie.

**To Reproduce**
Play any chart with an animated background on macOS or Linux.
"The first the last" from FFR community novice files compilation is one such chart. 

**Additional context**
These videos *do* work on SM5, so it's definitely an Etterna-specific problem.

**Comment by poco0317** [comment]
This is an issue present when using our opengl renderer on all platforms.

**Comment by poco0317** [comment]
I've narrowed the cause of this down to something that happened between 0.58 (unreleased) and 0.60.

**Comment by poco0317** [comment]
This commit causes the issue. ab42745fdb7a69cc68f6eebbc028f61680f0f238
