### ISSUE TITLE
Update Building.md to mention how to build a release configuration

### ISSUE THREAD

**Issue by bluebandit21** [etternagame/etterna#916]
Building.md doesn't currently mention explicitly how to build in a release configuration.

This is largely fine, since very few people would ever want to build macOS or Windows in non-debug, since there are pre-built releases available.

However, for Linux users, where the only way to play the game is through compiling it yourself, having the default build type be debug is a footgun for poor game performance.
It would be nice to have an explicit note in Building.md as to how you can build the game in release, and that you should do so if compiling on Linux to actually play the game, not develop.

An alternate (possibly poor) idea would be to have the default build be release in Linux only, still defaulting to debug for non-linux builds. Users would then have to explicitly opt into a debug build in Linux, which might be a more reasonable behavior. 

I'd make the PR to update it myself right now, but I'm both tired and busy so this issue is a note to myself to add it.

**Comment by poco0317** [comment]
675508bb542268704e3a39d80fac9adeeee41808

**Comment by Kangaroux** [comment]
@poco0317 That commit never made its way into master

**Comment by poco0317** [comment]
An update has not released, thus nothing has been merged to master.
