### ISSUE TITLE
Remove the hardcoding of the first set of keybinds

### ISSUE THREAD

**Issue by foxfire667** [etternagame/etterna#918]
When inside the keybinds menu, the first set of keybinds are hardcoded. This is to say that, unless you move a hardcoded key to a different slot, it cannot be changed, and also that you cannot configure keys within the first slot at all. 

I request that the default keybinds no longer be hardcoded, so that keys may be deleted or set as a user pleases without janky roundabout processes. This should also allow a user to configure all of the slots if desired, so that users can have more freedom if they play multiple styles, and have to swap back and forth less (e.g. spread / index / OH / controller(s) / pad).

**Comment by poco0317** [comment]
Related - allow modifying the column width of each Game. Both of these things happen in the same file. It was an idea to allow metrics to do this even before our time but it never went through for some reason.

**Comment by poco0317** [comment]
mitigated in 43ca6aaf339adb3dcfb7d978b1ad6fb54b5d7140
the default column is preset and cannot be changed directly, however will load if appropriately added in the keymaps.ini
