### ISSUE TITLE
[0.55.3] Full Progress Bar forgets Y position

### ISSUE THREAD

**Issue by JKAnderson** [etternagame/etterna#92]
Once you leave Customize Gameplay mode, the Full Progress Bar resets to its original Y coordinate.

**Comment by martensm** [comment]
Are you sure about this one? I can't reproduce on my end and another person who tried couldn't either.

**Comment by TKGP** [comment]
Quite sure. After adjusting the element, it stays in place if I exit the song and play again with customize mode still enabled. But if I exit, disable customizing, and then play it always jumps back to the top.

**Comment by JKAnderson** [comment]
Here's a video to demonstrate: https://my.mixtape.moe/oytyoo.webm

**Comment by martensm** [comment]
Thanks for the video, will have to investigate further.
