### ISSUE TITLE
In-Game Pack Downloads Fail After Valid Score Submission

### ISSUE THREAD

**Issue by hitonisan** [etternagame/etterna#924]
**Describe the bug**
Etterna has an in-game pack downloader that can run while the player is in the song select menu. However, if a player starts a pack download in this fashion, then plays a song to completion and submits a valid score as a result, the ongoing pack download can suddenly fail shortly after returning to song select.

Note that only valid score submissions have been noted to do this. This problem doesn't seem to occur if the song wasn't completed (the player quit out early) or if the submitted score was invalid (e.g. the score received a MSD rating of 0).

**To Reproduce**

1. Using the in-game pack downloader, begin downloading a pack of your choice. I recommend picking a pack of decent size (100 MB+), so you'll have time to execute the remaining parts of the issue before the download finishes.
2. Return to song select.
3. Play to completion any song you can obtain a valid score on, and submit a valid score. (Achieving a new personal best is not required.)
4. Return to the song select menu, and stay there. The pack download will suddenly terminate a short time later (usually within 30 seconds).

**Expected behavior**
The ongoing pack download on the UI should suddenly disappear, and all download progress will be lost.

**Video example**
The [video](https://youtu.be/buaHl6T3b1Q) attempts to showcase this bug, including what does and doesn't trigger it. The steps taken are lengthy, so the video's description has timestamps for quick access.

**Desktop:**
 - Windows 10 Home, version 10.0.18363
 - Observed in Etterna version 0.70.3
 - 64-bit architecture

**Comment by poco0317** [comment]
this issue is resolved/mitigated by new downloadmanager changes which move it to a different thread from the game and allow continued downloading in the background during gameplay. although the pack will not install until you exit gameplay, because that would suck if the game froze for 30 seconds while it unzipped the pack
