### ISSUE TITLE
Rename "Enable Easter Eggs" to "Enable Toasty"

### ISSUE THREAD

**Issue by kangalioo** [etternagame/etterna#925]
The "easter eggs" in question is a singular feature, referred to as "toasties". It's a pretty well-known feature about the game and a common aspect of customizing the game. It's not nearly unknown enough to be called easter eggs.

For that reason, I think it makes sense to rename the settings entry to toggle their visibility from "Enable Easter Eggs" to "Enable Toasty"

**Comment by poco0317** [comment]
In the near future this feature will toggle more than toasties.
