### ISSUE TITLE
MP3 File Extraction Error Occurs with In-game Pack Downloader

### ISSUE THREAD

**Issue by hitonisan** [etternagame/etterna#926]
Created by request.

**Describe the bug**
The Xoon 3 ranked song pack contains the song Feast for Eternity ([https://etternaonline.com/song/view/5316#38868](url)). An error occurs if you try to extract this song via the in-game pack downloader, and the MP3 for Feast of Eternity won't be retrieved. Feast of Eternity won't appear in the song list after extraction completes. If it appears the next time Etterna is started, playing it crashes the game.

Note that this doesn't occur if the pack is downloaded from Etterna's website and is extracted manually. However, this may still lead to an issue with the song's preview music not playing until the song is played at least once.

**To Reproduce**
1. If you already have the Xoon 3 song pack, remove it from your Songs directory for these tests.
2. Download the Xoon 3 song pack via the in-game pack downloader. You can use either the standard or mirror download link - these issues have been observed with both links.
3. Let the pack download complete.
4. Watch the extraction process for error messages, and then check your song files.

**Expected behavior**
An error should be thrown during the song extraction process, and the MP3 file for Feast of Eternity won't be extracted.

**Screenshots and logs**
The following error shows up during the extraction process (and also appears in in-game logs):

![2020-11-14_180903](https://user-images.githubusercontent.com/37351790/99160356-21e7c580-26ac-11eb-8b03-d973658d58f8.png)

If you extract the Xoon 3 pack manually, this message is logged when starting Etterna:

00:03.086: Song '/Songs/Xoon 3/(Kommisar) Feast for eternity/' points to a music file that doesn't exist, found music file '15 - IOSYS - 宴・永遠・.mp3'

**Desktop:**
 - Windows 10 Home, version 10.0.18363
 - Observed in Etterna version 0.70.3
 - 64-bit architecture

**Comment by poco0317** [comment]
A recent version like 0.72.0 should have resolved this issue by replacing unknown characters with _ in the path, renaming the files. This may break some .sm files, but the auto-resolution the game does should take care of it most of the time. If that fails, we need specific examples and at that point will need to consider re-mirroring the said pack(s)
