### ISSUE TITLE
[0.55.3] Draw preview rectangles when in Customize Gameplay

### ISSUE THREAD

**Issue by JKAnderson** [etternagame/etterna#93]
Combo Text isn't shown at all in AutoPlay so you can only adjust it by guesswork, and other elements like the Error Bar or Life Bar don't show their full extent all the time, so getting the width right is an exercise in trial and error. While Customize Gameplay is on, it would be nice if a simple colored rectangle was drawn behind each element so you could see where and how large they were at all times.

**Comment by martensm** [comment]
> Combo Text isn't shown at all in AutoPlay so you can only adjust it by guesswork

<kbd>Shift</kbd> + <kbd>F8</kbd>.

I agree with the rest of the issue though that this would be a good feature to have.

**Comment by MinaciousGrace** [comment]
added as part of https://github.com/etternagame/etterna/pull/349
