### ISSUE TITLE
Crashing when trying to access playlists

### ISSUE THREAD

**Issue by Glaxes09** [etternagame/etterna#933]
To Reproduce
1.Go to a chart and favorite the chart and add it to a playlist
2. Try to access the playlists tab
3. Repeat until crash

Expected behavior
Crashing when trying to access playlists

OS: Windows 10
Version: 0.70.3
64bit

[Etterna log.txt](https://github.com/etternagame/etterna/files/5684239/Etterna.log.txt)
[Etterna crashinfo.txt](https://github.com/etternagame/etterna/files/5684240/Etterna.crashinfo.txt)

**Comment by poco0317** [comment]
This should already be fixed but I'm not completely sure.
381ce6c9bea2bfbcd4b766069e0322c5a432195c
Check again when 0.71 or a newer version is out and reopen this if it still occurs.
