### ISSUE TITLE
Crashed upon MFCing Blockbuster from NBJS2

### ISSUE THREAD

**Issue by Aquellex** [etternagame/etterna#934]
[crashinfo.txt](https://github.com/etternagame/etterna/files/5696019/crashinfo.txt)

**Comment by Aquellex** [comment]
[log.txt](https://github.com/etternagame/etterna/files/5696027/log.txt)

**Comment by Aquellex** [comment]
![2020-12-16_000511](https://user-images.githubusercontent.com/30398086/102218972-ece0c400-3f32-11eb-95df-389786b51c09.png)

**Comment by poco0317** [comment]
kind of related not really #716 
the information given here gives some small clues as to what went wrong, though and does narrow the search

**Comment by poco0317** [comment]
it's likely that this crash was related to replays or score uploading. both of these has been rewritten some way or another and the specific issue should be resolved in 0.72
