### ISSUE TITLE
Document building without crashpad

### ISSUE THREAD

**Issue by graemephi** [etternagame/etterna#939]
Crashpad requires depot_tools. To build without Crashpad cmake needs to be invoked with `-DWITH_CRASHPAD=OFF`, which is currently undocumented.

The actual way the build fails without depot_tools is also kind of obscure. Detecting that depot_tools is missing and telling people to build with this flag would be ideal.

**Comment by poco0317** [comment]
675508bb542268704e3a39d80fac9adeeee41808
