### ISSUE TITLE
[0.55.3] Mines before any notes confuses % display

### ISSUE THREAD

**Issue by JKAnderson** [etternagame/etterna#94]
See pic. Mines passed before any notes did. As soon as some notes passed it was fine.

![stepmania 2017-10-21 20-54-51-93](https://user-images.githubusercontent.com/28029167/31857090-54ffab86-b6a2-11e7-979a-24948ab2fb7e.png)

**Comment by MinaciousGrace** [comment]
fine fine i'll fix it....65728c89a73247f1a923fc9c893d808230194d5e
