### ISSUE TITLE
Lag when scrolling, disappears when holding Tab

### ISSUE THREAD

**Issue by kangalioo** [etternagame/etterna#947]
**Describe the bug**
When scrolling through the song selection screen normally, I get consistent lag of ~10-40ms. This level of lag seems the same when scrolling through the pack list vs scrolling through the charts of an opened pack.

However, when holding Tab while scrolling, the lag almost disappears.

In other words (listen to the videos; the irregularity in the tick sounds makes the lag noticeable and slightly annoying):
|Lag|Holding Tab|Not holding Tab
|-|-|-
|Scrolling through packs|[None](https://streamable.com/aycpic)|[10-40ms](https://streamable.com/ku150s)
|Scrolling through songs|[None or 10-20ms](https://streamable.com/pnfprm)|[10-40ms](https://streamable.com/8os9v8)

**To Reproduce**
1. Scroll through the song selection screen

**Expected behavior**
I'd have expected fast scrolling using Tab to lag more because the game needs to load resources more quickly...? And ideally, of course, there'd be no lag at all.

**Screenshots**
The table above includes videos.

**Desktop (please complete the following information):**
 - OS: Linux 5.9.14, KDE Plasma 5.20.5
 - 64bit
 - Etterna 0.71.0 54e8ede8d3 (though this has been happening for much longer)

**Comment by Jolomann** [comment]
The lag is from loading backgrounds which is disabled while holding tab because it would cause immense lag

**Comment by poco0317** [comment]
We deliberately designed the updates in Til Death in a way that the interval of lag you get is the way it is instead of at every single music wheel entry. The updates happen after a certain amount of time passes basically. So it's normal, and not just the background loading. Might look into it in general though
Probably will close sooner or later

**Comment by nico-abram** [comment]
Closing
