### ISSUE TITLE
Game crashing when trying to install packs in game

### ISSUE THREAD

**Issue by lazichicken123** [etternagame/etterna#948]
**Describe the bug**
The game crashes whenever I try to download song packs in game.

**To Reproduce**
1. Open up the game (version 0.70.3 if that helps)
2. click on pack downloader
3. Click download on any pack that isn't installed
4. 

**Expected behavior**
I just want to download song packs in game.

**Screenshots**
not needed

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version 2004 - 64bit

**Additional context**
not needed

**Comment by poco0317** [comment]
Not enough information
lacking permissions?
what pack? any?
unreproducable
possibly a duplicate
#229 #762
