### ISSUE TITLE
Ubuntu package manager / ppa?

### ISSUE THREAD

**Issue by jxu** [etternagame/etterna#949]
So I don't have to recompile every version

**Comment by Ulti-FD** [comment]
There was [some work](https://github.com/etternagame/etterna/tree/debian-pkg) put into it 3 years ago. Not sure how much more is necessary to actually make it happen, but not only would the work to make a functional .deb need to be finished, there would likely be more work making it function with a version that's advanced 3 years. Do also keep in mind that this would need to be maintained throughout future iterations (more work) and that this work would only cover one segment of linux users.
There's a lot more things higher on the priority list and considering that building on linux is relatively easy I doubt its gonna happen any time soon. I have seen one of the main devs @jameskr97 still express interest in doing so somewhat recently so it's still possible, may as well get his word on it.

**Comment by jxu** [comment]
Also for building you can do clone with depth 1 to avoid downloading so much

**Comment by nico-abram** [comment]
Closing this as a duplicate of https://github.com/etternagame/etterna/issues/651
