### ISSUE TITLE
WIN10 - crash to desktop when creating a new profile (file perms related)

### ISSUE THREAD

**Issue by tylerstraub** [etternagame/etterna#95]
If you install Etterna to a Windows directory that is somewhere in user admin land (C:/Program Files in my case), this will cause a hard crash to desktop when attempting to create an in game user profile for the first time. 

Once I moved the installation out of Program Files and into C:/ everything worked fine. 

Nothing critical, just leaving this here. 

Cheers

**Comment by martensm** [comment]
Yeah this is a known issue. This is the reason why Etterna installs to `C:\Games` by default.

We'll need to add support for falling back to `%AppData%` if there is no write permission in `Program Files` in order to fix this.

**Comment by MinaciousGrace** [comment]
should be fixed
