### ISSUE TITLE
ActorFrameTexture usage on D3D can induce a crash when resetting D3D Device

### ISSUE THREAD

**Issue by poco0317** [etternagame/etterna#953]
And why? probably because of texture leaking if I had to take a random guess
Or this is my fault for driver reasons

To reproduce, use an AFT on any screen and then simply try to change themes, while on the D3D renderer. This should trigger d3ddevice->Reset which may fail, and if it does, the game will crash.

**Comment by nico-abram** [comment]
Fixed by https://github.com/etternagame/etterna/pull/1167
