### ISSUE TITLE
Note field cut off from resizing

### ISSUE THREAD

**Issue by WinterIsPretty** [etternagame/etterna#954]
**Describe the bug**
I want to make the receptors smaller because it is way too big and I would have to resize images to fix it and when I edit the note field and make it smaller the top of the note field is reached

**To Reproduce**
1. Edit play area
2. Resize note field height
3. See top of note field where notes spawn

**Expected behavior**
Resize of notes and that's it

**Screenshots**
I can't send any but if you need any I can do it during the day

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version any
 - 64bit

**Additional context**
Maybe add a note scale so it doesn't change the note field and you can have skinnier notes on anything

**Comment by poco0317** [comment]
Try the Receptor Size option in player options (double enter on a song) before making the entire notefield physically smaller.

**Comment by WinterIsPretty** [comment]
Idk I guess I'm blind I thought I carefully looked at and played with every setting and mode in etterna lol

**Comment by WinterIsPretty** [comment]
Also that was so fast
