### ISSUE TITLE
Favorites for charts are visible in different game modes

### ISSUE THREAD

**Issue by bluebandit21** [etternagame/etterna#962]
**Describe the bug**
If a chart has difficulties between two different game modes (say, a dance difficulty and a solo difficulty), favoriting the song in one game mode will make it show up as a favorite in other game modes.

**To Reproduce**
Favorite "Bullet Timing" from Dark Chanchellors in the dance game mode.
Switch to the solo game mode; the song will show up as favorited.

**Expected behavior**
This is unintuitive behavior. 
If I favorite a dance difficulty of a song, it doesn't mean that I love the song in solo as well where the difficulty that made me favorite the song in the first place isn't even available.
Ideally favorites of a song would track what game mode the song was favorited in, or (even better) should be tied to individual difficulties of a song, not the song as a whole.
Doing the latter would also make combinations of filters + favorite sort / playlist more intuitive as well.

**Comment by poco0317** [comment]
c803c09eae8d08218b167c2bb39b6a1fbcc5278f
