### ISSUE TITLE
No songs load

### ISSUE THREAD

**Issue by TheCoroboCorner** [etternagame/etterna#963]
**Describe the bug**
When selecting "Start Game" from the main menu, the music selection screen shows no songs, even if you download new ones they don't show up.

**To Reproduce**
Unknown; this happened upon initially downloading the game, the bug persists when the software is restarted.

**Expected behavior**
Expected behaviour is to see the songs on the list on the right.

**Screenshots**
![image](https://user-images.githubusercontent.com/81382526/112520445-cde3a080-8d71-11eb-863e-03c46c328a43.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: 10.0.18363 Build 18363
 - 64bit or 32bit: 64bit

**Additional context**

**Comment by poco0317** [comment]
go to main menu
options
select game
pick dance (you are on pump in this screenshot)

although it is a bug that this keeps happening, the game should not be defaulting to pump for new players
