### ISSUE TITLE
Overwritten score removed the score

### ISSUE THREAD

**Issue by WinterIsPretty** [etternagame/etterna#970]
**Describe the bug**
I beat my score and it became my new top play but I lost points and I think it doesn't register as a score anymore even though I submitted it right before I played it that time and it was fine.

**To Reproduce**
1. Pick a map
2. Play the map
3. Replay the map beating your score every time
4. Get unlucky
5. Look at profile stats

**Expected behavior**
My score gets submitted

**Screenshots**
https://cdn.discordapp.com/attachments/463638143422169088/831314417118478346/unknown.png

I was 26 for jack speed my last time I checked before it happened

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.70.3
 - 64bit

**Additional context**
I'm sure it could just be because my request after my score got submitted was lost or something. I reported this because it could happen to more people.

**Comment by poco0317** [comment]
no maps here sorry
not enough information
and this is a site issue, not a client issue

**Comment by WinterIsPretty** [comment]
whre do I report for site issue

**Comment by poco0317** [comment]
discord

**Comment by WinterIsPretty** [comment]
oh I guess I had to wait for a while
