### ISSUE TITLE
Using 'Shift + 0' in Search tab causes switch to Player Tag tab

### ISSUE THREAD

**Issue by Sarrg** [etternagame/etterna#972]
**Desc**
German Keyboard locale uses Shift + 0 to input a "=".
This cannot be inputted without also switching to "Player Tags" tab (Bound to '0').
Holding Control will omit the Shift modifier and input "0" instead of "=".
This behaviour is not reproducible with Shift + (1 - 9)

**Reproduce**
1. Go to search tab
2. Hold "Shift + 0"
3. Input is correctly process but Switches to "Player Tags"

**Expected**
Pressing Shift + 0 will input '=' without switch to Player Tags (same as using 1-9 instead of 0)

**Comment by poco0317** [comment]
already fixed for .71  33c0331d4a1ffb2dcabfe3e1d0991139cc5fa820
