### ISSUE TITLE
Allow longer passwords in user authentication

### ISSUE THREAD

**Issue by dmngrsk** [etternagame/etterna#975]
**Describe the bug**
When trying to login to Etterna, it is not possible to enter a password longer than 50 characters. On the registration page, there is no such constraint, and (I believe) there is no way to change password via WebUI, rendering an account registered with a password longer than 50 characters unusable in-game.

**To Reproduce**
1. Start the game in the context of not being logged in as any user.
2. Press "Game Start" via main menu.
3. Press "Click to login" at the bottom of the screen.
4. Type any username.
5. Try to type a password longer than 50 characters. On 51st character and later, there will be a sound indicating that the input is not being registered.

**Expected behavior**
I expected that there would be no length constraint on the password and that it would allow me to type it from start to finish. In the current state, I have no means to access my account in-game.

**Screenshots**
Nothing interesting here tbh lol
![image](https://user-images.githubusercontent.com/12501552/115114529-2cc2c100-9f90-11eb-8831-d903098331ac.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.70.3
 - 64-bit

**Additional context**
Low priority, but was nuisance to work around. In the current state I had to delete my account and create an another one with a shorter password.

If the password length constraint is the expected behavior (which I believe it might be), then the WebUI should have an option to reset a user's password so it's possible to authenticate in-game with a password that meets the criteria.

**Comment by poco0317** [comment]
dont know what webgui is
im glad you counted how many characters fit tho
fixed for .71 by 070346adabc7fdac95ed7a00d7405c9b3731d6a7 and the change is safe to apply yourself in your current game version if you want

**Comment by bluebandit21** [comment]
For the future -- "In the current state I had to delete my account and create an another one with a shorter password."
[This](http://etternaonline.com/user/forgot) will let you change it instead of have to re-create your account.
