### ISSUE TITLE
Change behaviour of Top Grades to make it more useful

### ISSUE THREAD

**Issue by bluebandit21** [etternagame/etterna#977]
**Describe the bug**
The main use case of Top Grades I see is as follows: Someone decides they want to play all of the songs they've only gotten a B on and try to do better, or maybe play songs they haven't played before.
When you sort by Top Grades, find a song to play, and play it, here is the issue.
If you improve your score on the song, when you return to the song wheel you will have been moved from the group of grades the song was previously in to the new group the song is in.
As a result, the above use cases are very painful to do.

Although this isn't non-intuitive behaviour (your currently selected song remains the same after finishing a song, like all other sort), it makes Top Grades all but useless, as using it involves 
a) Scroll to the group of songs you want to improve
b) Play a song (doing better on it)
c) Scroll forever through the new group you're in to make it back to where you were before

With how long c can take for very large song libraries (I have many many hundreds of songs I've gotten a A on), it is literally faster to go pack-through-pack in group sort to find specific letter grades to improve than to use the sort mode exclusively made for that purpose.

**Expected behavior**
I think it would be more useful if you stayed "near" where the song was before improving your score on it.
Perhaps the cursor could be made to select the song that had previously been right after it, or the like.

**Comment by poco0317** [comment]
Utilize the up+down shortcut to exit an opened musicwheel folder.
Will reopen if you make a better argument
