### ISSUE TITLE
Caps lock key doesn't work

### ISSUE THREAD

**Issue by g-robertson** [etternagame/etterna#978]
**Describe the bug**
Caps lock doesn't capitalize letters in game

**To Reproduce**
Turn caps lock on
Enter text into some field with caps lock on

**Expected behavior**
The letter to be capitalized

**Screenshots**
![image](https://user-images.githubusercontent.com/39735358/115924438-b3bee000-a44d-11eb-9d1d-f6c4466fc7b5.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux 5.11.15-arch1-2
 - Version 0.70.4
 - 64bit

**Additional context**
IDK probably linux only?

**Comment by poco0317** [comment]
Shift should work

**Comment by g-robertson** [comment]
Shift does work

**Comment by bluebandit21** [comment]
I looked into this.
`wchar_t InputHandler::ApplyKeyModifiers(wchar_t c)`
appears to be where shift applies, and where caps lock support would be added.

I have no earthly clue how it currently *does* work on Windows; as far as I can tell it really shouldn't. 

I think I made a fix for this issue; I'll make the PR soon.

**Comment by poco0317** [comment]
done 0bc55111e8687cad402413ef9a9b3cbc77989b51 #994
