### ISSUE TITLE
Unknown video renderer value:  opengl

### ISSUE THREAD

**Issue by nootnoot6989** [etternagame/etterna#979]
Fatal Error
Unknown video renderer value:  opengl
The game won't lunch because of this bug, tried finding solutions but found nothing.

Windows 10
Home Edition (unactivated)
64bit

**Comment by poco0317** [comment]
Try a reboot or switching the options in /save/preferences.ini VideoRenderers=

**Comment by nootnoot6989** [comment]
> Try a reboot or switching the options in /save/preferences.ini VideoRenderers=

Tried rebooting and switching the options including installing the newest version of the game and the error is still appearing.

**Comment by poco0317** [comment]
Under normal conditions this error occurs when d3d or RageDisplay in general cannot initialize the device. Other than that, this could mean that you are missing drivers for opengl for some odd reason.

You could try an older version of the game to see if there is any difference.

**Comment by nootnoot6989** [comment]
> You could try an older version of the game to see if there is any difference.

Which older version pacifically (I cant spell sometimes)￼ like the multiplayer releases or one of the pre-releases.

**Comment by poco0317** [comment]
anything older than like .69 https://github.com/etternagame/etterna/releases

**Comment by nootnoot6989** [comment]
okay installed .69 and it still crashes, but now it crashes with a crash log

Etterna0.69.0 crash report (build )
--------------------------------------

Crash reason: Access Violation

Thread: Main thread
        RageFileDriverDirectHelpers.cpp:165 F:/Games/Etterna/Save/Keymaps.ini
        RageFileDriverDirectHelpers.cpp:165 F:/Games/Etterna/Logs/log.txt
        RageFileDriverDirectHelpers.cpp:165 F:/Games/Etterna/Logs/info.txt
        RageFileDriverDirectHelpers.cpp:165 F:/Games/Etterna/Logs/userlog.txt
        RageFileDriverDirectHelpers.cpp:165 F:/Games/Etterna/Logs/timelog.txt
debug resource file 'F:\Games\Etterna\Program\Etterna.vdi': CreateFile failed (The system cannot find the file specified.).

Static log:
Etterna0.69.0
(build )
Log starting 2021-04-25 09:58:52
	Verbosity: 1
Windows 6.2 (Win8) build 9200 []
WARNING: RegOpenKeyEx(80000002,HARDWARE\DEVICEMAP\Scsi) error (The system cannot find the file specified.)
WARNING: Selected theme '_fallback' not found.  Trying Theme preference default value '_fallback'.
WARNING: Theme preference defaults to '_fallback', which cannot be used.  Trying DefaultTheme preference 'Til Death'.
Attempting to connect to: multi.etternaonline.com, Port: 8765
Server Version: 0 
Video renderers: 'd3d, opengl'
Current renderer: Direct3D
Current renderer: Direct3D

Partial log:
00:03.588: Video card has changed from  to NVIDIA GeForce GT 710.  Applying new defaults.
00:03.588: Video renderers: 'd3d, opengl'
00:03.589: RageDisplay_D3D::RageDisplay_D3D()
00:03.674: RageDisplay_D3D::~RageDisplay()
00:03.690: 
00:03.690: //////////////////////////////////////////////////////
00:03.690: Exception: Unknown video renderer value:  opengl
00:03.690: //////////////////////////////////////////////////////
00:03.690: 
00:03.826: Current renderer: Direct3D

-- End of report

**Comment by nootnoot6989** [comment]
Oh and I forgot to say that I updated my graphics drivers because they were 6 months out of date

**Comment by nootnoot6989** [comment]
Hello?

**Comment by poco0317** [comment]
At this time I do not have a solution. It appears your graphics card may somehow be too out of date, which doesn't make sense given this game is from 2002

**Comment by jameskr97** [comment]
@nootnoot6989 We've updated to 0.70.4 since this issue was created. I've installed it on Windows myself had have had no issues. Please download the latest version and let us know if you still have this issue. I'm going to close this issue, but if you continue to have trouble, please reopen it and @ mention me.

**Comment by nootnoot6989** [comment]
It's all good now I upgraded to a new computer and everything is working fine.
Thanks for the help though.
