### ISSUE TITLE
İ cant Download Bundle Pack İts Says 0 MB 

### ISSUE THREAD

**Issue by Crz-ux** [etternagame/etterna#980]
![Screenshot_2](https://user-images.githubusercontent.com/59148334/115970870-0384d080-a54e-11eb-95ac-c7f8c28e8d13.png)

**Comment by Crz-ux** [comment]
İ Cant Download Packs İt Say 0 MB

**Comment by poco0317** [comment]
this occurs when you do not have a connection to the api server
