### ISSUE TITLE
Add In-Client Noteskin, Judgement, and Toasty Downloader

### ISSUE THREAD

**Issue by bluebandit21** [etternagame/etterna#982]
We already have a in-game song downloader, so why not add the ability to effortlessly install other types of assets?

People very frequently mess up or are unable to figure out how to install them on their own, so there would be a reason to do so.
Also, with the pack downloader, other than the above assets the user theoretically never has to manually access the game folder on their computer. Adding in the above downloaders would remove this one interaction left (ignoring custom user avatars, for the time being)

This may be a limitation of the EO API more than with the client, but I think it's definitely worth adding in the future (and adding in API support for EO2 if it doesn't exist)

**Comment by poco0317** [comment]
duplicate #224
