### ISSUE TITLE
Introduction of loading songs from the server

### ISSUE THREAD

**Issue by 1NANI1** [etternagame/etterna#984]
I want to give you an idea of ​​how you can make the game better. You can make a download of the chart just before the start of the level, when you click on it, not the whole pack, but a separate song. So the game would have come out much more compact, we, the players, would not have to download gigabytes of charts.

**Comment by TheROPFather** [comment]
This is not going to happen. Stepmania has always been a pack based experience and will likely remain so. Individual song downloading simply goes against the game culture.

**Comment by poco0317** [comment]
This suggestion is also more of a feature suggestion for online services. Client development is mostly separate from online development. It's built to accept any API server as long as the API is consistently used. Pack downloads can just as easily be singles. On that note, do not send Etternaonline suggestions to this repository, rather send them to the discord where they can be discussed by the relevant community.
