### ISSUE TITLE
Playing some osu!mania charts will bring up a persistent "Song offset" warning.

### ISSUE THREAD

**Issue by MillaBasset** [etternagame/etterna#985]
**Describe the bug**
Title should say it all. Even after being presented with the offset dialog after exiting the song and hitting Yes, the Song offset text reappears on next play.

**To Reproduce**
I don't have a great list of osu!mania charts that can cause this bug, but [this](https://osu.ppy.sh/beatmapsets/173612#mania/502132) should be one of them.

Open the chart, exit (either by finishing the song or quitting), press Yes on the dialog, and re-open the song to find the text is still there.

**Expected behavior**
The Song offset text to disappear after the first time through, or better yet not appear at all.

**Screenshots**
![Screenshot](https://pbs.twimg.com/media/E04utRRXsAE9qPo?format=jpg&name=large)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home, version 19041
 - Etterna Version: v0.70.4
 - 64-bit.

**Additional context**
Shouldn't be any more context, really.

**EDIT:** Didn't occur to me to put in the Etterna version, sorry.

**Comment by SashLilac** [comment]
Huh, this specific beatmap doesn't seem to trigger the bug anymore. I'm not quite sure what's up with that.

I don't even remember what I did to fix it, sadly.

The issue might just be extremely inconsistent. Will post an update if I trigger it again.

**Comment by poco0317** [comment]
You are right that this is an inconsistent bug. But it isn't related to osu loaded files. Changes I made in 0.67.0 caused this to happen and I know where to look to fix it, but don't know how to reliably reproduce it.

**Comment by SashLilac** [comment]
Huh, thanks for clarifying. What changes, if I may ask?

**Comment by poco0317** [comment]
20c833800b4fd9c07ae44edfdc135645d9a69dd1 0c667f510f8a561d9232a833a38d7f4c1166ea6a

**Comment by SashLilac** [comment]
@poco0317 It appears that triggering the bug and switching to a different song without reset will cause the message to pop up there, too, although it doesn't actually change anything. Not sure if that's known.

**Comment by poco0317** [comment]
That is exactly the definition of the bug. It stays on the overlay even when nothing is happening

**Comment by SashLilac** [comment]
Whoops. It also seems that playing a working song beforehand will not cause the message to pop up.

**Comment by poco0317** [comment]
resolved by various osu loader changes probably, particularly the change which fixes the fact that offsets dont exist for osu files and when you attempted to change them it didnt save anything
eb1585cb424ef322b350e067f0764179d8ad76f4
