### ISSUE TITLE
execv /var/tmp/pamac-build-dubluayaychtee/etterna-git/src/etterna/build/gn_crashpad/crashpad_handler: No such file or directory

### ISSUE THREAD

**Issue by dublUayaychtee** [etternagame/etterna#987]
**Describe the bug**

**To Reproduce**
1. Install using `pamac install etterna-git`
2. Wait for it to finish
3. `cd /opt/etterna-git/`
4. `./etterna`
5. Error: `[2480764:2480764:20210510,145544.052486:FATAL double_fork_and_exec.cc:131] execv /var/tmp/pamac-build-dubluayaychtee/etterna-git/src/etterna/build/gn_crashpad/crashpad_handler: No such file or directory (2)`

**Expected behavior**
When I do `./etterna`, it should launch etterna

**Desktop**
 - OS: Garuda Linux (arch linux, based off manjaro I think)
 - 64bit

**Additional context**
I also tried using `pamac install etterna` instead of etterna-git, but that one fails at build.

**Comment by poco0317** [comment]
For AUR related support, contact the maintainers.

For develop related build issues, contact us through the discords.
