### ISSUE TITLE
Bare-Frames Crash

### ISSUE THREAD

**Issue by Gilbertil** [etternagame/etterna#995]
[inrelevant i guess] when i try to play this theme the game crashes 
![Captura de pantalla (2291)](https://user-images.githubusercontent.com/84993798/120038647-d0a48100-bfc0-11eb-891b-232ab9c26671.png)
![Captura de pantalla (2293)](https://user-images.githubusercontent.com/84993798/120038733-f598f400-bfc0-11eb-93e8-0b0f9860a9a8.png)

Crash info:
Etterna0.70.3 crash report (build )
--------------------------------------

Crash reason: Unhandled Microsoft C++ Exception

Thread: Main thread
        FontManager.cpp:70 FontManager::UnloadFont(/Themes/_fallback/Fonts/_open sans semibold 24px.ini).
        FontManager.cpp:70 FontManager::UnloadFont(/Themes/_fallback/Fonts/_open sans semibold 24px.ini).
        FontManager.cpp:70 FontManager::UnloadFont(/Themes/_fallback/Fonts/_open sans semibold 24px.ini).
        FontManager.cpp:70 FontManager::UnloadFont(/Themes/_fallback/Fonts/_open sans semibold 24px.ini).
        RageTextureManager.cpp:168 RageTextureManager::LoadTexture(__blank__).
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:237 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:237 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:237 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:237 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:237 Processing the sound while buffers are available.
Thread: Mixer thread
Thread: Music thread
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:893 
        InputHandler_DirectInput.cpp:868 
        InputHandler_DirectInput.cpp:887 
        InputHandler_DirectInput.cpp:893 
        InputHandler_DirectInput.cpp:868 
debug resource file 'C:\Games\Etterna\Program\Etterna.vdi': CreateFile failed (El sistema no puede encontrar el archivo especificado.).

Static log:
Etterna0.70.3
(build )
Log starting 2021-05-28 14:24:28
	Verbosity: 1
Windows 6.2 (Win8) build 9200 []
WARNING: RegOpenKeyEx(80000002,HARDWARE\DEVICEMAP\Scsi) error (El sistema no puede encontrar el archivo especificado.)
Attempting to connect to: multi.etternaonline.com, Port: 8765
Server Version: 0 
Video renderers: 'd3d, opengl'
WARNING: RageDisplay_D3D::TryVideoMode( 1, 1024, 576, 16, 0, 0 )
D3D Ventana 1024x576 16 color 32 textura 60Hz Sin VSync Líneas suaves
Players joined: P1
Top Screen: ScreenSelectMusic
Current renderer: Direct3D

Partial log:
03:09.768: Reading 'NoteSkins/dance/default/metrics.ini' failed: No such file or directory
03:09.772: Reading 'NoteSkins/dance/default/metrics.ini' failed: No such file or directory
03:09.777: Reading 'NoteSkins/dance/default/metrics.ini' failed: No such file or directory
03:09.784: Reading 'NoteSkins/dance/default/metrics.ini' failed: No such file or directory
03:09.788: Reading 'NoteSkins/dance/default/metrics.ini' failed: No such file or directory
03:09.792: Reading 'NoteSkins/dance/default/metrics.ini' failed: No such file or directory
03:09.795: Reading 'NoteSkins/dance/default/metrics.ini' failed: No such file or directory
03:09.800: Reading 'NoteSkins/dance/default/metrics.ini' failed: No such file or directory
03:32.529: MusicWheel sorting took: 212.529999
03:32.555: MusicWheel sorting took: 212.555008

-- End of report

Log:
00:00.010: Etterna0.70.3
00:00.010: (build )
00:00.010: Log starting 2021-05-28 14:24:28
00:00.010: 	Verbosity: 1
00:00.010:  
00:00.011: Reading 'Data/Defaults.ini' failed: No such file or directory
00:00.012: Reading 'Data/Static.ini' failed: No such file or directory
00:00.012: Reading 'Data/Static.ini' failed: No such file or directory
00:00.970: Windows 6.2 (Win8) build 9200 []
/////////////////////////////////////////
00:00.971: WARNING: RegOpenKeyEx(80000002,HARDWARE\DEVICEMAP\Scsi) error (El sistema no puede encontrar el archivo especificado.)
/////////////////////////////////////////
00:01.151: Reading 'Themes/bare-frames/Languages/es.ini' failed: No such file or directory
00:01.182: Reading 'Themes/_fallback/ThemeInfo.ini' failed: No such file or directory
00:01.288: Reading 'Themes/bare-frames/ThemeInfo.ini' failed: No such file or directory
00:26.441: Profile::LoadAllFromDir( /Save/LocalProfiles/00000000/ )
00:28.774: Calculating stats from scores
00:30.941: Loaded replay data type 2 at Save/ReplaysV2/Sf2641ae70819dbad98e7e03d75489864e9b9ac15
00:30.943: Loaded replay data type 2 at Save/ReplaysV2/S38a9751f74782b7a4055044408e762e332e8a9f6
00:31.086: Loaded replay data type 2 at Save/ReplaysV2/S0e9ea21102cbab8d2a7193899a75297933f2579c
00:31.261: Loaded replay data type 2 at Save/ReplaysV2/S346461b08f6eb44b46b8f7c90f622cab2052c4ea
00:33.646: Attempting to connect to: multi.etternaonline.com, Port: 8765
00:34.828: Could not create ettp connection because: Connection creation attempt failed
00:36.516: Connected to ett server: multi.etternaonline.com
00:36.585: Server Version: 0 
00:37.882: Video renderers: 'd3d, opengl'
00:37.972: RageDisplay_D3D::RageDisplay_D3D()
00:38.569: Driver: igdumd64.dll
00:38.569: Description: Intel(R) HD Graphics
00:38.569: Max texture size: 8192
00:38.569: Alpha in palette: no
00:38.569: 
00:38.569: This display adaptor supports the following modes:
00:38.616:   320x200 60Hz, format 22
00:38.616:   320x240 60Hz, format 22
00:38.616:   400x300 60Hz, format 22
00:38.616:   512x384 60Hz, format 22
00:38.616:   640x400 60Hz, format 22
00:38.616:   640x400 70Hz, format 22
00:38.616:   640x480 59Hz, format 22
00:38.616:   640x480 60Hz, format 22
00:38.616:   640x480 70Hz, format 22
00:38.616:   640x480 73Hz, format 22
00:38.616:   640x480 75Hz, format 22
00:38.616:   800x600 60Hz, format 22
00:38.616:   800x600 72Hz, format 22
00:38.616:   800x600 75Hz, format 22
00:38.616:   1024x768 60Hz, format 22
00:38.616:   1024x768 70Hz, format 22
00:38.616:   1024x768 75Hz, format 22
00:38.616:   1280x600 60Hz, format 22
00:38.616:   1280x720 60Hz, format 22
00:38.616:   1280x768 60Hz, format 22
00:38.616:   1360x768 60Hz, format 22
00:38.616:   1366x768 60Hz, format 22
/////////////////////////////////////////
00:38.637: WARNING: RageDisplay_D3D::TryVideoMode( 1, 1024, 576, 16, 0, 0 )
/////////////////////////////////////////
00:38.637: Testing format: display 22, back buffer 20, windowed 1...
00:38.637: Testing format: display 22, back buffer 22, windowed 1...
00:38.637: This will work.
00:38.909: Testing format: display 22, back buffer 20, windowed 1...
00:38.909: Testing format: display 22, back buffer 22, windowed 1...
00:38.909: This will work.
00:38.921: Present Parameters: 1024, 576, 22, 1, 0, 1, 3147790, 1, 1, 80, 0, 0, -2147483648
00:41.104: D3D Ventana 1024x576 16 color 32 textura 60Hz Sin VSync Líneas suaves

**Comment by poco0317** [comment]
likely fixed for next release 0.71
unknown cause
